### ISSUE TITLE
(23551) Error when receiving mapurl

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.mihome-vacuum#100]
using S55 with enable map from Xiaomi cloud

![Schermafbeelding 2020-02-19 om 13 13 31](https://user-images.githubusercontent.com/7318445/74833379-a2de8000-5319-11ea-81c9-c88f01b890d4.png)
![Schermafbeelding 2020-02-19 om 13 13 50](https://user-images.githubusercontent.com/7318445/74833400-ad991500-5319-11ea-8e12-713f0ebb0131.png)

**Comment by Scotty-89** [comment]
Hallo,

ich habe auch ein Problem mit meinen zwei S50 ;) 
![image](https://user-images.githubusercontent.com/54929714/74853212-e6e37c00-533d-11ea-9407-be007348d871.png)

mir ist auch grade nicht klar wie ich die Karte dann auch im VIS zum laufen bekommen... gibt es da eine Anleitung etc ? 

neu ist ja auch das Räume definiert werden können kann ich die hier auch finden und dann gezielt ansteuern ?

**Comment by MeisterTR** [comment]
bitte 2.0.6 testen

**Comment by Scotty-89** [comment]
Abend. 
Soweit ich das sehe kommen da jetzt Daten an... vielen Dank. Schau mir morgen an was da ankommt. 

Ist die Karte dann ein Image ?
Frage am Rande wie bekommt man eigentlich Positionen auf der Karte dann raus ? Grade für die move to Funktion 

Vielen Dank.

**Comment by DutchmanNL** [comment]
Karte kommt rein in sw raeume leider nicht

**Comment by dirkhe** [comment]
Aktuelle Version installiert? Ist heute Abend noch öfter aktualisiert worden. In der App hast du Räume?

**Comment by DutchmanNL** [comment]
Nochmal heute morgen von git, luppt vol geil !!!
