### ISSUE TITLE
Cleaning rooms not working

### ISSUE THREAD

**Issue by nightmare04** [iobroker-community-adapters/ioBroker.mihome-vacuum#102]
> 
mihome-vacuum.0 | 2020-02-22 23:37:52.503 | debug | (6216) stateChange mihome-vacuum.0.control.fan_power {"val":101,"ack":false,"ts":1582382272502,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1582380923931}
-- | -- | -- | --
mihome-vacuum.0 | 2020-02-22 23:37:52.501 | info | (6216) should trigger cleaning segment 19, but is currently active. Add to queue
mihome-vacuum.0 | 2020-02-22 23:37:52.499 | debug | (6216) sendTo "cleanSegments" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0: 19
mihome-vacuum.0 | 2020-02-22 23:37:52.499 | debug | (6216) stateChange mihome-vacuum.0.rooms.727001106804.roomClean {"val":true,"ack":false,"ts":1582382272497,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1582381812026}

**Comment by nightmare04** [comment]
after restart adapter start workin from objects but script still not...

> 
sendTo("mihome-vacuum.0", 
    "cleanSegments",
    {rooms: [21]},
    function (response) { log(response)}
);
>

**Comment by dirkhe** [comment]
Try
sendTo("mihome-vacuum.0",
"cleanSegments",
"21",
function (response) { log(response)}
);

**Comment by nightmare04** [comment]
> Try
> sendTo("mihome-vacuum.0",
> "cleanSegments",
> "21",
> function (response) { log(response)}
> );

Thx, this works.
