### ISSUE TITLE
2 Instanzen 1 map die überschrieben wird

### ISSUE THREAD

**Issue by Scotty-89** [iobroker-community-adapters/ioBroker.mihome-vacuum#103]
Guten Abend ;) 

mir ist grade aufgefallen, da ich zwei von diesen Teilen habe, das die Map an eine "zentrale" stelle abgelegt wird und von beiden Überschrieben.
ich habe also immer nur die Map vom letzten Sauger der gelaufen ist.

ist es möglich nicht für jede Instance eine map zu erhalten ?

**Comment by MeisterTR** [comment]
fixed
