### ISSUE TITLE
Xiaowa E2

### ISSUE THREAD

**Issue by Balu0127** [iobroker-community-adapters/ioBroker.mihome-vacuum#105]
Hi there

Is the Roborock Xiaowa E2 integrated in the adapter.

Kind regards
Balu

**Comment by dirkhe** [comment]
Installe the adapter and test. There is nothing Special vor this. Have a look in the Code Main.js and Search for Model and Firmware. If there something, wehre you say this is also Assigned to your Model, give us a hint
