### ISSUE TITLE
SyntaxError: Unexpected token G in JSON at position 0

### ISSUE THREAD

**Issue by losnoxos** [iobroker-community-adapters/ioBroker.mihome-vacuum#109]
Hallo,

leider ist das Problem wieder da.

Adapter Version 2.0.5

Fehler tritt auf, wenn ich den Roborock S6 über die Mihome App starte und Räume saugen lasse.
Werfe beim nächsten Saugen den debugger an.

mihome-vacuum.0 | 2020-03-04 18:25:00.239 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
-- | -- | -- | --
host.iobroker | 2020-03-04 18:25:00.013 | info | instance system.adapter.tvspielfilm.0 started with pid 30799
mihome-vacuum.0 | 2020-03-04 18:24:58.179 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:56.115 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:54.060 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:51.989 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:49.935 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:47.872 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:45.811 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:43.734 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:41.664 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:39.591 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:37.538 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:35.460 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:33.406 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:31.334 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:29.279 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:27.195 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:25.138 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:23.066 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:21.010 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:18.938 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:16.885 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:14.812 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:12.739 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:10.676 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:08.571 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:06.498 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:04.436 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:02.364 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:24:00.279 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:58.207 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:56.154 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:54.081 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:52.024 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:49.952 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:47.896 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:45.825 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:43.768 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:41.709 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:39.643 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:37.588 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:35.510 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:33.454 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:31.381 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:29.327 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:27.253 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:25.198 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:23.134 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:21.092 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:19.031 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:16.958 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:14.887 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:12.823 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:10.768 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:08.701 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:06.646 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:04.574 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:02.520 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:23:00.447 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:58.391 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:56.311 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:54.253 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:52.181 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:50.126 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:48.050 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:45.993 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:43.908 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:41.851 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:39.779 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:37.722 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:35.651 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:33.596 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:31.523 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:29.464 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:27.400 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:25.341 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:23.269 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:21.227 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:19.170 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:17.081 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:15.010 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:12.936 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:10.876 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:08.803 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:06.748 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:04.673 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:02.618 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:22:00.544 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:58.487 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:56.415 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:54.358 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:52.288 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:50.219 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:48.163 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:46.089 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:44.034 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:41.956 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:39.900 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:37.827 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:35.772 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:33.690 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:31.628 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:29.550 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:27.494 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:25.421 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:23.366 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:21.312 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:19.242 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:17.155 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:15.066 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:13.010 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:10.937 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:08.879 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:06.788 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:04.733 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:02.659 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:21:00.605 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:58.551 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:56.478 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:54.409 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:52.282 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:50.228 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:48.154 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:46.097 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:44.018 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:41.963 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:39.891 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:37.837 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:35.765 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:33.711 | error | (557) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-03-04 18:20:31.637 | error | (557) SyntaxError: Unexpected token G in JSON at position 0

**Comment by Diginix** [comment]
Bitte auch die aktuellste Version nutzen. Der Adapter bereits in Version 2.0.7 verfügbar und im Fork von @dirkhe schon 2.0.8.

**Comment by losnoxos** [comment]
ok sorry mit 2.0.7 sieht es besser aus.

Komisch, da 2.0.5 die ganze Zeit ordentlich lief.

Danke!
