### ISSUE TITLE
Adapter does not start after Update to node.js 10.20.0

### ISSUE THREAD

**Issue by SoldierOc** [iobroker-community-adapters/ioBroker.mihome-vacuum#115]
Hi Everyone,

after updating node.js 10.20.0 (Ubuntu) with a complete restart my two mihome-vacuum adapters does not work/start correct.

![10-04-_2020_00-14-52](https://user-images.githubusercontent.com/63428971/78945474-ab089f80-7ac0-11ea-9af4-cf4caf9031d9.jpg)

![10-04-_2020_00-19-18](https://user-images.githubusercontent.com/63428971/78945591-fde25700-7ac0-11ea-9dca-6dafbf64a22e.jpg)

Can everyone help or fix the problem?

**Comment by dirkhe** [comment]
Please Show Log with debug Level. Set it to only one

**Comment by SoldierOc** [comment]
Thanks for your fast response. I've stopped one of the adapters, set do debug-level and restarted - thats the result.

![neu](https://user-images.githubusercontent.com/63428971/78946517-384cf380-7ac3-11ea-8fc7-46d1c5ae0caa.jpg)

**Comment by dirkhe** [comment]
Please go to Current Version, because there is the Logging better

**Comment by dirkhe** [comment]
Is it working now? Can we close the Ticket?

**Comment by dirkhe** [comment]
clsed, because no user answer
