### ISSUE TITLE
check Adapter with js-controller 3.x Error object dnd is invalid

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.mihome-vacuum#116]
Hi, 
mit js-controller 3.0.7 unter Node 12 kommt folgender Fehler:

`

mihome-vacuum.0 | 2020-04-13 12:21:12.064 | warn | (10015) Time difference between Mihome Vacuum and ioBroker: -2 sec
-- | -- | -- | --
mihome-vacuum.0 | 2020-04-13 12:21:11.149 | warn | (10015) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-04-13 12:21:11.148 | warn | (10015) Object mihome-vacuum.0.info.dnd is invalid: obj.common.type has  an invalid value (switch) but has to be one of number, string, boolean,  array, object, mixed, file, json
host.ioB-D10 | 2020-04-13 12:21:09.367 | info | instance system.adapter.mihome-vacuum.0 started with pid 10015

`

**Comment by mswiege** [comment]
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/pull/118
