### ISSUE TITLE
no MAP after update Nodejs 10->12

### ISSUE THREAD

**Issue by root01** [iobroker-community-adapters/ioBroker.mihome-vacuum#119]
Im updating nodejs 10 to 12. After this i get no map updates. I roll back to 10 and it works.
ioBroker latest (js controller 3.0.14 - 3.0.17)
Nodejs 10.20.1 works
Nodejs 12.16.1 no Map update

Mi Vacuum Gen1 lastest FW (testing other FW. Same thing)

**Comment by mswiege** [comment]
I also updated from 10 to 12 and the logs get flooded with the following error (every 3 seconds while the vacuum is driving):
`(29831) TypeError: mapCreator.CanvasMap is not a function`
Is that the same behaviour for you?

**Comment by Apollon77** [comment]
Yes you need to rebuild the adapter! ... Did you considered all steps for upgading nodejs propertly? There is a forum post ...
With js.controller 3.0 you can run "iobroker rebuild mihome-vacuum --install" to fix it

**Comment by Ilovegym66** [comment]
sorry, tested, iobroker rebuild ( with or without --install ) doesn't fix the issue. With Node 10 is working fine, with Node12.x not.

**Comment by Apollon77** [comment]
Was genau ist denn das log bei rebuild mit --install?

**Comment by Ilovegym66** [comment]
also wenn ich im laufenden Betrieb den Adapter stoppe, dann in der Konsole ein iobroker rebuild mihome-vacuum --install eingebebe, kommt folgendes:
Konsole:
`ilovegym@iobroker /opt/iobroker $ iobroker rebuild mihome-vacuum --install
npm install --loglevel error --production (System call) in "/opt/iobroker/node_modules/iobroker.mihome-vacuum"

Rebuild mihome-vacuum done
ilovegym@iobroker /opt/iobroker $ 
`

Im logfile:
nix! Rebuild erzeugt bei mir kein logeintrag, weder im normalen Log (iobroker.2020-0505 ) noch im current.log oder im Admin ist auch nix zu sehen..???????

Wo sitzt der Fehler? :-)

**Comment by Ilovegym66** [comment]
also ich hab auch gerade mit dem iot adapter getestet, da kommt auch kein Eintrag ins logfile..

**Comment by Ilovegym66** [comment]
hab mal im node_modules/iobroker.mihome-vacuum ein "npm i" gemacht.. jetzt kommt bei dem mit der alten Firmware 1886 oder was ist eine Karte, bei denen mit der neuen Firmware 2008, keine.
Im Logfile stehen keine! Fehler, extra auf debug gestellt.

Vielleicht auch oben falsch ausgedrückt, das ist nicht! nach dem Update von Node 10 auf Node 12, sondern generell unter Node12 gibts da Probleme mit der Karte.
Hab ein System gleich mit Node12 aufgesetzt, iobroker installiert, Adapter installiert, keine Karte.

Beim alten Testsystem mit Node10 funktioniert es ja.
Also muss sich irgendwas da geändert haben, was auch im Adapter geändert werden muss. :-)
Wer noch n Zauberspruch hat, den man in die Konsole hacken kann, her damit.. :-)

**Comment by Ilovegym66** [comment]
sooo nachdem ich vorhin das "npm i" im mihome-vacuum Ordner gemacht habe, und die Adapter nochmal neu gestartet habe, kam jetzt bei allen auch eine Karte!

Also meine Meinung dazu. Das "iobroker rebuild" funktioniert nicht.
Der Adapter hier ist ok, das Issue kann zu.

**Comment by root01** [comment]
Dann müsste ja auch bei einer Neuinstallation unter node12 die Karte funktionieren. Tut sie aber, zumindest bei mir, nicht.

**Comment by Ilovegym66** [comment]
Dich, weil das rebuild nicht geht, geh Mal ins Verzeichnis und mach ein npm i dann Adapter wieder starten, zur Sicherheit ins config gehen und den Key nochmal laden, und warten... Nach 10-15 Minuten ist dann die Karte da.

**Comment by Apollon77** [comment]
Also an sich tut das rebuild und ja es kann sein das keine Ausgabe kommt. ggf mal installation fixer laufen lassen.
Welches kommando das rebuild in welchem Verzeichnis ausführt steht ja in der ausgabe. Und ja eine manuelle ausführung avon im angeebenen Verzeichnis sollte den gleichen Effekt haben

**Comment by Ilovegym66** [comment]
Eben nicht. Es sieht so aus, als ob der Aufruf bei "iobroker rebuild" gar nicht starten würde, da er sofort fertig ist und im Log nichts steht!

Wenn ich per Hand ins Verzeichnis wechsel, und ein npm i eingebe, was nix anderes ist, dann funktioniert es ja und es kommt auch ne Ausgabe von npm!

Mir wurde gerade "alles Gute" gewünscht von iobroker,cweil ich "iobroker fix" zum 100.ten Mal aufgerufen habe.. 🤣

**Comment by Apollon77** [comment]
wie ist denn die ausgabe von npm?

**Comment by Ilovegym66** [comment]
das ist ja das, was mich so wundert, es sieht so aus, als ob npm garnicht starten würde..
hier auszug aus der Konsole, in den logs steht einfach nichts.. :-((
``ilovegym@iobroker /opt/iobroker $ iobroker rebuild mihome-vacuum --install
npm install --loglevel error --production (System call) in "/opt/iobroker/node_modules/iobroker.mihome-vacuum"

Rebuild mihome-vacuum done
ilovegym@iobroker /opt/iobroker $`

Da steht sofort nur "rebuild done" also der Aufruf, was iobroker gerne machen würde, und dann sofort "rebuild done" . Schön, dass er schnell fertig ist.. aber der Aufruf von NPM startet garnicht.. auch in den Systemlogs ist nix.. und NPM macht ja gern ne Ausgabe in der console.. da kommt garnix.. nix nuescht nothing..

**Comment by Ilovegym66** [comment]
assigned to [iobroker.js-controller](https://github.com/ioBroker/ioBroker.js-controller/issues/872)

looks like a problem from the 3.x Controller, not from mihome-vacuum adapter.

**Comment by root01** [comment]
> sooo nachdem ich vorhin das "npm i" im mihome-vacuum Ordner gemacht habe, und die Adapter nochmal neu gestartet habe, kam jetzt bei allen auch eine Karte!
> 
> Also meine Meinung dazu. Das "iobroker rebuild" funktioniert nicht.
> Der Adapter hier ist ok, das Issue kann zu.

Funktioniert super. Danke

**Comment by gaga191281** [comment]
> sooo nachdem ich vorhin das "npm i" im mihome-vacuum Ordner gemacht habe, und die Adapter nochmal neu gestartet habe, kam jetzt bei allen auch eine Karte!
> 
> Also meine Meinung dazu. Das "iobroker rebuild" funktioniert nicht.
> Der Adapter hier ist ok, das Issue kann zu.

habe dasselbe Problem. Wie und wo genau muss das command eingegeben werden?
Habe es unter `/opt/iobroker/iobroker-data/files/mihome-vacuum.admin$` versucht. Lediglich `npm i` in genanntem Verzeichnis führt bei mir zu Fehlern.

```
98 verbose stack Error: iobroker.inst@2.0.3 postinstall: `node lib/install.js`
98 verbose stack Exit status 100
98 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
98 verbose stack     at EventEmitter.emit (events.js:315:20)
98 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
98 verbose stack     at ChildProcess.emit (events.js:315:20)
98 verbose stack     at maybeClose (internal/child_process.js:1048:16)
98 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
99 verbose pkgid iobroker.inst@2.0.3
100 verbose cwd /opt/iobroker/iobroker-data/files/mihome-vacuum.admin
101 verbose Linux 4.15.0-130-generic
102 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
103 verbose node v14.15.1
104 verbose npm  v6.14.8
105 error code ELIFECYCLE
106 error errno 100
107 error iobroker.inst@2.0.3 postinstall: `node lib/install.js`
107 error Exit status 100
108 error Failed at the iobroker.inst@2.0.3 postinstall script.
108 error This is probably not a problem with npm. There is likely additional logging output above.
109 verbose exit [ 100, true ]
```
Bitte um Hilfe.

**Comment by backfisch88** [comment]
> 
> 
> > sooo nachdem ich vorhin das "npm i" im mihome-vacuum Ordner gemacht habe, und die Adapter nochmal neu gestartet habe, kam jetzt bei allen auch eine Karte!
> > Also meine Meinung dazu. Das "iobroker rebuild" funktioniert nicht.
> > Der Adapter hier ist ok, das Issue kann zu.
> 
> habe dasselbe Problem. Wie und wo genau muss das command eingegeben werden?
> Habe es unter `/opt/iobroker/iobroker-data/files/mihome-vacuum.admin$` versucht. Lediglich `npm i` in genanntem Verzeichnis führt bei mir zu Fehlern.
> 
> ```
> 98 verbose stack Error: iobroker.inst@2.0.3 postinstall: `node lib/install.js`
> 98 verbose stack Exit status 100
> 98 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 98 verbose stack     at EventEmitter.emit (events.js:315:20)
> 98 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 98 verbose stack     at ChildProcess.emit (events.js:315:20)
> 98 verbose stack     at maybeClose (internal/child_process.js:1048:16)
> 98 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 99 verbose pkgid iobroker.inst@2.0.3
> 100 verbose cwd /opt/iobroker/iobroker-data/files/mihome-vacuum.admin
> 101 verbose Linux 4.15.0-130-generic
> 102 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
> 103 verbose node v14.15.1
> 104 verbose npm  v6.14.8
> 105 error code ELIFECYCLE
> 106 error errno 100
> 107 error iobroker.inst@2.0.3 postinstall: `node lib/install.js`
> 107 error Exit status 100
> 108 error Failed at the iobroker.inst@2.0.3 postinstall script.
> 108 error This is probably not a problem with npm. There is likely additional logging output above.
> 109 verbose exit [ 100, true ]
> ```
> 
> Bitte um Hilfe.

mach es mit "sudo npm -i" in dem Ordner.. ich habe zusätzlich noch das map feature deaktviert und wieder aktiviert und den Key neu geladen

**Comment by Apollon77** [comment]
STTOOOPPPPPP!!!!!
Das Verzeichnis über was Ihr hier redet ist komplett das falsche!

Wenn ist es /opt/iobroker/node_modules/iobroker.mihome-vacuum

und dort ein "npm i"
