### ISSUE TITLE
Nach Update auf js-controller 3.0.18

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.mihome-vacuum#120]
kommt folgender Fehler:
`

mihome-vacuum.0 | 2020-04-24 14:17:59.259 | warn | (15990) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
mihome-vacuum.0 | 2020-04-24 14:17:59.258 | warn | (15990) Object mihome-vacuum.0.info.dnd is invalid: obj.common.type has  an invalid value (switch) but has to be one of number, string, boolean,  array, object, mixed, file, json

`

**Comment by dirkhe** [comment]
Ist in der aktuellen Version auf github bereis gefixt
