### ISSUE TITLE
2.0.9 grade von github installiert:  Adapter startet nicht

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.mihome-vacuum#121]
`

mihome-vacuum.0 | 2020-04-25 11:06:44.577 | debug | (28636) sendMsg[3] >>> {"id":3,"method":"get_status"}
-- | -- | -- | --
mihome-vacuum.0 | 2020-04-25 11:06:39.574 | debug | (28636) sendMsg[2] >>> {"id":3,"method":"get_status"}
mihome-vacuum.0 | 2020-04-25 11:06:34.574 | debug | (28636) sendMsg[1] >>> {"id":3,"method":"get_status"}
mihome-vacuum.0 | 2020-04-25 11:06:34.572 | debug | (28636) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2020-04-25 11:06:34.572 | info | (28636) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-04-25 11:06:34.572 | debug | (28636) Receive <<< Helo <<< 213100200000000005bfa9f25ea3fd9affffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2020-04-25 11:06:29.575 | debug | (28636) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2020-04-25 11:06:29.575 | debug | (28636) no answer for undefined(id:2) received, giving up
mihome-vacuum.0 | 2020-04-25 11:06:24.573 | debug | (28636) sendMsg[3] >>> {"id":2,"method":"get_status"}
mihome-vacuum.0 | 2020-04-25 11:06:19.573 | debug | (28636) sendMsg[2] >>> {"id":2,"method":"get_status"}
mihome-vacuum.0 | 2020-04-25 11:06:14.573 | debug | (28636) sendMsg[1] >>> {"id":2,"method":"get_status"}
mihome-vacuum.0 | 2020-04-25 11:06:14.570 | debug | (28636) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2020-04-25 11:06:14.570 | info | (28636) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-04-25 11:06:14.570 | debug | (28636) Receive <<< Helo <<< 213100200000000005bfa9f25ea3fd86ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2020-04-25 11:06:09.641 | debug | (28636) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2020-04-25 11:06:09.640 | debug | (28636) no answer for undefined(id:1) received, giving up
mihome-vacuum.0 | 2020-04-25 11:06:04.639 | debug | (28636) sendMsg[3] >>> {"id":1,"method":"get_status"}
mihome-vacuum.0 | 2020-04-25 11:05:59.638 | debug | (28636) sendMsg[2] >>> {"id":1,"method":"get_status"}
mihome-vacuum.0 | 2020-04-25 11:05:56.716 | debug | (28636) Xiaomi Cloud: Login successful
mihome-vacuum.0 | 2020-04-25 11:05:55.081 | info | (28636) set nächster Timer: Nicht verfügbar

`
![grafik](https://user-images.githubusercontent.com/34395245/80275967-77935b00-86e5-11ea-92f0-33180157f257.png)
![grafik](https://user-images.githubusercontent.com/34395245/80275977-8712a400-86e5-11ea-8770-d70cb7e1b3ea.png)

**Comment by dirkhe** [comment]
Einmal in die mihome App gehen, und ggf. Dann den adapter neu starten

**Comment by guergen1** [comment]
Könnte Dir jetzt 10 Minuten Log-Daten senden....
`

mihome-vacuum.0 | 2020-04-25 12:01:40.299 | info | (31165) starting. Version 2.0.9-RC07 in  /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.16.2,  js-controller: 3.0.18
-- | -- | -- | --


`
Mit der Xiaomi Home App habe ich den Robi zwischendurch zum Mülleimer fahren lassen, das ging.
Aber weder während noch nach dem fahren bringt der Start des Adapters nichts

**Comment by guergen1** [comment]
Hat grade mehr als 10 Minuten gedauert, aber es hat funktioniert!
