### ISSUE TITLE
dnd object invalid type

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.mihome-vacuum#122]
it tells me to report this ...

mihome-vacuum.0 | 2020-04-30 05:04:05.874 | warn | (1890) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
mihome-vacuum.0 | 2020-04-30 05:04:05.872 | warn | (1890) Object mihome-vacuum.0.info.dnd is invalid: obj.common.type has  an invalid value (switch) but has to be one of number, string, boolean,  array, object, mixed, file, json

**Comment by dirkhe** [comment]
Id already fixed in Current Version
