### ISSUE TITLE
Dot not green - no connection with cleaner

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.mihome-vacuum#123]
Hi .. I have some problems maintaining a green light .. the connection to the cleaner seems to get lost. I did update to 2.09 (former 2.07) but it doesn't help. Logfile looks good IMO (see below). I wonder of it's normal that the adapter is yellow when the cleaner is in standby?!

mihome-vacuum.0 | 2020-05-01 13:36:10.339 | info | (29585) set nächster Timer: Nicht verfügbar
-- | -- | -- | --
mihome-vacuum.0 | 2020-05-01 13:36:09.836 | info | (29585) New generation or new fw(3.5.0,003532) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2020-05-01 13:36:09.817 | info | (29585) Create state clean_home for controlling by cloud adapter
mihome-vacuum.0 | 2020-05-01 13:36:09.816 | info | (29585) Expert mode enabled, states created
mihome-vacuum.0 | 2020-05-01 13:36:09.791 | info | (29585) starting. Version 2.0.9-RC07 in  /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v10.20.1,  js-controller: 3.0.20
host.iobroker | 2020-05-01 13:36:06.702 | info | instance system.adapter.mihome-vacuum.0 started with pid 29585
host.iobroker | 2020-05-01 13:36:04.214 | info | instance system.adapter.mihome-vacuum.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
mihome-vacuum.0 | 2020-05-01 13:36:03.698 | info | (29089) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2020-05-01 13:36:03.697 | info | (29089) terminating
mihome-vacuum.0 | 2020-05-01 13:36:03.696 | info | (29089) Got terminate signal TERMINATE_YOURSELF
host.iobroker | 2020-05-01 13:36:03.693 | info | stopInstance system.adapter.mihome-vacuum.0 send kill signal

**Comment by daniel-lo** [comment]
I currently cannot exclude that my device has a problem. In case anything comes to anyones mind .. it's welcome of course :-)

**Comment by dirkhe** [comment]
Open your app and let the same minutes communicate. Than Restart adapter. If it Not Work, provide Log with debug Level

**Comment by daniel-lo** [comment]
ok .. turns green as soon as I adress it via app .. getting loads of these then:

2020-05-02 08:11:29.015 | debug | (7256) sendMsg[2] >>> {"id":31059,"method":"get_clean_record","params":[1575026375]}
-- | -- | --

Though my app does have problems acquiring status .. but that seems to be a different issue.

thanks

**Comment by daniel-lo** [comment]
deleting the object tree and restarting the adapter seems to have done some good .. I will observe if it's sustainable
