### ISSUE TITLE
Time difference

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.mihome-vacuum#124]
any idea how i can fix this:

(2175) Time difference between Mihome Vacuum and ioBroker: -1588470200 sec

**Comment by EddyDsSmartHome** [comment]
same message here

**Comment by linchen4000** [comment]
Same problem for me with a new S5 MAX. I'm not able to connect with the robot.

> 

(5173) no answer received after after 3 times -> pause miIO.info from request parameters, try again in one hour
--

**Comment by dirkhe** [comment]
I get this, if my robot has no connection to internet, which I wan't. SO if your robbot is connected via Internet to the china server, the time differnece warning is gone.

**Comment by dirkhe** [comment]
Can we close this issue?

**Comment by daniel-lo** [comment]
haven't seen it in a while .. so IMO yes
