### ISSUE TITLE
Could not receive Mappointer, giving up

### ISSUE THREAD

**Issue by Stefan592** [iobroker-community-adapters/ioBroker.mihome-vacuum#125]
Hi,

i have a s5 roborock with valetudo 0.4, firmware 01886 and adapter version 2.0.9.

I cant load the valetudo map or the rooms from the robot. All other statuses are received and commands can also be sent.

Log after press the "loadMap" button:

> 2020-05-05 10:28:51.651 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":36,"method":"get_room_mapping"}
--
2020-05-05 10:28:51.670 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":"unknown_method","id":36}
2020-05-05 10:28:54.978 - debug: mihome-vacuum.0 (4543) stateChange mihome-vacuum.0.map.loadMap {"val":true,"ack":false,"ts":1588667334973,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1588262582584}
2020-05-05 10:28:54.979 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":37,"method":"get_map_v1"}
2020-05-05 10:28:54.985 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":37}
2020-05-05 10:28:55.488 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":38,"method":"get_map_v1"}
2020-05-05 10:28:55.489 - debug: mihome-vacuum.0 (4543) 0. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:55.536 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":38}
2020-05-05 10:28:56.038 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":39,"method":"get_map_v1"}
2020-05-05 10:28:56.039 - debug: mihome-vacuum.0 (4543) 1. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:56.044 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":39}
2020-05-05 10:28:56.546 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":40,"method":"get_map_v1"}
2020-05-05 10:28:56.547 - debug: mihome-vacuum.0 (4543) 2. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:56.556 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":40}
2020-05-05 10:28:56.797 - debug: mihome-vacuum.0 (4543) system.adapter.admin.0: logging true
2020-05-05 10:28:57.058 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":41,"method":"get_map_v1"}
2020-05-05 10:28:57.058 - debug: mihome-vacuum.0 (4543) 3. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:57.062 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":41}
2020-05-05 10:28:57.544 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":42,"method":"get_status"}
2020-05-05 10:28:57.550 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":[{"msg_ver":2,"msg_seq":2582,"state":5,"battery":75,"clean_time":2571,"clean_area":53072500,"error_code":0,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0,"lab_status":1,"fan_power":75,"dnd_enabled":0}],"id":42}
2020-05-05 10:28:57.564 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":43,"method":"get_map_v1"}
2020-05-05 10:28:57.565 - debug: mihome-vacuum.0 (4543) 4. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:57.571 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":43}
2020-05-05 10:28:58.073 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":44,"method":"get_map_v1"}
2020-05-05 10:28:58.074 - debug: mihome-vacuum.0 (4543) 5. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:58.078 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":44}
2020-05-05 10:28:58.581 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":45,"method":"get_map_v1"}
2020-05-05 10:28:58.582 - debug: mihome-vacuum.0 (4543) 6. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:58.586 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":45}
2020-05-05 10:28:59.089 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":46,"method":"get_map_v1"}
2020-05-05 10:28:59.090 - debug: mihome-vacuum.0 (4543) 7. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:59.095 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":46}
2020-05-05 10:28:59.597 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":47,"method":"get_map_v1"}
2020-05-05 10:28:59.598 - debug: mihome-vacuum.0 (4543) 8. Mappointer_nomap___map_upload_handler
2020-05-05 10:28:59.603 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":47}
2020-05-05 10:29:00.105 - debug: mihome-vacuum.0 (4543) sendMsg[1] >>> {"id":48,"method":"get_map_v1"}
2020-05-05 10:29:00.106 - debug: mihome-vacuum.0 (4543) 9. Mappointer_nomap___map_upload_handler
2020-05-05 10:29:00.111 - debug: mihome-vacuum.0 (4543) Receive <<< {"result":["map_upload_handler"],"id":48}
2020-05-05 10:29:00.113 - warn: mihome-vacuum.0 (4543) Could not receive Mappointer, giving up

**Comment by hail0** [comment]
Hi,

same on my side. Enlosed the debug log files:

JS-Controller: 3.1.4
Node.js: v12.16.3 
Adapter: 2.0.9

`
mihome-vacuum.0 | 2020-05-27 16:08:23.188 | debug | (1597)  Receive <<<  {"result":[{"msg_ver":8,"msg_seq":17,"state":8,"battery":100,"clean_time":0,"clean_area":745000,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":63,"dnd_enabled":0}],"id":
-- | -- | -- | --
mihome-vacuum.0 | 2020-05-27 16:08:23.183 | debug | (1597) sendMsg[1] >>> {"id":63,"method":"get_status"}
mihome-vacuum.0 | 2020-05-27 16:08:03.187 | debug | (1597)  Receive <<<  {"result":[{"msg_ver":8,"msg_seq":16,"state":8,"battery":100,"clean_time":0,"clean_area":745000,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":63,"dnd_enabled":0}],"id":
mihome-vacuum.0 | 2020-05-27 16:08:03.182 | debug | (1597) sendMsg[1] >>> {"id":62,"method":"get_status"}
mihome-vacuum.0 | 2020-05-27 16:07:50.254 | warn | (1597) Could not receive Mappointer, giving up
mihome-vacuum.0 | 2020-05-27 16:07:50.254 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":61}
mihome-vacuum.0 | 2020-05-27 16:07:50.250 | debug | (1597) 9. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:50.250 | debug | (1597) sendMsg[1] >>> {"id":61,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:49.749 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":60}
mihome-vacuum.0 | 2020-05-27 16:07:49.745 | debug | (1597) 8. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:49.745 | debug | (1597) sendMsg[1] >>> {"id":60,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:49.244 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":59}
mihome-vacuum.0 | 2020-05-27 16:07:49.240 | debug | (1597) 7. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:49.240 | debug | (1597) sendMsg[1] >>> {"id":59,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:48.739 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":58}
mihome-vacuum.0 | 2020-05-27 16:07:48.735 | debug | (1597) 6. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:48.735 | debug | (1597) sendMsg[1] >>> {"id":58,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:48.234 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":57}
mihome-vacuum.0 | 2020-05-27 16:07:48.230 | debug | (1597) 5. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:48.229 | debug | (1597) sendMsg[1] >>> {"id":57,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:47.729 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":56}
mihome-vacuum.0 | 2020-05-27 16:07:47.725 | debug | (1597) 4. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:47.725 | debug | (1597) sendMsg[1] >>> {"id":56,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:47.224 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":55}
mihome-vacuum.0 | 2020-05-27 16:07:47.219 | debug | (1597) 3. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:47.219 | debug | (1597) sendMsg[1] >>> {"id":55,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:46.718 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":54}
mihome-vacuum.0 | 2020-05-27 16:07:46.713 | debug | (1597) 2. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:46.713 | debug | (1597) sendMsg[1] >>> {"id":54,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:46.212 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":53}
mihome-vacuum.0 | 2020-05-27 16:07:46.208 | debug | (1597) 1. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:46.208 | debug | (1597) sendMsg[1] >>> {"id":53,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:45.707 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":52}
mihome-vacuum.0 | 2020-05-27 16:07:45.694 | debug | (1597) 0. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:45.693 | debug | (1597) sendMsg[1] >>> {"id":52,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:45.192 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":51}
mihome-vacuum.0 | 2020-05-27 16:07:45.188 | debug | (1597) sendMsg[1] >>> {"id":51,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:43.693 | debug | (1597)  Receive <<<  {"result":[373752,5383752500,196,[1590412996,1590159774,1590047127,1589813020,1589812855,1589811915,1589811799,1589811788,1589811051,1589807988,1589807338,1589806003,1589805818,1589
mihome-vacuum.0 | 2020-05-27 16:07:43.687 | debug | (1597) sendMsg[1] >>> {"id":50,"method":"get_clean_summary"}
mihome-vacuum.0 | 2020-05-27 16:07:43.191 | debug | (1597)  Receive <<<  {"result":[{"main_brush_work_time":131848,"side_brush_work_time":30132,"filter_work_time":22124,"sensor_dirty_time":30126}],"id":49}
mihome-vacuum.0 | 2020-05-27 16:07:43.186 | debug | (1597) sendMsg[1] >>> {"id":49,"method":"get_consumable"}
mihome-vacuum.0 | 2020-05-27 16:07:43.185 | debug | (1597)  Receive <<<  {"result":[{"msg_ver":8,"msg_seq":15,"state":8,"battery":100,"clean_time":0,"clean_area":745000,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":63,"dnd_enabled":0}],"id":
mihome-vacuum.0 | 2020-05-27 16:07:43.180 | debug | (1597) sendMsg[1] >>> {"id":48,"method":"get_status"}
mihome-vacuum.0 | 2020-05-27 16:07:29.502 | warn | (1597) Could not receive Mappointer, giving up
mihome-vacuum.0 | 2020-05-27 16:07:29.502 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":47}
mihome-vacuum.0 | 2020-05-27 16:07:29.498 | debug | (1597) 9. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:29.498 | debug | (1597) sendMsg[1] >>> {"id":47,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:28.997 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":46}
mihome-vacuum.0 | 2020-05-27 16:07:28.993 | debug | (1597) 8. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:28.993 | debug | (1597) sendMsg[1] >>> {"id":46,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:28.492 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":45}
mihome-vacuum.0 | 2020-05-27 16:07:28.485 | debug | (1597) 7. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:28.485 | debug | (1597) sendMsg[1] >>> {"id":45,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:28.009 | debug | (1597)  CLEAN_LOGGING[{"Datum":"25.5","Start":"15:23","Saugzeit":"0  min","Fläche":"0.75  m²","Error":0,"Ende":false},{"Datum":"22.5","Start":"17:02","Saugzeit":"91  min","Fläche":"78.78 m²","Error":0,"En
mihome-vacuum.0 | 2020-05-27 16:07:27.986 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":44}
mihome-vacuum.0 | 2020-05-27 16:07:27.981 | debug | (1597) 6. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:27.981 | debug | (1597) sendMsg[1] >>> {"id":44,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:27.823 | debug | (1597) Receive <<< {"result":[[1589793516,1589794070,554,9877500,0,1]],"id":43}
mihome-vacuum.0 | 2020-05-27 16:07:27.809 | debug | (1597) sendMsg[1] >>> {"id":43,"method":"get_clean_record","params":[1589793516]}
mihome-vacuum.0 | 2020-05-27 16:07:27.614 | debug | (1597) Receive <<< {"result":[[1589796884,1589796954,0,1200000,0,0]],"id":42}
mihome-vacuum.0 | 2020-05-27 16:07:27.610 | debug | (1597) sendMsg[1] >>> {"id":42,"method":"get_clean_record","params":[1589796884]}
mihome-vacuum.0 | 2020-05-27 16:07:27.481 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":41}
mihome-vacuum.0 | 2020-05-27 16:07:27.477 | debug | (1597) 5. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:27.477 | debug | (1597) sendMsg[1] >>> {"id":41,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:27.413 | debug | (1597) Receive <<< {"result":[[1589801327,1589801603,276,4907500,0,1]],"id":40}
mihome-vacuum.0 | 2020-05-27 16:07:27.409 | debug | (1597) sendMsg[1] >>> {"id":40,"method":"get_clean_record","params":[1589801327]}
mihome-vacuum.0 | 2020-05-27 16:07:27.224 | debug | (1597) Receive <<< {"result":[[1589802735,1589802837,102,0,0,1]],"id":39}
mihome-vacuum.0 | 2020-05-27 16:07:27.208 | debug | (1597) sendMsg[1] >>> {"id":39,"method":"get_clean_record","params":[1589802735]}
mihome-vacuum.0 | 2020-05-27 16:07:27.012 | debug | (1597) Receive <<< {"result":[[1589804616,1589804632,0,0,0,0]],"id":38}
mihome-vacuum.0 | 2020-05-27 16:07:27.007 | debug | (1597) sendMsg[1] >>> {"id":38,"method":"get_clean_record","params":[1589804616]}
mihome-vacuum.0 | 2020-05-27 16:07:26.977 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":37}
mihome-vacuum.0 | 2020-05-27 16:07:26.973 | debug | (1597) 4. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:26.972 | debug | (1597) sendMsg[1] >>> {"id":37,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:26.811 | debug | (1597) Receive <<< {"result":[[1589804656,1589804717,0,1457500,0,0]],"id":36}
mihome-vacuum.0 | 2020-05-27 16:07:26.806 | debug | (1597) sendMsg[1] >>> {"id":36,"method":"get_clean_record","params":[1589804656]}
mihome-vacuum.0 | 2020-05-27 16:07:26.611 | debug | (1597) Receive <<< {"result":[[1589804971,1589804993,0,0,0,0]],"id":35}
mihome-vacuum.0 | 2020-05-27 16:07:26.606 | debug | (1597) sendMsg[1] >>> {"id":35,"method":"get_clean_record","params":[1589804971]}
mihome-vacuum.0 | 2020-05-27 16:07:26.472 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":34}
mihome-vacuum.0 | 2020-05-27 16:07:26.466 | debug | (1597) 3. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:26.466 | debug | (1597) sendMsg[1] >>> {"id":34,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:26.415 | debug | (1597) Receive <<< {"result":[[1589805818,1589805869,0,380000,0,0]],"id":33}
mihome-vacuum.0 | 2020-05-27 16:07:26.406 | debug | (1597) sendMsg[1] >>> {"id":33,"method":"get_clean_record","params":[1589805818]}
mihome-vacuum.0 | 2020-05-27 16:07:26.211 | debug | (1597) Receive <<< {"result":[[1589806003,1589806009,0,0,0,0]],"id":32}
mihome-vacuum.0 | 2020-05-27 16:07:26.206 | debug | (1597) sendMsg[1] >>> {"id":32,"method":"get_clean_record","params":[1589806003]}
mihome-vacuum.0 | 2020-05-27 16:07:26.010 | debug | (1597) Receive <<< {"result":[[1589807338,1589807420,0,1222500,0,0]],"id":31}
mihome-vacuum.0 | 2020-05-27 16:07:26.005 | debug | (1597) sendMsg[1] >>> {"id":31,"method":"get_clean_record","params":[1589807338]}
mihome-vacuum.0 | 2020-05-27 16:07:25.965 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":30}
mihome-vacuum.0 | 2020-05-27 16:07:25.958 | debug | (1597) 2. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:25.958 | debug | (1597) sendMsg[1] >>> {"id":30,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:25.811 | debug | (1597) Receive <<< {"result":[[1589807988,1589808017,0,565000,0,0]],"id":29}
mihome-vacuum.0 | 2020-05-27 16:07:25.805 | debug | (1597) sendMsg[1] >>> {"id":29,"method":"get_clean_record","params":[1589807988]}
mihome-vacuum.0 | 2020-05-27 16:07:25.609 | debug | (1597) Receive <<< {"result":[[1589811051,1589811123,12,0,0,0]],"id":28}
mihome-vacuum.0 | 2020-05-27 16:07:25.604 | debug | (1597) sendMsg[1] >>> {"id":28,"method":"get_clean_record","params":[1589811051]}
mihome-vacuum.0 | 2020-05-27 16:07:25.457 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":27}
mihome-vacuum.0 | 2020-05-27 16:07:25.448 | debug | (1597) 1. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:25.448 | debug | (1597) sendMsg[1] >>> {"id":27,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:25.410 | debug | (1597) Receive <<< {"result":[[1589811788,1589811799,9,0,0,0]],"id":26}
mihome-vacuum.0 | 2020-05-27 16:07:25.403 | debug | (1597) sendMsg[1] >>> {"id":26,"method":"get_clean_record","params":[1589811788]}
mihome-vacuum.0 | 2020-05-27 16:07:25.206 | debug | (1597) Receive <<< {"result":[[1589811799,1589811812,13,0,0,1]],"id":25}
mihome-vacuum.0 | 2020-05-27 16:07:25.202 | debug | (1597) sendMsg[1] >>> {"id":25,"method":"get_clean_record","params":[1589811799]}
mihome-vacuum.0 | 2020-05-27 16:07:25.006 | debug | (1597) Receive <<< {"result":[[1589811915,1589812051,8,0,0,0]],"id":24}
mihome-vacuum.0 | 2020-05-27 16:07:25.001 | debug | (1597) sendMsg[1] >>> {"id":24,"method":"get_clean_record","params":[1589811915]}
mihome-vacuum.0 | 2020-05-27 16:07:24.947 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":23}
mihome-vacuum.0 | 2020-05-27 16:07:24.893 | debug | (1597) 0. Mappointer_nomap___map_upload_handler
mihome-vacuum.0 | 2020-05-27 16:07:24.893 | debug | (1597) sendMsg[1] >>> {"id":23,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:24.805 | debug | (1597) Receive <<< {"result":[[1589812855,1589813020,137,2762500,0,0]],"id":22}
mihome-vacuum.0 | 2020-05-27 16:07:24.800 | debug | (1597) sendMsg[1] >>> {"id":22,"method":"get_clean_record","params":[1589812855]}
mihome-vacuum.0 | 2020-05-27 16:07:24.604 | debug | (1597) Receive <<< {"result":[[1589813020,1589813058,0,0,0,0]],"id":21}
mihome-vacuum.0 | 2020-05-27 16:07:24.599 | debug | (1597) sendMsg[1] >>> {"id":21,"method":"get_clean_record","params":[1589813020]}
mihome-vacuum.0 | 2020-05-27 16:07:24.404 | debug | (1597) Receive <<< {"result":[[1590047127,1590047214,38,467500,0,0]],"id":20}
mihome-vacuum.0 | 2020-05-27 16:07:24.398 | debug | (1597) sendMsg[1] >>> {"id":20,"method":"get_clean_record","params":[1590047127]}
mihome-vacuum.0 | 2020-05-27 16:07:24.392 | debug | (1597) Receive <<< {"result":["map_upload_handler"],"id":19}
mihome-vacuum.0 | 2020-05-27 16:07:24.389 | debug | (1597) sendMsg[1] >>> {"id":19,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-05-27 16:07:24.202 | debug | (1597) Receive <<< {"result":[[1590159774,1590165262,5454,78777500,0,1]],"id":18}
mihome-vacuum.0 | 2020-05-27 16:07:24.198 | debug | (1597) sendMsg[1] >>> {"id":18,"method":"get_clean_record","params":[1590159774]}
mihome-vacuum.0 | 2020-05-27 16:07:24.196 | debug | (1597) Receive <<< {"result":"unknown_method","id":17}
mihome-vacuum.0 | 2020-05-27 16:07:24.196 | info | (1597) create state for carpet_mode
mihome-vacuum.0 | 2020-05-27 16:07:24.196 | debug | (1597)  Receive <<<  {"result":[{"enable":0,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}],"id":16}
mihome-vacuum.0 | 2020-05-27 16:07:24.189 | debug | (1597) sendMsg[1] >>> {"id":17,"method":"get_room_mapping"}
mihome-vacuum.0 | 2020-05-27 16:07:24.189 | debug | (1597) sendMsg[1] >>> {"id":16,"method":"get_carpet_mode"}
mihome-vacuum.0 | 2020-05-27 16:07:24.002 | debug | (1597) Receive <<< {"result":[[1590412996,1590413044,0,745000,0,0]],"id":15}
mihome-vacuum.0 | 2020-05-27 16:07:23.996 | debug | (1597) sendMsg[1] >>> {"id":15,"method":"get_clean_record","params":[1590412996]}
mihome-vacuum.0 | 2020-05-27 16:07:23.995 | debug | (1597)  Receive <<<  {"result":[373752,5383752500,196,[1590412996,1590159774,1590047127,1589813020,1589812855,1589811915,1589811799,1589811788,1589811051,1589807988,1589807338,1589806003,1589805818,1589
mihome-vacuum.0 | 2020-05-27 16:07:23.988 | debug | (1597) sendMsg[1] >>> {"id":14,"method":"get_clean_summary"}
mihome-vacuum.0 | 2020-05-27 16:07:23.794 | debug | (1597)  Receive <<<  {"result":[{"main_brush_work_time":131848,"side_brush_work_time":30132,"filter_work_time":22124,"sensor_dirty_time":30126}],"id":13}
mihome-vacuum.0 | 2020-05-27 16:07:23.789 | debug | (1597) sendMsg[1] >>> {"id":13,"method":"get_consumable"}
mihome-vacuum.0 | 2020-05-27 16:07:23.596 | debug | (1597) Receive <<< {"result":[80],"id":12}
mihome-vacuum.0 | 2020-05-27 16:07:23.589 | debug | (1597) sendMsg[1] >>> {"id":12,"method":"get_sound_volume"}
mihome-vacuum.0 | 2020-05-27 16:07:23.395 | debug | (1597)  Receive <<<  {"partner_id":"","id":11,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.3.9_003468","ap":{"ssid":"Roundhousekick","bssid":"44:4E:6D:2C:FC:F0","rssi":-68},"netif":{"l
mihome-vacuum.0 | 2020-05-27 16:07:23.390 | debug | (1597) Next WiFi check: 27.05 16:08
mihome-vacuum.0 | 2020-05-27 16:07:23.389 | debug | (1597) sendMsg[1] >>> {"id":11,"method":"miIO.info"}
mihome-vacuum.0 | 2020-05-27 16:07:23.189 | info | (1597) Connected
`

**Comment by Schattenruf** [comment]
Also mentioned in issue #167

**Comment by AdrianFajt** [comment]
Hi all,

I have the same problem as well with a Valetudo version 2021.01.1. 
Adapter version is 2.2.4. 

Is there any approach to solve this?

Thanks

**Comment by MeisterTR** [comment]
normal cloud map should be fixed, valetudo only >= V0.6
