### ISSUE TITLE
No connection new FW 01.17.08 for 6S

### ISSUE THREAD

**Issue by MrDuFF85** [iobroker-community-adapters/ioBroker.mihome-vacuum#126]
There is a new firmware for the Roborock S6, this can now save different floors.

Unfortunately I can no longer connect to the adapter.
The traffic light remains yellow.

Debug:

`

mihome-vacuum.0 | 2020-05-06 09:20:35.736 | debug | (21803) Xiaomi Cloud: Login successful
-- | -- | -- | --
mihome-vacuum.0 | 2020-05-06 09:20:33.960 | info | (21803) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2020-05-06 09:20:33.608 | debug | (21803) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
mihome-vacuum.0 | 2020-05-06 09:20:33.594 | info | (21803) New generation or new fw(3.5.8,1708) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2020-05-06 09:20:33.593 | info | (21803) extend state mop for State control.fan_power
mihome-vacuum.0 | 2020-05-06 09:20:33.591 | info | (21803) change states from State control.fan_power
mihome-vacuum.0 | 2020-05-06 09:20:33.446 | debug | (21803) server started on 0.0.0.0:54321
mihome-vacuum.0 | 2020-05-06 09:20:33.430 | info | (21803) Create state clean_home for controlling by cloud adapter
mihome-vacuum.0 | 2020-05-06 09:20:33.428 | info | (21803) Expert mode enabled, states created
mihome-vacuum.0 | 2020-05-06 09:20:33.415 | debug | (21803) Xiaomi Cloud: Logging in
mihome-vacuum.0 | 2020-05-06 09:20:33.413 | debug | (21803) load Map creator... true
mihome-vacuum.0 | 2020-05-06 09:20:33.324 | info | (21803) starting. Version 2.0.9-RC07 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.1.0, js-controller: 3.0.20
mihome-vacuum.0 | 2020-05-06 09:20:28.382 | info | (21781) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2020-05-06 09:20:28.380 | info | (21781) terminating
mihome-vacuum.0 | 2020-05-06 09:20:28.379 | info | (21781) Got terminate signal TERMINATE_YOURSELF
mihome-vacuum.0 | 2020-05-06 09:18:29.808 | debug | (21781) system.adapter.admin.0: logging true
mihome-vacuum.0 | 2020-05-06 09:18:24.582 | debug | (21781) sendTo "discovery" to system.adapter.admin.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2020-05-06 09:18:24.581 | debug | (21781) discover__[{"did":"262090561","token":"7662353058766f67497068623658754d","longitude":"0.00000000","latitude":"0.00000000","name":"Roborock S6","pid":"0","localip":"192.168.1.136","mac":"50:EC
mihome-vacuum.0 | 2020-05-06 09:18:24.579 | debug | (21781) {"code":0,"message":"ok","result":{"list":[{"did":"262090561","token":"7662353058766f67497068623658754d","longitude":"0.00000000","latitude":"0.00000000","name":"Roborock S6","pid":"0","local
mihome-vacuum.0 | 2020-05-06 09:18:24.433 | debug | (21781) GET devices from:https://de.api.io.mi.com/app/home/device_list
mihome-vacuum.0 | 2020-05-06 09:18:24.427 | debug | (21781) Xiaomi Cloud: Login successful
mihome-vacuum.0 | 2020-05-06 09:18:23.906 | debug | (21781) system.adapter.admin.0: logging false
mihome-vacuum.0 | 2020-05-06 09:18:22.653 | debug | (21781) Xiaomi Cloud: Logging in
mihome-vacuum.0 | 2020-05-06 09:17:55.849 | debug | (21781) Xiaomi Cloud: Login successful
mihome-vacuum.0 | 2020-05-06 09:17:53.980 | info | (21781) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2020-05-06 09:17:53.718 | debug | (21781) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
mihome-vacuum.0 | 2020-05-06 09:17:53.707 | info | (21781) New generation or new fw(3.5.8,1708) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2020-05-06 09:17:53.702 | info | (21781) extend state mop for State control.fan_power
mihome-vacuum.0 | 2020-05-06 09:17:53.701 | info | (21781) change states from State control.fan_power
mihome-vacuum.0 | 2020-05-06 09:17:53.465 | debug | (21781) server started on 0.0.0.0:54321

`

**Comment by dirkhe** [comment]
Please Show Log, where we can see, how the adapter try to Connect to the robot

**Comment by ericsboro** [comment]
I have the same problem. once at the very beginning adapter successfully connected, but in a minute got disconnected and I get the same debug log.

**Comment by ericsboro** [comment]
here's what i have in debug log:
2020-05-26 17:22:17.745  - [34mdebug[39m: mihome-vacuum.0 (12694) Redis Objects: Use Redis connection: 0.0.0.0:9001
2020-05-26 17:22:17.896  - [34mdebug[39m: mihome-vacuum.0 (12694) Objects client ready ... initialize now
2020-05-26 17:22:17.899  - [34mdebug[39m: mihome-vacuum.0 (12694) Objects create System PubSub Client
2020-05-26 17:22:17.900  - [34mdebug[39m: mihome-vacuum.0 (12694) Objects create User PubSub Client
2020-05-26 17:22:17.900  - [34mdebug[39m: mihome-vacuum.0 (12694) Objects client initialize lua scripts
2020-05-26 17:22:17.908  - [34mdebug[39m: mihome-vacuum.0 (12694) Objects connected to redis: 0.0.0.0:9001
2020-05-26 17:22:17.912  - [34mdebug[39m: mihome-vacuum.0 (12694) objectDB connected
2020-05-26 17:22:17.915  - [34mdebug[39m: mihome-vacuum.0 (12694) Redis States: Use Redis connection: 0.0.0.0:9000
2020-05-26 17:22:17.929  - [34mdebug[39m: mihome-vacuum.0 (12694) States create User PubSub Client
2020-05-26 17:22:17.930  - [34mdebug[39m: mihome-vacuum.0 (12694) States create System PubSub Client
2020-05-26 17:22:17.936  - [34mdebug[39m: mihome-vacuum.0 (12694) States connected to redis: 0.0.0.0:9000
2020-05-26 17:22:17.937  - [34mdebug[39m: mihome-vacuum.0 (12694) statesDB connected
2020-05-26 17:22:20.087  - [32minfo[39m: mihome-vacuum.0 (12694) starting. Version 2.0.9-RC07 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.16.3, js-controller: 3.1.4
2020-05-26 17:22:20.122  - [34mdebug[39m: mihome-vacuum.0 (12694) load Map creator... true
2020-05-26 17:22:20.123  - [34mdebug[39m: mihome-vacuum.0 (12694) Xiaomi Cloud: Logging in
2020-05-26 17:22:20.129  - [32minfo[39m: mihome-vacuum.0 (12694) Expert mode disabled, states deleted
2020-05-26 17:22:20.130  - [32minfo[39m: mihome-vacuum.0 (12694) Cloud control disabled
2020-05-26 17:22:20.137  - [34mdebug[39m: mihome-vacuum.0 (12694) server started on 0.0.0.0:53421
2020-05-26 17:22:20.179  - [34mdebug[39m: mihome-vacuum.0 (12694) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
2020-05-26 17:22:20.648  - [32minfo[39m: mihome-vacuum.0 (12694) set next timer: not available
2020-05-26 17:22:22.424  - [34mdebug[39m: mihome-vacuum.0 (12694) Xiaomi Cloud: Login successful

**Comment by dirkhe** [comment]
Please Show Log, where we can see, how the adapter try to Connect to the robot. In both Log I don't See any connecting to the robot, only to Cloud

**Comment by ericsboro** [comment]
I think I found the issue. I did reconnect robot with new token from latest version of modified Mi-home app and it worked properly. But after that I switched back to Roborock app on my iPhone (to be able to use new room-cleaning-order feature) robot got disconnected from iobroker.

**Comment by ericsboro** [comment]
here's the log:

mihome-vacuum.0 | 2020-05-28 11:45:09.038 | warn | (7408) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
mihome-vacuum.0 | 2020-05-28 11:45:09.038 | warn | (7408) Object mihome-vacuum.0.info.water_box is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:45:09.033 | info | (7408) create states for water box filter
mihome-vacuum.0 | 2020-05-28 11:45:09.032 | info | (7408) create states for water box
mihome-vacuum.0 | 2020-05-28 11:44:50.043 | info | (7408) create state for carpet_mode
mihome-vacuum.0 | 2020-05-28 11:44:49.035 | info | (7408) Connected
mihome-vacuum.0 | 2020-05-28 11:44:49.023 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:44:29.023 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:44:09.391 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:43:49.019 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:43:29.018 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:43:09.019 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:42:49.015 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:42:29.015 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:42:09.013 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:41:49.011 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:41:29.011 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:41:09.010 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:40:49.520 | info | (7408) set next timer: not available
mihome-vacuum.0 | 2020-05-28 11:40:49.046 | info | (7408) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:40:49.028 | info | (7408) New generation or new fw(3.5.8,1708) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2020-05-28 11:40:49.024 | info | (7408) extend state mop for State control.fan_power
mihome-vacuum.0 | 2020-05-28 11:40:49.019 | info | (7408) change states from State control.fan_power
mihome-vacuum.0 | 2020-05-28 11:40:49.000 | info | (7408) Cloud control disabled
mihome-vacuum.0 | 2020-05-28 11:40:48.999 | info | (7408) Expert mode disabled, states deleted
mihome-vacuum.0 | 2020-05-28 11:40:48.980 | info | (7408) starting. Version 2.0.9-RC07 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.16.3, js-controller: 3.1.4
mihome-vacuum.0 | 2020-05-28 11:40:19.663 | info | (7373) Terminated (NO_ERROR): Without reason
mihome-vacuum.0 | 2020-05-28 11:40:19.663 | info | (7373) terminating
mihome-vacuum.0 | 2020-05-28 11:40:19.660 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.660 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.660 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.659 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.659 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.659 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.627 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.626 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.626 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.626 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.626 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.626 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.626 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.625 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.625 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.625 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.625 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.624 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.624 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.624 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.624 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.624 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.623 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.623 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.623 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.623 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.622 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.622 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.622 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.621 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.620 | error | (7373) TypeError: Cannot read property 'id' of undefined at /opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/roomManager.js:250:52 at setObjectWithDefaultValue (/opt/iobroker/node_modules
mihome-vacuum.0 | 2020-05-28 11:40:19.616 | error | (7373) unhandled promise rejection: Cannot read property 'id' of undefined
mihome-vacuum.0 | 2020-05-28 11:40:19.616 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2020-05-28 11:40:19.497 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.496 | warn | (7373) Object mihome-vacuum.0.rooms.853001008472.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.493 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.493 | warn | (7373) Object mihome-vacuum.0.rooms.853001008470.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.493 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.492 | warn | (7373) Object mihome-vacuum.0.rooms.853001008467.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.492 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.491 | warn | (7373) Object mihome-vacuum.0.rooms.853001008474.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.491 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.490 | warn | (7373) Object mihome-vacuum.0.rooms.853001008466.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.490 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.489 | warn | (7373) Object mihome-vacuum.0.rooms.853001008515.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.489 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.489 | warn | (7373) Object mihome-vacuum.0.rooms.853001008447.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.488 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.488 | warn | (7373) Object mihome-vacuum.0.rooms.853001008473.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.487 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.487 | warn | (7373) Object mihome-vacuum.0.rooms.853001008469.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.486 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.486 | warn | (7373) Object mihome-vacuum.0.rooms.853001008380.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.485 | warn | (7373) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2020-05-28 11:40:19.485 | warn | (7373) Object mihome-vacuum.0.rooms.853001008514.state is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-05-28 11:40:19.444 | info | (7373) create new room: 853001008472
mihome-vacuum.0 | 2020-05-28 11:40:19.444 | info | (7373) create new room: 853001008470
mihome-vacuum.0 | 2020-05-28 11:40:19.444 | info | (7373) create new room: 853001008467
mihome-vacuum.0 | 2020-05-28 11:40:19.443 | info | (7373) create new room: 853001008474
mihome-vacuum.0 | 2020-05-28 11:40:19.443 | info | (7373) create new room: 853001008466
mihome-vacuum.0 | 2020-05-28 11:40:19.443 | info | (7373) create new room: 853001008515
mihome-vacuum.0 | 2020-05-28 11:40:19.442 | info | (7373) create new room: 853001008447
mihome-vacuum.0 | 2020-05-28 11:40:19.442 | info | (7373) create new room: 853001008473
mihome-vacuum.0 | 2020-05-28 11:40:19.441 | info | (7373) create new room: 853001008469
mihome-vacuum.0 | 2020-05-28 11:40:19.441 | info | (7373) create new room: 853001008380
mihome-vacuum.0 | 2020-05-28 11:40:19.440 | info | (7373) create new room: 853001008514
mihome-vacuum.0 | 2020-05-28 11:40:19.428 | info | (7373) create state for carpet_mode
mihome-vacuum.0 | 2020-05-28 11:40:18.874 | info | (7373) set next timer: not available
mihome-vacuum.0 | 2020-05-28 11:40:18.630 | info | (7373) extend state mop for State control.fan_power
mihome-vacuum.0 | 2020-05-28 11:40:18.629 | info | (7373) change states from State control.fan_power
mihome-vacuum.0 | 2020-05-28 11:40:18.627 | info | (7373) New generation or new fw(3.5.8,1708) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2020-05-28 11:40:18.419 | info | (7373) Connected
mihome-vacuum.0 | 2020-05-28 11:40:18.377 | info | (7373) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-05-28 11:40:18.351 | info | (7373) Cloud control disabled
mihome-vacuum.0 | 2020-05-28 11:40:18.349 | info | (7373) Expert mode disabled, states deleted
mihome-vacuum.0 | 2020-05-28 11:40:18.330 | info | (7373) starting. Version 2.0.9-RC07 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.16.3, js-controller: 3.1.4

**Comment by MrDuFF85** [comment]
can be closed . the error only occurs with the roborock app which is not supported.
It works again with the xiaomi app.
