### ISSUE TITLE
cannot install running raspberry under buster

### ISSUE THREAD

**Issue by Marty56** [iobroker-community-adapters/ioBroker.mihome-vacuum#129]
Installation is failing

`

host.ioBroker-RasPi4 | 2020-05-11 09:33:18.752 | info | iobroker exit 25
-- | -- | -- | --
host.ioBroker-RasPi4 | 2020-05-11 09:33:17.714 | error | iobroker host.ioBroker-RasPi4 Cannot install iobroker.mihome-vacuum@2.0.7: 1
host.ioBroker-RasPi4 | 2020-05-11 09:33:17.636 | info | iobroker npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2020-05-11T07_33_17_530Z-debug.log
host.ioBroker-RasPi4 | 2020-05-11 09:33:17.632 | info | iobroker
host.ioBroker-RasPi4 | 2020-05-11 09:33:17.502 | info | iobroker ERR! npm ERR! Failed at the canvas@2.6.1 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
host.ioBroker-RasPi4 | 2020-05-11 09:33:17.489 | info | iobroker
host.ioBroker-RasPi4 | 2020-05-11 09:33:17.475 | info | iobroker ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`npm ERR! Exit status 1npm
host.ioBroker-RasPi4 | 2020-05-11 09:33:17.469 | info | iobroker npm
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.970 | info | iobroker node-pre-gyp ERR! not ok
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.963 | info | iobroker node-pre-gyp ERR! System Linux 4.19.97-v7+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.958 | info | iobroker ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/bu
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.952 | info | iobroker ERR! build error node-pre-gyp
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.948 | info | iobroker node-pre-gyp
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.923 | info | iobroker ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.905 | info | iobroker gyp
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.854 | info | iobroker gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
host.ioBroker-RasPi4 | 2020-05-11 09:33:10.843 | info | iobroker Package pixman-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `pixman-1.pc'to the PKG_CONFIG_PATH environment variableNo package 'pixman-1' foun
host.ioBroker-RasPi4 | 2020-05-11 09:32:04.944 | info | iobroker npm install iobroker.mihome-vacuum@2.0.7 --loglevel error --prefix "/opt/iobroker" (System call)
host.ioBroker-RasPi4 | 2020-05-11 09:32:04.938 | info | iobroker NPM version: 6.14.4
host.ioBroker-RasPi4 | 2020-05-11 09:31:56.128 | info | iobroker add mihome-vacuum --host ioBroker-RasPi4

`

I have also tried to apply the additional installs 

`
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
sudo npm install canvas --unsafe-perm=true
`
but they failed as well

`pi@ioBroker-RasPi4:~ $ sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
build-essential ist schon die neueste Version (12.6).
Die folgenden zusätzlichen Pakete werden installiert:
  gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-harfbuzz-0.0
  gir1.2-pango-1.0 gir1.2-rsvg-2.0 icu-devtools libblkid-dev
  libcairo-script-interpreter2 libffi-dev libfontconfig1-dev libfribidi-dev
  libgdk-pixbuf2.0-dev libgif7 libgirepository-1.0-1 libglib2.0-bin
  libglib2.0-dev libglib2.0-dev-bin libgraphite2-dev libharfbuzz-dev
  libharfbuzz-gobject0 libharfbuzz-icu0 libice-dev libicu-dev
  libjpeg62-turbo-dev liblzo2-2 libmount-dev libpangoxft-1.0-0 libpcre16-3
  libpcre3-dev libpcre32-3 libpcrecpp0v5 libpixman-1-dev libpthread-stubs0-dev
  libselinux1-dev libsepol1-dev libsm-dev libx11-dev libxau-dev
  libxcb-render0-dev libxcb-shm0-dev libxcb1-dev libxdmcp-dev libxext-dev
  libxft-dev libxrender-dev pango1.0-tools python3-distutils python3-lib2to3
  uuid-dev x11proto-core-dev x11proto-dev x11proto-xext-dev xorg-sgml-doctools
  xtrans-dev
Vorgeschlagene Pakete:
  libcairo2-doc libglib2.0-doc libxml2-utils libgraphite2-utils libice-doc
  icu-doc imagemagick libpango1.0-doc librsvg2-doc libsm-doc libx11-doc
  libxcb-doc libxext-doc
Die folgenden NEUEN Pakete werden installiert:
  gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-harfbuzz-0.0
  gir1.2-pango-1.0 gir1.2-rsvg-2.0 icu-devtools libblkid-dev
  libcairo-script-interpreter2 libcairo2-dev libffi-dev libfontconfig1-dev
  libfribidi-dev libgdk-pixbuf2.0-dev libgif-dev libgif7 libgirepository-1.0-1
  libglib2.0-bin libglib2.0-dev libglib2.0-dev-bin libgraphite2-dev
  libharfbuzz-dev libharfbuzz-gobject0 libharfbuzz-icu0 libice-dev libicu-dev
  libjpeg-dev libjpeg62-turbo-dev liblzo2-2 libmount-dev libpango1.0-dev
  libpangoxft-1.0-0 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5
  libpixman-1-dev libpthread-stubs0-dev librsvg2-dev libselinux1-dev
  libsepol1-dev libsm-dev libx11-dev libxau-dev libxcb-render0-dev
  libxcb-shm0-dev libxcb1-dev libxdmcp-dev libxext-dev libxft-dev
  libxrender-dev pango1.0-tools python3-distutils python3-lib2to3 uuid-dev
  x11proto-core-dev x11proto-dev x11proto-xext-dev xorg-sgml-doctools
  xtrans-dev
0 aktualisiert, 60 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 22,2 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 78,4 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
Holen:1 http://archive.raspberrypi.org/debian buster/main armhf libcairo-script-interpreter2 armhf 1.16.0-4+rpt1 [150 kB]
Holen:3 http://archive.raspberrypi.org/debian buster/main armhf libpixman-1-dev armhf 0.36.0-1+rpt1 [498 kB]
Holen:4 http://archive.raspberrypi.org/debian buster/main armhf libcairo2-dev armhf 1.16.0-4+rpt1 [618 kB]
Holen:2 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libgirepository-1.0-1 armhf 1.58.3-2 [78,8 kB]
Holen:5 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf gir1.2-glib-2.0 armhf 1.58.3-2 [143 kB]
Holen:6 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf gir1.2-freedesktop armhf 1.58.3-2 [20,3 kB]
Holen:7 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf gir1.2-gdkpixbuf-2.0 armhf 2.38.1+dfsg-1 [18,3 kB]
Holen:8 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libharfbuzz-gobject0 armhf 2.3.1-1 [845 kB]
Holen:9 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf gir1.2-harfbuzz-0.0 armhf 2.3.1-1 [853 kB]
Fehl:10 http://raspbian.raspberrypi.org/raspbian buster/main armhf libpangoxft-1.0-0 armhf 1.42.4-7~deb10u1
  404  Not Found [IP: 93.93.128.193 80]
Fehl:11 http://raspbian.raspberrypi.org/raspbian buster/main armhf gir1.2-pango-1.0 armhf 1.42.4-7~deb10u1
  404  Not Found [IP: 93.93.128.193 80]
Holen:12 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf gir1.2-rsvg-2.0 armhf 2.44.10-2.1+rpi1 [22,0 kB]
Holen:13 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf icu-devtools armhf 63.1-6+deb10u1 [163 kB]
Holen:14 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf uuid-dev armhf 2.33.1-0.1 [92,4 kB]
Holen:15 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libblkid-dev armhf 2.33.1-0.1 [210 kB]
Holen:16 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf liblzo2-2 armhf 2.10-0.1 [48,4 kB]
Holen:17 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libfontconfig1-dev armhf 2.13.1-2 [943 kB]
Holen:18 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf xorg-sgml-doctools all 1:1.11-1 [21,9 kB]
Holen:19 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf x11proto-dev all 2018.4-4 [251 kB]
Holen:20 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf x11proto-core-dev all 2018.4-4 [3.128 B]
Holen:21 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxau-dev armhf 1:1.0.8-1+b2 [22,4 kB]
Holen:22 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxdmcp-dev armhf 1:1.1.2-3 [40,9 kB]
Holen:23 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf xtrans-dev all 1.3.5-1 [100 kB]
Holen:24 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libpthread-stubs0-dev armhf 0.4-1 [5.344 B]
Holen:25 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxcb1-dev armhf 1.13.1-2 [169 kB]
Holen:26 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libx11-dev armhf 2:1.6.7-1 [760 kB]
Holen:27 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxrender-dev armhf 1:0.9.10-1 [37,7 kB]
Holen:28 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf x11proto-xext-dev all 2018.4-4 [3.128 B]
Holen:29 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxext-dev armhf 2:1.3.3-1+b2 [102 kB]
Holen:30 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libice-dev armhf 2:1.0.9-2 [58,8 kB]
Holen:31 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libsm-dev armhf 2:1.2.3-1 [35,4 kB]
Holen:32 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxcb-render0-dev armhf 1.13.1-2 [111 kB]
Holen:33 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxcb-shm0-dev armhf 1.13.1-2 [100 kB]
Holen:34 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libffi-dev armhf 3.2.1-9 [159 kB]
Holen:35 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libglib2.0-bin armhf 2.58.3-2+deb10u2 [117 kB]
Holen:36 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf python3-lib2to3 all 3.7.3-1 [76,7 kB]
Holen:37 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf python3-distutils all 3.7.3-1 [142 kB]
Holen:38 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libglib2.0-dev-bin armhf 2.58.3-2+deb10u2 [155 kB]
Holen:39 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libmount-dev armhf 2.33.1-0.1 [209 kB]
Holen:40 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libpcre16-3 armhf 2:8.39-12 [234 kB]
Holen:41 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libpcre32-3 armhf 2:8.39-12 [227 kB]
Holen:42 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libpcrecpp0v5 armhf 2:8.39-12 [150 kB]
Holen:43 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libpcre3-dev armhf 2:8.39-12 [564 kB]
Holen:44 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libsepol1-dev armhf 2.8-1 [309 kB]
Holen:45 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libselinux1-dev armhf 2.8-1+b1 [156 kB]
Holen:46 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libglib2.0-dev armhf 2.58.3-2+deb10u2 [1.372 kB]
Holen:47 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libfribidi-dev armhf 1.0.5-3.1+deb10u1 [99,3 kB]
Holen:48 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libgdk-pixbuf2.0-dev armhf 2.38.1+dfsg-1 [49,5 kB]
Holen:49 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libgif7 armhf 5.1.4-3 [41,0 kB]
Holen:50 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libgif-dev armhf 5.1.4-3 [43,4 kB]
Holen:51 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libgraphite2-dev armhf 1.3.13-7 [23,1 kB]
Holen:52 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libharfbuzz-icu0 armhf 2.3.1-1 [833 kB]
Holen:53 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libicu-dev armhf 63.1-6+deb10u1 [8.841 kB]
Fehl:58 http://raspbian.raspberrypi.org/raspbian buster/main armhf pango1.0-tools armhf 1.42.4-7~deb10u1
  404  Not Found [IP: 93.93.128.193 80]
Fehl:59 http://raspbian.raspberrypi.org/raspbian buster/main armhf libpango1.0-dev armhf 1.42.4-7~deb10u1
  404  Not Found [IP: 93.93.128.193 80]
Holen:54 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libharfbuzz-dev armhf 2.3.1-1 [1.244 kB]
Holen:55 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libjpeg62-turbo-dev armhf 1:1.5.2-2+b1 [179 kB]
Holen:56 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libjpeg-dev all 1:1.5.2-2 [57,5 kB]
Holen:57 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf libxft-dev armhf 2.3.2-2 [60,3 kB]
Holen:60 http://debian.bio.lmu.de/raspbian/raspbian buster/main armhf librsvg2-dev armhf 2.44.10-2.1+rpi1 [42,1 kB]
Es wurden 21,9 MB in 11 s geholt (1.991 kB/s).                                 
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/p/pango1.0/libpangoxft-1.0-0_1.42.4-7~deb10u1_armhf.deb 404  Not Found [IP: 93.93.128.193 80]
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/p/pango1.0/gir1.2-pango-1.0_1.42.4-7~deb10u1_armhf.deb 404  Not Found [IP: 93.93.128.193 80]
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/p/pango1.0/pango1.0-tools_1.42.4-7~deb10u1_armhf.deb 404  Not Found [IP: 93.93.128.193 80]
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/p/pango1.0/libpango1.0-dev_1.42.4-7~deb10u1_armhf.deb 404  Not Found [IP: 93.93.128.193 80]
E: Einige Archive konnten nicht heruntergeladen werden; vielleicht »apt-get update« ausführen oder mit »--fix-missing« probieren?
pi@ioBroker-RasPi4:~ $ sudo npm install canvas --unsafe-perm=true

> canvas@2.6.1 install /home/pi/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/pi/node_modules/canvas
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.97-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/node_modules/canvas
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-11T07_31_35_864Z-debug.log`

**Comment by Apollon77** [comment]
> npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'

npm befehl im falschen verzeichnis ausgeführt, weilhin ist das kein Weg den Adapter zu installieren.

**Comment by Apollon77** [comment]
canvas wird auf einem raspi nach aktuellem Stand nicht funktionieren, daher egal weil ist nur ein optionales dependency

**Comment by Marty56** [comment]
Ich habe das Ganze nochmal wiederholt, nachdem ich 'apt-get update' gemacht habe.
Dann hat es funktioniert und ich konnte den Adapter installieren
