### ISSUE TITLE
Go Home Trigger is not working depending on the current status

### ISSUE THREAD

**Issue by linchen4000** [iobroker-community-adapters/ioBroker.mihome-vacuum#130]
Hi,

it would be nice, if the "home" trigger / dock command would also work eg. in the current status sleeping(2). Maybe it's better not to make it dependent of the current status in general; like it's done in the App. If i click there on "dock", it will always goto the dock.

**Comment by dirkhe** [comment]
In the Current Version 2.0.10 there is directly home send, instead of First pause
