### ISSUE TITLE
BUG: No Map after upgrade to NODE 10.2

### ISSUE THREAD

**Issue by hyperbit00** [iobroker-community-adapters/ioBroker.mihome-vacuum#131]
With the new mihome.vacuum adapter it was possible to get a map from valetudo.
After Updgrade to Node 10.2 this function stops working.

Issue is described here: https://forum.iobroker.net/post/430329

**Comment by Apollon77** [comment]
Did you followed the instructions to nodejs upgrades in Forum? So did you executed the rebuild?

**Comment by hyperbit00** [comment]
`node -v
cd /opt/iobroker
iobroker backup
iobroker stop
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
node -v
curl -sL https://iobroker.net/fix.sh | bash -`

that was my steps.
Did i miss something?

**Comment by Apollon77** [comment]
--> https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten
