### ISSUE TITLE
No Map after upgrade to NODE 12.16.3

### ISSUE THREAD

**Issue by hoepps2802** [iobroker-community-adapters/ioBroker.mihome-vacuum#133]
today i have update to node.js 12.16.3 from 10.20.1
befor update the map still work in VIS

till the update the mapURL and map64 do not update

Node.js: v12.16.3
NPM: 6.14.4
js-controller: 3.1.4

i downgrade to 10.20.1 and it work again

**Comment by Apollon77** [comment]
Do you have followed the instructions for a nodejs update? check in forum

**Comment by hoepps2802** [comment]
Yes, i have follow the instructions and all other works, all my adapters

**Comment by Apollon77** [comment]
WHich way to "rebuild" you did?

**Comment by hoepps2802** [comment]
installation node.js 12

cd /opt/iobroker
iobroker backup
iobroker stop
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
curl -sL https://iobroker.net/fix.sh | bash -

map not work i do npm rebuild

node 12 to node 10

sudo apt-get purge nodejs
sudo apt-get autoremove
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
curl -sL https://iobroker.net/fix.sh | bash -
sudo reboot
npm rebuild
iobroker start


map work

**Comment by sk8er-boi90** [comment]
The map doesnt work with Node v14.3.0  . Before with Node v10 it worked.
I have two mi Robots in my iobroker.

**Comment by Apollon77** [comment]
Did you run all needed rebuilds afte rthe update of npdejs and followed the instructiosn in forum?

**Comment by hoepps2802** [comment]
i do "npm i" in node_modules/iobroker.mihome-vacuum
