### ISSUE TITLE
Fan power of widget not working for some models

### ISSUE THREAD

**Issue by mswiege** [iobroker-community-adapters/ioBroker.mihome-vacuum#140]
When I implemented the widget the fan power was always set by setting a percentage. 
Never models now expect a value between 101 and 107.
I updated the widget now so users can just enter the number they want in the settings. This also has the benefit that users can decide on their own what suction level they prefer for the three buttons of the widget.

I also removed the "not finished" message from the readme since I'm using the widget for years now without issues (this was the first one I encountered).

**Comment by dirkhe** [comment]
Thank you for implementing. I Merger jt into master
