### ISSUE TITLE
100% RAM and CPU-Load

### ISSUE THREAD

**Issue by kueppert** [iobroker-community-adapters/ioBroker.mihome-vacuum#145]
Hi, i was only able to resolve the problem via kill the process via console. I received following entries in my log. Adapter tried to get the map, but my vacuum has some times lost the wlan-signal because it was running in my basement.
`

host.ioBroker2 | 2020-05-29 17:46:45.391 | warn | instance system.adapter.mihome-vacuum.0 terminated due to SIGABRT
-- | -- | -- | --
host.ioBroker2 | 2020-05-29 17:46:45.390 | error | Caught by controller[17]: 18: 0x13c5c79  [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.390 | error | Caught by controller[16]: 17: 0xc2eecb  v8::internal::Builtin_JsonStringify(int, unsigned long*,  v8::internal::Isolate*) [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.390 | error | Caught by controller[15]: 16: 0xe252e4  v8::internal::JsonStringify(v8::internal::Isolate*,  v8::internal::Handle<v8::internal::Object>,  v8::internal::Handle<v8::internal::Object>, v8::internal::Handle
host.ioBroker2 | 2020-05-29 17:46:45.390 | error | Caught by controller[14]: 15: 0xe2463f  v8::internal::JsonStringifier::Result  v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>,  bool, v8::internal::Handle<v8
host.ioBroker2 | 2020-05-29 17:46:45.390 | error | Caught by controller[13]: 14: 0xe24936  v8::internal::JsonStringifier::Result  v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>,  bool, v8::internal::Handle<v8
host.ioBroker2 | 2020-05-29 17:46:45.389 | error | Caught by controller[12]: 13: 0xe20421  v8::internal::JsonStringifier::Result  v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>,  bool, v8::internal::Handle<v8:
host.ioBroker2 | 2020-05-29 17:46:45.389 | error | Caught by controller[11]: 12: 0xe1ecc8  v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>)  [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.389 | error | Caught by controller[10]: 11: 0x10c0c45 v8::internal::IncrementalStringBuilder::Extend() [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.389 | error | Caught by controller[9]: 10: 0xd0891c  v8::internal::Factory::NewRawOneByteString(int,  v8::internal::AllocationType) [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.388 | error | Caught by controller[8]:  9: 0xd3aa6c  v8::internal::Heap::AllocateRawWithRetryOrFail(int,  v8::internal::AllocationType, v8::internal::AllocationOrigin,  v8::internal::AllocationAlignment) [io.mihome-v
host.ioBroker2 | 2020-05-29 17:46:45.388 | error | Caught by controller[7]:  8: 0xd37fb5  v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace,  v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)  [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.388 | error | Caught by controller[6]:  7: 0xd37105  v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector,  v8::GCCallbackFlags) [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.388 | error | Caught by controller[5]:  6: 0xd2a886 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.387 | error | Caught by controller[4]:  5: 0xd2a1f5  [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.387 | error | Caught by controller[3]:  4: 0xb7da99  v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char  const*, bool) [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.387 | error | Caught by controller[2]:  3: 0xb7d71e  v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool)  [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.387 | error | Caught by controller[1]:  2: 0xa09c55 node::OnFatalError(char const*, char const*) [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.386 | error | Caught by controller[1]:  1: 0xa09830 node::Abort() [io.mihome-vacuum.0]
host.ioBroker2 | 2020-05-29 17:46:45.385 | error | Caught by controller[0]: FATAL ERROR: Ineffective mark-compacts near  heap limit Allocation failed - JavaScript heap out of memory

`

**Comment by Apollon77** [comment]
In fact it is a "Out of memory" situation ... How much RAM is free normally? 100% CPU and such simply states that the system is doing swapping ...make sure there is enought RAM available!
