### ISSUE TITLE
no connection to S6

### ISSUE THREAD

**Issue by nils50122** [iobroker-community-adapters/ioBroker.mihome-vacuum#150]
The adapter stucks i state "yellow".

Here is the log file (debug-level).

`

mihome-vacuum.0	2020-05-29 12:20:05.690	info	(26828) set nächster Timer: Nicht verfügbar
--
  | mihome-vacuum.0	2020-05-29 12:20:05.295	info	(26828) New generation or new fw(3.5.8,1708) detected, create new states goto and zoneclean
  | mihome-vacuum.0	2020-05-29 12:20:05.293	info	(26828) extend state mop for State control.fan_power
  | mihome-vacuum.0	2020-05-29 12:20:05.291	info	(26828) change states from State control.fan_power
  | mihome-vacuum.0	2020-05-29 12:20:05.174	debug	(26828) server started on 0.0.0.0:53421
  | mihome-vacuum.0	2020-05-29 12:20:05.156	info	(26828) Create state clean_home for controlling by cloud adapter
  | mihome-vacuum.0	2020-05-29 12:20:05.154	info	(26828) Expert mode enabled, states created
  | mihome-vacuum.0	2020-05-29 12:20:05.084	info	(26828) starting. Version 2.0.9-RC07 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.17.0
  | mihome-vacuum.0	2020-05-29 12:20:03.493	debug	(26828) statesDB connected
  | mihome-vacuum.0	2020-05-29 12:20:03.491	debug	(26828) States connected to redis: 127.0.0.1:9000
  | mihome-vacuum.0	2020-05-29 12:20:03.473	debug	(26828) States create System PubSub Client
  | mihome-vacuum.0	2020-05-29 12:20:03.469	debug	(26828) States create User PubSub Client
  | mihome-vacuum.0	2020-05-29 12:20:03.455	debug	(26828) Redis States: Use Redis connection: 127.0.0.1:9000
  | mihome-vacuum.0	2020-05-29 12:20:03.452	debug	(26828) objectDB connected
  | mihome-vacuum.0	2020-05-29 12:20:03.444	debug	(26828) Objects connected to redis: 127.0.0.1:9001
  | mihome-vacuum.0	2020-05-29 12:20:03.315	debug	(26828) Objects client initialize lua scripts
  | mihome-vacuum.0	2020-05-29 12:20:03.311	debug	(26828) Objects create User PubSub Client
  | mihome-vacuum.0	2020-05-29 12:20:03.307	debug	(26828) Objects create System PubSub Client
  | mihome-vacuum.0	2020-05-29 12:20:03.287	debug	(26828) Objects client ready ... initialize now
  | mihome-vacuum.0	2020-05-29 12:20:02.651	debug	(26828) Redis Objects: Use Redis connection: 127.0.0.1:9001
`

I try these things to fix the problem:

- Reset WIFI on S6
- Delete complete adapter and reinstall it (no errors while installation)
- recheck token and ip (ip is reachable from iobroker host).

Anyone can help?

**Comment by dirkhe** [comment]
If your Problem solved, than close issue
