### ISSUE TITLE
Recover_map??!

### ISSUE THREAD

**Issue by backfisch88** [iobroker-community-adapters/ioBroker.mihome-vacuum#153]
Hallo!

Gibt es noch einen Befehl für revover_map? Seit der neuen Firmware Version geht dieser leider nicht mehr. 

Hintergrund ist dieser: 
Bei mir geht die „automatische Stockwerkerkennung“ nicht richtig zuverlässig. 
Wenn ich das EG reinige und dann ins OG hege funktioniert alles klasse
Wenn erst das OG gereinigt wird und dann das EG erkennt er auf den Tod das Stockwerk nicht. 
Auch!!! Wenn erst EG dann OG gesaugt wird - beim zurückfahren zum Dock (wenn ich ihn oben abhole und unten hinstelle) „ortet“ er sich neu und fährt wirr durch die Gegend und stellt fest, dass er im OG ist. 

AUSSER!!!! Ich lade die map vom EG in der App neu. Da das ziemlich unkomfortabel ist hatte ich das mal über den recover_map load gelöst. Aber wie gesagt. Befehlt geht nicht mehr. 

Gibts da schon was?

**Comment by MeisterTR** [comment]
nicht bekannt
