### ISSUE TITLE
[dreame.vacuum.mc1808] Support Xiaomi Mijia 1c

### ISSUE THREAD

**Issue by audi1503** [iobroker-community-adapters/ioBroker.mihome-vacuum#155]
Hallo zusammen,

Ich habe mir einen Xiaomi Mijia 1c zugelegt und habe  mir den Adapter 2.0.10-rc01 aus dem git installiert. Bei dem 1.1.5 besteht die Verbindung aber man kann keinerlei Aktionen ausführen. Der Adapter bleibt aber gelb und verbindet nicht , habe schon alles was hier so geschrieben wurde versucht . Kann es sein das der auch noch nicht unterstützt wird ?

**Comment by MeisterTR** [comment]
Leider haben die neueren Modelle von Xiaomi ein geänderte Protokoll, dies kann ich nicht  ohne die Hardware einbinden. Versuche über Helfer die so ein Gerät besitzen, sind mehrfach gescheitert.

**Comment by niko1987** [comment]
Hall MeisterTR, Ich habe auch einen 1C. Wie kann ich dich hierbei unterstützen? Müsste ich mein Baby leihweise zu dir schicken?
Gruß Niko

**Comment by MeisterTR** [comment]
Du könntest den adapter mal starten und schauen was bei model drin steht

**Comment by niko1987** [comment]
Servus, 
Bei Model steht: dreame.vacuum.mc1808
Firmware wäre die: 3.5.8_1059

Gruß
Niko

**Comment by MeisterTR** [comment]
Bitte mal die 2.2.0 von git testen viel geht noch nicht, ist erstmal ein test ich werde  den Adapter wahrscheinlich einmal auf links ziehen müssen weil es zwei komplett unterschiedliche apis sind.
was sollte gehen:
* connecten
* start/stop
* Einstellen der Saugstufe
* Werte für Batterie / Saugzeit und Fläche

**Comment by audi1503** [comment]
Also der Adapter connected  nicht  habe den jetzt die ganze Nacht laufen lassen ,bei miIO.info erscheint folgendes: 
mihome-vacuum.0 (4552) Receive <<< {"partner_id":"","id":195,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_1059","ap":{"ssid":"","bssid":"DC:39:6F:75:53:93","rssi":-34},"netif":{"localIp":"192.168.178.100","mask":"255.255.255.0","gw":"192.168.178.1"},"miio_ver":"miio-client 3.5.8","model":"dreame.vacuum.mc1808","mac":"44:23:7C:A0:DC:5A","token":"597537664151677176663333313xxxxx","life":4705028}}
Debug log kommt nur: (Auszug aus dem Debug-Log)

sendMsg[1] >>>  {"id":196,"method":"get_prop","params":["run_state","suction_grade","mode","err_state","battary_life","start_time","order_time","s_time","s_area","v_state","zone_data","repeat_state","remember_map","has_map","water_grade","box_type","mop_type","is_mop","light_state","has_newmap","is_charge","is_work"]}
--
2020-08-14 08:37:24.369  - debug:  mihome-vacuum.0 (4552) sendMsg[2] >>>  {"id":196,"method":"get_prop","params":["run_state","suction_grade","mode","err_state","battary_life","start_time","order_time","s_time","s_area","v_state","zone_data","repeat_state","remember_map","has_map","water_grade","box_type","mop_type","is_mop","light_state","has_newmap","is_charge","is_work"]}
no answer for get_prop id:196 received, giving up

**Comment by Anzic23** [comment]
owner of the same vacuum cleaner. Wait for support to appear? or I can help with testing.

**Comment by derherrgraf** [comment]
@MeisterTR ich hab jetzt ein bisschen rumprobiert und deinen fork ([https://github.com/MeisterTR/ioBroker.mihome-vacuum](https://github.com/MeisterTR/ioBroker.mihome-vacuum)) installiert. Damit wird zwar eine Verbindung hergesetllt aber mehr leider noch nicht. Wie ist denn der aktuelle Stand für den 1c? Kann ich dir irgendwie behilflich sein?

**Comment by MeisterTR** [comment]
Um zu sehen welche Modelle am verbreitetsten sind bitte hier Abstimmen
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum#supported-devices-and-fetures

**Comment by CodingTfC** [comment]
Hi würde es auch super finden wenn der dreame.vacuum.mc1808 hinzugefügt wird. Besitze auch einen und kann gerne mit Infos oder ähnlichem unterstützen.
