### ISSUE TITLE
use osDependencies

### ISSUE THREAD

**Issue by foxriver76** [iobroker-community-adapters/ioBroker.mihome-vacuum#156]
Docs state the following:

> Please install canvas and the libs manually with:
> sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

Would be more user friendly to use `common.osDependencies` as described in https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#adapter

**Comment by dirkhe** [comment]
I added only canvas as OS dependency, because the lib above is for systems, like Raspberry, where you have to compile canvas himself
