### ISSUE TITLE
20472) HTTP error when getting token cookie{} in Version 20.10

### ISSUE THREAD

**Issue by gravidigit** [iobroker-community-adapters/ioBroker.mihome-vacuum#158]
Hi bei Version 20.10-RC01 komtm in den Instranz Einstellungen bei Verbinden mir richtigen Zugangsdaten und Server der Fehler HTTP error when getting token cookie{}

**Comment by dirkhe** [comment]
Bitte mal debug Log Posten

**Comment by gravidigit** [comment]
mihome-vacuum.0 | 2020-07-14 16:28:56.124 | info | (15643) connecting, this can take up to 10 minutes ...
-- | -- | -- | --
mihome-vacuum.0 | 2020-07-14 16:28:36.028 | info | (15643) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-07-14 16:28:33.077 | info | (15643) discover HTTP error when getting token cookie
mihome-vacuum.0 | 2020-07-14 16:28:33.077 | error | (15643) HTTP error when getting token cookie{}
mihome-vacuum.0 | 2020-07-14 16:28:21.729 | info | (15643) discover HTTP error when getting token cookie
mihome-vacuum.0 | 2020-07-14 16:28:21.729 | error | (15643) HTTP error when getting token cookie{}
mihome-vacuum.0 | 2020-07-14 16:28:16.445 | info | (15643) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2020-07-14 16:28:15.963 | info | (15643) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-07-14 16:28:15.963 | warn | (15643) Time difference between Mihome Vacuum and ioBroker: 1 sec
mihome-vacuum.0 | 2020-07-14 16:28:15.892 | info | (15643) Cloud control disabled
mihome-vacuum.0 | 2020-07-14 16:28:15.891 | info | (15643) Expert mode disabled, states deleted
mihome-vacuum.0 | 2020-07-14 16:28:15.864 | info | (15643) starting. Version 2.0.10 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.18.2, js-controller: 3.1.6

**Comment by gravidigit** [comment]
Ich habe den Adapter mal Probeweise auf eine anderen IOBroker Server installiert, selber Fehler.

**Comment by dirkhe** [comment]
Also entweder ist der Token nicht richtig oder der Server nicht der richtige. Wenn du in mihome App bist, kannst du dich verbinden? Hast du den Token per adapter ermittelt?

**Comment by suhl-cloudian** [comment]
Gibt es hierzu eine Lösung? habe die gleiche Fehlermeldung und kann mich nicht anmelden. In der App läuft alles.

**Comment by MeisterTR** [comment]
bitte mal von git intsllieren, ich hab den log erweitert

**Comment by suhl-cloudian** [comment]
Habe es gerade installiert, aber da ist nichts anders. Sehe aber in GitHub keine neuen Files... 

<img width="911" alt="Bildschirmfoto 2020-12-16 um 09 41 46" src="https://user-images.githubusercontent.com/69597653/102325020-ed08b000-3f82-11eb-9ec5-864d56ebbac4.png">

<img width="710" alt="Bildschirmfoto 2020-12-16 um 09 37 04" src="https://user-images.githubusercontent.com/69597653/102324622-5dfb9800-3f82-11eb-867d-c58eb726ed37.png">

**Comment by MeisterTR** [comment]
wie gesagt ich habe die logausgabe erweitert, damit ich den Fehler näher eingrenzen kann. (in deinem screenshot sehe ich die Änderung!!)

**Comment by suhl-cloudian** [comment]
![Uploading Bildschirmfoto 2020-12-17 um 09.34.57.png…]()

**Comment by Frisco72** [comment]
Hallo,
hatte auch den Fehler. Ihr müsst Euch im Browser bei MiHome anmelden und bekommt einen Code per Mail den Ihr im Browser eingebt. Danach funktioniert es.
LG

**Comment by Maveric2005** [comment]
danke an drisco72 . genau damit wird der fehler behoben

**Comment by MeisterTR** [comment]
habs in die Readme aufgenommen.

**Comment by florian1984** [comment]
habe genau den Fehler .... die Email Bestätigung hilft leider nicht weiter ... der Fehler kommt immer noch.
