### ISSUE TITLE
keine Verbindung mehr

### ISSUE THREAD

**Issue by Marty56** [iobroker-community-adapters/ioBroker.mihome-vacuum#159]
Wenn ich den Adapter aktiviere, bekomme ich eine "Error Loop" und der Staubsauger verbindet sich nicht.
Anbei das Log (mit Debug Level):

`

mihome-vacuum.0 | 2020-06-29 10:33:30.269 | warn | (11649) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
mihome-vacuum.0 | 2020-06-29 10:33:30.264 | warn | (11649) Object mihome-vacuum.0.info.dnd is invalid: obj.common.type has an invalid value (switch) but has to be one of number, string, boolean, array, object, mixed, file, json
mihome-vacuum.0 | 2020-06-29 10:33:28.790 | debug | (11649) statesDB connected
mihome-vacuum.0 | 2020-06-29 10:33:28.789 | debug | (11649) States connected to redis: 127.0.0.1:6379
mihome-vacuum.0 | 2020-06-29 10:33:28.779 | debug | (11649) States create System PubSub Client
mihome-vacuum.0 | 2020-06-29 10:33:28.775 | debug | (11649) States create User PubSub Client
mihome-vacuum.0 | 2020-06-29 10:33:28.755 | debug | (11649) Redis States: Use Redis connection: 127.0.0.1:6379
mihome-vacuum.0 | 2020-06-29 10:33:28.752 | debug | (11649) objectDB connected
mihome-vacuum.0 | 2020-06-29 10:33:28.744 | debug | (11649) Objects connected to redis: 127.0.0.1:9001
mihome-vacuum.0 | 2020-06-29 10:33:28.728 | debug | (11649) Objects client initialize lua scripts
mihome-vacuum.0 | 2020-06-29 10:33:28.726 | debug | (11649) Objects create User PubSub Client
mihome-vacuum.0 | 2020-06-29 10:33:28.724 | debug | (11649) Objects create System PubSub Client
mihome-vacuum.0 | 2020-06-29 10:33:28.720 | debug | (11649) Objects client ready ... initialize now
mihome-vacuum.0 | 2020-06-29 10:33:28.344 | debug | (11649) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.nuc | 2020-06-29 10:33:27.498 | info | instance system.adapter.mihome-vacuum.0 started with pid 11649
host.nuc | 2020-06-29 10:32:57.454 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled
host.nuc | 2020-06-29 10:32:57.453 | info | instance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)
mihome-vacuum.0 | 2020-06-29 10:32:57.316 | info | (11630) starting. Version 2.0.7 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.18.1, js-controller: 3.1.6

`

**Comment by dirkhe** [comment]
Das sieht so aus, als wenn du 2 Instanzen laufen hast?

**Comment by Marty56** [comment]
von dem Adapter läuft nur eine Instanz. Ich habe zwei Javascript Instanzen laufen, aber das sollte wohl nichts ausmachen oder?

**Comment by dirkhe** [comment]
Dannn zeige uns bitte mal den interessanten teil, denn das ist ja nur der start des Adapter, danach kommt dann das connecten usw. Installiere aber bitte vorher mal die aktuelle Version über die Katze.

**Comment by Marty56** [comment]
Habe den RC 10 von Github installiert.  Keine Änderung. Anbei das Log File.

[iobroker.current.log](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/4850291/iobroker.current.log)

**Comment by dirkhe** [comment]
Der adapter beendet sich doch sofort wieder. Ich denke, der ist gar nicht richtig installiert. Vlt. Solltest du mal das Log anschauen, wenn du installierst. Fehlt da vlt. Etwas? Der wurde vom system disabled

**Comment by Apollon77** [comment]
ggf mal manuell starten. ins iobroker verzeichnis wechseln

node node_modules/iobroker.mihome-vacuum/min.js --debug

**Comment by Marty56** [comment]
Manueller Start erzeugt folgende Ausgabe auf der Console
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/4853764/log.txt)

**Comment by Marty56** [comment]
Jetzt habe ich den Adapter deinstalliert und dann wieder installiert.
Anbei das Log
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/4853820/log.txt)

**Comment by dirkhe** [comment]
Du hast mehrere Instanzen laufen, zumindest als du manuell gestartet hast. Dann musst den Adapter vorhet deaktivieren.

**Comment by Marty56** [comment]
Das hatte ich gemacht. Jetzt habe ich iobroker gestoppt und mit list instances geprüft, ob irgendwelche Instanzen laufen.
Dann wieder iobroker neugestartet und das Adapter funktioniert nicht.

Ich habe auch schon den Adapter komplett deinstalliert und wieder installiert. Auch kein Erfolg.

**Comment by Apollon77** [comment]
Beende mal alle instanzen, schau das keine Prozesse mehr laufen und dann manuell starten bitte wie oben beschrieben

**Comment by Marty56** [comment]
genau das habe ich schon gemacht.

**Comment by Apollon77** [comment]
> 2020-06-30 20:26:09.448  - error: mihome-vacuum.0 (22617) UDP error: Error: bind EADDRINUSE 0.0.0.0:53421

irgendetwas blockiert den Port. Finde heraus was

**Comment by Marty56** [comment]
@Appollon: mein tvheadend Server nutzt diesen Port. Das aber schon immer. Ok, jetzt habe ich den Port geändert und der EADDRINUSE Error ist weg, der Adapter wird gelb, aber verbinden tut er sich immer noch nicht.

**Comment by Apollon77** [comment]
Log wieder bitte?

**Comment by Marty56** [comment]
Ich habe den Adapter deinstalliert und den RC10 von Github installiert.
Außerdem habe ich den UPNP Port geändert.
Der Adapter kann sich mit der Cloud verbinden und empfängt auch meine Geräte, IPs und Tokens.
Token habe ich eingetragen und die statische IP auch. Ich habe in meinem Router auch die IP überprüft und gecheckt, ob der Staubsauger im Router online ist.

Es scheint, dass die Xiaomi Cloud auch erreicht wird. Allerdings werden die Objekte des Staubsaugers nicht aktualisiert.
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/4863546/log.txt)

**Comment by dirkhe** [comment]
Schicke doch bitte mal das Log, wenn der robbi sich verbindet. In deinem Log Ausschnitt ist er noch nicht mal angefangen, sich zu verbinden

**Comment by Marty56** [comment]
Das ist doch genau das Problem. Der Staubsauger verbindet sich nicht. Auch nach langem Warten!

**Comment by dirkhe** [comment]
Dann ist bei dir aber noch irgendwas anderes schief, der startet auch ständig neu. Also meiner Meinung nach ist der nicht richtig installiert.

**Comment by Marty56** [comment]
Wo siehst Du im letzten Log, dass der Adapter dauern neu startet?
Das tut er nämlich nicht mehr, nachdem ich ihn komplett deinstalliert und neuinstalliert habe und dann noch den UPNP Port geändert habe.

**Comment by dirkhe** [comment]
Sorry, ich hatte gerade noch ein altes Log von dir offen. Was hast du denn als Intervall im admin unter settings stehen?

**Comment by Marty56** [comment]
Status anfordern:20  secnWLAN Status anfordern:  60 sec

**Comment by dirkhe** [comment]
Auch normal.. stell das Log mal auxf Silly, normalerweise sollte er Versuchen, eine Connection zum robbi herzustellen

**Comment by Marty56** [comment]
anbei das gewünschte log.
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/4869068/log.txt)

**Comment by dirkhe** [comment]
Sieh mal hier, drin System beendet den adapter
`2020-07-03 11:58:30.649 - info: host.nuc "system.adapter.mihome-vacuum.0" disabled
2020-07-03 11:58:30.651 - info: host.nuc stopInstance system.adapter.mihome-vacuum.0 (force=false, process=true)
2020-07-03 11:58:30.655 - info: host.nuc stopInstance system.adapter.mihome-vacuum.0 send kill signal
2020-07-03 11:58:30.656 - silly: mihome-vacuum.0 (14776) States system redis pmessage io.system.adapter.mihome-vacuum.0.sigKill/io.system.adapter.mihome-vacuum.0.sigKill:{"val":-1,"ack":false,"ts":1593770310654,"q":0,"from":"system.host.nuc","lc":1593770310654}
2020-07-03 11:58:30.657 - info: mihome-vacuum.0 (14776) Got terminate signal TERMINATE_YOURSELF`

**Comment by Marty56** [comment]
ja, weil ich den Adapter manuell gestoppt habe.
Ich hatte keine Lust mit das das Log Files mit endlosen Wiederholungen von 

"States user redis pmessage io.mihome-vacuum.0.*/io.mihome-vacuum.0.info.connection:{"val":false,"ack":true,"ts":1593770271905,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1593576633313}"

voll zu füllen.

**Comment by dirkhe** [comment]
Dein Ernst? Du gibst dem Adapter nicht mal 2 Minuten zeit? Manchmal lässt der Roboter sich 10 Minuten und länger Zeit, bis er mit dem adapter spricht, wenn man neu startet. Aber bei dir versucht er es gar nicht, aber im Log steht auch nichts. Probiere doch mal den Roboter per adapter zu starten, mit Silly log

**Comment by Marty56** [comment]
Es spielt keine Rolle, ob ich länger warte oder nicht. Der Staubsauger verbindet sich nicht.

Ich habe auch schon versucht, den Staubsauger über den Adapter zu starten, der reagiert aber nicht, weil er sich nicht verbindet.

Meinen Linux Rechner habe ich auch schon gebootet. Mir fällt nicht mehr ein.

Im Router sind auch keine Ports oder IPs geblockt.

**Comment by dirkhe** [comment]
Naja, der Adapter an sich läuft ja generell bei den anderen usern. Ich versuche ja nur dir zu helfen. Normalerweise versucht er alle 20sec den Status abzufragen oder sich zu connecten, davon sehe ich aber nichts im Log. Deswegen dachte ich, dass du halt versuchst über den Adapter etwas anzutriggern, damit man im Log was sieht und das am besten im Silly mode, weil dann die meisten Informationen zu sehen sind

**Comment by Marty56** [comment]
und auch danke für Deinen Support. Ich bin jetzt nicht zuhause und würde mich in ein paar Tagen wieder melden.

**Comment by Marty56** [comment]
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/4877684/log.txt)

**Comment by Marty56** [comment]
Was mir noch aufgefallen ist, ich habe zwei Staubsauger unter dem selben Account.
Wenn ich GET DEVICE machen, werden auch beide Staubsauger erkannt.
Ich habe die Daten des relevanten Staubsaugers in den manuellen Teil übertragen.

Was mir auffällt ist aber, dass ich bei den erkannten Devices in der"XIAOMI Cloud" Login den relevanten Staubsauger nicht auswählen kann und immer der Staubsauger von meiner Ferienwohnung selektiert ist, der in der Regel offline ist.

Könnte es somit daran liegen, dass der Adapter immer versucht, sich mit dem falschen Staubsauger zu verbinden.

**Comment by Marty56** [comment]
Ich habe jetzt einen Staubsauger aus der XIAOMI Cloud gelöscht und GET DEVICES nochmal ausgeführt.
Jetzt wird auch nur noch ein Staubsauger gefunden, aber leider kann diese Konfiguration nicht gespeichert werden.

Ich habe dann in dem manuellen Teil ein Datum geändert und konnte dann speichern.
Leider ist dies Speicherung verloren, wenn ich das Konfiguration UI wieder öffne.

**Comment by Marty56** [comment]
Ok. Meine Vermutung war richtig. Jetzt funktioniert die Verbindung!

Die Konfigurationsseite ist noch grob fehlerhaft. Man bekommt inkorrekte Fehlermeldung, wie "Instanz ist deaktiviert", ob wohl das nicht der Fall ist. Der Fehler ging dann nach mehrfachem Aufruf irgendwann weg.

Das Token, was durch GET DEVICES ermittelt wurde, lässt sich nicht kopieren und bei manuell eintragen.
Wenn man aber bei manuell nicht einträgt hat, lässt sich die Konfiguration nicht speichern. usw ...

**Comment by dirkhe** [comment]
Man wählt ein device, dessen Daten werden übernommen. Die Auswahl selber merkt er sich nicht. Wenn man dann auf speichern klickt, werden die übernommenen Daten gespeichert. Im Prinzip ist das nur die Hilfe, dass man die Daten nicht wo anderweitig herholen muß. 
Aber dann sieht es ja aus, als wenn funktioniert? Wenn ja, dann schließe den Issue bitte

**Comment by Marty56** [comment]
So wie Du das beschreibst, funktioniert es leider nicht.
Vielleicht liegt es am Browser (ich verwende Safari).

Wenn ich ein Device wähle, wird das Device NICHT beibehalten, wenn es nicht das Erste in dem Drop Down Menu ist. 
Dass war bei mir der Fall. Das erste Device war der Staubsauger in meiner Ferienwohnung der Offline war, das zweite der andere, mit dem ich mich verbinden will.

Das Issue bei diesem Zustand zu schließen, halte ich deshalb für nicht ok.

**Comment by dirkhe** [comment]
Da ich kein angebissenen Obst habe, kann ich das nicht nachvollziehen. Öffne mal die entwicklertools des Safari und schau mal, ob es da zu Fehler in der Console kommt. Vlt fragst du auch mal im Forum, ob noch jemand Probleme mit Safari hat oder das nachstellen kann

**Comment by MeisterTR** [comment]
sollte in der git version mittlerweile besser gehen
