### ISSUE TITLE
get current position coordinates

### ISSUE THREAD

**Issue by mar565** [iobroker-community-adapters/ioBroker.mihome-vacuum#161]
Hello everybody,
is there an easy way to get the live coordinates of the roboter?
I want to use it to make a more precise "find me" command. Example: "Hey! Im over here by the sofa"

**Comment by MeisterTR** [comment]
but without the mapdata you cant find out where the robot is because the position of the robot is relative

**Comment by mar565** [comment]
Exactly. The position is relativ to the docking station. With an underlayed floorplan and the current coordinates I can set my own zones for location.
![IMG_20200809_203258](https://user-images.githubusercontent.com/49168222/89739256-8c6ee100-da7f-11ea-82b9-3109c50f7670.jpg)
