### ISSUE TITLE
Connect two robots failed?

### ISSUE THREAD

**Issue by w0nk1** [iobroker-community-adapters/ioBroker.mihome-vacuum#162]
First of all I love your extension. It works like a charm. Now I'm getting some trouble while trying to connect another robot with a new instance of mihome-vacuum. Could it be, that just one instance can connect at the same time? Is there another way I have not think about?

**Comment by dirkhe** [comment]
I didn't test it, but I know, that there some people use it. Do you use different ports for the robots?

**Comment by w0nk1** [comment]
Good point regarding the ports! Where could I change the port for the robot itself? 

At the moment after changing the ports just in the other instance leads to:


```
mihome-vacuum.1 | 2020-07-04 15:09:45.827 | info | (5478) set nächster Timer: Nicht verfügbar
-- | -- | -- | --
mihome-vacuum.1 | 2020-07-04 15:09:45.283 | info | (5478) Cloud control disabled
mihome-vacuum.1 | 2020-07-04 15:09:45.280 | info | (5478) Expert mode disabled, states deleted
mihome-vacuum.1 | 2020-07-04 15:09:45.235 | info | (5478) starting. Version 2.0.10-RC01 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v10.21.0, js-controller: 3.1.6
```

But no connection attempt at all.

**Comment by dirkhe** [comment]
If I read the Readme, you have only change the own port, I guess. But otherwise read in iobroker forum

**Comment by w0nk1** [comment]
You were right! Just changing the own port did the trick! Maybe it would be worth to add it to the FAQ section?

**Comment by dirkhe** [comment]
This is already documented in the README. Which FAQ do you mean?

**Comment by w0nk1** [comment]
The coarse two robots procedure. Including the advice with the port. Thanks for your very fast support!
