### ISSUE TITLE
Custom Commands ohne Funktion

### ISSUE THREAD

**Issue by gaga191281** [iobroker-community-adapters/ioBroker.mihome-vacuum#163]
Hi ich versuche mit dem Methodenaufruf 'cleanSegments' eine Raumreinigung anzustoßen. Das führt jedoch nicht zu einer Reinigung der Räume sondern zu einem Funktionsunfähigen Adapter. Der Adapter zeigt zwar an dass alles ok ist, der Roboter verarbeitet bis zu einem Neustart des Adapters aber nicht mehr alle Befehle. Ein Starten einer Reinigung ist über den Adapter nicht mehr möglich, komischer weise die findMe Funktion geht noch. Erst durch einen Adapterneustart gehen wieder alle Funktionen.

Hier die Fehlerausgabe
`
javascript.0 | 2020-07-05 15:39:48.508 | error | (1185) script.js.common.eg.vacuum.vac_zone_clean: {'error':'no answer received after after 3 times'}
-- | -- | -- | --
mihome-vacuum.0 | 2020-07-05 15:39:33.506 | error | (4846) [84](undefined) -> Param is not an array
mihome-vacuum.0 | 2020-07-05 15:39:33.492 | info | (4846) trigger cleaning segment [object Object]
javascript.0 | 2020-07-05 15:39:33.483 | error | (1185) script.js.common.eg.vacuum.vac_zone_clean: YAY its an Array
javascript.0 | 2020-07-05 15:39:33.481 | error | (1185) script.js.common.eg.vacuum.vac_zone_clean: Rooms to clean: 16,18`

So wird der Befehl in dem Skript gemacht:
`        if (Array.isArray(roomsToClean))
        {
            console.error("YAY its an Array");
            sendTo('mihome-vacuum.0'/*0*/, 
            'cleanSegments', 
            {roomsToClean}, 
            function (response) {console.error(response)});
        }
        else {
            console.error("ITS NOT AN ARRAY!!!")
        }`

**Comment by dirkhe** [comment]
Du übergibt ja auch ein Objekt, weil du es in geschweifte Klammern übergibst, also entweder ein Array oder ein kommaseparierter String

**Comment by dirkhe** [comment]
Wenn es jetzt bei dir funktioniert, kannst das issue dann bitte schließen

**Comment by gaga191281** [comment]
ohne die geschweiften Klammern kommt nun keine Fehlermeldung mehr, aber der Staubsauger fährt nicht los. Er befüllt lediglich den Datenpunkt queue mit ["segment Raum1 Raum2"]

**Comment by dirkhe** [comment]
Was steht denn im log,  am besten auf debug

**Comment by gaga191281** [comment]
`

mihome-vacuum.0 | 2020-07-10 18:01:40.423 | info | (3091) should trigger cleaning segment 16,18, but is currently active(18). Add to queue
-- | -- | -- | --
javascript.0 | 2020-07-10 18:01:40.409 | error | (1173) script.js.common.eg.vacuum.vac_zone_clean: YAY its an Array
javascript.0 | 2020-07-10 18:01:40.407 | error | (1173) script.js.common.eg.vacuum.vac_zone_clean: Rooms to clean: 16,18

`

**Comment by dirkhe** [comment]
Installiere mal die aktuelle Version. Manchmal reagiert der robbi nicht, und dann wurde der Status nicht zurückgesetzt. Das habe ich aber in der aktuellen Version behoben, da versucht er es auch bis zu 3 mal.

**Comment by gaga191281** [comment]
hmmm... die neuste ist eigentlich drauf.. v2.1.0

**Comment by dirkhe** [comment]
Ok, dann brauche ich mal mehr Log, damit man sieht was er macht

**Comment by gaga191281** [comment]
Hier mal das Skript:

`on({
    id:'javascript.0.variables.eg.vacuum.var_trigger_zoneClean',
    change: 'any'
},  function (obj) {
    if (obj.state.val === true)
    {
        var roomsToClean = [];
        var wohnzimmer = getState('javascript.0.variables.eg.vacuum.var_zone_wz'/*var zone wz*/).val;
        var flur = getState('javascript.0.variables.eg.vacuum.var_zone_flur'/*var zone flur*/).val;
        var kueche = getState('javascript.0.variables.eg.vacuum.var_zone_kueche'/*var zone kueche*/).val;
        if (wohnzimmer === true)
        {
            roomsToClean.push(16);
        }
        if (flur === true)
        {
            roomsToClean.push(17);
        }
        if (kueche === true)
        {
            roomsToClean.push(18);
        }
        console.error("Rooms to clean: " + roomsToClean);

        if (Array.isArray(roomsToClean))
        {
            sendTo('mihome-vacuum.0'/*0*/, 
            'cleanSegments', 
            roomsToClean, 
            function (response) {console.error(response)});
        }
    }
});

on({
    id:'mihome-vacuum.0.control.start'/*Start vacuum*/,
    change: 'any'
},  function (obj) {
    if (getState('mihome-vacuum.0.info.state'/*Vacuum state*/).val === 10)
    {
        setState('mihome-vacuum.0.control.resumeRoomClean'/*Resume paused roomClean*/, true);
    }
});`


An welchen stellen brauchst du ein log? Oder kann man den Loglevel des Saugers/Adapters einstellen?

**Comment by dirkhe** [comment]
Also was dein Script macht, verstehe ich nicht so ganz, das kann der Adapter eigentlich alleine, mache dich mal mit de  Räume vertraut, da kannst du sogar manuelle Räume anlegen, wo du deine Koordinaten einträgst, mal die Readme lesen und km Forum lesen.
Du kannst den adapter mal auf debug stellen und dann Aktionen ausführen, dann schreibt er rein was er macht und ob der robbi antwortet usw.

**Comment by gaga191281** [comment]
Die hatte ich durch, aber nicht so ganz verstanden. Daher war der Ansatz mit den custom commands.

"Wenn man spontan mal mehrere Räume reinigen will, kann man das über multiRoomClean tun, indem man diesem Datenpunkt die ioBroker-Räume zuweist und dann den Butten drückt."

Wie kann ich einem Datenpunkt, welcher boolsche Werte annehmen kann, Räume zuweisen?? Mit ioBroker-Räume sind die Datenpunkte aus enum.Rooms gemeint? Wie genau funktioniert das? Hast du mir ein Beispiel?

**Comment by dirkhe** [comment]
Schau mal hier https://forum.iobroker.net/topic/28615/adapter-mihome-vacuum-anpassungen

**Comment by gaga191281** [comment]
Klar soweit.. gibt es denn eine Möglichkeit die Raumzuordnung des Datenpunkts (multiRoomClean) via Skript zu ändern?

**Comment by dirkhe** [comment]
Nicht so einfach. Ich mache das bei mir so, dass ich einen Timer für wz und Küche habe,  der täglich  ausgeführt wird. Manchmal aktiviere ich den aber auch manuell. Sonst schicke ich den einfach, meist per Alexa, in alle räume gleichzeitig, dafür ist ja die queue da.

**Comment by gaga191281** [comment]
Ok dann versuch ich mal den Queue Ansatz. Danke
