### ISSUE TITLE
untested  non-function version released ?!!

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.mihome-vacuum#164]
Hi, sorry, but the 2.1.0 is not tested released, the complete map-function are doesn't work! :-/ 👎 
Bad thing: rollback to an old version is not possible any more!

For the future, please first test, ask and than release the build!

https://forum.iobroker.net/post/461054

**Comment by Apollon77** [comment]
Why a rollback should not be possible? Select the old version in admin. 

This new version is available in latest repository only and this is by definition test versions! If you want to make sure it always work stay with the stable repository. 

Please provide more details and logs for The Problem with the newest version.

**Comment by Ilovegym66** [comment]
Roll Back doesnt Work.. Looks Like so, but dont Install an old Version ..

**Comment by Ilovegym66** [comment]
Hi, I've configured a new container with debian buster, node 12, iobroker js-controller 3.1.6, admin 4.1.1, and mihome-vacuum 2.1.0.
I've in summary 4 Robots, for the test I configured one instance of the adapter, set to debug and start them.
On the next I configured the adapter, setup my credentials and click to load the map from the server.
The adapter starts, no issues in the log, the datapoints are created. The objects in the folder map/ are not filled. I open the mihome-app on my smartphone and login, sometimes this helps for the first start. But here not. 
Nothing happens.
I wait 3 hours, no faults, no map. 

Now I want to go back to the latest 2.0.10 or earlier, I can select this, the window open, and the output was realistic to go backwards.. but after the restart of the adapter the adapter is always on 2.1.0.

Same with other versions..  Some with other installations, on my productiv and at other users ( see forum ).

What I have tried, is to build canvas new "npm install canvas --unsafe-perm=true" and a "npm i" in the node_modules/iobroker.mihome-vacuum folder, but no effect.

iobroker fix the same, runs trough, no maps.

Any hints? :-)

**Comment by Ilovegym66** [comment]
iobroker iobroker # iobroker upgrade mihome-vacuum@2.0.9
Update mihome-vacuum from @2.1.0 to @2.0.9
NPM version: 6.14.5
npm install iobroker.mihome-vacuum@2.0.9 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.mihome-vacuum@2.0.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2020-07-12T10_48_33_762Z-debug.log

and in this:

iobroker iobroker # cat /home/iobroker/.npm/_logs/2020-07-12T10_48_33_762Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'iobroker.mihome-vacuum@2.0.9',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose npm-session a0684d32bcd26559
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/iobroker.mihome-vacuum 199ms (from cache)
8 silly registry:manifest no matching version for iobroker.mihome-vacuum@2.0.9 in the cache. Forcing revalidation.
9 http fetch GET 200 https://registry.npmjs.org/iobroker.mihome-vacuum 85ms
10 silly fetchPackageMetaData error for iobroker.mihome-vacuum@2.0.9 No matching version found for iobroker.mihome-vacuum@2.0.9.
11 timing stage:rollbackFailedOptional Completed in 2ms
12 timing stage:runTopLevelLifecycles Completed in 11325ms
13 verbose type version
14 verbose stack iobroker.mihome-vacuum: No matching version found for iobroker.mihome-vacuum@2.0.9.
14 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
14 verbose stack     at /usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:43:18
14 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
14 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
14 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
14 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
14 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
14 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
14 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
14 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
14 verbose stack     at processImmediate (internal/timers.js:456:21)
15 verbose cwd /opt/iobroker
16 verbose Linux 4.15.0-107-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.mihome-vacuum@2.0.9" "--loglevel" "error" "--prefix" "/opt/iobroker"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ETARGET
21 error notarget No matching version found for iobroker.mihome-vacuum@2.0.9.
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]
iobroker iobroker #

**Comment by Apollon77** [comment]
Available npm versions see https://www.npmjs.com/package/iobroker.mihome-vacuum and click on "Versions"
