### ISSUE TITLE
Adapter 2.2.0 Map wird nicht geladen Links bleiben leer

### ISSUE THREAD

**Issue by kapsreiter** [iobroker-community-adapters/ioBroker.mihome-vacuum#172]
Hall o
Ich hab nen PI 4 eigentlich alles aktuell
Der Adapter läuft
alle Räume sind da
nur der Map Pfad bleibt leer

im Log steht nur das

mihome-vacuum.0 | 2020-08-14 22:09:25.857 | info | (19642) create states for water box filter
-- | -- | -- | --
mihome-vacuum.0 | 2020-08-14 22:09:25.856 | info | (19642) create states for water box
mihome-vacuum.0 | 2020-08-14 22:09:07.025 | info | (19642) create state for carpet_mode
mihome-vacuum.0 | 2020-08-14 22:09:06.395 | info | (19642) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2020-08-14 22:09:06.015 | info | (19642) Connected
mihome-vacuum.0 | 2020-08-14 22:09:05.952 | info | (19642) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-08-14 22:09:05.935 | info | (19642) New generation or new fw(3.5.8,0876) detected, create new states goto and zoneclean

ich bin leider in Linux nicht so fit, bitte verzeiht mir

falls wer in Telegramm in der iobroker Gruppe ist oder mir ectl per Teamviewer oder speak  helfen kann wäre ich froh
danke
tom

**Comment by MeisterTR** [comment]
welches Model Hast du? bitte einmal einen Debug Log Auszug.

**Comment by kapsreiter** [comment]
Hallo!

Apter mihome-vacuum  Version 2.2.0  
Modell S5 Max
Firmware lt Mi Home APP 3.5.8_0876

Hier der debug LOG:



  |   |   |  
-- | -- | -- | --
mihome-vacuum.0 | 2020-08-15 08:23:49.494 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":891,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1
mihome-vacuum.0 | 2020-08-15 08:23:49.491 | debug | (28150) Receive <<< {"partner_id":"","id":45,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_0876","ap":{"ssid":"dexter","bssid":"74:83:c2:87:ca:a6","rssi":-47},"netif":{"localIp":"
mihome-vacuum.0 | 2020-08-15 08:23:49.483 | debug | (28150) Next WiFi check: 15.08 08:24
mihome-vacuum.0 | 2020-08-15 08:23:49.481 | debug | (28150) sendMsg[1] >>> {"id":45,"method":"miIO.info"}
mihome-vacuum.0 | 2020-08-15 08:23:49.479 | debug | (28150) sendMsg[1] >>> {"id":44,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:23:30.647 | debug | (28150) system.adapter.admin.0: logging true
mihome-vacuum.0 | 2020-08-15 08:23:29.484 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":880,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:23:29.476 | debug | (28150) sendMsg[1] >>> {"id":43,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:23:09.483 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":868,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:23:09.474 | debug | (28150) sendMsg[1] >>> {"id":42,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:22:50.518 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":862,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:22:50.516 | debug | (28150) Receive <<< {"partner_id":"","id":41,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_0876","ap":{"ssid":"dexter","bssid":"74:83:c2:87:ca:a6","rssi":-47},"netif":{"localIp":
mihome-vacuum.0 | 2020-08-15 08:22:49.472 | debug | (28150) Next WiFi check: 15.08 08:23
mihome-vacuum.0 | 2020-08-15 08:22:49.471 | debug | (28150) sendMsg[1] >>> {"id":41,"method":"miIO.info"}
mihome-vacuum.0 | 2020-08-15 08:22:49.469 | debug | (28150) sendMsg[1] >>> {"id":40,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:22:29.477 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":861,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:22:29.466 | debug | (28150) sendMsg[1] >>> {"id":39,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:22:09.473 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":860,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:22:09.465 | debug | (28150) sendMsg[1] >>> {"id":38,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:21:49.472 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":859,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:21:49.469 | debug | (28150) Receive <<< {"partner_id":"","id":37,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_0876","ap":{"ssid":"dexter","bssid":"74:83:c2:87:ca:a6","rssi":-47},"netif":{"localIp":
mihome-vacuum.0 | 2020-08-15 08:21:49.464 | debug | (28150) Next WiFi check: 15.08 08:22
mihome-vacuum.0 | 2020-08-15 08:21:49.462 | debug | (28150) sendMsg[1] >>> {"id":37,"method":"miIO.info"}
mihome-vacuum.0 | 2020-08-15 08:21:49.460 | debug | (28150) sendMsg[1] >>> {"id":36,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:21:29.471 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":858,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:21:29.458 | debug | (28150) sendMsg[1] >>> {"id":35,"method":"get_status"}
mihome-vacuum.0 | 2020-08-15 08:21:17.277 | debug | (28150) system.adapter.admin.0: logging false
mihome-vacuum.0 | 2020-08-15 08:21:09.463 | debug | (28150) Receive <<< {"result":[{"msg_ver":2,"msg_seq":857,"state":8,"battery":100,"clean_time":13,"clean_area":140000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":
mihome-vacuum.0 | 2020-08-15 08:21:09.456 | debug | (28150) sendMsg[1] >>> {"id":34,"method":"get_status"}




danke für deine Hilfe

**Comment by MeisterTR** [comment]
ich bräuchte einen auszug vom Saugvorgang, wo ich sehe ob und wie die Karte geholt wird

**Comment by kapsreiter** [comment]
bitte sehr

`

mihome-vacuum.0 | 2020-08-16 01:53:34.685 | debug | (2779) Mappointer_updated
-- | -- | -- | --
mihome-vacuum.0 | 2020-08-16 01:53:34.684 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F9"],"id":2360}
mihome-vacuum.0 | 2020-08-16 01:53:34.678 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:34.678 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:34.678 | debug | (2779) sendMsg[1] >>> {"id":2360,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:33.672 | debug | (2779) Receive <<< {"result":["ok"],"id":2359}
mihome-vacuum.0 | 2020-08-16 01:53:33.666 | debug | (2779) sendMsg[1] >>> {"id":2359,"method":"app_charge"}
mihome-vacuum.0 | 2020-08-16 01:53:33.663 | debug | (2779) stateChange mihome-vacuum.0.control.home {"val":true,"ack":false,"ts":1597535613659,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1597432361481}
mihome-vacuum.0 | 2020-08-16 01:53:32.676 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:32.538 | debug | (2779) update_Map got new time:1597535612
mihome-vacuum.0 | 2020-08-16 01:53:32.537 | debug | (2779) update_Map got new expires:1597537412
mihome-vacuum.0 | 2020-08-16 01:53:32.537 | debug | (2779) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/rubyslite/320252511/7?Expires=1597537412000&GalaxyAccessKeyId=5271733786445&Signature=Nq3Ni/4ckjx++Ljv13AfRfvC24U=
mihome-vacuum.0 | 2020-08-16 01:53:32.441 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:32.441 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F8"],"id":2358}
mihome-vacuum.0 | 2020-08-16 01:53:32.427 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:32.427 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:32.426 | debug | (2779) sendMsg[1] >>> {"id":2358,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:31.927 | debug | (2779) Receive <<< {"result":[{"msg_ver":2,"msg_seq":4260,"state":5,"battery":100,"clean_time":19,"clean_area":405000,"error_code":0,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0
mihome-vacuum.0 | 2020-08-16 01:53:31.926 | debug | (2779) Receive <<< {"partner_id":"","id":2357,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_0876","ap":{"ssid":"dexter","bssid":"74:83:c2:87:ca:a6","rssi":-47},"netif":{"localIp":
mihome-vacuum.0 | 2020-08-16 01:53:31.921 | debug | (2779) Next WiFi check: 16.08 01:54
mihome-vacuum.0 | 2020-08-16 01:53:31.920 | debug | (2779) sendMsg[1] >>> {"id":2357,"method":"miIO.info"}
mihome-vacuum.0 | 2020-08-16 01:53:31.920 | debug | (2779) sendMsg[1] >>> {"id":2356,"method":"get_status"}
mihome-vacuum.0 | 2020-08-16 01:53:30.426 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:30.297 | debug | (2779) update_Map got new time:1597535610
mihome-vacuum.0 | 2020-08-16 01:53:30.297 | debug | (2779) update_Map got new expires:1597537410
mihome-vacuum.0 | 2020-08-16 01:53:30.297 | debug | (2779) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/rubyslite/320252511/6?Expires=1597537410000&GalaxyAccessKeyId=5271733786445&Signature=I1r1YsjSLQJlM7Qw8SP/DCkR/SI=
mihome-vacuum.0 | 2020-08-16 01:53:30.208 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:30.207 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F7"],"id":2355}
mihome-vacuum.0 | 2020-08-16 01:53:30.201 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:30.201 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:30.200 | debug | (2779) sendMsg[1] >>> {"id":2355,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:28.199 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:28.068 | debug | (2779) update_Map got new time:1597535607
mihome-vacuum.0 | 2020-08-16 01:53:28.067 | debug | (2779) update_Map got new expires:1597537408
mihome-vacuum.0 | 2020-08-16 01:53:28.065 | debug | (2779) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/rubyslite/320252511/5?Expires=1597537408000&GalaxyAccessKeyId=5271733786445&Signature=JTBJCqLKf/mXJCpVIeWEPLTGFfQ=
mihome-vacuum.0 | 2020-08-16 01:53:27.928 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:27.927 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F6"],"id":2354}
mihome-vacuum.0 | 2020-08-16 01:53:27.916 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:27.916 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:27.907 | debug | (2779) sendMsg[1] >>> {"id":2354,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:25.904 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:25.723 | debug | (2779) update_Map got new time:1597535605
mihome-vacuum.0 | 2020-08-16 01:53:25.723 | debug | (2779) update_Map got new expires:1597537405
mihome-vacuum.0 | 2020-08-16 01:53:25.723 | debug | (2779) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/rubyslite/320252511/4?Expires=1597537405000&GalaxyAccessKeyId=5271733786445&Signature=+eko4U453CCKnyc+RiWm9W1RDt4=
mihome-vacuum.0 | 2020-08-16 01:53:25.577 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:25.575 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F5"],"id":2353}
mihome-vacuum.0 | 2020-08-16 01:53:25.566 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:25.566 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:25.565 | debug | (2779) sendMsg[1] >>> {"id":2353,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:23.564 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:23.434 | debug | (2779) update_Map got new time:1597535603
mihome-vacuum.0 | 2020-08-16 01:53:23.434 | debug | (2779) update_Map got new expires:1597537403
mihome-vacuum.0 | 2020-08-16 01:53:23.434 | debug | (2779) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/rubyslite/320252511/3?Expires=1597537403000&GalaxyAccessKeyId=5271733786445&Signature=CiWtSOVFBD9uxVjOJ9fDCF//pKU=
mihome-vacuum.0 | 2020-08-16 01:53:23.296 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:23.295 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F4"],"id":2352}
mihome-vacuum.0 | 2020-08-16 01:53:23.287 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:23.287 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:23.286 | debug | (2779) sendMsg[1] >>> {"id":2352,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:21.284 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:21.147 | debug | (2779) update_Map got new time:1597535601
mihome-vacuum.0 | 2020-08-16 01:53:21.147 | debug | (2779) update_Map got new expires:1597537401
mihome-vacuum.0 | 2020-08-16 01:53:21.146 | debug | (2779) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/rubyslite/320252511/2?Expires=1597537401000&GalaxyAccessKeyId=5271733786445&Signature=71qd2EM76sazK0HXc6UgwCqlK+E=
mihome-vacuum.0 | 2020-08-16 01:53:21.047 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:21.046 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F3"],"id":2351}
mihome-vacuum.0 | 2020-08-16 01:53:21.034 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:21.034 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:21.033 | debug | (2779) sendMsg[1] >>> {"id":2351,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:19.033 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:18.918 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:18.918 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F2"],"id":2350}
mihome-vacuum.0 | 2020-08-16 01:53:18.909 | debug | (2779) update_Map use old mapurl
mihome-vacuum.0 | 2020-08-16 01:53:18.908 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:18.908 | debug | (2779) sendMsg[1] >>> {"id":2350,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:16.906 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:16.661 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:16.660 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F0"],"id":2349}
mihome-vacuum.0 | 2020-08-16 01:53:16.654 | debug | (2779) update_Map use old mapurl
mihome-vacuum.0 | 2020-08-16 01:53:16.653 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:16.653 | debug | (2779) sendMsg[1] >>> {"id":2349,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:16.424 | debug | (2779) Mappointer_updated
mihome-vacuum.0 | 2020-08-16 01:53:16.423 | debug | (2779) Receive <<< {"result":["rubyslite%2F320252511%2F0"],"id":2348}
mihome-vacuum.0 | 2020-08-16 01:53:16.416 | debug | (2779) 1. Mappointer_nomap___retry
mihome-vacuum.0 | 2020-08-16 01:53:16.415 | debug | (2779) sendMsg[1] >>> {"id":2348,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:15.913 | debug | (2779) Receive <<< {"result":["retry"],"id":2347}
mihome-vacuum.0 | 2020-08-16 01:53:15.909 | debug | (2779) 0. Mappointer_nomap___retry
mihome-vacuum.0 | 2020-08-16 01:53:15.908 | debug | (2779) sendMsg[1] >>> {"id":2347,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:15.408 | debug | (2779) Receive <<< {"result":["retry"],"id":2346}
mihome-vacuum.0 | 2020-08-16 01:53:14.652 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:14.428 | debug | (2779) update_Map use old mapurl
mihome-vacuum.0 | 2020-08-16 01:53:14.427 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:14.427 | debug | (2779) sendMsg[1] >>> {"id":2346,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-08-16 01:53:12.426 | debug | (2779) TypeError: mapCreator.CanvasMap is not a function
mihome-vacuum.0 | 2020-08-16 01:53:12.131 | debug | (2779) Receive <<< {"result":[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}],"id":2345}
mihome-vacuum.0 | 2020-08-16 01:53:12.126 | debug | (2779) sendMsg[1] >>> {"id":2345,"method":"get_carpet_mode"}
mihome-vacuum.0 | 2020-08-16 01:53:12.114 | debug | (2779) update_Map got new time:1597535591
mihome-vacuum.0 | 2020-08-16 01:53:12.114 | debug | (2779) update_Map got new expires:1597537392
mihome-vacuum.0 | 2020-08-16 01:53:12.113 | debug | (2779) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/rubyslite/320252511/0?Expires=1597537392000&GalaxyAccessKeyId=5271733786445&Signature=KZiZxJjzO5quElJw1dYHDqyhz9s=
mihome-vacuum.0 | 2020-08-16 01:53:11.939 | debug | (2779) Receive <<< {"result":[78],"id":2344}
mihome-vacuum.0 | 2020-08-16 01:53:11.926 | debug | (2779) update_Map need new mapurl
mihome-vacuum.0 | 2020-08-16 01:53:11.926 | debug | (2779) update_Map Mimap enabled
mihome-vacuum.0 | 2020-08-16 01:53:11.925 | debug | (2779) sendMsg[1] >>> {"id":2344,"method":"get_sound_volume"}
mihome-vacuum.0 | 2020-08-16 01:53:11.924 | debug | (2779) Receive <<< {"result":[{"msg_ver":2,"msg_seq":4259,"state":5,"battery":100,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0,"lab_
mihome-vacuum.0 | 2020-08-16 01:53:11.918 | debug | (2779) sendMsg[1] >>> {"id":2343,"method":"get_status"}
mihome-vacuum.0 | 2020-08-16 01:53:09.924 | debug | (2779) Receive <<< {"result":["ok"],"id":2342}
mihome-vacuum.0 | 2020-08-16 01:53:09.918 | debug | (2779) sendMsg[1] >>> {"id":2342,"method":"app_start"}
mihome-vacuum.0 | 2020-08-16 01:53:09.917 | info | (2779) trigger cleaning all

`

**Comment by MeisterTR** [comment]
```
(2779) TypeError: mapCreator.CanvasMap is not a function
```

Dein Canvas Modul ist nicht richtig installiert kann sein dass die Rechte falsch gesetzt sind oder das Modul noch nciht intsalliert ist Schau mal im Forum da wurde das Problem schon behandelt

**Comment by kapsreiter** [comment]
hallo
das haben sich schon 2 Leute remote angesehen und das problem nicht gefunden

kannst mal evtl kurz das bei mir Chechen?  ich bin leider linux newbie   kämpf mich seit 1 jähr durch h iobroker  normal läuft alles

werke jetzt mehrere tage dran und bekomme nicht hin

kontakt gerne per mail

pinballer
at
gmx
.net


lg
tom
