### ISSUE TITLE
Suche Hilfe mit MAP Link der nicht erscheint

### ISSUE THREAD

**Issue by kapsreiter** [iobroker-community-adapters/ioBroker.mihome-vacuum#173]
vorab, JA es wird wohl kein Adapter BUG sein

jedoch haben nun 2 Leute netterweise probiert mir Linux newbie zu helfen und es nicht hinbekommen.

Leider weiß ich nicht wem oder wo ich noch um Hilfe fragen könnte

Thema war

https//github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/172

falls sich wer gegen Spende bereiterklären würde mir per Teamvifer zu helfen, wäre ich sehr dankbar

bin unter  folgende email erreichbar     pinballer@              Gmx.net               

danke
tom

**Comment by MeisterTR** [comment]
bitte diesen aufruf im forum und nicht auf git. viel erfolg

**Comment by kapsreiter** [comment]
Ok

Von meinem iPhone gesendet
