### ISSUE TITLE
[ kxf321.mop.mo001] Support ZDG300

### ISSUE THREAD

**Issue by fuchs-1978** [iobroker-community-adapters/ioBroker.mihome-vacuum#174]
Der Wischroboter wird aktuell nicht unterstützt. Der Token kann ausgelesen werden, allerdings ohne Funktion

**Comment by gremlin1982** [comment]
Hi Meister, war die letzten Tage hiezu auch mit dir in Kontakt, wäre klasse wenn es irgendwann funktionieren würde. Teamviewersession jederzeit

**Comment by MeisterTR** [comment]
bitte Mal den neuen Adapter installieren um die Modellbezeichnung zu bekommen

**Comment by gremlin1982** [comment]
Model kxf321.mop.mo001 not supported!

**Comment by MeisterTR** [comment]
Um zu sehen welche Modelle am verbreitetsten sind bitte hier Abstimmen
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum#supported-devices-and-fetures
