### ISSUE TITLE
(second) Instance restarts in a loop

### ISSUE THREAD

**Issue by AndreasExner** [iobroker-community-adapters/ioBroker.mihome-vacuum#183]
The (second) instance terminates immediately after the first start. I'm not able to finisch "Get Devices". Objects are created but empty. There is only a warning in the logs:

host.xxx | 2020-09-27 13:09:51.318 | info | instance system.adapter.mihome-vacuum.1 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
mihome-vacuum.1 | 2020-09-27 13:09:51.127 | info | (5736) starting. Version 2.0.7 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.18.3, js-controller: 3.1.6
mihome-vacuum.1 | 2020-09-27 13:09:50.896 | warn | (5736) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.1 | 2020-09-27 13:09:50.893 | warn | (5736) Object mihome-vacuum.1.info.dnd is invalid: obj.common.type has an invalid value (switch) but has to be one of number, string, boolean, array, object, mixed, file, json
host.xxx | 2020-09-27 13:09:48.888 | info | instance system.adapter.mihome-vacuum.1 started with pid 5736
host.xxx | 2020-09-27 13:09:18.830 | info | Restart adapter system.adapter.mihome-vacuum.1 because enabled

**Comment by ZeroQool007** [comment]
Hallo, leider läßt sich keine 2. Instanz starten. Wir haben 2 MI ROBOTS im Haus. Gibt es einen Workaround? 

Danke

Gruß
