### ISSUE TITLE
Warn Message for developer

### ISSUE THREAD

**Issue by flapman** [iobroker-community-adapters/ioBroker.mihome-vacuum#186]
mihome-vacuum.0 | 2020-10-03 18:30:28.426 | warn | (28030) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
mihome-vacuum.0 | 2020-10-03 18:30:28.418 | warn | (28030) Object mihome-vacuum.0.info.dnd is invalid: obj.common.type has an invalid value (switch) but has to be one of number, string, boolean, array, object,

**Comment by DerT94** [comment]
I have also received it
![image](https://user-images.githubusercontent.com/58786605/100541573-1b795200-3245-11eb-85a3-87584f3c5ee5.png)

**Comment by MeisterTR** [comment]
should be fixed
