### ISSUE TITLE
GoHome Tastendruck funktioniert nur zum Teil

### ISSUE THREAD

**Issue by flapman** [iobroker-community-adapters/ioBroker.mihome-vacuum#188]
Wenn der Roboter zu einer Koordinate geschickt wird, lässt er sich nicht über GoHome zur Station zurückschicken.
GoHome funktioniert allerdings während des reinigens.

-------------------------------English----------------------------------------------------------
There is no action on the robock S5Max when I try to push the simulated button on the data point GoHome.

GoHome works in cleaning mode.
If sending the robot to a specific point, he can not be send back after reaching the point by pushing the button.

**Comment by MeisterTR** [comment]
shoud be fixed
