### ISSUE TITLE
Cleaning finished datapoint missing

### ISSUE THREAD

**Issue by flapman** [iobroker-community-adapters/ioBroker.mihome-vacuum#189]
Ich vermisse den Datenpunkt, Reinigung abgeschlossen. Der Roboter informiert ja einen das er fertig ist und sendet auch eine Push Nachricht und fährt zurück zur Station. Kann man diesen mit einbinden?

------------English----------------
I am missing the datapoint cleaning finished. As the roboter inform about the cleaning and sending a push notification, there should be something.

**Comment by MeisterTR** [comment]
das siehst du ja im state : "mihome-vacuum.0.info.state" wenn er von cleaning nach docked wechselt
