### ISSUE TITLE
Errors "New generation or new fw detected, create new states goto and zoneclean"

### ISSUE THREAD

**Issue by markuslosco** [iobroker-community-adapters/ioBroker.mihome-vacuum#193]
(4204) New generation or new fw detected, create new states goto and zoneclean
viomi.vacuum.v8 - 
Firmware 3.5.3_0017 
Gerät wird erkannt jedoch Meldung siehe oben erscheint. Keine Map Url usw verfügbar. Debian mit IOBroker auf Intel Nuc
mihome-vacuum Adapter Version 2.0.7

Zusatzinfo lt Log:
mihome-vacuum.0 | 2020-11-12 20:35:50.351 | warn | (4204) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
mihome-vacuum.0 | 2020-11-12 20:35:50.348 | warn | (4204) Object mihome-vacuum.0.info.dnd is invalid: obj.common.type has an invalid value (switch) but has to be one of number, string, boolean, array, object, mixed, file, json

Debian mit iobroker
Node.js: v10.23.0
NPM: 6.14.8

I think its the same... https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/165

**Comment by markuslosco** [comment]
mihome-vacuum habe ich auf die Version 2.2.4 aktualisiert. 
- Log "starting. Version 2.2.4 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v10.23.0, js-controller: 3.1.6"
- Die Warnung "This object will not be created in future versions. Please report this to the developer." erscheint nicht mehr. 
- Die Hinweismeldung "New generation or new fw(3.5.3,0017) detected, create new states goto and zoneclean" erscheint noch jedoch nicht mehr als Fehler oder Warnung
-Interessant ist die Warnung "Time difference between Mihome Vacuum and ioBroker: 1 sec" die zeigt mir das die Verbindung schon besteht.

**Comment by dirkhe** [comment]
Das mit der Firmware ist nur zur Info. Mit der Zeitdifferenz ist meistens ein Zeichen, dass der robbi nicht mit dem inet verbunden ist. Ist aber nicht weiter tragisch, wenn er connected ist.
