### ISSUE TITLE
Nach Update von 2.0.7 auf 2.1.1 MAP ohne Funktion

### ISSUE THREAD

**Issue by hoepps2802** [iobroker-community-adapters/ioBroker.mihome-vacuum#195]
nach dem Update auf 2.1.1 von 2.0.7 wird der Datenpunkt
MAP64 und MAPURL nicht mehr aktualisiert

bin dann zurück auf 2.0.7 
da kam dann  TypeError: mapCreator.CanvasMap is not a function

bin dann auf 2.4.4 aber auch keine Besserung.

Gruß

Matze aus Kiel

**Comment by hoepps2802** [comment]
habs selbst gelöst
muss CANVAS neu installieren
in  2.1.1 kam aber dazu kein Hinweis
nur unter 2.0.7 stand dazu was

**Comment by DennisRoschke** [comment]
sorry hab das gleich Problem und weis leider nicht was CANVAS ist bzw wie ich es neu instaliere für hilfe bzw ne mini erklärung währe ich sehr dankbar

**Comment by hoepps2802** [comment]
Ich habe es so gemacht

cd /opt/iobroker

sudo npm install canvas --unsafe-perm=true

**Comment by DennisRoschke** [comment]
hmm hab genau das probiert bei mir passiert dann einfach garnichts

**Comment by hoepps2802** [comment]
Was steht den im Log?
Bei mir war unter 2.0.7 der Fehler mit Canvas im Log.
