### ISSUE TITLE
Can't retrieve connection on server

### ISSUE THREAD

**Issue by Spampunk** [iobroker-community-adapters/ioBroker.mihome-vacuum#196]
Roborock S5 Max, F/W 3.5.8_1026
Connected to german server on Xiaomi Home App
iobroker on Debian Buster
mihome-vacuum app version 2.1.1

I don't get a connction to the server in the adapter. When clicking on "get devices" the circle just keeps on turning.

Log:

> 

mihome-vacuum.0 | 2020-12-06 18:41:01.224 | debug | (10042) Xiaomi Cloud: Logging in
-- | -- | -- | --
mihome-vacuum.0 | 2020-12-06 18:41:01.217 | silly | (10042) States system redis pmessage io.messagebox.system.adapter.mihome-vacuum.0/io.messagebox.system.adapter.mihome-vacuum.0:{"command":"discovery","message":{"password":"xxxxxxxxxxxx","username":"spa
mihome-vacuum.0 | 2020-12-06 18:40:21.171 | silly | (10042) States system redis pmessage system.adapter.mihome-vacuum.0.logLevel/system.adapter.mihome-vacuum.0.logLevel:{"val":"silly","ack":true,"ts":1607276421152,"q":0,"from":"system.adapter.mihome-va
mihome-vacuum.0 | 2020-12-06 18:40:21.142 | error | (10042) Token not specified!
mihome-vacuum.0 | 2020-12-06 18:40:21.069 | info | (10042) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.20.0, js-controller: 3.1.6

I just tried the FloleVac app and got connection immediatly with the european server.

**Comment by SLongus** [comment]
Same here =(

**Comment by waoler** [comment]
I got the same issue!

**Comment by HerrKuscho** [comment]
I got the issue of a yellow dot, no connection to mihome-vacuum  
connection to host = true and heart beat= true

**Comment by HerrKuscho** [comment]
mit 2.2.4 und 10 Minuten Wartezeit ist die Verbindung da !!!!

**Comment by waoler** [comment]
> 
> 
> mit 2.2.4 und 10 Minuten Wartezeit ist die Verbindung da !!!!

I still got the Problem even after i update to version 2.2.4. After I clicked the "GET DEVICES" Button the loading bar is spinnig endless.

**Comment by Spampunk** [comment]
Good news: I have access to the map now. Bad news: I don't know how or why, didn't change anything consciously, just one routine-update to the latest JS engine.  Then tried the "get devices" button one day almost accidentally and bang! I was in.

Happy!
