### ISSUE TITLE
Keine Verbindung

### ISSUE THREAD

**Issue by blackluzie** [iobroker-community-adapters/ioBroker.mihome-vacuum#197]
App und Adapter auf China
Auslesen des Token funktioniert 1a - nur die Felder unten werden nicht automatisch gefüllt - musste ich von Hand machen.

Adapter Version 2.2.4 - Node.JS 12.16.2, NPM 6.14.9

hier die Log

![image](https://user-images.githubusercontent.com/56870555/101825669-3645a380-3b2e-11eb-90a1-2b46a99bde68.png)
![image](https://user-images.githubusercontent.com/56870555/101825807-7147d700-3b2e-11eb-943a-1f24c1e971a8.png)

**Comment by quorle** [comment]
Bei mir das gleiche Problem. Habe schon mehrere Versionen getestet.
 Version 2.1.1 , node: v12.20.0, js-controller: 3.1.6

**Comment by MeisterTR** [comment]
die Verbindung kann gelegentlich etwas dauern der markierte eintrag kommt nicht vom adapter und kann vernachlässigt werden, ggf mal den roboter neustarten
