### ISSUE TITLE
Map wird nicht geladen

### ISSUE THREAD

**Issue by quorle** [iobroker-community-adapters/ioBroker.mihome-vacuum#206]
Habe ein Problem mit der aktuellen Version des Adapters.

 js-controller: 3.1.6
Node.js v12.20.0
NPM 6.14.8

Hier wird die Karte vom Roboter S5 nicht geladen. Adapter wurde mehrmals neu installiert und auch der Roboter wurde in die App XiaomiHome eingebunden.

LOG:

`mihome-vacuum.0` | 2020-12-29 14:33:31.315 | debug | (10077) Receive <<< {"result":[{"msg_ver":3,"msg_seq":2078,"state":8,"battery":100,"clean_time":125,"clean_area":1817500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state
-- | -- | -- | --
mihome-vacuum.0 | 2020-12-29 14:33:31.307 | debug | (10077) sendMsg[1] >>> {"id":36,"method":"get_status"}
mihome-vacuum.0 | 2020-12-29 14:33:13.330 | debug | (10077) Mappointer_updated
mihome-vacuum.0 | 2020-12-29 14:33:13.329 | debug | (10077) Receive <<< {"result":["robomap%2F117889139%2F1"],"id":35}
mihome-vacuum.0 | 2020-12-29 14:33:13.323 | debug | (10077) sendMsg[1] >>> {"id":35,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-12-29 14:33:12.527 | debug | (10077) update_Map got new time:1609248792
mihome-vacuum.0 | 2020-12-29 14:33:12.527 | debug | (10077) update_Map got new expires:1609250592
mihome-vacuum.0 | 2020-12-29 14:33:12.527 | debug | (10077) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/robomap/117889139/0?Expires=1609250592000&GalaxyAccessKeyId="AUSKOMMENTIERT"&Signature="AUSKOMMENTIERT"=
mihome-vacuum.0 | 2020-12-29 14:33:12.428 | debug | (10077) update_Map need new mapurl
mihome-vacuum.0 | 2020-12-29 14:33:12.428 | debug | (10077) update_Map Mimap enabled
mihome-vacuum.0 | 2020-12-29 14:33:12.428 | debug | (10077) get rooms from map
mihome-vacuum.0 | 2020-12-29 14:33:12.427 | debug | (10077) Empty array try to get from Map
mihome-vacuum.0 | 2020-12-29 14:33:12.427 | debug | (10077) Receive <<< {"result":[],"id":34}
mihome-vacuum.0 | 2020-12-29 14:33:12.422 | debug | (10077) sendMsg[1] >>> {"id":34,"method":"get_room_mapping"}
mihome-vacuum.0 | 2020-12-29 14:33:11.833 | debug | (10077) Receive <<< {"result":[284445,4011195000,270,[1609174797,1608888682,1608396007,1608225365,1608138608,1608138588,1608053262,1607946809,1607799630,1607779608,1607778824,1607681074,1607621404,160
mihome-vacuum.0 | 2020-12-29 14:33:11.824 | debug | (10077) sendMsg[1] >>> {"id":33,"method":"get_clean_summary"}
mihome-vacuum.0 | 2020-12-29 14:33:11.336 | debug | (10077) Receive <<< {"result":[{"main_brush_work_time":285141,"side_brush_work_time":285141,"filter_work_time":285141,"filter_element_work_time":0,"sensor_dirty_time":74663}],"id":32}
mihome-vacuum.0 | 2020-12-29 14:33:11.322 | debug | (10077) sendMsg[1] >>> {"id":32,"method":"get_consumable"}
mihome-vacuum.0 | 2020-12-29 14:33:11.321 | info | (10077) create states for water box filter
mihome-vacuum.0 | 2020-12-29 14:33:11.321 | info | (10077) create states for water box
mihome-vacuum.0 | 2020-12-29 14:33:11.319 | debug | (10077) Receive <<< {"result":[{"msg_ver":3,"msg_seq":2077,"state":8,"battery":100,"clean_time":125,"clean_area":1817500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state
mihome-vacuum.0 | 2020-12-29 14:33:11.304 | debug | (10077) sendMsg[1] >>> {"id":31,"method":"get_status"}
mihome-vacuum.0 | 2020-12-29 14:32:56.771 | debug | (10077) Xiaomi Cloud: Login successful
mihome-vacuum.0 | 2020-12-29 14:32:56.266 | debug | (10077) CLEAN_LOGGING[{"Datum":"28.12","Start":"17:59","Saugzeit":"2 min","Fläche":"1.82 m²","Error":0,"Ende":false},{"Datum":"25.12","Start":"10:31","Saugzeit":"14 min","Fläche":"15.9 m²","Error":0,"
mihome-vacuum.0 | 2020-12-29 14:32:56.071 | debug | (10077) Receive <<< {"result":[[1584532593,1584533862,1251,21082500,0,1,1,1]],"id":30}
mihome-vacuum.0 | 2020-12-29 14:32:56.065 | debug | (10077) sendMsg[1] >>> {"id":30,"method":"get_clean_record","params":[1584532593]}
mihome-vacuum.0 | 2020-12-29 14:32:55.868 | debug | (10077) Receive <<< {"result":[[1607348296,1607351171,2761,44535000,0,0,2,1]],"id":29}
mihome-vacuum.0 | 2020-12-29 14:32:55.863 | debug | (10077) sendMsg[1] >>> {"id":29,"method":"get_clean_record","params":[1607348296]}
mihome-vacuum.0 | 2020-12-29 14:32:55.675 | debug | (10077) Receive <<< {"result":[[1607360626,1607364290,3658,52395000,0,1,2,1]],"id":28}
mihome-vacuum.0 | 2020-12-29 14:32:55.662 | debug | (10077) sendMsg[1] >>> {"id":28,"method":"get_clean_record","params":[1607360626]}
mihome-vacuum.0 | 2020-12-29 14:32:55.266 | debug | (10077) Receive <<< {"result":[[1607536168,1607536542,368,9460000,0,0,2,3]],"id":26}
mihome-vacuum.0 | 2020-12-29 14:32:55.259 | debug | (10077) sendMsg[1] >>> {"id":26,"method":"get_clean_record","params":[1607536168]}
mihome-vacuum.0 | 2020-12-29 14:32:55.064 | debug | (10077) Receive <<< {"result":[[1607537484,1607538211,722,15402500,0,0,1,1]],"id":25}
mihome-vacuum.0 | 2020-12-29 14:32:55.057 | debug | (10077) sendMsg[1] >>> {"id":25,"method":"get_clean_record","params":[1607537484]}
mihome-vacuum.0 | 2020-12-29 14:32:54.869 | debug | (10077) Receive <<< {"result":[[1607595622,1607596283,661,13370000,0,1,1,1]],"id":24}
mihome-vacuum.0 | 2020-12-29 14:32:54.855 | debug | (10077) sendMsg[1] >>> {"id":24,"method":"get_clean_record","params":[1607595622]}
mihome-vacuum.0 | 2020-12-29 14:32:54.682 | debug | (10077) Receive <<< {"result":[[1607621404,1607623532,2117,34615000,0,1,1,1]],"id":23}
mihome-vacuum.0 | 2020-12-29 14:32:54.653 | debug | (10077) sendMsg[1] >>> {"id":23,"method":"get_clean_record","params":[1607621404]}
mihome-vacuum.0 | 2020-12-29 14:32:54.468 | debug | (10077) Receive <<< {"result":[[1607681074,1607681079,3,0,0,0,2,1]],"id":22}
mihome-vacuum.0 | 2020-12-29 14:32:54.451 | debug | (10077) sendMsg[1] >>> {"id":22,"method":"get_clean_record","params":[1607681074]}
mihome-vacuum.0 | 2020-12-29 14:32:54.260 | debug | (10077) Receive <<< {"result":[[1607778824,1607779505,681,13437500,0,1,1,1]],"id":21}
mihome-vacuum.0 | 2020-12-29 14:32:54.249 | debug | (10077) sendMsg[1] >>> {"id":21,"method":"get_clean_record","params":[1607778824]}
mihome-vacuum.0 | 2020-12-29 14:32:54.065 | debug | (10077) Receive <<< {"result":[[1607779608,1607780315,620,12752500,0,0,1,1]],"id":20}
mihome-vacuum.0 | 2020-12-29 14:32:54.047 | debug | (10077) sendMsg[1] >>> {"id":20,"method":"get_clean_record","params":[1607779608]}
mihome-vacuum.0 | 2020-12-29 14:32:53.858 | debug | (10077) Receive <<< {"result":[[1607799630,1607799780,150,2532500,0,1,2,2]],"id":19}
mihome-vacuum.0 | 2020-12-29 14:32:53.846 | debug | (10077) sendMsg[1] >>> {"id":19,"method":"get_clean_record","params":[1607799630]}
mihome-vacuum.0 | 2020-12-29 14:32:53.658 | debug | (10077) Receive <<< {"result":[[1607946809,1607947609,721,15052500,0,0,1,1]],"id":18}
mihome-vacuum.0 | 2020-12-29 14:32:53.645 | debug | (10077) sendMsg[1] >>> {"id":18,"method":"get_clean_record","params":[1607946809]}
mihome-vacuum.0 | 2020-12-29 14:32:53.638 | debug | (10077) Mappointer_updated
mihome-vacuum.0 | 2020-12-29 14:32:53.637 | debug | (10077) Receive <<< {"result":["robomap%2F117889139%2F0"],"id":17}
mihome-vacuum.0 | 2020-12-29 14:32:53.628 | debug | (10077) 1. Mappointer_nomap___retry
mihome-vacuum.0 | 2020-12-29 14:32:53.628 | debug | (10077) sendMsg[1] >>> {"id":17,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-12-29 14:32:53.454 | debug | (10077) Receive <<< {"result":[[1608053262,1608054584,1304,25605000,0,1,1,1]],"id":16}
mihome-vacuum.0 | 2020-12-29 14:32:53.443 | debug | (10077) sendMsg[1] >>> {"id":16,"method":"get_clean_record","params":[1608053262]}
mihome-vacuum.0 | 2020-12-29 14:32:53.233 | debug | (10077) Receive <<< {"result":[[1608138588,1608138596,8,0,0,0,1,1]],"id":15}
mihome-vacuum.0 | 2020-12-29 14:32:53.224 | debug | (10077) sendMsg[1] >>> {"id":15,"method":"get_clean_record","params":[1608138588]}
mihome-vacuum.0 | 2020-12-29 14:32:53.127 | debug | (10077) Receive <<< {"result":["retry"],"id":14}
mihome-vacuum.0 | 2020-12-29 14:32:53.118 | debug | (10077) 0. Mappointer_nomap___retry
mihome-vacuum.0 | 2020-12-29 14:32:53.118 | debug | (10077) sendMsg[1] >>> {"id":14,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-12-29 14:32:53.034 | debug | (10077) Receive <<< {"result":[[1608138608,1608139248,640,13540000,0,1,2,3]],"id":13}
mihome-vacuum.0 | 2020-12-29 14:32:53.023 | debug | (10077) sendMsg[1] >>> {"id":13,"method":"get_clean_record","params":[1608138608]}
mihome-vacuum.0 | 2020-12-29 14:32:52.840 | debug | (10077) Receive <<< {"result":[[1608225365,1608226001,636,13482500,0,1,2,3]],"id":12}
mihome-vacuum.0 | 2020-12-29 14:32:52.821 | debug | (10077) sendMsg[1] >>> {"id":12,"method":"get_clean_record","params":[1608225365]}
mihome-vacuum.0 | 2020-12-29 14:32:52.631 | debug | (10077) Receive <<< {"result":[[1608396007,1608397972,1965,40797500,0,1,2,3]],"id":11}
mihome-vacuum.0 | 2020-12-29 14:32:52.620 | debug | (10077) sendMsg[1] >>> {"id":11,"method":"get_clean_record","params":[1608396007]}
mihome-vacuum.0 | 2020-12-29 14:32:52.616 | debug | (10077) Receive <<< {"result":["retry"],"id":10}
mihome-vacuum.0 | 2020-12-29 14:32:52.604 | debug | (10077) sendMsg[1] >>> {"id":10,"method":"get_map_v1"}
mihome-vacuum.0 | 2020-12-29 14:32:52.426 | debug | (10077) Receive <<< {"result":[[1608888682,1608889549,867,15897500,0,1,2,3]],"id":9}
mihome-vacuum.0 | 2020-12-29 14:32:52.421 | debug | (10077) get rooms from map pending...
mihome-vacuum.0 | 2020-12-29 14:32:52.421 | debug | (10077) get rooms from map
mihome-vacuum.0 | 2020-12-29 14:32:52.421 | debug | (10077) Empty array try to get from Map
mihome-vacuum.0 | 2020-12-29 14:32:52.420 | debug | (10077) Receive <<< {"result":[],"id":8}
mihome-vacuum.0 | 2020-12-29 14:32:52.419 | debug | (10077) sendMsg[1] >>> {"id":9,"method":"get_clean_record","params":[1608888682]}
mihome-vacuum.0 | 2020-12-29 14:32:52.415 | info | (10077) create state for carpet_mode
mihome-vacuum.0 | 2020-12-29 14:32:52.414 | debug | (10077) Receive <<< {"result":[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}],"id":7}
mihome-vacuum.0 | 2020-12-29 14:32:52.405 | debug | (10077) sendMsg[1] >>> {"id":8,"method":"get_room_mapping"}
mihome-vacuum.0 | 2020-12-29 14:32:52.404 | debug | (10077) sendMsg[1] >>> {"id":7,"method":"get_carpet_mode"}
mihome-vacuum.0 | 2020-12-29 14:32:52.229 | debug | (10077) Receive <<< {"result":[[1609174797,1609174922,125,1817500,0,0,2,2]],"id":6}
mihome-vacuum.0 | 2020-12-29 14:32:52.218 | debug | (10077) sendMsg[1] >>> {"id":6,"method":"get_clean_record","params":[1609174797]}
mihome-vacuum.0 | 2020-12-29 14:32:52.216 | debug | (10077) Receive <<< {"result":[284445,4011195000,270,[1609174797,1608888682,1608396007,1608225365,1608138608,1608138588,1608053262,1607946809,1607799630,1607779608,1607778824,1607681074,1607621404,16
mihome-vacuum.0 | 2020-12-29 14:32:52.204 | debug | (10077) sendMsg[1] >>> {"id":5,"method":"get_clean_summary"}
mihome-vacuum.0 | 2020-12-29 14:32:52.020 | debug | (10077) Receive <<< {"result":[{"main_brush_work_time":285141,"side_brush_work_time":285141,"filter_work_time":285141,"filter_element_work_time":0,"sensor_dirty_time":74663}],"id":4}
mihome-vacuum.0 | 2020-12-29 14:32:52.004 | debug | (10077) sendMsg[1] >>> {"id":4,"method":"get_consumable"}
mihome-vacuum.0 | 2020-12-29 14:32:51.833 | info | (10077) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2020-12-29 14:32:51.819 | debug | (10077) Receive <<< {"result":[75],"id":3}
mihome-vacuum.0 | 2020-12-29 14:32:51.805 | debug | (10077) sendMsg[1] >>> {"id":3,"method":"get_sound_volume"}
mihome-vacuum.0 | 2020-12-29 14:32:51.622 | debug | (10077) Receive <<< {"partner_id":"","id":2,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.7_002008","ap":{"ssid":"AUSKOMMENTIERT","bssid":""AUSKOMMENTIERT"","rssi":-75},"netif":{"localI
mihome-vacuum.0 | 2020-12-29 14:32:51.605 | debug | (10077) Next WiFi check: 29.12 14:33
mihome-vacuum.0 | 2020-12-29 14:32:51.604 | debug | (10077) sendMsg[1] >>> {"id":2,"method":"miIO.info"}
mihome-vacuum.0 | 2020-12-29 14:32:51.402 | info | (10077) Connected
mihome-vacuum.0 | 2020-12-29 14:32:51.395 | debug | (10077) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2020-12-29 14:32:51.393 | debug | (10077) Receive <<< {"result":[{"msg_ver":3,"msg_seq":2076,"state":8,"battery":100,"clean_time":125,"clean_area":1817500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_stat
mihome-vacuum.0 | 2020-12-29 14:32:51.382 | debug | (10077) sendMsg[1] >>> {"id":1,"method":"get_status"}
mihome-vacuum.0 | 2020-12-29 14:32:51.362 | debug | (10077) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type=='state') emit(doc._id, doc) }
mihome-vacuum.0 | 2020-12-29 14:32:51.354 | debug | (10077) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2020-12-29 14:32:51.353 | info | (10077) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2020-12-29 14:32:51.352 | debug | (10077) Receive <<< Helo <<< "AUSKOMMENTIERT"
mihome-vacuum.0 | 2020-12-29 14:32:51.345 | info | (10077) New generation or new fw(3.5.7,002008) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2020-12-29 14:32:51.343 | info | (10077) extend state mop for State control.fan_power
mihome-vacuum.0 | 2020-12-29 14:32:51.341 | info | (10077) change states from State control.fan_power
mihome-vacuum.0 | 2020-12-29 14:32:51.307 | debug | (10077) server started on 0.0.0.0:53421
mihome-vacuum.0 | 2020-12-29 14:32:51.295 | info | (10077) Create state clean_home for controlling by cloud adapter
mihome-vacuum.0 | 2020-12-29 14:32:51.294 | info | (10077) Expert mode enabled, states created
mihome-vacuum.0 | 2020-12-29 14:32:51.285 | debug | (10077) Xiaomi Cloud: Logging in
mihome-vacuum.0 | 2020-12-29 14:32:51.284 | debug | (10077) load Map creator... false
mihome-vacuum.0 | 2020-12-29 14:32:51.246 | info | (10077) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.20.0, js-controller: 3.1.6

Eventuell kann man das Problem mit der aktuellen Node beheben?

**Comment by root01** [comment]
Hab das gleiche Problem seit 24.12. mit dem MiVacuum.

Adapter: 2.2.4
Nodejs: 14.15.3 (ging auch mit 12.20.0 nicht)
NPM:6.14.9

**Comment by quorle** [comment]
Also bei mir läuft es nun.
hab bei der Installation gesehen, dass Canvas nicht installiert wurde. Bitte checke das mal bei der Installation des Treibers.
Sollte dies der Fall sein, dann Canvas folgendermaßen ( wie auch in der Anleitung beschrieben ) installieren:
```
Fehler bei der Installation
Wenn der Adapter nicht installiert werden kann, kann Canvas nicht installiert werden

npm ERR! canvas@2.6.1 install: node-pre-gyp install --fallback-to-build npm ERR! Exit status 1

Dann müssen folgende Packete und Bibliotheken selber installiert werden:

sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

sudo npm install canvas --unsafe-perm=true
```

Im Anschluss bin ich via Putty auf meinen ioBroker und habe folgendes ausgeführt:

1. Adapter vacuum stoppen
2. in das Verzeichnis gehen: /opt/iobroker/node_modules/iobroker.mihome-vacuum
3. Befehl ausführen: npm i
4. Adapter starten
5. Kann bis zu 20 Minuten dauern, bis die Karte erscheint

**Comment by root01** [comment]
Funktioniert. Dankeschön.
