### ISSUE TITLE
Adapter not Starting 

### ISSUE THREAD

**Issue by chrineuh** [iobroker-community-adapters/ioBroker.mihome-vacuum#209]
Hello, 

Since i rebootet my iobroker server the vacuum adater ist always red ist never goes to green or yellow, 

I have uninstall it for about 3 times and reinstall but the fault is alread there. 

Picture of the log 

![grafik](https://user-images.githubusercontent.com/60777681/103923134-05e52b00-5115-11eb-98a1-8a2c68eef19c.png)

**Comment by MeisterTR** [comment]
please post a debug log to and/or the error message
