### ISSUE TITLE
Keine 2. Instanz möglich

### ISSUE THREAD

**Issue by ZeroQool007** [iobroker-community-adapters/ioBroker.mihome-vacuum#212]
Hallo, 

leider ist es nicht möglich eine 2. Instanz zu starten, z.B. wenn man 2 Robots im Haus hat. 

Gibt es einen Workaround?

Danke

Gruß

**Comment by MeisterTR** [comment]
hast du wie in der readme beschrieben den Port geänder?

**Comment by ZeroQool007** [comment]
Hallo,

ach Mist. Mein Fehler. Funktioniert nun. Vielen Dank!

Gruß
