### ISSUE TITLE
Log warning with new JS-controller 3.2.8

### ISSUE THREAD

**Issue by Xenon-s** [iobroker-community-adapters/ioBroker.mihome-vacuum#213]
![mi issue](https://user-images.githubusercontent.com/65488191/105577529-85603480-5d7a-11eb-97f0-30c24d72d007.png)

adapter: V 2.1.1
js-controller: 3.2.8
nodeJS: 12.20.1

**Comment by Baenker** [comment]
Bei mir nach Update js-controller ebenfalls:

`2021-03-13 08:01:08.016 - warn: mihome-vacuum.0 (1350) State "mihome-vacuum.0.control.clean_home" has no existing object, this might lead to an error in future versions`

**Comment by marlan99** [comment]
Diese Warnung ist leider immer noch vorhanden.
Einen Tipp wie man zwischenzeitlich das Objekt manuell anlegen soll/kann ?
