### ISSUE TITLE
uncaught exception: Cannot read property 'val' of null

### ISSUE THREAD

**Issue by Daniel-K84** [iobroker-community-adapters/ioBroker.mihome-vacuum#215]
Hey,

I got the adapter on a freshly installed iobroker on Raspberry Pi 4B with OS Lite. The adapter works well, installation worked and the I could read the Token from the Xiaomi cloud login. After starting the adapter, It takes some time for the light to switch to green, but then It works and I can read every state. I even can start a command. But if I do so (eg. cleaning room), the command reaches the Roborock and it will start, but then the adapter stops for a while, reboots and the log says this:

Can you help me fixing this? Thanks, Daniel

mihome-vacuum.0 | 2021-02-08 09:50:42.974 | info | (13279) Connected
-- | -- | -- | --
mihome-vacuum.0 | 2021-02-08 09:50:42.929 | info | (13279) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2021-02-08 09:50:42.917 | info | (13279) New generation or new fw(3.5.8,2652) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2021-02-08 09:50:42.915 | info | (13279) extend state mop for State control.fan_power
mihome-vacuum.0 | 2021-02-08 09:50:42.914 | info | (13279) change states from State control.fan_power
mihome-vacuum.0 | 2021-02-08 09:50:42.839 | info | (13279) Create state clean_home for controlling by cloud adapter
mihome-vacuum.0 | 2021-02-08 09:50:42.837 | info | (13279) Expert mode disabled, states deleted
mihome-vacuum.0 | 2021-02-08 09:50:42.739 | info | (13279) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.20.1, js-controller: 3.1.6
host.iobroker | 2021-02-08 09:50:41.113 | info | instance system.adapter.mihome-vacuum.0 started with pid 13279
host.iobroker | 2021-02-08 09:50:11.063 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled
host.iobroker | 2021-02-08 09:50:11.051 | info | instance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)
mihome-vacuum.0 | 2021-02-08 09:50:10.521 | info | (28819) Terminated (NO_ERROR): Without reason
mihome-vacuum.0 | 2021-02-08 09:50:10.519 | info | (28819) terminating
mihome-vacuum.0 | 2021-02-08 09:50:10.505 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
mihome-vacuum.0 | 2021-02-08 09:50:10.505 | error | at runMicrotasks (<anonymous>)
mihome-vacuum.0 | 2021-02-08 09:50:10.505 | error | at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
mihome-vacuum.0 | 2021-02-08 09:50:10.505 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
mihome-vacuum.0 | 2021-02-08 09:50:10.505 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33
mihome-vacuum.0 | 2021-02-08 09:50:10.505 | error | at /opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:187:68
mihome-vacuum.0 | 2021-02-08 09:50:10.505 | error | (28819) TypeError: Cannot read property 'val' of null
mihome-vacuum.0 | 2021-02-08 09:50:10.502 | error | (28819) uncaught exception: Cannot read property 'val' of null
mihome-vacuum.0 | 2021-02-08 09:50:10.482 | info | (28819) trigger cleaning segment 17

**Comment by dirkhe** [comment]
Do you have roomFanPower Set for the rooms?

**Comment by Daniel-K84** [comment]
@dirkhe Should it be that easy? You are right, I hadn't. Now, once I have set the roomFanPower, the problem seems to be solved. More tests tomorrow, for now the kids are sleeping and the robot is way too loud. Thank you very much!

**Comment by Daniel-K84** [comment]
Everything worked with this issue. The roomFanPower shouldn't be Null. Thank you!
