### ISSUE TITLE
Roidmi Eve Plus Vacuum Cleaner

### ISSUE THREAD

**Issue by actionbyte** [iobroker-community-adapters/ioBroker.mihome-vacuum#217]
Suche einen Roidmi Eve Adapter für den Saugroboter mit dem Staupbeutel in der Ladestation.
Dieser sollte die eingerichteten Räume auslesen und über entsprechende DPs die gesamte Wohung oder gezielt diese Räume oder Bereiche saugen können.

**Comment by MeisterTR** [comment]
bitte hier einen issue anlegen https://github.com/ioBroker/AdapterRequests
