### ISSUE TITLE
Timer mit Adapter 2.2.1 und Roborock S6 funktioniert nicht

### ISSUE THREAD

**Issue by TTBerlin** [iobroker-community-adapters/ioBroker.mihome-vacuum#219]
Ich habe die Map in mehrere Räume aufgeteilt. Die Reinigung der einzelnen Räume funktioniert über die Buttons im Adapter. Aber leider passiert nichts, wenn ich einen Timer einstelle. Egal, ob nur in einem oder in mehreren Räumen gereinigt werden soll. Wenn der programmierte Zeitpunkt erreicht ist, passiert nichts. Auch im Log (instanz auf debug) ist zum Zeitpunkt nichts zu erkennen. Die Datenpunkte werden aber m.E. korrekt gesetzt.
<img width="1205" alt="Bildschirmfoto 2021-03-05 um 12 55 04" src="https://user-images.githubusercontent.com/64016944/110112491-1bdc3880-7db2-11eb-8ce2-44e3f7af05fd.png">

**Comment by dirkhe** [comment]
Was sagt denn das Log im debug mode? Schau bitte auch mal, ob du für die Räume die saugstufe gesetzt hast

**Comment by TTBerlin** [comment]
Hallo, zunächst mal vielen Dank für Deine Antwort! Ich hatte vorher keine Saugstufen (suction Power) in den einzelnen Räumen gesetzt. Habe ich dann eingetragen. Das hat aber auch keinen Erfolg gebracht. Anbei mal der Debug-Log nach dem Neustart des Adapters. Leider kann ich nicht erkennen, an welcher Stelle der Fehler liegt.
[Robot2.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/6095220/Robot2.txt)

**Comment by dirkhe** [comment]
Ich sehe in dem Log nicht, was zu dem Zeitpunkt passiert. Ganz oben steht Next Timer 21.35 Uhr, aber das Log geht nur bis 21:21

**Comment by TTBerlin** [comment]
Sorry...war ein Missverständnis. Hier mal der komplette log von heute vom Adapter-Start bis zum Ereigniszeitpunkt (SSID und Token verfälscht). Timer eingestellt auf 13:35. M.E. passiert um 13:35 nichts Besonderes im log. Server ist Germany
<img width="1323" alt="Bildschirmfoto 2021-03-08 um 13 50 09" src="https://user-images.githubusercontent.com/64016944/110323708-4548ce80-8015-11eb-905c-89b69b6ae4bf.png">
[robot_13_35.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/6101442/robot_13_35.txt)

**Comment by dirkhe** [comment]
Hmmm, das ist wirklich komisch, normalerweise sollte er zumindest was im log ausgeben, auch wenn er zb. keine Räume findet.
Aber deine Räume sind auch mit den iobroker Rämen verknüpft?
![image](https://user-images.githubusercontent.com/9537962/110392241-e9a83080-8068-11eb-9f24-166056c3184b.png)

**Comment by TTBerlin** [comment]
Ja...die Räume habe ich in iobroker verknüpft. Unter Aufzählungen, Räume tauchen die entsprechenden Felder auch auf, also clean assigned room und ggf. der entsprechende Timer. Merkwürdig ist das ">"-Zeichen im Datenpunkt des Timers (ganz unten):
<img width="1234" alt="Bildschirmfoto 2021-03-09 um 11 34 02" src="https://user-images.githubusercontent.com/64016944/110487058-7f859f00-80ed-11eb-8ab2-472bd1a898e1.png">
<img width="1288" alt="Bildschirmfoto 2021-03-09 um 11 34 35" src="https://user-images.githubusercontent.com/64016944/110487079-84e2e980-80ed-11eb-90ac-927144cfcc38.png">

**Comment by TTBerlin** [comment]
Stop! ich muss den Fehler woanders suchen. Habe festgestellt, dass mit der MiHome App in den Plänen die Reinigung von einzelnen Räumen auch nicht funktioniert. Werde das Issue dann schließen! Vielen Dank nochmal für Deine Mühe!
