### ISSUE TITLE
xia robot vacuum-Mop v8 adapter bleibt gelb 

### ISSUE THREAD

**Issue by mikewolf** [iobroker-community-adapters/ioBroker.mihome-vacuum#222]
.0 | 2021-03-08 22:16:36.579 | debug | (22356) sendMsg[1] >>> {"id":6,"method":"get_status"}
-- | -- | -- | --
mihome-vacuum.0 | 2021-03-08 22:16:36.573 | debug | (22356) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-03-08 22:16:36.573 | info | (22356) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2021-03-08 22:16:36.572 | debug | (22356) Receive <<< Helo <<< 2131002000000000166586e760469434ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-03-08 22:16:31.637 | debug | (22356) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-03-08 22:16:31.636 | debug | (22356) no answer for id:5 received, giving up
mihome-vacuum.0 | 2021-03-08 22:16:26.636 | debug | (22356) sendMsg[3] >>> {"id":5,"method":"get_status"}
mihome-vacuum.0 | 2021-03-08 22:16:21.635 | debug | (22356) sendMsg[2] >>> {"id":5,"method":"get_status"}
mihome-vacuum.0 | 2021-03-08 22:16:16.631 | debug | (22356) sendMsg[1] >>> {"id":5,"method":"get_status"}
mihome-vacuum.0 | 2021-03-08 22:16:16.626 | debug | (22356) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-03-08 22:16:16.626 | info | (22356) connecting, this can take up to 10 minutes ...

**Comment by mikewolf** [comment]
Token und Ip stimmt 100%`

021-03-08 22:28:32.863 | debug | (9815) Login step3: [{"key":"userId","value":"642xxx7560","domain":"sts.api.io.mi.com","path":"/","hostOnly":false,"creation":"2021-03-08T21:28:32.841Z","lastAccessed":"2021-03-08T21:28:32.862Z"},{"k
-- | -- | --
mihome-vacuum.0 | 2021-03-08 22:28:32.576 | debug | (9815) Login step2: &&&START&&&{"qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","ssecurity":"A9xzSj/mEs2CSTOxtPgyjg==","code":0,"passToken":"V1:4zvf9SzYkTxMnzOId/xL8VS9zGq46N0nO1E6LeKlfRGgL5THrG/dwPGrnb1i8//
mihome-vacuum.0 | 2021-03-08 22:28:31.670 | debug | (9815) Login step1: &&&START&&&{"serviceParam":"{\"checkSafePhone\":false,\"checkSafeAddress\":false,\"lsrp_score\":0.0}","qs":"%3Fsid%3Dxiaomiio%26_jso

`

**Comment by mikewolf** [comment]
xiaomi server USA,

**Comment by spheara** [comment]
Du hast den falschen Adapter installiert!
Nimm den hier
https://github.com/MeisterTR/ioBroker.mihome-vacuum
dann geht es auch!
Hatte das selbe Problem, bis ich gemerkt habe dass die neueste Version bereits 3.x.x ist!
Nun läuft es Tip Top.

**Comment by mikewolf** [comment]
danke Bist mein Held you made my Day !!
