### ISSUE TITLE
Possible to detect an open lid / removed dust container on the 1st gen Model?

### ISSUE THREAD

**Issue by Night2k5** [iobroker-community-adapters/ioBroker.mihome-vacuum#229]
Hey there.
I am running a Roborock Vacuum v1 which works great with your adapter.
Every 10 runs through my home i use 
`mihome-vacuum.0.control.goTo`
to move him in front of the bin so i am reminded of emptying the dust container.
Is there a way to detect me opening / closing the lid or refitting the dust container in order to automatically sending him back to the charger?

So far the codes from
`mihome-vacuum.0.info.state`
i found are

- 16 Going to spot
- 3 Waiting
- 6 Back to home
- 8 Charging
- 17 Zone Cleaning
- 11 Spot Cleaning

Would i be possible for you to display some more states like i mentioned above?

Thanks in advance.

**Comment by Diginix** [comment]
Afaik no Xiaomi/Roborock cleaner has a sensor for dust bin level and no sensor for the lid as well.
But you can place a xiaomi door sensor inside the dust bin and in the little hole under the lid there is enough place for the magnet. I have an own object that counts the cleaned area after each empting of dust bin. If the value reaches 240 m² iobroker sends the robot to goto coordinates and if the xiaomi motion sensor detects motion in this room, Alexa says that the dust bin should be emptied. After re-inserting the empty dust bin the door sensor is triggered and iobroker can send the robot back to docking station.

**Comment by Night2k5** [comment]
Great Idea.
Thank you very much. That's probably what i am going to do then.

**Comment by MeisterTR** [comment]
that is something for the forum not for an issue
