### ISSUE TITLE
Roborock S7 - Support

### ISSUE THREAD

**Issue by Peter1980FFM** [iobroker-community-adapters/ioBroker.mihome-vacuum#232]
Hello,
we got the Roborock S7,
make a Second Instance in IO Broker fill in Token IP and change Port...

But the Adapter would be yello.

From Xiaomi Cloud get Device it show me the S7.. but no conect 
Posibale

mihome-vacuum.0 | 2021-04-02 09:32:35.396 | warn | (31197) Time difference between Mihome Vacuum and ioBroker: -1617327302 sec
-- | -- | -- | --
mihome-vacuum.0 | 2021-04-02 09:32:15.904 | info | (31197) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2021-04-02 09:32:15.792 | info | (31197) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2021-04-02 09:32:15.791 | warn | (31197) Time difference between Mihome Vacuum and ioBroker: -1617327302 sec
mihome-vacuum.0 | 2021-04-02 09:32:15.468 | info | (31197) New generation or new fw(3.5.8,002034) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2021-04-02 09:32:15.466 | info | (31197) extend state mop for State control.fan_power
mihome-vacuum.0 | 2021-04-02 09:32:15.466 | info | (31197) change states from State control.fan_power
mihome-vacuum.0 | 2021-04-02 09:32:15.383 | info | (31197) Cloud control disabled
mihome-vacuum.0 | 2021-04-02 09:32:15.381 | info | (31197) Expert mode disabled, states deleted
mihome-vacuum.0 | 2021-04-02 09:32:15.280 | info | (31197) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.21.0, js-controller: 3.2.16
mihome-vacuum.0 | 2021-04-02 09:32:09.481 | info | (26298) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2021-04-02 09:32:09.480 | info | (26298) terminating
mihome-vacuum.0 | 2021-04-02 09:32:09.477 | info | (26298) Got terminate signal TERMINATE_YOURSELF

**Comment by MeisterTR** [comment]
der Roboter ist keine 2 Wochen alt :) da bring dir eine Version die ein halbes Jahr alt ist nicht viel, bitt emal von git installeiren dann gehts.

**Comment by icemanmw** [comment]
Hi Peter1980FFM,
is it working for you now ? I still have the "yellow" button with the Roborock S7 and the newest version (2.2.5)

**Comment by icemanmw** [comment]
> Hello,
> we got the Roborock S7,
> make a Second Instance in IO Broker fill in Token IP and change Port...
> 
> But the Adapter would be yello.
> 
> From Xiaomi Cloud get Device it show me the S7.. but no conect
> Posibale
> 
> mihome-vacuum.0	2021-04-02 09:32:35.396	warn	(31197) Time difference between Mihome Vacuum and ioBroker: -1617327302 sec
> mihome-vacuum.0	2021-04-02 09:32:15.904	info	(31197) set nächster Timer: Nicht verfügbar
> mihome-vacuum.0	2021-04-02 09:32:15.792	info	(31197) connecting, this can take up to 10 minutes ...
> mihome-vacuum.0	2021-04-02 09:32:15.791	warn	(31197) Time difference between Mihome Vacuum and ioBroker: -1617327302 sec
> mihome-vacuum.0	2021-04-02 09:32:15.468	info	(31197) New generation or new fw(3.5.8,002034) detected, create new states goto and zoneclean
> mihome-vacuum.0	2021-04-02 09:32:15.466	info	(31197) extend state mop for State control.fan_power
> mihome-vacuum.0	2021-04-02 09:32:15.466	info	(31197) change states from State control.fan_power
> mihome-vacuum.0	2021-04-02 09:32:15.383	info	(31197) Cloud control disabled
> mihome-vacuum.0	2021-04-02 09:32:15.381	info	(31197) Expert mode disabled, states deleted
> mihome-vacuum.0	2021-04-02 09:32:15.280	info	(31197) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.21.0, js-controller: 3.2.16
> mihome-vacuum.0	2021-04-02 09:32:09.481	info	(26298) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
> mihome-vacuum.0	2021-04-02 09:32:09.480	info	(26298) terminating
> mihome-vacuum.0	2021-04-02 09:32:09.477	info	(26298) Got terminate signal TERMINATE_YOURSELF


Hi Peter1980FFM,
is it working for you now ? I still have the "yellow" button with the Roborock S7 and the newest version (2.2.5)

**Comment by Peter1980FFM** [comment]
Yes IT Working with the Version from Git, but it have one Hours to Connect the old S5 nur now both working

**Comment by icemanmw** [comment]
I fixed my problem after some tryouts.

initial situation:
- S5max in my IOT sub-net worked fine (iobroker is not in the IOT network)
- update to the new git level 2.2.5
- new S7 did not change status from yellow to red 
- **now i changed roborock S7 wifi into the same sub-net as the iobroker** 
- now it works fine ..........

so far , i can not understand why ; because S5max runs very well in the different subnet layer and the S7 not
