### ISSUE TITLE
Dream Support (miot)

### ISSUE THREAD

**Issue by MeisterTR** [iobroker-community-adapters/ioBroker.mihome-vacuum#235]
die Dream Modelle kommunizieren anders als die anderen nicht über miio sondern über miot das ist das neue Standartprotokoll von Xiaomi mit DID (DeviceID kein Problem kommt mit über die cloud) SID (ServiceID) und PID (ParameterID) wie meine Nachforschungen ergeben haben geht diese Kommunikation auch verschlüsselt über udp wie beim miio (Schonmal gut somit kann man das alte nutzen) Ich bin gerade wieder mal an dem Adapter rewrite und baue es so, dass es Modular aufgebaut ist und schnell und einfach neue Geräte hinzugefügt werden können.

Jetzt Kommt aber das ABER Das Testen der Nachrichten ist sehr zeitaufwendig. Hilfe bietet jeder an (das aber auch nur, wenn es um bugreport und testen geht) für miot gibt es eine webapi wo alle komandos beschrieben sind (Reschere über git adresse ist mi.spect....) Der Adapter bieten in allen Versionen die Möglichkeit eigene Komandos zu schicken. also eigentlich nichts weltbewegendes, was auch jeder Beginner kann.

Ablauf:
1: Komandos SID und PID aus der mi.spect suchen (da gibs für jedes device einen apiurl)
2: config aus admin herunterladen und mit dem Texteditor öffen (unter devices müsste in einer json die DID stehen)
3: am besten in einen Texteditor die Messages zusammenbauen und abschicken und sehen was zurückkommt.
4: das ganze dokumentieren und mir zukommen lassen. dann ist der Roboter im nu eingebunden

da fällt mir gerade ein dass es so mit dem Adapter noch nciht geht weil die Nachricht auf miio Standard geprüft wird. Wenn Interesse besteht mach ich eine Version fertig in der man raw daten senden kann.

Ablauf:
1: Komandos SID und PID aus der mi.spect suchen (da gibs für jedes device einen apiurl)
2: config aus admin herunterladen und mit dem Texteditor öffen (unter devices müsste in einer json die DID stehen)
3: am besten in einen Texteditor die Messages zusammenbauen und abschicken und sehen was zurückkommt.
4: das ganze dokumentieren und mir zukommen lassen. dann ist der Roboter im nu eingebunden

da fällt mir gerade ein dass es so mit dem adapter noch nciht geht weil die Nachricht auf miio standard geprüft wird. Wenn Interesse besteht mach ich eine Version fertig in der man raw daten senden kann.

**Comment by canim60** [comment]
Vielen Dank für die Info :), ich kann versuchen bei der Umsetzung zu helfen, habe ein Dream D9.
Habe aber den Ablauf nicht verstanden, welche datei sollen wir bei Admin herunterladen und Öffnen?

Für deine Arbeit springt definitiv ne Spende raus :)

**Comment by derherrgraf** [comment]
Geht mir auch so. Ich habe die URL für den 1C raus gesucht und nun erschließen sich mir die nächsten Schritte leider nicht mehr.

**Comment by MeisterTR** [comment]
https://github.com/openhab/openhab-addons/pull/9859/files

**Comment by MeisterTR** [comment]
Um zu sehen welche Modelle am verbreitetsten sind bitte hier Abstimmen
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum#supported-devices-and-fetures
