### ISSUE TITLE
Viomi V8 viomi.vacuum.v8 keine Map

### ISSUE THREAD

**Issue by mikewolf** [iobroker-community-adapters/ioBroker.mihome-vacuum#238]
Hallo frage :
besagter Roboter wird ja unter mi Xiaomi verkauft , wäre es möglich die Map, in den adapter zu bekommen in Mi Home 
funktioniert dies  ??

**Comment by MeisterTR** [comment]
nein ist nicht möglich da diese von viomi komplett über die cloud läuft der  Mappointer (pfad zur Karte) kann lokal nicht abgerufen werden
