### ISSUE TITLE
Keine Karte xiaomi mija 1s in Beta 2.2.5

### ISSUE THREAD

**Issue by ChrisWoehrle** [iobroker-community-adapters/ioBroker.mihome-vacuum#240]
Habe heute von der aktuellen stable auf die Beta gewechselt. Seither habe ich keine aktuelle Karte mehr sondern immer die alte Karte.
In der Log bekomme ich außerdem folgende Warnung: 5853 Login failed

**Comment by MeisterTR** [comment]
Schonmal neu eingeloggt? Da das passwort jetzt anders verschlüsselt wird, kann es sein, dass du dich neu einloggen musst

**Comment by Diginix** [comment]
Mein 1S inkl. Karte funktioniert nach dem ich die Xiaomi Logindaten neue in der Instanz gespeichert habe.

**Comment by ChrisWoehrle** [comment]
All right, versuche ich mal und Gib dann Feedback--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.04.21, 21:43 schrieb Diginix ***@***.***>:

   
  Mein 1S inkl. Karte funktioniert nach dem ich die Xiaomi Logindaten neue in der Instanz gespeichert habe.
