### ISSUE TITLE
Probleme mit neuem S7

### ISSUE THREAD

**Issue by bbr111** [iobroker-community-adapters/ioBroker.mihome-vacuum#241]
Hier ein Debug-Logauszug.

mihome-vacuum.0 | 2021-04-05 21:10:02.245 | info | (16767) connecting, this can take up to 10 minutes ...
-- | -- | -- | --
mihome-vacuum.0 | 2021-04-05 21:10:02.244 | warn | (16767) Time difference between Mihome Vacuum and ioBroker: -1617639940 sec
mihome-vacuum.0 | 2021-04-05 21:10:02.243 | debug | (16767) Receive <<< Helo <<< 21310020000000001750c65500002686ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-04-05 21:09:57.311 | debug | (16767) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-04-05 21:09:57.310 | debug | (16767) no answer for id:1 received, giving up
mihome-vacuum.0 | 2021-04-05 21:09:54.081 | debug | (16767) The answer from the robot is not correct! (SyntaxError: Unexpected end of JSON input) "{\"id\":1,\"result\":[{\"msg_ver\":2,\"msg_seq\":593,\"state\":8,\"battery\":100,\"clean_time\":55,\"clea
mihome-vacuum.0 | 2021-04-05 21:09:54.080 | debug | (16767) Receive <<< {"id":1,"result":[{"msg_ver":2,"msg_seq":593,"state":8,"battery":100,"clean_time":55,"clean_area":1185000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_
mihome-vacuum.0 | 2021-04-05 21:09:52.310 | debug | (16767) sendMsg[3] >>> {"id":1,"method":"get_status"}

Muss ich noch was umstellen? Bin neu in dem Thema.

**Comment by MeisterTR** [comment]
bitte version von git installieren, da ist der s7 Schon voll integriert
