### ISSUE TITLE
Mehrere Räume reinigen funktioniert nicht mehr / Restart Adapter

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.mihome-vacuum#242]
Mit dem Update auf die 2.2.5 macht der Adapter immer einen Restart wenn ich mehrere Räume gleichzeitig reinigen lassen will.

Mit einem Script setze ich die DP roomClean der einzelnen Zimmer auf true (Script stark verkürtzt)
`

ar id_Sauger_Schlafzimmer = 'mihome-vacuum.0.rooms.43001012121.roomClean'/*clean Room*/;
--
  | setState(id_Sauger_Schlafzimmer,true);
  | setStateDelayed(id_Sauger_Badezimmer,true,1000);
  | setStateDelayed(id_Sauger_kleiner_Flur,true,2000);
  | setStateDelayed(id_Sauger_Flur,true,3000);

`
Danach startet der Roboter aber er reinigt nur einen Raum. Ich vermute sobald ich den zweiten DP zu Queue hinzufüge stürtzt der Adapter ab:

`

host.iobroker_V41	2021-04-06 17:11:03.634	info	instance system.adapter.mihome-vacuum.0 started with pid 1516
--
  | host.iobroker_V41	2021-04-06 17:10:33.605	info	Restart adapter system.adapter.mihome-vacuum.0 because enabled
  | host.iobroker_V41	2021-04-06 17:10:33.604	error	instance system.adapter.mihome-vacuum.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
  | mihome-vacuum.0	2021-04-06 17:10:32.905	error	(15258) Cannot read property 'val' of null
  | mihome-vacuum.0	2021-04-06 17:10:32.905	error	at processImmediate (timers.js:658:5)
  | mihome-vacuum.0	2021-04-06 17:10:32.905	error	at tryOnImmediate (timers.js:676:5)
  | mihome-vacuum.0	2021-04-06 17:10:32.905	error	at runCallback (timers.js:706:11)
  | mihome-vacuum.0	2021-04-06 17:10:32.905	error	at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:194:63)
  | mihome-vacuum.0	2021-04-06 17:10:32.905	error	(15258) TypeError: Cannot read property 'val' of null
  | mihome-vacuum.0	2021-04-06 17:10:32.902	error	(15258) uncaught exception: Cannot read property 'val' of null
  | javascript.2	2021-04-06 17:10:32.888	info	(804) script.js.Flur.Sauger: Reinigung wurde durch den Schalter im Flur gestartet. Keine erneute Sprachaussage
  | javascript.2	2021-04-06 17:10:32.887	info	(804) script.js.Flur.Sauger: Reinigungsprogramm 1: Wohnzimmer und Küche

`

Ein Downgrade auf eine alte Version bricht mit Fehlermeldung leider ab:

`

  | ibroker npm ERR! notarget No matching version found for iobroker.mihome-vacuum@2.2.3.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version
-- | --
  | host.iobroker_V41	2021-04-06 18:11:22.727	info	iobroker npm ERR! code ETARGET
  | host.iobroker_V41	2021-04-06 18:11:18.260	info	iobroker NPM version: 6.13.4npm install iobroker.mihome-vacuum@2.2.3 --loglevel error --prefix "/opt/iobroker" (System call)
  | host.iobroker_V41	2021-04-06 18:11:17.768	info	iobroker Update mihome-vacuum from @2.2.5 to @2.2.3

`

**Comment by dirkhe** [comment]
Schau bitte mal, ob du bei den Räumen eine saugstärke gesetzt gast

**Comment by Baenker** [comment]
@dirkhe selbstverständlich sind die saugstärken gesetzt

**Comment by Baenker** [comment]
Habe den Adapter jetzt mal auf debug gestellt. Dann in der ioBroker admi den Button für die Reinigung Raum 20 gedrückt. Als der Roboter los fuhr, dann noch den Button für Raum 22 und der Adapter beendet sich erneut. Das Log gibt leider keine weiteren Infos. Man sieht das er mit Raum 20 anfängt und das wars:

`mihome-vacuum.0	2021-04-07 08:54:11.876	info	(10607) Connected
mihome-vacuum.0	2021-04-07 08:54:11.873	debug	(10607) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0	2021-04-07 08:54:11.871	debug	(10607) Receive <<< {"result":[{"msg_ver":2,"msg_seq":1109,"state":18,"battery":100,"clean_time":30,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":3,"in_returning":0,"in_fresh_state":0,"
mihome-vacuum.0	2021-04-07 08:54:11.864	debug	(10607) sendMsg[1] >>> {"id":1,"method":"get_status"}
mihome-vacuum.0	2021-04-07 08:54:11.858	debug	(10607) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0	2021-04-07 08:54:11.857	info	(10607) connecting, this can take up to 10 minutes ...
mihome-vacuum.0	2021-04-07 08:54:11.856	debug	(10607) Receive <<< Helo <<< 2131002000000000132a8cef606d5713ffffffffffffffffffffffffffffffff
mihome-vacuum.0	2021-04-07 08:54:11.781	debug	(10607) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
mihome-vacuum.0	2021-04-07 08:54:11.766	info	(10607) New generation or new fw(3.5.8,5690) detected, create new states goto and zoneclean
mihome-vacuum.0	2021-04-07 08:54:11.746	debug	(10607) server started on 0.0.0.0:53421
mihome-vacuum.0	2021-04-07 08:54:11.733	info	(10607) Cloud control disabled
mihome-vacuum.0	2021-04-07 08:54:11.731	info	(10607) Expert mode disabled, states deleted
mihome-vacuum.0	2021-04-07 08:54:11.703	info	(10607) starting. Version 2.2.5 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v10.18.1, js-controller: 3.2.16
mihome-vacuum.0	2021-04-07 08:54:11.029	debug	(10607) statesDB connected
mihome-vacuum.0	2021-04-07 08:54:11.028	debug	(10607) States connected to redis: 127.0.0.1:9000
mihome-vacuum.0	2021-04-07 08:54:10.970	debug	(10607) States create User PubSub Client
mihome-vacuum.0	2021-04-07 08:54:10.969	debug	(10607) States create System PubSub Client
mihome-vacuum.0	2021-04-07 08:54:10.944	debug	(10607) Redis States: Use Redis connection: 127.0.0.1:9000
mihome-vacuum.0	2021-04-07 08:54:10.941	debug	(10607) objectDB connected
mihome-vacuum.0	2021-04-07 08:54:10.932	debug	(10607) Objects connected to redis: 127.0.0.1:9001
mihome-vacuum.0	2021-04-07 08:54:10.874	debug	(10607) Objects client initialize lua scripts
mihome-vacuum.0	2021-04-07 08:54:10.872	debug	(10607) Objects create User PubSub Client
mihome-vacuum.0	2021-04-07 08:54:10.871	debug	(10607) Objects create System PubSub Client
mihome-vacuum.0	2021-04-07 08:54:10.826	debug	(10607) Objects client ready ... initialize now
mihome-vacuum.0	2021-04-07 08:54:10.700	debug	(10607) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.iobroker_V41	2021-04-07 08:54:09.520	info	instance system.adapter.mihome-vacuum.0 started with pid 10607
host.iobroker_V41	2021-04-07 08:53:39.486	info	Restart adapter system.adapter.mihome-vacuum.0 because enabled
host.iobroker_V41	2021-04-07 08:53:39.485	error	instance system.adapter.mihome-vacuum.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
mihome-vacuum.0	2021-04-07 08:53:38.835	warn	(10245) Terminated (UNCAUGHT_EXCEPTION): Without reason
mihome-vacuum.0	2021-04-07 08:53:38.834	info	(10245) terminating
mihome-vacuum.0	2021-04-07 08:53:38.824	error	(10245) Cannot read property 'val' of null
mihome-vacuum.0	2021-04-07 08:53:38.823	error	at processImmediate (timers.js:658:5)
mihome-vacuum.0	2021-04-07 08:53:38.823	error	at tryOnImmediate (timers.js:676:5)
mihome-vacuum.0	2021-04-07 08:53:38.823	error	at runCallback (timers.js:706:11)
mihome-vacuum.0	2021-04-07 08:53:38.823	error	at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:194:63)
mihome-vacuum.0	2021-04-07 08:53:38.823	error	(10245) TypeError: Cannot read property 'val' of null
mihome-vacuum.0	2021-04-07 08:53:38.822	error	(10245) uncaught exception: Cannot read property 'val' of null
mihome-vacuum.0	2021-04-07 08:53:38.819	debug	(10245) sendMsg[1] >>> {"id":59,"method":"app_segment_clean","params":[20]}
mihome-vacuum.0	2021-04-07 08:53:38.818	info	(10245) trigger cleaning segment 20
mihome-vacuum.0	2021-04-07 08:53:38.815	debug	(10245) sendTo "cleanSegments" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0	2021-04-07 08:53:38.812	debug	(10245) stateChange mihome-vacuum.0.rooms.43001012134.roomClean {"val":true,"ack":false,"ts":1617778418808,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1617727021757}
mihome-vacuum.0	2021-04-07 08:53:30.595	debug	(10245) Receive <<< {"result":[{"msg_ver":2,"msg_seq":1106,"state":8,"battery":100,"clean_time":179,"clean_area":2400000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_stat
mihome-vacuum.0	2021-04-07 08:53:30.591	debug	(10245) Receive <<< {"partner_id":"","id":58,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_5690","ap":{"ssid":"088WLAN24ghz","bssid":"44:4e:6d:50:1b:19","rssi":-56},"netif":{"loc
mihome-vacuum.0	2021-04-07 08:53:30.557	debug	(10245) Next WiFi check: 07.04 08:54`

**Comment by MeisterTR** [comment]
lösche mal einfach den folder rooms unter objekte und starte den adapter nochmal. dann sollte es gehen.

**Comment by Baenker** [comment]
@MeisterTR das habe ich gemacht bzw ich habe den kompletten Objektbaum gestern Abend gelöscht weil ich auch gedacht hatte danach wird alles gut.. Nach Start des Adapters wurden alle Objekte angelegt. Es gab auch Fehlermeldungen im log. Wahrscheinlich weil die Saugstufe nicht gefüllt war. Nachdem ich das händisch gemacht habe wurde nach einen erneuten Adapter start auch der Adapter grün. Es sind auch soweit ich sehe alle anderen Datenpunkte unter den anderen Punkten automatisch gefüllt. Ich nutze übrigens einen s6max aber halt auch schon ewig. Ich habe keine Idee.

**Comment by Baenker** [comment]
was ich noch nicht erwähnt habe: Ich nutze keine Karten oder solche Funktionen sondern wirklich nur die Buttons für die Räume zu reinigen. In der Adapter Konfig habe ich dort also nichts eingetragen oder gemacht

**Comment by MeisterTR** [comment]
wie gesagt, losch mal **NUR** die räume, dann sollte es gehen

**Comment by Baenker** [comment]
@MeisterTR tja was soll ich sagen? Das ist die Lösung. Verstehen tue ich es aber nicht. Nach dem löschen und Adapter Neustart wurden die Objekte unter Räume neu angelegt und sogar befüllt. Außerdem gibt es jetzt einen neuen Datenpunkt: roomWaterBoxMode
