### ISSUE TITLE
Timer, Map Probleme mit V2.2.5

### ISSUE THREAD

**Issue by Scotty-89** [iobroker-community-adapters/ioBroker.mihome-vacuum#243]
Hallo zusammen,

ich habe zwei S5 im Haus und im Iobroker drin.
Leider habe ich jetzt seit längeren das die Map nicht mehr aktualisiert wurde und bin deshalb auf die "neue" Version 2.2.5 gegangen.
leider geht seitdem weder die Map noch die Timer.
Map wurde einmal vor ein paar tage aktualisiert und seitdem nicht mehr.

**Comment by MeisterTR** [comment]
Log???

**Comment by Scotty-89** [comment]
was genau soll ich erstellen für ein log bzw was wird benötigt? 
im Iobroker wird selbst nicht wirklich was interessantes angezeigt zu dem Adapter.
![image](https://user-images.githubusercontent.com/54929714/114205541-adfbd180-995a-11eb-94d4-b111cc68e523.png)

**Comment by MeisterTR** [comment]
was sagt das log(debug) wenn ein Timer erstellt wird, was sagt das log, wenn der Timer auslösen sollte. (du hast die cloud auch deaktiviert, so kann die map nicht generiert werden)

**Comment by Scotty-89** [comment]
habe mir jetzt die iobroker logs angeschaut und es wird nicht eingetragen wenn der Timer auslösen sollte.

das habe ich auch schon gelesen mit "Could deaktivert" ich habe aber da nichts deaktivert... sowohl map als auch Timer sind aktiv.
![image](https://user-images.githubusercontent.com/54929714/114218659-fb336f80-9969-11eb-8993-0ccd527f8cc8.png)

![image](https://user-images.githubusercontent.com/54929714/114218682-06869b00-996a-11eb-8612-ba4a659d6655.png)

**Comment by MeisterTR** [comment]
fixed in der 3.0.3

**Comment by Scotty-89** [comment]
gibt es die Version den irgendwo zum testen?

**Comment by MeisterTR** [comment]
https://forum.iobroker.net/topic/44077/test-adapter-mihome-vacuum-v3-0-4-next-generarition?_=1618406041342

Hab aber gerade gesehen dass noch ein kleiner Bug drin ist, den fix ich gleich
