### ISSUE TITLE
Can't get devices

### ISSUE THREAD

**Issue by radebold** [iobroker-community-adapters/ioBroker.mihome-vacuum#248]
I tryed often in the last days. Put in my credentials (User, PW) and select Germany as server and click "getdevices" but it don't received anything.

What can I do?
I have to open ports on my firewall or something else ?

**Comment by BlackHawk3000** [comment]
Welche Version nutzt du?
Welchen Staubsauger?
Was steht in den Logs und im Debug?

Mit deinen Angaben kann man dir schwer helfen.

**Comment by radebold** [comment]
> Welche Version nutzt du?
Version 2.2.5

> Welchen Staubsauger?
S6maxv

> Was steht in den Logs und im Debug?
nicht wirklich viel:

`
mihome-vacuum.0 | 2021-04-16 16:26:02.397 | debug | (7589) Xiaomi Cloud: Logging in
-- | -- | -- | --
mihome-vacuum.0 | 2021-04-16 16:25:20.590 | error | (7589) Token not specified!
mihome-vacuum.0 | 2021-04-16 16:25:20.539 | info | (7589) starting. Version 2.2.5 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.22.1, js-controller: 3.2.16

`
mehr passiert leider nicht

> Mit deinen Angaben kann man dir schwer helfen.

**Comment by BlackHawk3000** [comment]
Auch für dich dann, wenn du es dir zutraust:

```
Installieren bitte über https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tarball/rebuild3

Bitte Vorher den alten Adapter vollständig löschen.

Dies ist die Alpha also BITTE nur installieren wenn ihr wisst was ihr macht und einen qualifizierten Bugreport liefern könnt

Bitte in dieses Thema NUR Fehler oder Requests die den Adapter betreffen. KEINE Installationsfehler oder sonstige Fragen. macht dafür bitte wenn die Suche nichts ergeben hat ein neues Thema auf damit es hier nicht so überläuft wie in den alten Threads..
```

Ansonsten, Instanz starten, daten eingeben und beim Klick auf den Button kommt schon eine Meldung ob kein Login möglich oder Passwort falsch etc. 
Sollte er sich eingeloggt haben, kannst du dann auch deine Geräte auswählen, die in der MI Cloud registriert sind.

**Comment by radebold** [comment]
Also ich bekomme nix, wenn ich auf "get devices" klicke.
Gibt auch keine Fehlermeldung und im debug-log steht `Xiaomi Cloud: Logging in` und das wars, danach passiert nix mehr.

**Comment by MeisterTR** [comment]
Auf was für einem Unterbau läuft dein iobroker? Sitzen die rechte alle? Ggf mal installtionsfixer laufen lassen. Es gibt einzelne Systeme da werden die requests nicht geschickt oder geblockt..

**Comment by radebold** [comment]
hab ich versucht, ändert leider auch nichts.

läuft bei mir auf einem Raspberry 4 mit Ubuntu buster

**Comment by MeisterTR** [comment]
nutzt du pihole oder vergleichbares tool was den traffic untersucht und filtert?

**Comment by radebold** [comment]
@MeisterTR 
ich könnte pihole mal auf nem docker installieren, aber ich kann damit nicht wirklich umgehen.

**Comment by MeisterTR** [comment]
nein so war das nicht gemeint. "irgendetwas" in deinem Netzwerk "blocked" die Nachrticht. sie geht nicht aus deinem "Haus" raus zu dem Server

**Comment by radebold** [comment]
Ich habe eine Fritzbox 6591 Cable und der Raspberry ist direkt dran. Da ist nichts speziell geblockt.
Wenn es also nicht ein spezieller Port ist, dann sollte es durchgehen. Die normalen IOBroker Ports sind frei.

**Comment by MeisterTR** [comment]
Am Adapter kann es nicht liegen, leider kann ich da auch nicht weiterhelfen
