### ISSUE TITLE
[dreame.vacuum.2041] Support Xiaomi Mijia 1T

### ISSUE THREAD

**Issue by Seele737** [iobroker-community-adapters/ioBroker.mihome-vacuum#249]
Hallo,
kann man denn neuen Roboter (xiaomi mijia 1t) hinzufügen? Oder was muss ich machen?
Ich bekomme keine Verbindung zum Roboter.
Danke für die mühen mit dem Adapter.

![mihome](https://user-images.githubusercontent.com/82650331/115012383-0e859400-9eb0-11eb-98cd-81fc00febcee.JPG)

**Comment by BlackHawk3000** [comment]
Versuche mal den neueren Adapter (NOCH in der Alpha Phase) übers manuelle installieren. 

```
Installieren bitte über https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tarball/rebuild3

Bitte Vorher den alten Adapter vollständig löschen.

Dies ist die Alpha also BITTE nur installieren wenn ihr wisst was ihr macht und einen qualifizierten Bugreport liefern könnt

Bitte in dieses Thema NUR Fehler oder Requests die den Adapter betreffen. KEINE Installationsfehler oder sonstige Fragen. macht dafür bitte wenn die Suche nichts ergeben hat ein neues Thema auf damit es hier nicht so überläuft wie in den alten Threads..
```


Sollte es damit auch nicht gehen, könnte es sein, dass der 1T auch schon auf ein anderes Standard zur Datenübertragung setzt. 
Daran arbeitet der Entwickler aktuell noch, da würde es nur warten bedeuten.

**Comment by Seele737** [comment]
Leider wird mein Gerät nicht mit unterstützt.
Es war ein Versuch wert.
Trotzdem danke.

![mihome-v](https://user-images.githubusercontent.com/82650331/115110429-af8d5100-9f7b-11eb-81be-6839d73b6ea0.JPG)

**Comment by MeisterTR** [comment]
Um zu sehen welche Modelle am verbreitetsten sind bitte hier Abstimmen
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum#supported-devices-and-fetures
