### ISSUE TITLE
Fehler beim Starten des Adapters Version 3.1

### ISSUE THREAD

**Issue by SebastianSchultz** [iobroker-community-adapters/ioBroker.mihome-vacuum#256]
Ich habe den Adapter komplett deinstalliert und neu installiert.
Dann meinen Sauger samt Token hinzugefügt und bekomme nun folgenden Fehler beim Starten:

`

mihome-vacuum.0 | 2021-04-20 13:16:25.606 | warn | (1458) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
mihome-vacuum.0 | 2021-04-20 13:16:25.605 | info | (1458) terminating
mihome-vacuum.0 | 2021-04-20 13:16:25.597 | error | (1458) Cannot read property 'split' of undefined
mihome-vacuum.0 | 2021-04-20 13:16:25.597 | error | (1458) TypeError: Cannot read property 'split' of undefined at MihomeVacuum.getModel (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:151:34) at processTicksAndRejections (internal/p
mihome-vacuum.0 | 2021-04-20 13:16:25.597 | error | (1458) unhandled promise rejection: Cannot read property 'split' of undefined
mihome-vacuum.0 | 2021-04-20 13:16:25.596 | error | (1458) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2021-04-20 13:16:25.596 | warn | (1458) Model undefined not supported! Please open issue on git: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues
mihome-vacuum.0 | 2021-04-20 13:16:15.582 | info | (1458) check group user admin group admin: false
mihome-vacuum.0 | 2021-04-20 13:16:15.580 | info | (1458) check user admin pw iobroker: false
mihome-vacuum.0 | 2021-04-20 13:16:15.495 | info | (1458) starting. Version 3.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.22.1, js-controller: 3.2.16
host.SRV-IOBROKER | 2021-04-20 13:16:14.803 | info | instance system.adapter.mihome-vacuum.0 started with pid 1458
host.SRV-IOBROKER | 2021-04-20 13:15:44.792 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled

`

**Comment by SebastianSchultz** [comment]
Nachtrag: Mit der Vorgängerversion lief vorher alles reibungslos.

**Comment by BlackHawk3000** [comment]
Welches Modell des Saugers?
Debug Ausgabe?

MIt den Infos kann man dir dann besser helfen :)

**Comment by MeisterTR** [comment]
ich gehe davon aus, dass du das gerät nicht aus der Geräteliste ausgewählt hast und die cloudverbindung unterbrochen hast? Der Adapter braucht nun nach dem Start zwingend die Modellbezeichnung. hab es auf git gefixed, sollte mit der gitversion laufen

**Comment by SebastianSchultz** [comment]
Jupp, funktioniert.
Vielen Dank!
