### ISSUE TITLE
V3.1.1 Verbindungsabbruch nach Roboterneustart

### ISSUE THREAD

**Issue by Scotty-89** [iobroker-community-adapters/ioBroker.mihome-vacuum#259]
Hallo,

da ich meine Saugroboter zwecks Akku "Nutzung / Schonung" über Steckdosen schaltbar gemacht habe ist mir aufgefallen das der Adapter neuerdings sehr lange braucht um wieder eine Verbindung zu dem Saugern aufzubauen.
um genau zu sagen weit mehr als 3 Minuten, teilweise habe ich den Eindruck das ich erst eine Verbindung wiederherstellen kann wenn ich den Adapter Neustarte.. ist so etwas bekannt ?

Und mich würde interessieren ob die "Kommunikation" rein über WLan geht oder über die Cloud... ??? (oder wird die Cloud wirklich nur für die Map genutzt? )

auch nach über 30min verbindet sich der Adapter nicht automatisch erst nach einen Neustart...

**Comment by MeisterTR** [comment]
Der Adapter kommuniziert rein im lokalen Netz, nur die Karte und die DeviceList werden von der Cloud geholt. Neuere Modelle (Dreame oder Viomi) brauchen jedoch die Verbindung zur Cloud, sonst schalten sie die lokale Schnittstelle ab. 

Das mit der Verbindung ist mir auch schon aufgefallen, dass daten erst nach einem Restart des Adapter kommen, hatte ich aber erst 2 mal und schau ich mir genauer an.
