### ISSUE TITLE
Keine Räume 

### ISSUE THREAD

**Issue by Xamude** [iobroker-community-adapters/ioBroker.mihome-vacuum#260]
Hab erst seit gestern den Xiaomi Vacuum Mop Pro, daher auch gut möglich das ich was übersehe.
Bekomme einfach bei den Datenpunkten keine Räume angezeigt.  
ich komm nicht drauf woran es liegt...
Danke schon mal für die Hilfe
`
mihome-vacuum.0 | 2021-04-22 13:56:30.013 | debug | (24705) Recievded params for viomi: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":5}
-- | -- | -- | --
mihome-vacuum.0 | 2021-04-22 13:56:30.010 | debug | (24705) MIIO RECIVE: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":5}
mihome-vacuum.0 | 2021-04-22 13:56:29.912 | debug | (24705) Message= {"id":5,"method":"get_prop","params":["run_state","suction_grade","mode","err_state","battary_life","start_time","order_time","s_time","s_area","v_state","zone_data","repeat_state","r
mihome-vacuum.0 | 2021-04-22 13:56:29.910 | debug | (24705) get params for Viomi
mihome-vacuum.0 | 2021-04-22 13:56:29.354 | debug | (24705) Receive <<< Helo <<< 2131002000000000198768686081646cffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-04-22 13:56:09.895 | debug | (24705) Recievded params for viomi: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":4}
mihome-vacuum.0 | 2021-04-22 13:56:09.892 | debug | (24705) MIIO RECIVE: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":4}
mihome-vacuum.0 | 2021-04-22 13:56:09.702 | debug | (24705) Message= {"id":4,"method":"get_prop","params":["run_state","suction_grade","mode","err_state","battary_life","start_time","order_time","s_time","s_area","v_state","zone_data","repeat_state","r
mihome-vacuum.0 | 2021-04-22 13:56:09.700 | debug | (24705) get params for Viomi
mihome-vacuum.0 | 2021-04-22 13:55:49.687 | debug | (24705) Recievded params for viomi: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":3}
mihome-vacuum.0 | 2021-04-22 13:55:49.684 | debug | (24705) MIIO RECIVE: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":3}
mihome-vacuum.0 | 2021-04-22 13:55:49.603 | debug | (24705) Message= {"id":3,"method":"get_prop","params":["run_state","suction_grade","mode","err_state","battary_life","start_time","order_time","s_time","s_area","v_state","zone_data","repeat_state","r
mihome-vacuum.0 | 2021-04-22 13:55:49.599 | debug | (24705) get params for Viomi
mihome-vacuum.0 | 2021-04-22 13:55:29.590 | debug | (24705) Recievded params for viomi: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":2}
mihome-vacuum.0 | 2021-04-22 13:55:29.589 | debug | (24705) MIIO RECIVE: {"result":[5,1,0,2105,100,0,"0",0,0,7,"0",0,1,1,12,1,0,1,0,0,1],"id":2}
mihome-vacuum.0 | 2021-04-22 13:55:29.379 | debug | (24705) Message= {"id":2,"method":"get_prop","params":["run_state","suction_grade","mode","err_state","battary_life","start_time","order_time","s_time","s_area","v_state","zone_data","repeat_state","
mihome-vacuum.0 | 2021-04-22 13:55:29.378 | debug | (24705) get params for Viomi
mihome-vacuum.0 | 2021-04-22 13:55:29.368 | debug | (24705) select viomi protocol....
mihome-vacuum.0 | 2021-04-22 13:55:29.366 | debug | (24705) DeviceModel selected to: viomi.vacuum.v8
mihome-vacuum.0 | 2021-04-22 13:55:29.362 | debug | (24705) Get Device data from robot..
mihome-vacuum.0 | 2021-04-22 13:55:29.361 | debug | (24705) Get Device data..0
mihome-vacuum.0 | 2021-04-22 13:55:29.360 | debug | (24705) GETMODELFROMAPI:Data: {"partner_id":"","id":1,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.3_0017","ap":{"ssid":"meins","bssid":"e8:df:70:dd:d8:c0"},"netif":{"localIp":"19
mihome-vacuum.0 | 2021-04-22 13:55:29.359 | debug | (24705) MIIO RECIVE: {"partner_id":"","id":1,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.3_0017","ap":{"ssid":"meins","bssid":"e8:df:70:dd:d8:c0"},"netif":{"localIp":"192.168.170
mihome-vacuum.0 | 2021-04-22 13:55:29.260 | debug | (24705) Message= {"id":1,"method":"miIO.info"}
mihome-vacuum.0 | 2021-04-22 13:55:29.257 | debug | (24705) GETMODELFROMAPI: objModel: {"val":"viomi.vacuum.v8","ack":true,"ts":1619091602762,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1619022139092}
mihome-vacuum.0 | 2021-04-22 13:55:29.250 | debug | (24705) MAIN: Connected to device, try to get model..
mihome-vacuum.0 | 2021-04-22 13:55:29.249 | debug | (24705) Receive <<< Helo <<< 21310020000000001987686860816430ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-04-22 13:55:29.210 | debug | (24705) server started on 0.0.0.0:53421
mihome-vacuum.0 | 2021-04-22 13:55:29.192 | debug | (24705) MIIO: Config: ip:192.168.170.114 token: 7645326f354655695576443664746936
mihome-vacuum.0 | 2021-04-22 13:55:29.190 | debug | (24705) Create State for deviceInfowifi_signal
mihome-vacuum.0 | 2021-04-22 13:55:29.189 | debug | (24705) Create State for deviceInfofw_ver
mihome-vacuum.0 | 2021-04-22 13:55:29.188 | debug | (24705) Create State for deviceInfomodel
mihome-vacuum.0 | 2021-04-22 13:55:29.187 | debug | (24705) Create State for deviceInfomac
mihome-vacuum.0 | 2021-04-22 13:55:29.171 | debug | (24705) load Map creator... true
mihome-vacuum.0 | 2021-04-22 13:55:29.114 | info | (24705) check group user admin group admin: false
mihome-vacuum.0 | 2021-04-22 13:55:29.105 | info | (24705) check user admin pw iobroker: true
mihome-vacuum.0 | 2021-04-22 13:55:28.770 | info | (24705) starting. Version 3.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.17.0, js-controller: 3.1.4
mihome-vacuum.0 | 2021-04-22 13:55:27.594 | debug | (24705) statesDB connected
mihome-vacuum.0 | 2021-04-22 13:55:27.591 | debug | (24705) States connected to redis: 127.0.0.1:9000
mihome-vacuum.0 | 2021-04-22 13:55:27.575 | debug | (24705) States create System PubSub Client
mihome-vacuum.0 | 2021-04-22 13:55:27.569 | debug | (24705) States create User PubSub Client
mihome-vacuum.0 | 2021-04-22 13:55:27.477 | debug | (24705) Redis States: Use Redis connection: 127.0.0.1:9000
mihome-vacuum.0 | 2021-04-22 13:55:27.472 | debug | (24705) objectDB connected
mihome-vacuum.0 | 2021-04-22 13:55:27.458 | debug | (24705) Objects connected to redis: 127.0.0.1:9001
mihome-vacuum.0 | 2021-04-22 13:55:27.415 | debug | (24705) Objects client initialize lua scripts
mihome-vacuum.0 | 2021-04-22 13:55:27.412 | debug | (24705) Objects create User PubSub Client
mihome-vacuum.0 | 2021-04-22 13:55:27.408 | debug | (24705) Objects create System PubSub Client
mihome-vacuum.0 | 2021-04-22 13:55:27.197 | debug | (24705) Objects client ready ... initialize now
mihome-vacuum.0 | 2021-04-22 13:55:27.097 | debug | (24705) Redis Objects: Use Redis connection: 127.0.0.1:9001
mihome-vacuum.0 | 2021-04-22 13:55:21.875 | info | (24267) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2021-04-22 13:55:21.872 | info | (24267) terminating
mihome-vacuum.0 | 2021-04-22 13:55:21.869 | info | (24267) Got terminate signal TERMINATE_YOURSELF
mihome-vacuum.0 | 2021-04-22 13:40:34.034 | warn | (24267) Could not build message without arguments
mihome-vacuum.0 | 2021-04-22 13:40:34.031 | info | (24267) send message: Method:
mihome-vacuum.0 | 2021-04-22 13:40:19.781 | info | (24267) send message: Method: loadRooms
mihome-vacuum.0 | 2021-04-22 13:40:02.484 | info | (24267) check group user admin group admin: false
mihome-vacuum.0 | 2021-04-22 13:40:02.478 | info | (24267) check user admin pw iobroker: true
mihome-vacuum.0 | 2021-04-22 13:40:02.142 | info | (24267) starting. Version 3.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.17.0, js-controller: 3.1.4
mihome-vacuum.0 | 2021-04-22 13:39:55.070 | info | (16792) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2021-04-22 13:39:55.068 | info | (16792) terminating
mihome-vacuum.0 | 2021-04-22 13:39:55.064 | info | (16792) Got terminate signal TERMINATE_YOURSELF

`

**Comment by MeisterTR** [comment]
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum#supported-devices-and-fetures
