### ISSUE TITLE
please add key lock / bitte Tastensperre / Kindersicherung hinzufügen für den Roborock S7

### ISSUE THREAD

**Issue by Ceel84** [iobroker-community-adapters/ioBroker.mihome-vacuum#263]
Hallo
Ist es möglich die Tastensperre / Kindersicherung in den Adapter für den Roborock S7 einzubauen?

**Comment by MeisterTR** [comment]
aktuell ist mir keine Lösung dafür bekannt, da ich in den Api Nachrichten kein Kommando für die Tastensperre finden kann.
