### ISSUE TITLE
error on update 2.2.5-->3.1.1

### ISSUE THREAD

**Issue by quinti123** [iobroker-community-adapters/ioBroker.mihome-vacuum#268]
hi there,
i´ve tried to update to 3.1.1 on my win10 system:

`$ ./iobroker upgrade mihome-vacuum
Update mihome-vacuum from @2.2.5 to @3.1.1
NPM version: 6.4.1
npm install iobroker.mihome-vacuum@3.1.1 --loglevel error (System call)
npm ERR! path C:\ioBroker\node_modules\iobroker.mihome-vacuum\node_modules\canvas\build\Release\libbrotlicommon.dll
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\ioBroker\node_modules\iobroker.mihome-vacuum\node_modules\canvas\build\Release\libbrotlicommon.dll'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\ioBroker\node_modules\iobroker.mihome-vacuum\node_modules\canvas\build\Release\libbrotlicommon.dll']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\ioBroker\node_modules\iobroker.mihome-vacuum\node_modules\canvas\build\Release\libbrotlicommon.dll'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\ioBroker\\node_modules\\iobroker.mihome-vacuum\\node_modules\\canvas\\build\\Release\\libbrotlicommon.dll' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\ioBroker\\node_modules\\iobroker.mihome-vacuum\\node_modules\\canvas\\build\\Release\\libbrotlicommon.dll\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\ioBroker\\node_modules\\iobroker.mihome-vacuum\\node_modules\\canvas\\build\\Release\\libbrotlicommon.dll',
npm ERR!   parent: 'iobroker.mihome-vacuum' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2021-04-26T15_21_43_397Z-debug.log
ERROR: host.KELLER Cannot install iobroker.mihome-vacuum@3.1.1: 4294963248
ERROR: process exited with code 25`

**Comment by Apollon77** [comment]
This is a permission error  "EPERM" . Best remove the mentioned files manually and try again

**Comment by MeisterTR** [comment]
is now working?
