### ISSUE TITLE
[dreame.vacuum.p2009] Support Dreame D9

### ISSUE THREAD

**Issue by Comotio82** [iobroker-community-adapters/ioBroker.mihome-vacuum#269]
Hallo, könnte man diesen auch hinzufügen?

`mihome-vacuum.0 | 2021-04-27 12:27:57.359 | warn | (1134) Model dreame.vacuum.p2009 not supported! Please open issue on git: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues
-- | -- | -- | --
mihome-vacuum.0 | 2021-04-27 12:27:57.359 | debug | (1134) DeviceModel selected to: dreame.vacuum.p2009
mihome-vacuum.0 | 2021-04-27 12:27:57.358 | debug | (1134) Get Device data from robot..
mihome-vacuum.0 | 2021-04-27 12:27:57.357 | debug | (1134) Get Device data..1
mihome-vacuum.0 | 2021-04-27 12:27:57.357 | debug | (1134) GETMODELFROMAPI:Data: {"partner_id":"","id":2,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_1082","ap":{"ssid":"xxx","bssid":"74:42:7F:40:08:F6","rssi":-47},"netif
mihome-vacuum.0 | 2021-04-27 12:27:57.356 | debug | (1134) MIIO RECIVE: {"partner_id":"","id":2,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_1082","ap":{"ssid":"xxx","bssid":"74:42:7F:40:08:F6","rssi":-47},"netif":{"local
mihome-vacuum.0 | 2021-04-27 12:27:57.325 | debug | (1134) Message= {"id":2,"method":"miIO.info"}
mihome-vacuum.0 | 2021-04-27 12:27:57.324 | debug | (1134) Get Device data..0
mihome-vacuum.0 | 2021-04-27 12:27:57.323 | debug | (1134) Receive Timeout<<<
mihome-vacuum.0 | 2021-04-27 12:27:55.318 | debug | (1134) Message= {"id":1,"method":"miIO.info"}
mihome-vacuum.0 | 2021-04-27 12:27:55.317 | debug | (1134) GETMODELFROMAPI: objModel: {"val":"dreame.vacuum.p2009","ack":true,"ts":1619518941014,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1618819820812}
mihome-vacuum.0 | 2021-04-27 12:27:55.313 | debug | (1134) MAIN: Connected to device, try to get model..
mihome-vacuum.0 | 2021-04-27 12:27:55.312 | debug | (1134) Receive <<< Helo <<< 213100200000000016d19b806087e72bffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-04-27 12:27:55.244 | debug | (1134) server started on 0.0.0.0:53421
mihome-vacuum.0 | 2021-04-27 12:27:55.238 | debug | (1134) MIIO: Config: ip:192.168.2.21 token: xxx
mihome-vacuum.0 | 2021-04-27 12:27:55.237 | debug | (1134) Create State for deviceInfowifi_signal
mihome-vacuum.0 | 2021-04-27 12:27:55.237 | debug | (1134) Create State for deviceInfofw_ver
mihome-vacuum.0 | 2021-04-27 12:27:55.236 | debug | (1134) Create State for deviceInfomodel
mihome-vacuum.0 | 2021-04-27 12:27:55.192 | debug | (1134) Create State for deviceInfomac
mihome-vacuum.0 | 2021-04-27 12:27:55.171 | info | (1134) check group user admin group admin: false
mihome-vacuum.0 | 2021-04-27 12:27:54.951 | info | (1134) check user admin pw iobroker: true
mihome-vacuum.0 | 2021-04-27 12:27:54.725 | info | (1134) starting. Version 3.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.22.1, js-controller: 3.2.16`

**Comment by MeisterTR** [comment]
Um zu sehen welche Modelle am verbreitetsten sind bitte hier Abstimmen
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum#supported-devices-and-fetures

**Comment by MeisterTR** [comment]
https://github.com/openhab/openhab-addons/blob/c7218c6d29637fa210145632562ebda63381a768/bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2009-miot.json

**Comment by canim60** [comment]
> 
> 
> https://github.com/openhab/openhab-addons/blob/c7218c6d29637fa210145632562ebda63381a768/bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2009-miot.json

Wie lange geht die Umfrage ?? bzw wann hören wir Neuigkeiten?

**Comment by n3roGit** [comment]
Any news here? Maybe alpha version to test?

**Comment by emanuelwo** [comment]
+1

**Comment by majidmostafa** [comment]
Hi Guys,
Please I have an issue with my Dreame Vacuum D9 (dreame.vacuum.p2009) which is dead!! (No interaction, no light, no reaction, ...) before that I have switched my Mi Home account from Singapore to French ( because I wanted to link it with my Alexa :( )
It was fully charged and it have requested me to update the firmeware but after that I disovered that the robot is dead and I tried to reset it but no reaction. from that moment I can't do anything as it is fully Off and no signe of reactvitiy, is like the systeme has been erased or its Soft have been broken due to the firmeware update.
Can you please help me to resolve this issue?
For information, I installed the token extractor and I can see the Vaccum linked in my account Singapore and I can see also its token.
Many thanks for your help and support

**Comment by XMottek** [comment]
Habeauch den Dreame D9. Gibt es schon irgendwelche Neuigkeiten zum Adapter?

**Comment by n3roGit** [comment]
Nope, leider

**Comment by n3roGit** [comment]
Ich frag nochmal nach. Gibt es hier Neuigkeiten? Wird daran gearbeitet? Können wir irgendwie helfen?

Ich nehme mir gerne ein paar Stunden Zeit dafür.

**Comment by Krustenlaese** [comment]
Würde auch meine Hilfe anbieten. Sitze zu Hause, habe Zeit und einen D9
Wenn man mir sagt, wie ich die Befehle mitschneide, könnte ich mich da mal ausgiebig dran setzen.
Hätte auch eine Winzigkeit Programmiererfahrung, wenn es dem Entwickler helfen würde.
Bin da für alles offen 😃

**Comment by TZanke** [comment]
Nenene lieber Bot, ist schon interessant für uns. Cool das ihr helfen wollt, und schade das keiner euch erklärt wie. Ich bin da aber auch überfragt. LG

**Comment by ChrisCross8214** [comment]
Für mich auch weiterhin interessant.
