### ISSUE TITLE
S5 Max

### ISSUE THREAD

**Issue by amnesia106** [iobroker-community-adapters/ioBroker.mihome-vacuum#270]
no card updates with the newest fw 3.5.8_1410 on roborock s5 max. Adapterversion 2.1.1

**Comment by MeisterTR** [comment]
Please Post a long debug log

**Comment by amnesia106** [comment]
`mihome-vacuum.0 | 2021-04-30 10:34:47.845 | warn | (17548) State "mihome-vacuum.0.control.clean_home" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
mihome-vacuum.0 | 2021-04-30 10:34:47.840 | info | (17548) create states for water box filter
mihome-vacuum.0 | 2021-04-30 10:34:47.840 | info | (17548) create states for water box
mihome-vacuum.0 | 2021-04-30 10:34:28.947 | info | (17548) create state for carpet_mode
mihome-vacuum.0 | 2021-04-30 10:34:28.382 | info | (17548) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2021-04-30 10:34:27.939 | info | (17548) Connected
mihome-vacuum.0 | 2021-04-30 10:34:27.903 | info | (17548) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2021-04-30 10:34:27.902 | warn | (17548) Time difference between Mihome Vacuum and ioBroker: 1 sec
mihome-vacuum.0 | 2021-04-30 10:34:27.895 | info | (17548) New generation or new fw(3.5.8,1410) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2021-04-30 10:34:27.827 | info | (17548) Cloud control disabled
mihome-vacuum.0 | 2021-04-30 10:34:27.826 | info | (17548) Expert mode disabled, states deleted
mihome-vacuum.0 | 2021-04-30 10:34:27.725 | info | (17548) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.21.0, js-controller: 3.2.16
mihome-vacuum.0 | 2021-04-30 10:34:26.028 | info | (17499) terminating with timeout
mihome-vacuum.0 | 2021-04-30 10:34:24.597 | warn | (17499) Got terminate signal. Checking desired PID: 17548 vs own PID 17499
mihome-vacuum.0 | 2021-04-30 10:34:24.527 | info | (17499) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2021-04-30 10:34:24.526 | info | (17499) terminating
mihome-vacuum.0 | 2021-04-30 10:34:24.525 | warn | (17499) Got terminate signal. Checking desired PID: 0 vs own PID 17499
mihome-vacuum.0 | 2021-04-30 10:31:48.515 | warn | (17499) State "mihome-vacuum.0.control.clean_home" has no existing object, this might lead to an error in future versions
mihome-vacuum.0 | 2021-04-30 10:31:48.501 | info | (17499) create states for water box filter`

log is clean. no debug entry. My first try. I delete the mapURL picture in the file explorer in vis, and after that i try the "loadmap" button on iobroker admin in object tree. No new picture created.

**Comment by MeisterTR** [comment]
please try the 3.1.2 from git (delete adapter first) and report

**Comment by amnesia106** [comment]
with 3.1.2 the map is loading, but when i start a specific room cleaning, the adapter crashes. 
all clean and home works, but no "segment"


`mihome-vacuum.0 | 2021-05-01 10:48:40.593 | warn | (39078) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
mihome-vacuum.0 | 2021-05-01 10:48:40.591 | info | (39078) terminating
mihome-vacuum.0 | 2021-05-01 10:48:40.577 | error | (39078) Cannot read property 'val' of null
mihome-vacuum.0 | 2021-05-01 10:48:40.577 | error | (39078) TypeError: Cannot read property 'val' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/vacuum.js:1324:63) at processImmediate (internal/timers.js
mihome-vacuum.0 | 2021-05-01 10:48:40.577 | error | (39078) uncaught exception: Cannot read property 'val' of null
mihome-vacuum.0 | 2021-05-01 10:48:40.575 | error | (39078) Cannot read property 'val' of null
mihome-vacuum.0 | 2021-05-01 10:48:40.575 | error | (39078) TypeError: Cannot read property 'val' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/vacuum.js:1320:53) at processImmediate (internal/timers.js
mihome-vacuum.0 | 2021-05-01 10:48:40.574 | error | (39078) uncaught exception: Cannot read property 'val' of null
mihome-vacuum.0 | 2021-05-01 10:48:40.568 | info | (39078) trigger cleaning segment 25
mihome-vacuum.0 | 2021-05-01 10:47:23.910 | info | (39078) trigger cleaning all`
