### ISSUE TITLE
JS-Controller 3.3 - LOG-EIntrag State value to set for "mihome-vacuum.0.control.sound_volume"

### ISSUE THREAD

**Issue by kueppert** [iobroker-community-adapters/ioBroker.mihome-vacuum#271]
mihome-vacuum.0 | 2021-04-30 10:03:55.788 | warn | (19112) State value to set for "mihome-vacuum.0.control.sound_volume" has value "2" less than min "100"

**Comment by Diginix** [comment]
Which mihome-vacuum version?
version 2.2.5 has 30 as min and version 3.1.1 min is 0

**Comment by Apollon77** [comment]
Maybe object needs to be deleted to get it updated?

**Comment by Flyor** [comment]
Here another Information, which got after updating JS to 3.3.2
Installed Adapter V 3.1.4
![image](https://user-images.githubusercontent.com/64526892/117126474-180d6800-ad9b-11eb-8517-302b59734170.png)
![image](https://user-images.githubusercontent.com/64526892/117126516-252a5700-ad9b-11eb-8102-8a44874658c0.png)

**Comment by MeisterTR** [comment]
fixed in 3.1.6
