### ISSUE TITLE
nach Update js-controller 3.3.5 kein Adapter Update

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.mihome-vacuum#273]
Bekomme folgende Fehlermeldung, wenn ich versuch auf 3.1.2 upzudaten.

`$ ./iobroker upgrade mihome-vacuum
Update mihome-vacuum from @3.1.1 to @3.1.2
NPM version: 6.14.11npm install iobroker.mihome-vacuum@3.1.2 --loglevel error (System call)
npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\iobroker\GLT\node_modules\iobroker.mihome-vacuum
npm ERR! dest C:\iobroker\GLT\node_modules\.iobroker.mihome-vacuum.DELETE
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\iobroker\GLT\node_modules\iobroker.mihome-vacuum' -> 'C:\iobroker\GLT\node_modules\.iobroker.mihome-vacuum.DELETE'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\iobroker\GLT\env\npm-cache\_logs\2021-05-01T20_18_38_407Z-debug.log
ERROR: host.GLT(GLT) Cannot install iobroker.mihome-vacuum@3.1.2: 4294963214
ERROR: process exited with code 25`

**Comment by Apollon77** [comment]
EBUSY bedeutet das die i/o resource busy ist - das kann virenscanner sein, permission kram oder oder oder ... hat nichts mit controller zu tun. Ist irgendwas mit Filesystem access. SOrry

**Comment by JBSullivan** [comment]
Kann es sein, das sich der Broker bzw. der js-controller selber ein Bein stellt ?

Nicht vergessen, ich bin Windows User. 

Stoppe ich ioBroker und führe dann das Update via Konsolen Aufruf durch, werden die beiden Adapter (ja sind bereits 2 wo die Fehlermeldung kam), einwandfrei upgedatet.

Im gestarteten Zustand  von ioBroker und aus der Adapter Liste heraus, kam es bei beiden Adaptern (mihome-vacuum & vis-inventwo) zu der schon oben beschriebenen EBUSY Meldung.

![image](https://user-images.githubusercontent.com/44617472/116803348-f3a15980-ab16-11eb-8fdd-7b3d2a5e67e6.png)

**Comment by Apollon77** [comment]
Ohne das wir rausfinden woher EBUSY kommt ist das ganze schwierig. Ich habe keine Ahnung ob zb nodejs irgendwleche files "lockt" (also so das WIndows demkt da ist ein File gelockt) ... dann wäre das aber ein nodejs thema ... Bei Windows bin ich leiider raus und kann nur Googlen
