### ISSUE TITLE
[Roborock.Vacuum.E2]  support (saphire)

### ISSUE THREAD

**Issue by M4tRiX92** [iobroker-community-adapters/ioBroker.mihome-vacuum#277]
Hi,
I can't connect my roborock.vacuum.e2. :( I can see my token and IP address but the connection to the robot is not successful.
In the log I can see only some "time difference" issues. But all time settings are set to the german time zone. I see that the robot is not in the supported device list, but I think on this device is nothing special? Can someone give me a hint?
Thanks!

![grafik](https://user-images.githubusercontent.com/77054170/116911143-bf2cbb00-ac46-11eb-926e-43ccdb535391.png)
![grafik](https://user-images.githubusercontent.com/77054170/116911193-cf449a80-ac46-11eb-9d9e-a89e95a93742.png)

**Comment by MeisterTR** [comment]
Please try the 3.1.4 from git and report a debug log

**Comment by Grothesk242** [comment]
One of the partners is running on unix timestamp, having not received the correct time (via ntp?). 
Have you set up the vacuum in the corresponding app yet?

**Comment by MeisterTR** [comment]
the warning with the timestamp doesnt matter.

**Comment by M4tRiX92** [comment]
> 
> 
> Please try the 3.1.4 from git and report a debug log

I tried it with version 3.1.4. and the error message chaned... Unfortunately the device is not supported :(
![grafik](https://user-images.githubusercontent.com/77054170/116919883-3ca9f880-ac52-11eb-9eb0-10898a66f7cb.png)
Can I change this? Or can you add this device for testing in the main.js? Thanks.

**Comment by MeisterTR** [comment]
That's not important, should work. Please post a debug log.

**Comment by M4tRiX92** [comment]
Attached a screenshot of the debug-log and a html-file
[iobroker.2021-05-04.html.zip](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/6422801/iobroker.2021-05-04.html.zip)

.
![grafik](https://user-images.githubusercontent.com/77054170/117042666-8f47eb00-ad0c-11eb-99bc-40041434ca42.png)

**Comment by MeisterTR** [comment]
ok please install form git again and post anonther log. the htmlflie is perfect. i exentend the log to find the error

**Comment by M4tRiX92** [comment]
So, i reinstalled 3.1.4 from GIT again.
Attached you can find the new html.
[iobroker.current.html.zip](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/6423568/iobroker.current.html.zip)

**Comment by MeisterTR** [comment]
hmm cant see more. added more logs in 3.1.5.TEST. please post another log with git version

**Comment by MeisterTR** [comment]
at this robot semms somthing different with the message format...

**Comment by MeisterTR** [comment]
now it is the 3.1.6

**Comment by M4tRiX92** [comment]
I tried to upgrade to 3.1.6 but this version was not found... what am I missing?
![grafik](https://user-images.githubusercontent.com/77054170/117196024-495f5580-ade6-11eb-949c-84d11107ddca.png)

**Comment by MeisterTR** [comment]
You tried to install from npm, on npm is the latest 3.1.4. You have to install from git. Try to update from the admin. Press on the cat in Adapterlist and select the Adapter, then it should work.

**Comment by M4tRiX92** [comment]
Here you find the new logfile. Thanks!
[Mihome.zip](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/6432971/Mihome.zip)

**Comment by MeisterTR** [comment]
bad news, the e2 have different Mesaages than the other vacuums...

**Comment by MeisterTR** [comment]
i impplemented the messages, please try the 3.1.7 from git plese make sure that realy installed 3.1.7

**Comment by M4tRiX92** [comment]
Hi, so I updated to git-version 3.1.8 but it's still failing.
See attachment.
Thank you.
[Mihome2.zip](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/6443489/Mihome2.zip)

**Comment by M4tRiX92** [comment]
Any updates on this? Thank you.
