### ISSUE TITLE
Could not calculate next timer TypeError: nextProcessTime.getDay is not a function

### ISSUE THREAD

**Issue by Grothesk242** [iobroker-community-adapters/ioBroker.mihome-vacuum#280]
In drop down menu for setting timers the weekday is greyed out. 
Log file shows: 

```error: mihome-vacuum.0 (3420) Could not calculate next timer TypeError: nextProcessTime.getDay is not a function```

mihome-vacuum : 3.1.4
js-controller 3.3.7
nodeJS 14.16.1
roborock.v1

**Comment by MeisterTR** [comment]
thats a little bug in the dropdown, you have to click a little bitt above the checkbox, then it is working
