### ISSUE TITLE
Roborock S5 no map

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.mihome-vacuum#285]
There ist no map-URL loading:
js-controller: 3.2.16
node.js 12.22.1
NPM: 6.14.12
Version 3.1.17
`
<html><body>

mihome-vacuum.0 | 2021-05-08 15:10:07.301 | debug | (6710) Receive <<< Helo <<< 213100200000000005bfa9f260968daeffffffffffffffffffffffffffffffff
-- | -- | -- | --
mihome-vacuum.0 | 2021-05-08 15:10:01.524 | debug | (6710) system.adapter.admin.0: logging true
mihome-vacuum.0 | 2021-05-08 15:10:00.286 | debug | (6710) Mappointer_updated
mihome-vacuum.0 | 2021-05-08 15:10:00.285 | debug | (6710) MIIO RECIVE: {"result":["robomap%2F96446962%2F6"],"id":38}
mihome-vacuum.0 | 2021-05-08 15:10:00.275 | debug | (6710) Message= {"id":38,"method":"get_map_v1"}
mihome-vacuum.0 | 2021-05-08 15:10:00.273 | debug | (6710) command: loadMap parent: cleanmap
mihome-vacuum.0 | 2021-05-08 15:09:59.992 | debug | (6710) system.adapter.admin.0: logging false
mihome-vacuum.0 | 2021-05-08 15:09:59.445 | debug | (6710) Mappointer_updated
mihome-vacuum.0 | 2021-05-08 15:09:59.445 | debug | (6710) MIIO RECIVE: {"result":["robomap%2F96446962%2F5"],"id":37}
mihome-vacuum.0 | 2021-05-08 15:09:59.423 | debug | (6710) Message= {"id":37,"method":"get_map_v1"}
mihome-vacuum.0 | 2021-05-08 15:09:59.423 | debug | (6710) command: loadMap parent: cleanmap

</body>
</html>`

**Comment by MeisterTR** [comment]
need a longer logfile

**Comment by guergen1** [comment]
After several restarts of the Adapter, he had not connected to the server, reinstalling has solved the problem!
