### ISSUE TITLE
Roborock S7: Errors without Cloud

### ISSUE THREAD

**Issue by DcFamas** [iobroker-community-adapters/ioBroker.mihome-vacuum#293]
Adapter version: 3.1.8
node.js: v12.22.1
npm: 6.14.12
js-controller: 3.2.16

Hey there,
I replaced my Xiaomi Mihome Vacuum for the Roborock S7. I want to use the vacuum cleaner without any cloud connection.
I got the token by the russian app and set the "manuel settings" in the adapter. I didn't touched any other settings.
When the cleaner can access the internet, there is no problem with the adapter. But when I forbid the connection via parental control in my FRITZ!Box, I get the following errors:

`
<html><body>

mihome-vacuum.0 | 2021-05-13 14:25:22.616 | warn | (10317) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
mihome-vacuum.0 | 2021-05-13 14:25:22.615 | info | (10317) terminating
mihome-vacuum.0 | 2021-05-13 14:25:22.605 | error | (10317) undefined
mihome-vacuum.0 | 2021-05-13 14:25:22.605 | error | (10317) unhandled promise rejection: undefined
mihome-vacuum.0 | 2021-05-13 14:25:22.605 | error | (10317)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
mihome-vacuum.0 | 2021-05-13 14:25:22.603 | debug | (10317) MIIO Receive  Timeout<<<
mihome-vacuum.0 | 2021-05-13 14:25:22.601 | warn | (10317) Cant send command please try againstart
mihome-vacuum.0 | 2021-05-13 14:25:22.601 | debug | (10317) MIIO Receive  Timeout<<<

</body>
</html>

Is there a chance to change this or is the S7 "cloud only"?

Best regards! :)

**Comment by MeisterTR** [comment]
Every new robot need the connection to the cloud, you cant use them without internet
