### ISSUE TITLE
Time difference between Mihome Vacuum and ioBroker: -1620928987 sec

### ISSUE THREAD

**Issue by BS-GIFHUB** [iobroker-community-adapters/ioBroker.mihome-vacuum#294]
Just installed my Xiaomi S7 and got attached failure, so no connection. Token is okay. Tiime Zone and Server is Germany,. 

Thanks

Bernhard

**Comment by MeisterTR** [comment]
please use for s7 version greater than 3.x.x timedifferenz is just an info. the robot should still connect

**Comment by BS-GIFHUB** [comment]
Sorry no connection at all. I got a connection with a homebridge plug-in and also in red-node but not with your adapter.

**Comment by BS-GIFHUB** [comment]
connecting, this can take up to 10 minutes ...

**Comment by BS-GIFHUB** [comment]
Still no connection
