### ISSUE TITLE
No connection to S7

### ISSUE THREAD

**Issue by BS-GIFHUB** [iobroker-community-adapters/ioBroker.mihome-vacuum#295]
I did all (hopefully :-)) according the instruction but I didn't get a green status, only yellow with the message "connecting, this can take up to 10 minutes ...". Connection via PLUG-IN of Homebridge works and also RED-Node Module works, but this IOBROKER adapter seems a little bit like a mule. Please help. Thanks.

**Comment by MeisterTR** [comment]
please poste a debuglog. Stop other connections that causes troubles.

**Comment by BS-GIFHUB** [comment]
<html>
<body>


mihome-vacuum.0 | 2021-05-14 16:43:10.187 | debug | (32082) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
-- | -- | -- | --
mihome-vacuum.0 | 2021-05-14 16:43:10.186 | debug | (32082) no answer for id:2 received, giving up
mihome-vacuum.0 | 2021-05-14 16:43:05.381 | debug | (32082) The answer from the robot is not correct! (SyntaxError: Unexpected end of JSON input) "{\"id\":2,\"result\":[{\"msg_ver\":2,\"msg_seq\":8630,\"state\":8,\"battery\":100,\"clean_time\":441,\"cl
mihome-vacuum.0 | 2021-05-14 16:43:05.378 | debug | (32082) Receive <<< {"id":2,"result":[{"msg_ver":2,"msg_seq":8630,"state":8,"battery":100,"clean_time":441,"clean_area":8240000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fres
mihome-vacuum.0 | 2021-05-14 16:43:05.185 | debug | (32082) sendMsg[3] >>> {"id":2,"method":"get_status"}
mihome-vacuum.0 | 2021-05-14 16:43:00.370 | debug | (32082) The answer from the robot is not correct! (SyntaxError: Unexpected end of JSON input) "{\"id\":2,\"result\":[{\"msg_ver\":2,\"msg_seq\":8628,\"state\":8,\"battery\":100,\"clean_time\":441,\"cl
mihome-vacuum.0 | 2021-05-14 16:43:00.368 | debug | (32082) Receive <<< {"id":2,"result":[{"msg_ver":2,"msg_seq":8628,"state":8,"battery":100,"clean_time":441,"clean_area":8240000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fres
mihome-vacuum.0 | 2021-05-14 16:43:00.183 | debug | (32082) sendMsg[2] >>> {"id":2,"method":"get_status"}
mihome-vacuum.0 | 2021-05-14 16:42:55.362 | debug | (32082) The answer from the robot is not correct! (SyntaxError: Unexpected end of JSON input) "{\"id\":2,\"result\":[{\"msg_ver\":2,\"msg_seq\":8627,\"state\":8,\"battery\":100,\"clean_time\":441,\"cl
mihome-vacuum.0 | 2021-05-14 16:42:55.360 | debug | (32082) Receive <<< {"id":2,"result":[{"msg_ver":2,"msg_seq":8627,"state":8,"battery":100,"clean_time":441,"clean_area":8240000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fres
mihome-vacuum.0 | 2021-05-14 16:42:55.180 | debug | (32082) sendMsg[1] >>> {"id":2,"method":"get_status"}
mihome-vacuum.0 | 2021-05-14 16:42:55.170 | debug | (32082) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-05-14 16:42:55.169 | info | (32082) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2021-05-14 16:42:55.168 | warn | (32082) Time difference between Mihome Vacuum and ioBroker: -1620954952 sec
mihome-vacuum.0 | 2021-05-14 16:42:55.165 | debug | (32082) Receive <<< Helo <<< 2131002000000000175146170000bd27ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-05-14 16:42:50.130 | debug | (32082) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-05-14 16:42:50.125 | debug | (32082) no answer for id:1 received, giving up
mihome-vacuum.0 | 2021-05-14 16:42:45.242 | debug | (32082) The answer from the robot is not correct! (SyntaxError: Unexpected end of JSON input) "{\"id\":1,\"result\":[{\"msg_ver\":2,\"msg_seq\":8623,\"state\":8,\"battery\":100,\"clean_time\":441,\"cl
mihome-vacuum.0 | 2021-05-14 16:42:45.240 | debug | (32082) Receive <<< {"id":1,"result":[{"msg_ver":2,"msg_seq":8623,"state":8,"battery":100,"clean_time":441,"clean_area":8240000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fres
mihome-vacuum.0 | 2021-05-14 16:42:45.124 | debug | (32082) sendMsg[3] >>> {"id":1,"method":"get_status"}
mihome-vacuum.0 | 2021-05-14 16:42:40.232 | debug | (32082) The answer from the robot is not correct! (SyntaxError: Unexpected end of JSON input) "{\"id\":1,\"result\":[{\"msg_ver\":2,\"msg_seq\":8621,\"state\":8,\"battery\":100,\"clean_time\":441,\"cl
mihome-vacuum.0 | 2021-05-14 16:42:40.230 | debug | (32082) Receive <<< {"id":1,"result":[{"msg_ver":2,"msg_seq":8621,"state":8,"battery":100,"clean_time":441,"clean_area":8240000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fres
mihome-vacuum.0 | 2021-05-14 16:42:40.120 | debug | (32082) sendMsg[2] >>> {"id":1,"method":"get_status"}
mihome-vacuum.0 | 2021-05-14 16:42:37.470 | debug | (32082) Xiaomi Cloud: Login successful
mihome-vacuum.0 | 2021-05-14 16:42:35.325 | debug | (32082) The answer from the robot is not correct! (SyntaxError: Unexpected end of JSON input) "{\"id\":1,\"result\":[{\"msg_ver\":2,\"msg_seq\":8620,\"state\":8,\"battery\":100,\"clean_time\":441,\"cl
mihome-vacuum.0 | 2021-05-14 16:42:35.322 | debug | (32082) Receive <<< {"id":1,"result":[{"msg_ver":2,"msg_seq":8620,"state":8,"battery":100,"clean_time":441,"clean_area":8240000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fres
mihome-vacuum.0 | 2021-05-14 16:42:35.255 | info | (32082) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2021-05-14 16:42:35.117 | debug | (32082) sendMsg[1] >>> {"id":1,"method":"get_status"}
mihome-vacuum.0 | 2021-05-14 16:42:35.096 | debug | (32082) sendTo "getStatus" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-05-14 16:42:35.093 | info | (32082) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2021-05-14 16:42:35.092 | warn | (32082) Time difference between Mihome Vacuum and ioBroker: -1620954952 sec
mihome-vacuum.0 | 2021-05-14 16:42:35.089 | debug | (32082) Receive <<< Helo <<< 2131002000000000175146170000bd13ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-05-14 16:42:34.805 | debug | (32082) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
mihome-vacuum.0 | 2021-05-14 16:42:34.703 | debug | (32082) server started on 0.0.0.0:53421


</body>
</html>

**Comment by BS-GIFHUB** [comment]
Hello here is my debug log

**Comment by MeisterTR** [comment]
you are not on version 3.1.X. You have to install a higher Version

**Comment by BS-GIFHUB** [comment]
HI, sorry update wasn't offered by IOBROKER till now. Thats the main problem. Actual version is 
2.1.1

I installed it now manually from github and it works great. Many thanks.

Bernhard
