### ISSUE TITLE
Incompatibility with JS-Controller 3.3.8

### ISSUE THREAD

**Issue by Flyor** [iobroker-community-adapters/ioBroker.mihome-vacuum#296]
Since updating to JS-Controller 3.3.8 (3.3.9 got the same effect) I got massive log entries for the wrong object type at the water box point. I already deleted the instances and adapter completely, but no changes at all. 

![image](https://user-images.githubusercontent.com/64526892/118256995-68c54500-b4ae-11eb-9585-4616c24a7d80.png)

**Comment by MeisterTR** [comment]
Version? Should be fixed in latest..

**Comment by Flyor** [comment]
> Version? Should be fixed in latest..

3.1.7

**Comment by MeisterTR** [comment]
please delete and reinstall
