### ISSUE TITLE
Error display instance after install

### ISSUE THREAD

**Issue by MedizinPumPer** [iobroker-community-adapters/ioBroker.mihome-vacuum#309]
Hey, 

i install the Version from totday -> after installation the "instance" not showing up and the Images for the Controll-Widget are not moved to the correct folder (folder not exist under "widgets/mihome-vacuum/img/home.png") 

there is no Error log for it.. 
![image](https://user-images.githubusercontent.com/49619839/120563647-6862fe80-c409-11eb-9a78-f41ed555e9af.png)

**Comment by MeisterTR** [comment]
i just tested it and wverything seems good, please install again
