### ISSUE TITLE
Falscher Datentyp / mihome-vacuum.0.info.water_box

### ISSUE THREAD

**Issue by mctom** [iobroker-community-adapters/ioBroker.mihome-vacuum#310]
Ich habe in den letzten Tagen diverse Update durchgeführt. 
In den Logs erhalte ich jetzt folgende Log Einträge.

`State value to set for "mihome-vacuum.0.info.water_box" has to be type "string" but received type "boolean"
--`

Controler: 3.3.11
mihome-vacuum: 3.2.0

**Comment by MeisterTR** [comment]
bitte die objekte vom adapter mauell löschen und neustarten
