### ISSUE TITLE
Empty room array S7

### ISSUE THREAD

**Issue by h3llh0und** [iobroker-community-adapters/ioBroker.mihome-vacuum#315]
Hi,

i received my Roborock S7 last week and i wanted to control it with my iobroker.

I have multiple Times the following error in log which cause a reboot of the instance:

host.raspberrypi | 2021-06-08 09:29:41.832 | info | instance system.adapter.mihome-vacuum.0 terminated with code NaN ()
host.raspberrypi | 2021-06-08 09:29:41.830 | warn | instance system.adapter.mihome-vacuum.0 terminated due to SIGSEGV
mihome-vacuum.0 | 2021-06-08 09:29:41.327 | debug | (26183) Message= {"id":7,"method":"get_network_info"}
mihome-vacuum.0 | 2021-06-08 09:29:41.325 | debug | (26183) Message= {"id":6,"method":"get_consumable"}
mihome-vacuum.0 | 2021-06-08 09:29:41.323 | debug | (26183) MIIO RECIVE: {"id":5,"result":[],"exe_time":100}
mihome-vacuum.0 | 2021-06-08 09:29:41.241 | debug | (26183) update_Map got new time:1623137381
mihome-vacuum.0 | 2021-06-08 09:29:41.241 | debug | (26183) update_Map got new expires:1623139181
mihome-vacuum.0 | 2021-06-08 09:29:41.240 | debug | (26183) update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/roboroommap/xxxx/17?Expires=xxxx&amp;GalaxyAccessKeyId=xxxxxxx&amp;Signature=xxxxx
mihome-vacuum.0 | 2021-06-08 09:29:41.141 | debug | (26183) Message= {"id":5,"method":"get_room_mapping"}
mihome-vacuum.0 | 2021-06-08 09:29:41.128 | debug | (26183) update_Map need new mapurl
mihome-vacuum.0 | 2021-06-08 09:29:41.127 | debug | (26183) update_Map Mimap enabled
mihome-vacuum.0 | 2021-06-08 09:29:41.124 | debug | (26183) Mappointer_updated
mihome-vacuum.0 | 2021-06-08 09:29:41.122 | debug | (26183) MIIO RECIVE: {"id":4,"result":["roboroommap%2F416236494%2F17"],"exe_time":100}
mihome-vacuum.0 | 2021-06-08 09:29:40.923 | debug | (26183) Message= {"id":4,"method":"get_map_v1"}
mihome-vacuum.0 | 2021-06-08 09:29:40.621 | debug | (26183) MIIO RECIVE: {"id":3,"result":["retry"],"exe_time":101}
mihome-vacuum.0 | 2021-06-08 09:29:40.488 | debug | (26183) Message= {"id":3,"method":"get_map_v1"}

Next Problem is when i try to load the Rooms i just get this error:

mihome-vacuum.0 | 2021-06-08 09:40:08.448 | warn | (26199) Cant send command please try againloadRooms
mihome-vacuum.0 | 2021-06-08 09:40:08.447 | debug | (26199) MIIO Receive Timeout&lt;&lt;&lt;
mihome-vacuum.0 | 2021-06-08 09:40:07.937 | debug | (26199) MIIO Receive Timeout&lt;&lt;&lt;
mihome-vacuum.0 | 2021-06-08 09:40:06.444 | debug | (26199) Message= {"id":116,"method":"get_room_mapping"}
mihome-vacuum.0 | 2021-06-08 09:40:06.443 | debug | (26199) command: loadRooms parent: rooms

And my last Problem is when i start to clean a Zone:

host.raspberrypi | 2021-06-08 09:48:14.613 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled
host.raspberrypi | 2021-06-08 09:48:14.612 | error | instance system.adapter.mihome-vacuum.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi | 2021-06-08 09:48:14.611 | error | Caught by controller[1]: MESSAGE TIMEOUT
host.raspberrypi | 2021-06-08 09:48:14.606 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected
mihome-vacuum.0 | 2021-06-08 09:48:14.015 | warn | (26378) Terminated (UNCAUGHT_EXCEPTION): Without reason
mihome-vacuum.0 | 2021-06-08 09:48:14.015 | debug | (26378) Plugin sentry destroyed
mihome-vacuum.0 | 2021-06-08 09:48:14.013 | info | (26378) terminating
mihome-vacuum.0 | 2021-06-08 09:48:13.841 | error | (26378) undefined
mihome-vacuum.0 | 2021-06-08 09:48:13.840 | error | (26378) unhandled promise rejection: undefined
mihome-vacuum.0 | 2021-06-08 09:48:13.839 | error | (26378) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2021-06-08 09:48:13.837 | debug | (26378) MIIO Receive Timeout&lt;&lt;&lt;
mihome-vacuum.0 | 2021-06-08 09:48:13.147 | debug | (26378) Message= {"id":32,"method":"get_map_v1"}
mihome-vacuum.0 | 2021-06-08 09:48:13.146 | debug | (26378) ERROR at setGetSoundVolume: MESSAGE TIMEOUT
mihome-vacuum.0 | 2021-06-08 09:48:13.145 | debug | (26378) MIIO Receive Timeout&lt;&lt;&lt;
mihome-vacuum.0 | 2021-06-08 09:48:11.835 | debug | (26378) Message= {"id":31,"method":"app_zoned_clean","params":[[27550,23000,30350,25000,1]]}
mihome-vacuum.0 | 2021-06-08 09:48:11.834 | info | (26378) trigger cleaning zone [27550,23000,30350,25000,1]

I see a lot of timeouts and "Time difference between Mihome Vacuum and ioBroker: -1623135896 sec"

Anyone an idee what i can do?

Thanks

**Comment by MeisterTR** [comment]
1: SIGSEGV seems like trouble with your sd card
2: runs in a timeout because the robot did not answer
3:  also robot did not answer (i take a look, because this should not run in errors)

**Comment by h3llh0und** [comment]
1. Ok, i will check my SD Card.
2. The Xiaomi App is working fine. No Problems there!?
3. see above

**Comment by h3llh0und** [comment]
So i did a reset to the S7 and changed some stuff in my router. Now the connection looks stable.

But i still cant load the Room List:

mihome-vacuum.0 | 2021-06-09 11:16:51.074 | debug | (2157) Time difference between Mihome Vacuum and ioBroker: -1623218096 sec
mihome-vacuum.0 | 2021-06-09 11:16:51.073 | debug | (2157) Receive &lt;&lt;&lt; Helo &lt;&lt;&lt; 213100200000000018cf43ce00002f53ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-06-09 11:16:46.277 | debug | (2157) MIIO RECIVE: {"id":678,"result":[],"exe_time":101}
mihome-vacuum.0 | 2021-06-09 11:16:46.157 | debug | (2157) Message= {"id":678,"method":"get_room_mapping"}
mihome-vacuum.0 | 2021-06-09 11:16:46.156 | debug | (2157) command: loadRooms parent: rooms

When i understand that right, the result is an Empty List. I used the S7 on 2 Floors and i have 2 Maps with Rooms. Is that a Problem?

**Comment by h3llh0und** [comment]
I just had a deeper look in the API. I just saw that you already use the MAPS_GET_MULTI_MAPS, and get the Map Information but dont do much with it:

2021-06-09 16:03:34.659 -&nbsp;debug: mihome-vacuum.0 (8199) MIIO RECIVE: {"id":8,"result":[74],"exe_time":100}
2021-06-09 16:03:34.661 -&nbsp;debug: mihome-vacuum.0 (8199) Message= {"id":10,"method":"get_multi_maps_list"}
2021-06-09 16:03:34.767 -&nbsp;debug: mihome-vacuum.0 (8199) MIIO RECIVE: {"id":9,"result":[{"begin":1623222023,"end":1623224558,"duration":2509,"area":31890000,"error":0,"complete":1,"start_type":3,"clean_type":3,"finish_reason":57,"dust_collection_status":0}],"exe_time":101}
2021-06-09 16:03:34.768 -&nbsp;debug: mihome-vacuum.0 (8199) Message= {"id":11,"method":"get_clean_record","params":[1623138102]}
2021-06-09 16:03:34.864 -&nbsp;debug: mihome-vacuum.0 (8199) MIIO RECIVE: {"id":10,"result":[{"max_multi_map":4,"max_bak_map":0,"multi_map_count":2,"map_info":[{"mapFlag":0,"add_time":1623138382,"length":11,"name":"Erdgeschoss","bak_maps":[]},{"mapFlag":1,"add_time":1622991483,"length":12,"name":"Obergeschoss","bak_maps":[]}]}],"exe_time":100}
2021-06-09 16:03:34.865 -&nbsp;debug: mihome-vacuum.0 (8199) States for 2 Map: [{"mapFlag":0,"add_time":1623138382,"length":11,"name":"Erdgeschoss","bak_maps":[]},{"mapFlag":1,"add_time":1622991483,"length":12,"name":"Obergeschoss","bak_maps":[]}]
2021-06-09 16:03:34.866 -&nbsp;debug: mihome-vacuum.0 (8199) States for Map: {"0":"Erdgeschoss","1":"Obergeschoss"}
2021-06-09 16:03:35.375 -&nbsp;debug: mihome-vacuum.0 (8199) Startup: getMultiMapsList Anser: true
2021-06-09 16:03:35.376 -&nbsp;debug: mihome-vacuum.0 (8199) Startup: Delete getMultiMapsList

But i dont see that there is a loading for one of the found maps?

**Comment by MeisterTR** [comment]
MAPS_GET_MULTI_MAPS is only for the displayed names in "actualmap". with the dropdown you can load the map, thats a diffrent command. Multi maps is not a problem. if you request the rooms from the robot, it shoud answer witch room contains in the actual loaded map.

**Comment by MeisterTR** [comment]
the connection from app to robot is only over cloud, the adapter only call local, thats two different ways you cant compare

**Comment by h3llh0und** [comment]
Ok, where can i find that dropdown? I dont see any?
If you need any more Input just let me know.

**Comment by MeisterTR** [comment]
![2021-06-10_03h54_59](https://user-images.githubusercontent.com/6328382/121452394-a29b4580-c99f-11eb-8109-9615cc44e3e4.png)

**Comment by h3llh0und** [comment]
![image](https://user-images.githubusercontent.com/6917818/121470563-b1452500-c9be-11eb-9c4e-f7f360a050a5.png)
The State is not existing :(

**Comment by h3llh0und** [comment]
I just reinstalled the adapter and then i saw the following in log at first start:

mihome-vacuum.0 | 2021-06-10 08:20:56.243 | warn | (14356) State "mihome-vacuum.0.cleanmap.actualMap" has no existing object, this might lead to an error in future versions

and 

mihome-vacuum.0 | 2021-06-10 08:20:58.073 | warn | (14356) This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2021-06-10 08:20:58.072 | warn | (14356) Object mihome-vacuum.0.cleanmap.actualMap is invalid: obj.type has to exist

**Comment by h3llh0und** [comment]
Now i have a really strange behavior.
I just wanted to create that State by myself and iobroker told me to that it already exists.
![image](https://user-images.githubusercontent.com/6917818/121501332-6d164c80-c9df-11eb-8bd8-01669b7d3093.png)

Then i tried to get it in an Script and i can read it and i got the right value.
![image](https://user-images.githubusercontent.com/6917818/121501819-dd24d280-c9df-11eb-8224-38416cc4d6c3.png)
I changed the map in App and Value changed!?

But still the Room List is returned empty :(
