### ISSUE TITLE
wrong type water.box 

### ISSUE THREAD

**Issue by zokkai** [iobroker-community-adapters/ioBroker.mihome-vacuum#316]
since couple of week logfile shows entry follwing entry:
State value to set for "mihome-vacuum.0.info.water_box" has to be type "text" but received type "boolean"

Adapter: Version 3.2.0
AdminVersion: 5.1.9 (also happens with Version 4.2.1)
 
![image](https://user-images.githubusercontent.com/49320831/121775228-9de4b600-cb86-11eb-869d-9ab4afc45d1a.png)

**Comment by MeisterTR** [comment]
delete state manually and restart adapter
