### ISSUE TITLE
Probleme bei der Installation

### ISSUE THREAD

**Issue by TMHEINE** [iobroker-community-adapters/ioBroker.mihome-vacuum#319]
Hallo,

leider habe ich Probleme bei der Installation:

########################################################
$ ./iobroker add mihome-vacuum  --host raspberrypi
host.raspberrypi install adapter mihome-vacuum
These apt-get packages were already installed: libcairo2-dev, libpango1.0-dev, libjpeg-dev, libgif-dev, librsvg2-dev
npm install --loglevel error --production (System call) in "/node_modules/iobroker.mihome-vacuum"
npm ERR! code EACCES
npm ERR! syscall mkdirnpm ERR! path /node_modules/iobroker.mihome-vacuum/node_modulesnpm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/node_modules/iobroker.mihome-vacuum/node_modules'
npm ERR!  { [Error: EACCES: permission denied, mkdir '/node_modules/iobroker.mihome-vacuum/node_modules']npm ERR!   stack:npm ERR!    'Error: EACCES: permission denied, mkdir \'/node_modules/iobroker.mihome-vacuum/node_modules\'',npm ERR!   errno: -13,npm ERR!   code: 'EACCES',npm ERR!   syscall: 'mkdir',npm ERR!   path: '/node_modules/iobroker.mihome-vacuum/node_modules' }npm ERR! npm ERR! The operation was rejected by your operating system.npm ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! npm ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-06-14T11_44_47_170Z-debug.log
Cannot install iobroker.mihome-vacuum: 243
ERROR: process exited with code 25
############################################################

Hab schon jede mengen foren durchsucht und alles möglich manuell versucht,. Ich komm jedoch nicht weiter...

Kann mir jemand helfen?

Danke 
Gruß Thomas

**Comment by MeisterTR** [comment]
EACCES. Fehler bei den Berechtigungen. bitte Installationsfixer nutzen da du dein iobroker falsch installiert hast
