### ISSUE TITLE
installation failed on fedora 33

### ISSUE THREAD

**Issue by MiRen76** [iobroker-community-adapters/ioBroker.mihome-vacuum#322]
I tried to install the adapter in iobroker running on fedora 33. Installation failed with the following error code:

$ ./iobroker add mihome-vacuum  --host linux
NPM version: 6.14.12npm install iobroker.mihome-vacuum@2.1.1 --loglevel error --prefix "/opt/iobroker" (System call)
host.linux install adapter mihome-vacuum
ERROR: /bin/sh: apt-get: Kommando nicht gefunden./bin/sh: apt: Kommando nicht gefunden.
ERROR: Cannot detect \"sudo -n yum -v\": sudo: Ein Passwort ist notwendigCannot detect dpkg: /bin/sh: dpkg: Kommando nicht gefunden.Uncaught Rejection: TypeError: Cannot read property 'error' of undefined    at Install.installAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:763:29)
ERROR: process exited with code 6

I don't know how to get this running. Could anybody help?

**Comment by Apollon77** [comment]
Which js-controller ist used?

**Comment by MiRen76** [comment]
I am running on
Node.js: v12.22.1
NPM: v6.14.12

**Comment by MiRen76** [comment]
Sorry, js-controller version is 3.2.16

**Comment by Apollon77** [comment]
Ok, this is a bug in js-controller and we will fix with the 3.3 release. For you as quick fix:

Edit /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js in Line 763 and change `adapter.log` to `console`
