### ISSUE TITLE
Adapter Crash wegen Netzwerkproblemen

### ISSUE THREAD

**Issue by saeft2003** [iobroker-community-adapters/ioBroker.mihome-vacuum#332]
Während dem Saugen crasht manchmal der Adapter. Vermutlich wegen Netzwerkproblemen.

Weitere Infos hier: https://forum.iobroker.net/topic/44077/test-adapter-mihome-vacuum-v3-1-6-next-generarition/235

**Comment by Apollon77** [comment]
Exception bitte auch hier posten!

**Comment by Apollon77** [comment]
Please test GitHub Version

**Comment by saeft2003** [comment]
aktuelle github version ist installiert adapter bleibt aber gelb auch nach 10min warten. Ich bin per snapshot zurück und adapter ist sofort grün geworden.

`mihome-vacuum.0	2021-06-30 07:30:42.607	warn	(16620) No Answer for DeviceModel use model from Config
mihome-vacuum.0	2021-06-30 07:30:42.607	warn	(16620) No Answer for DeviceModel use old one
mihome-vacuum.0	2021-06-30 07:30:42.606	warn	(16620) YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
mihome-vacuum.0	2021-06-30 07:29:25.066	error	(16033) Socket Close
mihome-vacuum.0	2021-06-30 07:19:47.012	warn	(16033) No Answer for DeviceModel use model from Config
mihome-vacuum.0	2021-06-30 07:19:47.012	warn	(16033) No Answer for DeviceModel use old one
mihome-vacuum.0	2021-06-30 07:19:47.011	warn	(16033) YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
mihome-vacuum.0	2021-06-30 07:19:41.065	error	(15781) Socket Close
mihome-vacuum.0	2021-06-30 07:16:02.260	warn	(15781) No Answer for DeviceModel use model from Config
mihome-vacuum.0	2021-06-30 07:16:02.260	warn	(15781) No Answer for DeviceModel use old one
mihome-vacuum.0	2021-06-30 07:16:02.259	warn	(15781) YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF`

**Comment by MeisterTR** [comment]
probier mal die 3.2.1 von git

**Comment by saeft2003** [comment]
Ok 3.2.1 ist installiert und Reinigung läuft. 

Ich habe immer wieder mal (auch bei Adapter Neustart) den Fehler "Socket closed" im log. Scheint nicht schlimmes zu sein, aber vorher hatte ich das nie.
