### ISSUE TITLE
keine Verbindung V3.2.0

### ISSUE THREAD

**Issue by an-klam** [iobroker-community-adapters/ioBroker.mihome-vacuum#333]
Ich nutze einen S5 und mit der V2.1.1 und mihome-vacuum.0.info.state stand dauerhaft auf Charging(8), daher habe ich die V3.2.0 installiert um zu sehen ob es dann geht.
Mit V3.2.0 konnte keine Karte geladen werden, der Adapter steht dauerhaft auf gelb (Verbunden= false), info.connection steht dauerhaft auf false und info.state steht weiterhin dauerhaft auf Charging(8).
Das Gerät reagiert aber trotzdem auf Befehle (RoomClean, etc).
Neustart der instanz und neu installation des Adapters und Instanz hat nicht geholfen.
Bin jetzt wieder auf der V2.1.1 und habe in den logs gesehen, dass der Adapter immer neu startet, wenn ich ein Befehl über X_send_command sende. Der Sauger führt den Befehl aber aus.

![grafik](https://user-images.githubusercontent.com/75025337/124226163-edc0f800-db08-11eb-8407-4b026c912ffb.png)

**Comment by MeisterTR** [comment]
bitte einmal die 3.2.1 von git installieren und den adapter vorher komplett löschen, wenn es dann nicht geht, bitte einen ausführlichen debug log

**Comment by an-klam** [comment]
Habe es nochmal gemacht wie beschrieben.
Die instanz war wieder dauerhaft gelb aber als ich dann abends den Log raussuchen wollte war alles wieder OK. weiß also leider nicht wie lange die auf gelb war.
Richtiger Status für den Sauger wird mir angezeigt.
Ich kann immer noch die Befehle senden und die werden auch ausgeführt.

In den Objekten werden mir die Räume nicht angezeigt. Load rooms bewirkt nichts.
Ich kenne die Raumnummern zwar von der V2.1.1 aber schön ist es trotzdem nicht.

**Comment by MeisterTR** [comment]
Hast du das Passwort für die cloud neu eingegeben? wenn keine räume da sind, ist auch keine Karte da

**Comment by an-klam** [comment]
Die Karte ist in den Objekten da und kann auch in die Visu eingebuden werden. (es ist auch definitiv die aktuelle Karte)
Nur die Räume fehlen in den Objekten.

**Comment by MeisterTR** [comment]
Bitte mal einen langen debuglog anhängen vom Start
