### ISSUE TITLE
Where I can finde the x/y postion of the vacuum?

### ISSUE THREAD

**Issue by radebold** [iobroker-community-adapters/ioBroker.mihome-vacuum#349]
In the docu I found "GoTo" aus command, but how I can find the correct position ?
Same for area cleaning, would be great to have this information in the adapter.

**Comment by Diginix** [comment]
Unfortunately only with trial and error.
Here you'll find some hints: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/blob/master/README.md#functions

If you enter e.g. values like 25000,25000 the robot should start to try to reach this point.
If you have the mihome app with robot map parallel open, you can see where this point will be in your map. Then you can adapt this coordinates to find a reachable point.

For me the coordinates math is this:
X +100 = 10 cm in East direction
Y +100 = 10 cm in North direction
But this depends on the orientation of the dock in your house.

**Comment by MeisterTR** [comment]
In  newer versin higher 3.1.x the coordinates are shown in the states when you start zone or point by app. There the cloud connection and map must be enabled

**Comment by Diginix** [comment]
My 1S doesn't have "go to point" in the app. But when I trigger it by adapter, I can use it in the app as well.
So, it is usually hidden but there. ;-)

**Comment by MeisterTR** [comment]
@Diginix it's time for a new one :)
