### ISSUE TITLE
Wrong Type

### ISSUE THREAD

**Issue by Speedbreaker12** [iobroker-community-adapters/ioBroker.mihome-vacuum#364]
info (10470) State value to set for "mihome-vacuum.0.info.water_box" has to be type "string" but received type "boolean"

**Comment by Apollon77** [comment]
Did you try to delete the object and restart adapter?

**Comment by Speedbreaker12** [comment]
> 
> 
> Did you try to delete the object and restart adapter?

Mist, du hast recht! Kleine Frage nebenbei, ist das auch so, wenn ich z.B. neu installiere und ein backup zurück spiele vor js-controller 3.3? Also werden die Typen im Backup gespeichert? Gibt es keine Möglichkeit das irgendwie bei JS Controller update batchmässig zu machen, sonst sehe ich in naher Zukunft viele verwirrte User. :D

**Comment by Apollon77** [comment]
na klar wird alles im Backuo gespeichert. Also am besten nach dem Fix ein neues Backlup machen :-)
