### ISSUE TITLE
deviceInfo.wifi_signal doesn't update from rockrobo.vacuum.v1

### ISSUE THREAD

**Issue by nicoh88** [iobroker-community-adapters/ioBroker.mihome-vacuum#369]
v3.2.2

`deviceInfo.wifi_signal` (old `info.wifi_signal`) doesn't update from `rockrobo.vacuum.v1`
`deviceInfo.wifi_signal` update works from `roborock.vacuum.s5`

**Comment by MeisterTR** [comment]
At some devices wifi signal is not supported anymore
