### ISSUE TITLE
Falscher Datentyp

### ISSUE THREAD

**Issue by Megawaldi** [iobroker-community-adapters/ioBroker.mihome-vacuum#370]
Ich hab da noch ne falschen Datentyp gefunden:
<html><body>

mihome-vacuum.0 | 2021-08-09 17:14:10.059 | info | State value to set for "mihome-vacuum.0.info.water_box" has to be type "text" but received type "boolean"
-- | -- | -- | --
mihome-vacuum.0 | 2021-08-09 17:14:09.590 | info | create states for water box

</body>
</html>

**Comment by ticaki** [comment]
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/316

**Comment by Megawaldi** [comment]
Thanks solved!
