### ISSUE TITLE
Cannot write file actualMap_0.png: mihome-vacuum.admin is not an object of type "meta"

### ISSUE THREAD

**Issue by allesgutewarweg** [iobroker-community-adapters/ioBroker.mihome-vacuum#379]
**Describe the bug**  
Map file cannot be written to disk.

**To Reproduce**  

Before the switch from my Roborock S5 to S7 the map worked without any issues. This is needed because S7 isn't able to talk over more than one subnet (https://github.com/rytilahti/python-miio/issues/422#issuecomment-455824152). So, in my opinion this is a MultiHost setup issue.

If somebody needs more information feel free to write a comment.

**Expected behavior**  
Map should be written to disk.

**Screenshots & Logfiles**  

> mihome-vacuum.0 | 2021-08-12 21:13:07.892 | debug | Mappointer_updated
> mihome-vacuum.0 | 2021-08-12 21:13:07.892 | debug | MIIO RECIVE: {"id":38,"result":["roboroommap%2F483002292%2F16"],"exe_time":100}
> mihome-vacuum.0 | 2021-08-12 21:13:07.351 | debug | Message= {"id":38,"method":"get_map_v1"}
> mihome-vacuum.0 | 2021-08-12 21:13:07.350 | debug | Get Mappointer while cleaning
> mihome-vacuum.0 | 2021-08-12 21:13:05.351 | error | Error by saving of the map
> mihome-vacuum.0 | 2021-08-12 21:13:05.350 | error | Cannot write file actualMap_0.png: mihome-vacuum.admin is not an object of type "meta"
> mihome-vacuum.0 | 2021-08-12 21:13:05.194 | debug | 28548
> mihome-vacuum.0 | 2021-08-12 21:13:04.905 | debug | update_Map got new time:1628795584
> mihome-vacuum.0 | 2021-08-12 21:13:04.905 | debug | update_Map got new expires:1628797384
> mihome-vacuum.0 | 2021-08-12 21:13:04.905 | debug | update_Map got new url:https://awsde0.fds.api.xiaomi.com/robomap/roboroommap/REDACTED/15?Expires=1628797384000&GalaxyAccessKeyId=REDACTED&Signature=REDACTED
> mihome-vacuum.0 | 2021-08-12 21:13:04.778 | debug | update_Map need new mapurl
> mihome-vacuum.0 | 2021-08-12 21:13:04.778 | debug | update_Map Mimap enabled
> mihome-vacuum.0 | 2021-08-12 21:13:04.778 | debug | Mappointer_updated

**Versions:**

-   Adapter version: 3.2.2
-   JS-Controller version: 3.3.15
-   Node version: v12.22.5
-   vacuum cleaner: Roborock S7

**Comment by MeisterTR** [comment]
was hat das Speichern der Karte mit dem subnet oder Multihost zu tun?

**Comment by allesgutewarweg** [comment]
Mein Roborock S5 arbeitet ohne MultiHost Installation fehlerfrei, daher meine Vermutung das es mit dem MultiHost zu tun haben muss. Auch weil ich keine anderen User gefunden habe die ähnliches berichten.

Ich kann natürlich auch auf dem Holzweg sein, daher habe ich das Problem hier einmal beschrieben.

**Comment by hwiedermann** [comment]
Halli hallo,

ich habe den Fehler auch, betreibe aber meines Wissens nach kein MultiHost Setup.
Mein iobroker ist im gleichen Netz wie der Sauger, trotzdem keine Karte...

Jemand ne Idee wie ich das noch weiter eingrenzen kann?

**Comment by allesgutewarweg** [comment]
Puh, dann wird es nun echt spannend da mein alte S5 im gleichen Setup ohne Probleme eine Karte zur Verfügung stellt. Somit können wir die eigentliche ioBroker Installation und das Linux-System darunter ausschließen. Das Problem muss meiner Meinung nach aus den Plugin und / oder Sauger kommen.

Ich habe leider keine Ahnung wie ich das Problem weiter debuggen kann, liefere aber gerne alle erforderlichen Informationen auf Anfrage hier ab.

**Comment by DutchmanNL** [comment]
> Puh, dann wird es nun echt spannend da mein alte S5 im gleichen Setup ohne Probleme eine Karte zur Verfügung stellt. Somit können wir die eigentliche ioBroker Installation und das Linux-System darunter ausschließen. Das Problem muss meiner Meinung nach aus den Plugin und / oder Sauger kommen.
> 
> Ich habe leider keine Ahnung wie ich das Problem weiter debuggen kann, liefere aber gerne alle erforderlichen Informationen auf Anfrage hier ab.

selbes problem hier kein multihost ;)

**Comment by RicardoHipp** [comment]
Hi, 

ich habe genau das gleiche Problem. Hat jemand schon ne Lösung dafür? Es hat alle bis vor kurzem ohne Probleme funktioniert. Seit einiger Zeit kann aber keine Karte mehr geladen werden.



mihome-vacuum.0 | 2021-09-12 11:09:09.810 | error | Error by saving of the map

mihome-vacuum.0 | 2021-09-12 11:09:09.808 | error | Cannot write file actualMap_0.png: mihome-vacuum.admin is not an object of type "meta"

**Comment by DutchmanNL** [comment]
@RicardoHipp karte und Räume werden bei mir nicht mehr eingelesen eventuell hat sich was an der api geändert @MeisterTR ?

**Comment by Apollon77** [comment]
@MeisterTR why you write in  mihome-vacuum.admin  ? thats wrong

**Comment by MeisterTR** [comment]
> @MeisterTR why you write in mihome-vacuum.admin ? thats wrong

Ich weiß. Weiß aber nicht wie ichs besser machen kann und über den admin hab ich den Zugriff von vis aus ...

**Comment by MeisterTR** [comment]
bei mir hängt die Karte zur Zeit auch gelegentlich, ein Neustart vom Adapter löst das Problem bei mir. (konnte dem aber noch nicht auf dem Grund gehen. da dafür mehrere Faktoren zusammenkommen müssen. Bin meistens früh morgen am PC da kann ich aber den robbi nicht laufen lassen und wenn ich ihn laufen lassen kann, hab ich keine Zeit am PC :) ) Ich habe selber 3 verschiedene Modelle und zig verschiedene Installationsvarianten zum Testen und es geht eigentlich überall. 

Für Die Karte müssen mehrere Faktoren zusammenspielen:

 = > Der Adapter schickt eine Kartenanfrage zum Robbi
 = > Dieser bestätigt das mit einem "Pointer" wo die Karte zu finden ist (Das macht er aber nur, wenn er die Karte erfolgreich 
        hochladen konnte ansonsten kommt ein "versuch es später nochmal")
= > Hat der Adapter erfolgreich einen Mappointer erhalten wird die Verschlüsselte Karte vom Server runtergeladen, decodiert 
       und gezeichnet

Da hier bei einem Abfrageintervall der Karte beim Saugen von 2 Sekunden des öfteren mal was daneben geht, sind im Bereich Kartenabfrage und Maperstellung alle Fehlermeldungen nur im Debug sichtbar 

zur Selbstkontrolle:
wenn keine Karte da ist:
= > Im Debug log Schauen was der Roboter auf die "get_map_v1" anfrage Antwortet (am besten log herunterladen und mit Suchfunktion) kommt nur "retry", kann der Roboter die Karte nicht hochladen, dies versucht der Adapter ein paar mal , dann gibt er für eine gewisse zeit auf.

= > Kommt anstelle von "retry" "roborock%F1XXXX" zurück ist die Karte erfolgreich auf dem Server, dann solle kurz darauf "update_Map...." kommen gefolgt von einer Zahl "25XXX" dies bedeutet das die Map erfolgreich decodiert und generiert wurde

= > Wenn kurz nach der Zahl keine Fehlemeldung im Debuglog auftaucht muss die Karte da sein :)

Gerne mal nachschauen oder mir den Log einfach per mail schicken, dann schau ich nach :)

**Comment by Apollon77** [comment]
> Ich weiß. Weiß aber nicht wie ichs besser machen kann und über den admin hab ich den Zugriff von vis aus ...

lege ein eigenes Meta Objekt an auf deinen Adapterinstanznamen, Beispiel zB sayit Adapter im io-package. Dann da rein.

Admi wird ggf bei einem adapter update überschrieben und nicht gebackupped

**Comment by Spampunk** [comment]
Gleiches hier, kein Multihost

`
<html>
<body>



2021-09-16 17:18:54.279 - info: mihome-vacuum.0 (31902) starting. Version 3.2.2 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.22.6, js-controller: 3.3.15
2021-09-16 17:18:54.446 - info: mihome-vacuum.0 (31902) IOT enabled, create state
2021-09-16 17:19:04.506 - warn: mihome-vacuum.0 (31902) YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
2021-09-16 17:19:04.508 - warn: mihome-vacuum.0 (31902) No Answer for DeviceModel use old one
2021-09-16 17:19:04.511 - warn: mihome-vacuum.0 (31902) No Answer for DeviceModel use model from Config
2021-09-16 17:19:04.555 - info: mihome-vacuum.0 (31902) select standard vacuum protocol....
2021-09-16 17:19:05.206 - info: mihome-vacuum.0 (31902) settest next timer: not available
2021-09-16 17:19:06.597 - info: mihome-vacuum.0 (31902) Map selected create states...
2021-09-16 17:20:58.846 - warn: mihome-vacuum.0 (31902) Error at history: MESSAGE TIMEOUT
2021-09-16 17:20:59.528 - info: mihome-vacuum.0 (31902) create state for carpet_mode
2021-09-16 17:21:01.846 - error: mihome-vacuum.0 (31902) Cannot write file actualMap_0.png: mihome-vacuum.admin is not an object of type "meta"
2021-09-16 17:21:01.848 - error: mihome-vacuum.0 (31902) Error by saving of the map
2021-09-16 17:21:19.572 - info: mihome-vacuum.0 (31902) change states from State control.fan_power
2021-09-16 17:21:19.587 - info: mihome-vacuum.0 (31902) create states for water box
2021-09-16 17:21:19.599 - info: mihome-vacuum.0 (31902) create states for water box mode
2021-09-16 17:21:19.607 - info: mihome-vacuum.0 (31902) create states for mop
2021-09-16 17:21:22.078 - error: mihome-vacuum.0 (31902) Cannot write file actualMap_0.png: mihome-vacuum.admin is not an object of type "meta"
2021-09-16 17:21:22.080 - error: mihome-vacuum.0 (31902) Error by saving of the map


</body>
</html>`

**Comment by Mouses007** [comment]
Ich habe den Fehler auch. Als base64 ist die Karte aber vorhanden und funktioniert problemlos in der VIS. Nur PNG funzt nicht.

**Comment by Spampunk** [comment]
> Ich habe den Fehler auch. Als base64 ist die Karte aber vorhanden und funktioniert problemlos in der VIS. Nur PNG funzt nicht.

Das war ein sehr guter Hinweis. die base64 wird unter dem DP 'mihome-vacuum.0.cleanmap.map64' abgelegt. In der VIS kann sie mittels Object Binding in ein Image-Widget (Quelle) eingefügt und dargestellt werden. Ein PNG wäre zwar eleganter und es wäre schön, im Protokoll die Fehlermeldung loszuwerden, aber als Workaround funktioniert es allemal.

**Comment by MeisterTR** [comment]
@allesgutewarweg versucht bitte die 3.3.x von git

**Comment by mule1972** [comment]
Sorry to say, but I am getting those error messages even with V3.3.1
`<html><body>


mihome-vacuum.0 | 2021-12-06 19:07:08.105 | error | Error by saving of the map
-- | -- | -- | --
mihome-vacuum.0 | 2021-12-06 19:07:08.102 | error | Cannot write file actualMap_0.png: mihome-vacuum.admin is not an object of type "meta"


</body>
</html>`

**Comment by mule1972** [comment]
I deleted the instances and adapter and installed it again. Now everything is working fine. Seems that one of the update of the adapter went wrong.
