### ISSUE TITLE
Roborock S5 Max, with Valetudo, without Xiaomi credientials?

### ISSUE THREAD

**Issue by thomas725** [iobroker-community-adapters/ioBroker.mihome-vacuum#381]
I do own a Roborock S5 Max which I setup Valetudo on right away when I got it, without first registering the device with Xiaomi.

This works fine on it's own and with the iobroker MQTT adapter, I was just wondering if I could get better IOBroker support (with more / easier to use features) by using this adapter instead.

But so far, I did not manage to connect my robot to this adapter, since I don't have a Xiaomi Account nor one of those cloud tokens since I (intentionally) never connected my robot with the Xiaomi cloud.

Is this supported? I see there is some Valetudo support here, but does this maybe only work for robots that where connected to Xiaomi in the past and only disconnected later by using Valetudo?

**Comment by MeisterTR** [comment]
you can read out the token from valetudo web interfadce but i dont know the api path. with that token you can connect with the adapter, but the map wont work

**Comment by thomas725** [comment]
I ran `find / -iname *token*` on the ssh terminal, which told me the path `/mnt/data/miio/device.token`.
I'm gonna try using the contents of that file with your iobroker adapter, let's see if that works.
