### ISSUE TITLE
Feature request: die Karte sollte per DP gedreht werden können

### ISSUE THREAD

**Issue by Spampunk** [iobroker-community-adapters/ioBroker.mihome-vacuum#404]
Das Drehen eines Widgets geht zwar auch per CSS, aber dann passen die Koordinaten nicht mehr und müssen in der VIS umständlich angepasst werden. Ich bin leider kein Coder und weiß nicht, ob man das innerhalb des Adapters eventuell eleganter hinbekommt. Aber es wäre ja vielleicht so umsetzbar, dass man einen Datenpunkt aufnimmt in dem man die Rotation bestimmen kann. 90°-Abstufungen per Auswahlliste wären wahrscheinlich ausreichend und sehr komfortabel.

**Comment by MeisterTR** [comment]
das ist nicht geplant, da der aufwand den Nutzen übersteigt
