### ISSUE TITLE
rockrobo.vacuum.v1 - no value in wifi_signal 

### ISSUE THREAD

**Issue by nicoh88** [iobroker-community-adapters/ioBroker.mihome-vacuum#406]
**Describe the bug**  
dBm will not be shown in `deviceInfo.wifi_signal` @ `rockrobo.vacuum.v1`
@ `rockrobo.vacuum.s5` works

**To Reproduce**  
Use every `rockrobo.vacuum.v1` 

**Screenshots & Logfiles**  
Debug: [mihome-vacuum.0.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/7215621/mihome-vacuum.0.txt)

![Bildschirmfoto 2021-09-23 um 09 15 57](https://user-images.githubusercontent.com/264264/134468255-cfb1794f-5a1a-4365-80a1-b60bd02ab1b8.png)

**Versions:**
-   Adapter version: `3.2.2`
-   JS-Controller version: `3.3.18`
-   Node version: `v12.22.5`
-   vacuum cleaner: `rockrobo.vacuum.v1`

**Reason:**
I think that the problem occurs since the datapoint `wifi_signal` moved from folder `info` to `deviceInfo`.

**Comment by MeisterTR** [comment]
V1 doesnt support wifisignal anymore.
