### ISSUE TITLE
[dreame.vacuum.p2041o] Support Xiaomi Vacuum Mop 2 Pro +

### ISSUE THREAD

**Issue by moritzps** [iobroker-community-adapters/ioBroker.mihome-vacuum#413]
**Infos zum Gerät:**

-   Marke: Xiamoi
-   Modell: Vacuum Mop 2 Pro + 3000Pa
-   Bezeichnung: dreame.vacuum.p2041o

**Einbindung ioBroker:**
Der Staubsauger wird nach Abrufen des Tokens erkannt und auch in den Objekten hinzugefügt:

<img width="1479" alt="dreame vacuum p2041o" src="https://user-images.githubusercontent.com/1819792/135580958-e36fc975-3fd3-4994-a8ed-a33b1fb881ba.png">

Ansonsten passiert aber nichts, auch ändern der Werte  von `clean_home` oder `pauseResume` hat keine Auswirkung.

**Weitere Infos**  
- Das Gerät wird in China auch als "Mi Robot Vacuum-Mop 1T" bezeichnet, siehe [hier](https://dontvacuum.me/robotinfo/firmwares/dreame.vacuum.p2041.html)
- Es ist in der Liste der [miot-enabled devices](https://github.com/rytilahti/python-miio/issues/627) enthalten
- [Hier](https://www.openhab.org/addons/bindings/miio/#dreame-vacuum-p2041o) gibt es eine Liste an Befehlen, ich kann aber nicht einschätzen, ob das hilft
- Dort gibt es auch eine Liste an **Identified manual actions for execution** auf der gleichen Seite in der [Tabelle Mi IO Devices](https://www.openhab.org/addons/bindings/miio/#mi-io-devices), wenn man nach `p2041o` sucht und dann in der Spalte "Remarks" schaut

**Comment by spoonie01** [comment]
Hi Mo,

bei mir das gleiche, alles soweit sauber eingebunden, Adapter ist grün, aber der Sauger startet nicht; - hast du es in der Zwischenzeit hinbekommen, dass du aus ioBroker den Sauger startest?

**Comment by figu328** [comment]
Hi Moritz,

bei mir wird der Roboter als ijai.vacuum.v3 (#705) angezeigt. Bist du dir sicher das es der gleiche ist?

LG
