### ISSUE TITLE
Seit 3.3.1 kein VIS vaccum Widget mehr vorhanden.

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.mihome-vacuum#419]
VIS Editor 1.4.5
mihome-vaccum 3.3.1
Admin 5.1.25
js-controller 3.3.18

Seit dem Update auf 3.3.1 ist das VIS Widget für den Staubsauger aus dem Editor verschwunden. Auch wird die Karte nicht mehr aufgebaut. Alle anderen Datenpunkte funktionieren. Verbindung zum Sauger ist OK. .......... könnte aber auch sein, das dass seit dem VIS Editor Update auf 1.4.5 schon der Fall ist. Mir ist es jetzt erst aufgefallen.

Aktueller Stand: 

![image](https://user-images.githubusercontent.com/44617472/137320457-03b33824-6fd7-4c9d-bd4a-b2b426cf693b.png)

Stand vor 3.3.1:

![image](https://user-images.githubusercontent.com/44617472/137321200-e0bccdfa-9fe0-4708-a032-50c3ef324984.png)

**Comment by grillmeister1** [comment]
Funktioniert in der 3.3.1 Version die Kartenumschaltung?

**Comment by speedmaster1** [comment]
Bei mir auch nicht mehr sichtbar!

**Comment by TheoThome** [comment]
Gibt es schon ein Update oder eine andere Möglichkeit das Widget wieder sichtbar zu bekommen?
