### ISSUE TITLE
Fan Power has value "100" less than min "101"

### ISSUE THREAD

**Issue by R3STEAS** [iobroker-community-adapters/ioBroker.mihome-vacuum#420]
**Describe the bug**  
mihome-vacuum.0.control.fan_power wird auf 100 gesetzt (kleiner als min. Value)

**To Reproduce**  
Ich starte den Staubsauger via Script:
```
setState("mihome-vacuum.0.control.fan_power", 104);
setState("mihome-vacuum.0.rooms.24001001164.roomFanPower", 104);
setState("mihome-vacuum.0.rooms.24001001164.roomClean", true);  
```

Dabei kommt folgender Log Eintrag:
`mihome-vacuum.0 | 2021-10-16 16:12:40.838 | warn | State value to set for "mihome-vacuum.0.control.fan_power" has value "100" less than min "101`
Und der Staubsauger geht nur in den "Balanced" Mode anstelle vom Max Mode.

Desweiteren kommt mehrmals am Tag der Logeintrag:
`mihome-vacuum.0 | 2021-10-16 16:13:26.769 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF`

**Logfiles**  
`
mihome-vacuum.0 | 2021-10-16 16:13:26.770 | warn | No Answer for DeviceModel use model from Config
-- | -- | -- | --
mihome-vacuum.0 | 2021-10-16 16:13:26.770 | warn | No Answer for DeviceModel use old one
mihome-vacuum.0 | 2021-10-16 16:13:26.769 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
host.smarthomepi | 2021-10-16 16:12:43.699 | error | instance system.adapter.mihome-vacuum.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
mihome-vacuum.0 | 2021-10-16 16:12:42.867 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
mihome-vacuum.0 | 2021-10-16 16:12:42.860 | error | Socket Close
mihome-vacuum.0 | 2021-10-16 16:12:42.836 | error | undefined
mihome-vacuum.0 | 2021-10-16 16:12:42.835 | error | unhandled promise rejection: undefined
mihome-vacuum.0 | 2021-10-16 16:12:42.833 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2021-10-16 16:12:42.800 | warn | Cant send command please try again "fan_power"
mihome-vacuum.0 | 2021-10-16 16:12:40.838 | warn | State value to set for "mihome-vacuum.0.control.fan_power" has value "100" less than min "101"`

**Versions:**

-   Adapter version: 3.3.1
-   JS-Controller version: 3.3.18
-   Node version: 14.18.1
-   vacuum cleaner: Roborock S6 Max (a10)

**Comment by dirkhe** [comment]
Wie sieht denn dein fan_power state aus, hast du 0-100% in deinen objekten? Wenn ja, brauchen wir die debug ausgabe beim Starten, dann scheint dein Modell ggf. nicht korrekt erkannt worden zu sein
