### ISSUE TITLE
mihome Vakuum Widget nicht mehr sichtbar

### ISSUE THREAD

**Issue by taucher17** [iobroker-community-adapters/ioBroker.mihome-vacuum#427]
<!-Hallo, 
seit dem letzten Update ist das Widget von mihome vakuum nicht mehr sichtbar

**Comment by AuTHeNTiiiX** [comment]
Bei mir leider auch nicht mehr bitte um Hilfe

**Comment by speedmaster1** [comment]
Bei auch nicht mehr vorhanden… war plötzlich weg!

**Comment by ericeggert** [comment]
bei mir leider auch :(

**Comment by kep42010** [comment]
Bei mir leider ebenfalls

**Comment by mar565** [comment]
Still an issue..

**Comment by mar565** [comment]
Are we the only ones having this issue?
Can someone confirm having the widget working on the latest release? Maybe this is a problem in our setup.

**Comment by ericeggert** [comment]
Still an issue..
