### ISSUE TITLE
HTTP error when getting token cookie{} => manual Login not helps....

### ISSUE THREAD

**Issue by florian1984** [iobroker-community-adapters/ioBroker.mihome-vacuum#438]
habe genau den Fehler .... die Email Bestätigung hilft leider nicht weiter ... der Fehler kommt immer noch.

![image](https://user-images.githubusercontent.com/12068197/139921296-2b298a25-acfb-4749-9b1e-bc6d4ac5187f.png)

_Originally posted by @florian1984 in https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/158#issuecomment-957943483_

**Comment by florian1984** [comment]
Just if someone else got this issue. The only way I get the Module to work again was to re-register @ xiaomi with new account. Xiaomi got some security system which tought someone attacking my account and show me on every login the 2end Auth Email Mask (not activated in settings!).  On the new Xiaomi account, the email confirmation only show up once.

**Comment by MurphysDr** [comment]
Can confirm this issue. Xiaomi support wasnt able to help me.
It also helps to create a second account and share the device with the newly created. login to iobroker with that. This way all settings are kept.
