### ISSUE TITLE
Roborock S6 MAXV "Helo Message Timeout"

### ISSUE THREAD

**Issue by boos87** [iobroker-community-adapters/ioBroker.mihome-vacuum#439]
Hello everybody,
i can´t connect my Roborock S6 MAXV with iobroker. There is a message "Helo Message Timeout" every 12 seconds.

![image](https://user-images.githubusercontent.com/93612837/139925117-1602124e-3247-45b1-9942-74ce609eadb5.png)

Can anybody help me, please???

**Versions:**

-   Adapter version: 3.3.1
-   JS-Controller version: 3.3.18
-   Node version: v10.17.0
-   vacuum cleaner: Roborock S6 MAXV

**Comment by boos87** [comment]
Is it really neccessary to set the ip address to 192.168.178.xx and why? The ip address of roborock is 192.168.0.27. So must i change the ip to 192.168.178.27?

**Comment by MeisterTR** [comment]
you have to set tihe ip to the right one, where your robot is reached. i dont know anything about aour network config but when you use a sub network you have to check that the udp messages can pass. in your screenshot iobroker cant reach the robot so the ip is wrong or the massages cant pass through your network

**Comment by boos87** [comment]
Thanks for your help. The ip is correct. I have no subnetwork. Roborock works with the App Xiaomi Home, but not over the iobroker (Windows). I have a lot of other devices and adapters, everything is working great. Only the Roborock S6 MAXV doesn´t work.

![image](https://user-images.githubusercontent.com/93612837/140464653-f1e2fdc1-8f4d-440b-9218-37f107cc9bf9.png)
![image](https://user-images.githubusercontent.com/93612837/140464502-5d312f57-6bd2-43de-aa57-52890f43bafc.png)

**Comment by boos87** [comment]
I have changed the system from windows (testsystem) to raspberry pi. Now, the adapter is working.
