### ISSUE TITLE
node.JS 14

### ISSUE THREAD

**Issue by backfisch88** [iobroker-community-adapters/ioBroker.mihome-vacuum#443]
Hallo 

jedes mal (schon öfter probiert), wenn ich auf nodejs 14 upgrade läuft danach der adapter nicht mehr.
Es läuft alles Reibungslos, bis es ein Befehl von IOBroker kommt... nach einigen Minuten ist er wieder verbunden (manchmal auch länger) und das Spiel geht von vorne los
mit node 12.X lief alles normal

auszug aus dem Log (bereits auf debug gestellt)

<html>
<body>

mihome-vacuum.0 | 2021-11-18 12:49:49.814 | info | Map selected create states...
-- | -- | -- | --
mihome-vacuum.0 | 2021-11-18 12:49:49.125 | info | settest next timer: not available
mihome-vacuum.0 | 2021-11-18 12:49:48.595 | info | select standard vacuum protocol....
mihome-vacuum.0 | 2021-11-18 12:49:48.569 | warn | No Answer for DeviceModel use model from Config
mihome-vacuum.0 | 2021-11-18 12:49:48.568 | warn | No Answer for DeviceModel use old one
mihome-vacuum.0 | 2021-11-18 12:49:48.567 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
mihome-vacuum.0 | 2021-11-18 12:49:38.508 | info | IOT enabled, create state
mihome-vacuum.0 | 2021-11-18 12:49:38.255 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.18.1, js-controller: 3.3.19
host.IOBroker | 2021-11-18 12:49:36.130 | info | instance system.adapter.mihome-vacuum.0 started with pid 6957
host.IOBroker | 2021-11-18 12:49:35.072 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled
host.IOBroker | 2021-11-18 12:49:35.071 | info | instance system.adapter.mihome-vacuum.0 terminated with code NaN ()
host.IOBroker | 2021-11-18 12:49:35.070 | warn | instance system.adapter.mihome-vacuum.0 terminated due to SIGABRT
host.IOBroker | 2021-11-18 12:49:35.063 | error | Caught by controller[0]: free(): invalid pointer
mihome-vacuum.0 | 2021-11-18 12:49:15.488 | info | trigger cleaning segment 17
mihome-vacuum.0 | 2021-11-18 12:49:00.086 | info | create state for carpet_mode
mihome-vacuum.0 | 2021-11-18 12:48:58.907 | info | create states for mop
mihome-vacuum.0 | 2021-11-18 12:48:58.904 | info | create states for water box
mihome-vacuum.0 | 2021-11-18 12:48:58.872 | info | change states from State control.fan_power
mihome-vacuum.0 | 2021-11-18 12:48:58.839 | info | Map selected create states..

</body>
</html>

**Comment by Apollon77** [comment]
Es ist bekannt das Pakete/Adapter die Binärteile enthalten bei einem Nodejs -Major Versionsupgrade neu gebaut werden müssen? 

Bitte Nodejs Upgrade Informationen beachten https://forum.iobroker.net/topic/44566/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten-2021-edition

**Comment by backfisch88** [comment]
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
iobroker fix


habe das alles gemacht und natürlich auf die rebuilds gewartet

**Comment by backfisch88** [comment]
zusätzlich jetzt noch
iobroker rebuild ioBroker.mihome-vacuum
iobroker rebuild ioBroker.mihome-vacuum --install

geht imer noch nicht :|

**Comment by Apollon77** [comment]
Bitte im Forum Thraed melden. mal ein "npm rebuld" im iobroker basis verzeichnis versucht?

PS: der "Iobroker fix" macht keinerlei rebuilds ...

**Comment by backfisch88** [comment]
> Bitte im Forum Thraed melden. mal ein "npm rebuld" im iobroker basis verzeichnis versucht?
> 
> PS: der "Iobroker fix" macht keinerlei rebuilds ...

ja wollte nur sagen was ich alles geamcht habe :)

ne rebuild im iob verzeichenis mache ich mal

**Comment by Apollon77** [comment]
> ne rebuild im iob verzeichenis mache ich mal
vorher backup sicherstellen!

**Comment by backfisch88** [comment]
> > ne rebuild im iob verzeichenis mache ich mal
> > vorher backup sicherstellen!

im Forum vom Adapter? oder von dem Node update?

**Comment by Apollon77** [comment]
AM besten im oben gelinkten Forum Thread?

**Comment by backfisch88** [comment]
> AM besten im oben gelinkten Forum Thread?

danke

**Comment by backfisch88** [comment]
Habe nochmal im Debug laufen lassen... jetzt kam mehr bei rum... vielleicht hilft das noch was... habe es zusätzlich im Forum gepostet

<html>
<body>


mihome-vacuum.0 | 2021-11-18 13:39:10.415 | debug | load Map creator... true
-- | -- | -- | --
mihome-vacuum.0 | 2021-11-18 13:39:10.257 | debug | Schedule restart: 0 0,1 * * *
mihome-vacuum.0 | 2021-11-18 13:39:10.172 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.18.1, js-controller: 3.3.19
mihome-vacuum.0 | 2021-11-18 13:39:09.903 | debug | Plugin sentry Initialize Plugin (enabled=true)
mihome-vacuum.0 | 2021-11-18 13:39:06.008 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
mihome-vacuum.0 | 2021-11-18 13:39:06.007 | debug | Plugin sentry destroyed
mihome-vacuum.0 | 2021-11-18 13:39:06.006 | info | terminating
mihome-vacuum.0 | 2021-11-18 13:39:06.005 | error | Socket Close
mihome-vacuum.0 | 2021-11-18 13:39:05.799 | error | undefined
mihome-vacuum.0 | 2021-11-18 13:39:05.798 | error | unhandled promise rejection: undefined
mihome-vacuum.0 | 2021-11-18 13:39:05.798 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2021-11-18 13:39:05.796 | debug | MIIO Receive Timeout for "app_segment_clean" <<<
mihome-vacuum.0 | 2021-11-18 13:39:04.078 | debug | Message= {"id":17,"method":"get_multi_maps_list"}
mihome-vacuum.0 | 2021-11-18 13:39:04.077 | debug | ERROR at setGetSoundVolume: MESSAGE TIMEOUT
mihome-vacuum.0 | 2021-11-18 13:39:04.076 | debug | MIIO Receive Timeout for "get_sound_volume" <<<
mihome-vacuum.0 | 2021-11-18 13:39:03.794 | debug | Message= {"id":16,"method":"app_segment_clean","params":[17]}
mihome-vacuum.0 | 2021-11-18 13:39:03.793 | info | trigger cleaning segment 17
mihome-vacuum.0 | 2021-11-18 13:39:03.792 | debug | start Cleaning: 18 MObj: {"command":"cleanSegments","message":"17","from":"system.adapter.mihome-vacuum.0","_id":62189570,"segments":[17],"channels":["mihome-vacuum.0.rooms.73001006380"]}
mihome-vacuum.0 | 2021-11-18 13:39:03.791 | debug | We are in onMessage:{"command":"cleanSegments","message":{"segments":[17],"channels":["mihome-vacuum.0.rooms.73001006380"]},"from":"system.adapter.mihome-vacuum.0","_id":62189570}
mihome-vacuum.0 | 2021-11-18 13:39:03.784 | debug | sendTo "cleanSegments" to system.adapter.mihome-vacuum.0 from system.adapter.mihome-vacuum.0
mihome-vacuum.0 | 2021-11-18 13:39:03.779 | debug | command: roomClean parent: 73001006380


</body>
</html>

**Comment by Apollon77** [comment]
But now it's an other error :-)

**Comment by backfisch88** [comment]
> But now it's an other error :-)

ja es ändert sich andauernd :D
wie gesagt das komische ist, dass das jedes mal erst kommt NACHDEM ich node 14 installiere. System unabhängig, da ich das auch schon aufm frischen System hatte :/
