### ISSUE TITLE
adapter node_modules (e.g. canvas) are removed after hours

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.mihome-vacuum#449]
Seit nodejs 14.x installiert der mihome-vacuum Adapter 3.3.1 nur folgende Dinge innerhalb seiner node_modules:

> /opt/iobroker/node_modules/iobroker.mihome-vacuum/node_modules/@iobroker/
> /opt/iobroker/node_modules/iobroker.mihome-vacuum/node_modules/@types/

Dadurch fehlt canvas usw. für die Karte. Mit einem "npm i" wird dann wirklich alles nachinstalliert. 
```
$ npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> canvas@2.8.0 install /opt/iobroker/node_modules/iobroker.mihome-vacuum/node_modules/canvas
> node-pre-gyp install --fallback-to-build

[canvas] Success: "/opt/iobroker/node_modules/iobroker.mihome-vacuum/node_modules/canvas/build/Release/canvas.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/glob-watcher/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 674 packages from 845 contributors and audited 685 packages in 37.555s

46 packages are looking for funding
  run `npm fund` for details

found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

npm audit fix:
```
$ npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/glob-watcher/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 4.768s

46 packages are looking for funding
  run `npm fund` for details

fixed 0 of 2 vulnerabilities in 685 scanned packages
  2 vulnerabilities required manual review and could not be updated
```
Nun sind statt 2 ganze 483 Ordner innerhalb der node_modules. U.a:
/opt/iobroker/node_modules/iobroker.mihome-vacuum/node_modules/canvas/

Leider verschwinden die ganzen zusätzliche Ordner aber nach Stunden wieder. Kein reboot, kein Adapter Restart o.ä.
Das führt dazu dass ich immer wenn ich den Sauger mit Karte verwenden will, ich erst "npm i" ausführen muss und danach den Adapter neu starten muss. Mit nodejs 12 gab es das Problem noch nicht.

**Comment by Apollon77** [comment]
Ich verstehe das Problem nicht. Idealerweise hat ein Adapter überhaupt nichts in seine, node_modules weil alles "eine ebene höher" liegt und von dort von mehreren Adaptern genutzt wurde. So funktioniert nodejs und npm regelt das und entscheidet was wo hin muss in Berücksichtigung aller Paket-Dependencies.

Manuelles nachinstallieren ist serhr kontraproduktiv. Besser wäre gewesen zu schauen was der Fehler ist wenn er es von "weiter iben" nutzen will. vllt braucht das dort ein rebuild?

**Comment by Diginix** [comment]
Das hatte ich alles schon probiert. Leider hilft das beim besagten Adapter nicht.
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt install -y nodejs
iobroker fix
npm rebuild

Im Forum haben andere auch Probleme mit dem mihome-vacuum Adapter unter nodejs 14:
https://forum.iobroker.net/topic/44566/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten-2021-edition/130?_=1638431626611

Und auch bei mir waren die ersten Probleme nach Update nur manuell mit rebuild vermeintlich gelöst:
https://forum.iobroker.net/topic/44566/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten-2021-edition/138?_=1638431626613

Aber nach nicht mal 24h verschwinden eben div. Ordner (Module) wieder.

**Comment by Apollon77** [comment]
"npm audit fix" ... Schlechte Idee!! Gibt keinen support wenn dadurch was kaputt geht ... nur so am rande.

ALso an sich sollten in einer sauberen Installation nie "einfach so" Dinge verschwinden. Dann muss man rausfinden wodurch. Da muss irgendtewas einen npm Befehl absetzen

**Comment by Diginix** [comment]
Das canvas unter /opt/iobroker/node_modules/ war auf jeden Fall noch aus nodejs12 Zeiten. Erst nach manuellem Löschen und dem npm i in /opt/iobroker/node_modules/ wurde es nun neu erzeugt.
Das ganze rebuild scheint bei bestehenden nodejs 12 Modulen nicht sauber alles neu zu bauen.
Was soll ich nun machen um das alles wieder sauber zu bekommen?
Komplett neu aufsetzen möchte ich ungern. Reicht iobroker fix und rebuild bzw npm i in /opt/iobroker/node_modules/ um ggf Dinge die durch "npm audit fix" verändert wurden glatt zu ziehen?

**Comment by Apollon77** [comment]
iobroker fix hat mit rebuild und so nichts zu tun. Das macht nur generelle Installationsthemen, rechte und sowas.

ein "npm rebuild" im Hauptverzeichnis sollte tun wenn der rest vom npm Baum in ordnung ist, kann aber auch auf nen fehler laufen und ggf dinge wegwerfen wo es denkt das die nicht nötig sind - wenn da sachen nicht sauber sind.

Von daher am ende Drei optionen:
* alles so lassen und punktuell fixen ... nervig aber sollte tun
* package.json im root ordner prüfen das da nur iobroker.* Pakete drin sind und alles andere wegwerfen, ggf diese die zuviel waren manuell im npm baum suchen und uninstallen und hoffen ... falls durch diese nummer adspter kaputt gehen diese manuell installieren .. viel aufwand für keine ahnung was rauskommt langfristig
* node_modules ordner löschen, js-controller manuell installieren und dann starten ... dann wird danach alles neu frisch (und hoffentlich sauber) installiert - das wäre die saubere "alles clean" variante ...

**Comment by Diginix** [comment]
Ok, bisher läuft erstmal alles nachdem ich canvas gelöscht hatte und es von npm rebuild neu mit node14 gebaut wurde.
Wenn es nach >24h dann immer noch eine Karte beim Sauger gibt, lasse ich erstmal alles so.
Falls weitere unklare Effekte auftreten, versuche ich ggf. mal deinen letzten Vorschlag.
Danke!
