### ISSUE TITLE
Tokenabruf für Deutschland

### ISSUE THREAD

**Issue by Basti189** [iobroker-community-adapters/ioBroker.mihome-vacuum#464]
Das Auslesen des Tokens ist auf dem deutschen Server nicht möglich.

HTTP-Error

**Comment by totocotonio** [comment]
Hi,
bei mir das gleiche. 

Die  Karte funktioniert nicht mehr.

Log:
`{"statusCode":401,"body":"{\"code\":0,\"message\":\"auth err\"}","headers":{"server":"Tengine","date":"Sat, 01 Jan 2022 12:54:22 GMT","content-type":"text/plain; charset=utf-8","content-length":"31","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"de.api.io.mi.com","port":443,"hostname":"de.api.io.mi.com","hash":null,"search":null,"query":null,"pathname":"/app/home/getmapfileurl","path":"/app/home/getmapfileurl","href":"https://de.api.io.mi.com/app/home/getmapfileurl"},"method":"POST","headers":{"Content-Type":"application/x-www-form-urlencoded","x-xiaomi-protocal-flag-cli":"PROTOCAL-HTTP2","User-Agent":"Android-7.1.1-1.0.0-ONEPLUS A3010-136-9D28921C354D7 APP/xiaomi.smarthome APPV/62830","Cookie":"userId=1903560925; yetAnotherServiceToken=*************=; serviceToken=*********************************=; locale=de_DE; timezone=GMT%2B01%3A00; is_daylight=1; dst_offset=3600000; channel=MI_APP_STORE","accept-encoding":"gzip, deflate","content-length":147}}}`

**Comment by denjo1982** [comment]
ja habe auch das gleiche problem "http error"

**Comment by Flyor** [comment]
Same here.

**Comment by EvilEls** [comment]
**+1**

```mihome-vacuum.0	info	starting Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.18.2, js-controller: 3.3.22```


```mihome-vacuum.0	warn	{
	"statusCode": 401,
	"body": "{\"code\":0,\"message\":\"auth err\"}",
	"headers": {
		"server": "Tengine",
		"date": "Sat, 01 Jan 2022 14:12:30 GMT",
		"content-type": "text/plain; charset=utf-8",
		"content-length": "31",
		"connection": "close"
	},
	"request": {
		"uri": {
			"protocol": "https:",
			"slashes": true,
			"auth": null,
			"host": "de.api.io.mi.com",
			"port": 443,
			"hostname": "de.api.io.mi.com",
			"hash": null,
			"search": null,
			"query": null,
			"pathname": "/app/home/getmapfileurl",
			"path": "/app/home/getmapfileurl",
			"href": "https://de.api.io.mi.com/app/home/getmapfileurl"
		},
		"method": "POST",
		"headers": {
			"Content-Type": "application/x-www-form-urlencoded",
			"x-xiaomi-protocal-flag-cli": "PROTOCAL-HTTP2",
			"User-Agent": "Android-7.1.1-1.0.0-ONEPLUS A3010-136-9D28921C354D7 APP/xiaomi.smarthome APPV/62830",
			"Cookie": "userId=xxx; yetAnotherServiceToken=xxx; serviceToken=xxx; locale=de_DE; timezone=GMT%2B01%3A00; is_daylight=1; dst_offset=3600000; channel=MI_APP_STORE",
			"accept-encoding": "gzip, deflate",
			"content-length": 146
		}
	}
}```

Android app still can get the map.
Unfortunately I cannot capture the apps map request, atm.

**Comment by Siggi0904** [comment]
Also beim Token-Extractor hat man wohl ermittelt, dass von plain text auf RC4 auf den EU Servern umgestellt wurde.
Siehe https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/50#issuecomment-1003546251

Demnach muss der Abruf komplett umgebaut werden.

**Comment by canim60** [comment]
abwarten ist angesagt?

**Comment by loemic87** [comment]
+1 habe das gleiche Problem.

**Comment by ddsak** [comment]
Same here... :-(

**Comment by fabiankrauss** [comment]
same here - so lets wait

**Comment by Apollon77** [comment]
Guys ... a "thumbs up" in first thread is completely sufgicient to state "me too"

**Comment by dirkhe** [comment]
@MeisterTR do you work on it or should I try it? I want to avoid double work.

**Comment by MeisterTR** [comment]
@dirke du kannst es gerne versuchen. Die rc4 Variante hab ich auf git nur im Py Code gefunden, habs mir 2 Stunden angeschaut und bin nix weiter gekommen obwohl es codetechnisch eigentlich nicht viel ist...

**Comment by sipiyou** [comment]
Schau mal hier rein, ich hab eben die Änderungen bei mir im PHP-Code ergänzt. Ist an sich keine große Sache.

https://github.com/sipiyou/edomi-roboroc/blob/main/php/miCloud.php

Die relevanten Sachen sind mit if ($this->useRC4), wenn du dich dadran orientierst sollte das ziemlich klar sein

**Comment by dirkhe** [comment]
Dank dir schon mal dafür, ich hatte mir das gestern auch schon grob bei PiotrMachowski angeschaut. Ich baue mir gleich eine test Umgebung auf, weil meiner geht aktuell noch...

**Comment by Xenon-s** [comment]
Bei mir läuft er aufmal wieder

**Comment by hoepps2802** [comment]
Läuft bei mir auch wieder, ohne das was gemacht werden musste.
Hatte bei mir im Adapter nur zeitweise, Map ausgeschaltet.

**Comment by Xenon-s** [comment]
Habe in der iobroker Facebook Gruppe mal einen Beitrag zu dem Thema erstellt. Da sammel ich mal den Status von den Leuten und berichte dann wieder hier

**Comment by dirkhe** [comment]
Mir ist heute morgen der laptop abgeschmiert, wahrscheinlich SSD defekt. Bin dadurch erst mal nicht in der Lage etwas umzuprogrammieren.
Ich vermute mal, dass die vlt doch die alte auth wieder zulassen, wir sollten aber trozdem schon mal gerüstet sein

**Comment by Strobelix80** [comment]
Es geht wieder!

**Comment by Siggi0904** [comment]
Wenn ihr das anpasst, bitte im mihome-Repo.
Denn das ist ja die zentrale Repo, die den Zugriff organisiert und die viele andere Projekte auch nutzen.
Danke.

**Comment by MeisterTR** [comment]
#470
