### ISSUE TITLE
StatusCode 401

### ISSUE THREAD

**Issue by Martin-Stein** [iobroker-community-adapters/ioBroker.mihome-vacuum#469]
Hi,
After updating the latest firmware, my adapter receives a warning with StatusCode 401.
Find attached the logfile.

Thanks & kind regards,

Martin Stein

[Roborock.log](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/7803202/Roborock.log)
g

**Comment by Michaelnorge** [comment]
Same here, using Roborock 5. 
ioBroker stopped the adapter because of to much crashes today.

**Comment by MeisterTR** [comment]
#470
