### ISSUE TITLE
Carpet Mode for S6 vmax not showing value in iobroker (null)

### ISSUE THREAD

**Issue by sysadmin0815** [iobroker-community-adapters/ioBroker.mihome-vacuum#477]
**Describe the bug**  
mihome-vacuum.0.control.carpet_mode data point state is not updated when changed it in the xiaomi app.
if i change the data point manually (true or false), it works and the app shows disabled or enabled.
I reintalled the adapter and cleaned up the objects. after I added my S6 vmax again, the state stays on null when I change it in the app. Changing the value manually on iob to true or false works and the app recognizes the changes and shows carpet mode enabled.
getting the value/state from the roborock to iob is not working right now.

**Debug Log**  

<html>
<body>

mihome-vacuum.0 | 2022-01-10 13:54:05.864 | warn | Object of state "mihome-vacuum.0.cleanmap.actualMap" is missing the required property "common.type"
-- | -- | -- | --
mihome-vacuum.0 | 2022-01-10 13:54:05.844 | info | create states for mop
mihome-vacuum.0 | 2022-01-10 13:54:05.838 | info | create states for water box mode
mihome-vacuum.0 | 2022-01-10 13:54:05.832 | info | create states for water box
mihome-vacuum.0 | 2022-01-10 13:54:05.807 | info | change states from State control.fan_power
mihome-vacuum.0 | 2022-01-10 13:53:03.014 | info | Map selected create states...
mihome-vacuum.0 | 2022-01-10 13:53:02.775 | info | settest next timer: not available
mihome-vacuum.0 | 2022-01-10 13:53:02.214 | info | select standard vacuum protocol....
mihome-vacuum.0 | 2022-01-10 13:53:02.195 | warn | No Answer for DeviceModel use model from Config
mihome-vacuum.0 | 2022-01-10 13:53:02.195 | warn | No Answer for DeviceModel use old one
mihome-vacuum.0 | 2022-01-10 13:53:02.194 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
mihome-vacuum.0 | 2022-01-10 13:52:52.083 | info | IOT enabled, create state
mihome-vacuum.0 | 2022-01-10 13:52:51.987 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.18.2, js-controller: 3.3.22
mihome-vacuum.0 | 2022-01-10 13:52:47.165 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2022-01-10 13:52:47.162 | info | terminating
mihome-vacuum.0 | 2022-01-10 13:52:47.162 | error | Socket Close
mihome-vacuum.0 | 2022-01-10 13:52:47.157 | info | Got terminate signal TERMINATE_YOURSELF
mihome-vacuum.0 | 2022-01-10 13:51:10.764 | info | create state for carpet_mode
mihome-vacuum.0 | 2022-01-10 13:51:10.522 | warn | Object of state "mihome-vacuum.0.cleanmap.actualMap" is missing the required property "common.type"
mihome-vacuum.0 | 2022-01-10 13:51:10.514 | info | create states for mop
mihome-vacuum.0 | 2022-01-10 13:51:10.512 | info | create states for water box mode
mihome-vacuum.0 | 2022-01-10 13:51:10.509 | info | create states for water box
mihome-vacuum.0 | 2022-01-10 13:51:10.496 | info | change states from State control.fan_power
mihome-vacuum.0 | 2022-01-10 13:51:10.352 | info | Map selected create states...
mihome-vacuum.0 | 2022-01-10 13:51:09.748 | info | settest next timer: not available
mihome-vacuum.0 | 2022-01-10 13:51:09.197 | info | select standard vacuum protocol....
mihome-vacuum.0 | 2022-01-10 13:51:09.080 | info | IOT enabled, create state
mihome-vacuum.0 | 2022-01-10 13:51:08.615 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.18.2, js-controller: 3.3.22

</body>
</html>

**To Reproduce**  
Set Value for object mihome-vacuum.0.control.carpet_mode to true or false in iob.
Set Carpet Mode enabled or disabled in the Xiaomi App.
No changes on IOB object mihome-vacuum.0.control.carpet_mode. 

**Expected behavior**  
Get the state for mihome-vacuum.0.control.carpet_mode from the roborock and display it in the objects as true or false.

**Screenshots & Logfiles**  
If screenshots are required, I can add them. but it is just true or false.

**Versions:**

-   Adapter version: 3.3.1
-   JS-Controller version: 3.3.22
-   Node version: 14.18.2
-   vacuum cleaner: roborock.vacuum.a10 (S6 MaxV)

**Comment by sysadmin0815** [comment]
Maybe this helps.
when i send the command **get_carpet_mode** with **X_send_command** i get this response when carpet mode is enabled in the xiaomi app:
`[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]`
when carpet mode is disabled i get this:
`[{"enable":0,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]`

**Comment by sysadmin0815** [comment]
it is getting the enabled:1 from the robo (at least in the logs):

<html>
<body>


**mihome-vacuum.0 | 2022-01-14 11:45:32.657 | debug | MIIO RECIVE: {"result":[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}],"id":32}**
mihome-vacuum.0 | 2022-01-14 11:45:32.651 | debug | Message= {"id":32,"method":"get_carpet_mode"}
mihome-vacuum.0 | 2022-01-14 11:45:32.651 | info | create state for carpet_mode
mihome-vacuum.0 | 2022-01-14 11:45:32.650 | debug | MIIO RECIVE: {"result":[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}],"id":31}
mihome-vacuum.0 | 2022-01-14 11:45:32.640 | info | settest next timer: not available
mihome-vacuum.0 | 2022-01-14 11:45:32.616 | debug | Message= {"id":31,"method":"get_carpet_mode"}
mihome-vacuum.0 | 2022-01-14 11:45:32.616 | debug | Mappointer_updated


</body>
</html>

but in the objects it's null.
it that a bug/issue or is it currently not working in the adapter?

![image](https://user-images.githubusercontent.com/81157346/149504983-23bf805d-5ecb-43d1-9bad-bcf98dade872.png)


changing the value manually to true or false works and it send the command to the robo, but the adapter is not showing any value.

**Comment by dirkhe** [comment]
Ok, I will check this later again

**Comment by dirkhe** [comment]
found error and fixed it in 3.3.2, currently only on github.
