### ISSUE TITLE
Roborock S7 Wischen Gründlich

### ISSUE THREAD

**Issue by CyrixTheDragon** [iobroker-community-adapters/ioBroker.mihome-vacuum#479]
Würde gerne den Wischmodus Gründlich über den Adapter aktivieren/deaktivieren können falls möglich.

Habe einen Roborock S7

**Comment by fefi-byte** [comment]
1+
Könnte auch testen

**Comment by dirkhe** [comment]
Ich denke dass ist mit https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/670 erfüllt und in der 3.7.0 drin? Bitte bestätigen und dann ggf schließen

**Comment by RkcCorian** [comment]
@Dirkhe: Ahhh... Du meinst mit ```mihome-vacuum.0.control.mop_mode```?! Hab's gerade mit der 3.7.0 ausprobiert, Anzeige was über die App eingestellt wurde klappt, aber steuern über den Adapter geht leider nicht.
![image](https://user-images.githubusercontent.com/79741077/198705848-4fbf3fd0-fe2b-4ad9-8941-d27d08faf7fb.png)

**Comment by RkcCorian** [comment]
@dirkhe : Folgefrage: Kann ich den mop_mode Kommandieren (für die Queue, wo ich ja Saug- und Wischmodus mit der 3.7.0 auch einstellen kann)? Das bräuchte man vermutlich auch.

**Comment by dirkhe** [comment]
Das das nicht geht, liegt daran, dass ich einen eintrag in den stockcommands vergessen habe, fixe uch morgen, nehme das dann auch mit in clean zone und clean segment mit auf

**Comment by RkcCorian** [comment]
Top!!

**Comment by dirkhe** [comment]
gefixt in 3.8.0 sollte jetzt auch pro Raum auftauchen (könnte aber sein, dass das nur passiert, wenn der raum neu angelegt wird.)

**Comment by RkcCorian** [comment]
@dirkhe : ```mihome-vacuum.0.control.mop_mode``` klappt. Bzgl. den Räumen... wie kann ich neu anlegen? DPs löschen und Adapter neu starten, damit die neu angelegt werden?

**Comment by RkcCorian** [comment]
@dirkhe: Folgender Code hat nicht geklappt (um den Mop-Mode auch hier zu testen)...
```
sendTo("mihome-vacuum.0", "cleanSegments", { rooms:22, fanSpeed:105, waterBoxMode:203, mapMode:303}, async function (result) {
    console.log(result);
  });
console.debug("mihome-vacuum.0: " + "");
```

**Comment by RkcCorian** [comment]
@dirkhe : Folgender Code hat ebenfalls geklappt > OK

```
sendTo("mihome-vacuum.0", "cleanSegments", { rooms:22, fanSpeed:105, waterBoxMode:203, mopMode:303}, async function (result) {
    console.log(result);
  });
console.debug("mihome-vacuum.0: " + "");
```

**Comment by RkcCorian** [comment]
Damit fehlt mir zum Glück nur noch https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/679

**Comment by dirkhe** [comment]
Wenn du die dp löscht, könnte es sein, das die enum weg sind, bin mir nicht ganz sicher, weil die verknüpfung bri den enums und nicht beim dp gespeichert wird. Du könntest abef mal versucgen, auf loudrooms zu klcken

**Comment by RkcCorian** [comment]
@dirkhe : Hab mal einen Raum gelöscht und ```mihome-vacuum.0.rooms.loadRooms``` auf True gesetzt, der Raum wurde aber nicht neu angelegt

**Comment by RkcCorian** [comment]
@dirkhe : Adapter Neustart hat den Raum wieder gebracht. Hinweis: Du hast noch einen Schreibfehler drin. Wird als ```mihome-vacuum.0.rooms.937001046414.roomMopode``` angelegt, da fehlt ein M, d.h. roomMop**M**ode

**Comment by dirkhe** [comment]
Ups, den kommentar habe ich völlig übersehen...

**Comment by RkcCorian** [comment]
> 

name vom DP im Raum für MopMode ist gefixed 👍
