### ISSUE TITLE
Viomi V3 v.13

### ISSUE THREAD

**Issue by Prof-Moriarty-x** [iobroker-community-adapters/ioBroker.mihome-vacuum#481]
**Infos zum Gerät:**

-   Viomi
-   V3
-   viomi.vacuum.v13

**Wichtig**  
Das Einbinden neuer Geräte ist aufwending und erfordert viel Recherche,
hierfür fehlt mir die Zeit. Also bitte sucht selbst auf git ob und wie der Sauger eingebunden werden kann,
und verlinkt die stellen

**Comment by MeisterTR** [comment]
was sagt der Adapterlog probiermal von git
