### ISSUE TITLE
Carpet Mode for S6 vmax not working as it should

### ISSUE THREAD

**Issue by sysadmin0815** [iobroker-community-adapters/ioBroker.mihome-vacuum#496]
**Describe the bug**  
Sorry, it's me again. 
First, thanks for the quick fix for my previous issues with carpet mode. We use it really often...
and btw you can answer in German if you like.

currently, if i set `carpet_mode` in iobroker to `true`, the robo vacuums always with max power. not only on carpets.
when I set the carpet mode in the xiaomi app, it works as expected.
**i found the following differenece:**
custom command: get_carpet_mode
message when set in xiaomi app: `[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]`
message when set in iobroker: `[{"enable":1,"current_integral":0,"current_high":0,"current_low":0,"stall_time":0}]`

![image](https://user-images.githubusercontent.com/81157346/150943763-8e6dd83d-7dfe-4582-9d99-29754b417c2c.png)

**To Reproduce**  

set carpet mode enabled in xiaomi app => robo changes fan power on carpets only.
set carpet mode enabled in iobroker (true) => robo always uses max power, not only on carpets.

important: the object fan_power **does not** change. it stays on the same level.
![image](https://user-images.githubusercontent.com/81157346/150944331-c31f9d97-1aa8-415d-8427-befe27f3123f.png)

**Expected behavior**  
when I set the carpet mode the robo should only vacuum with max power on carpets, not all the time.

**Screenshots & Logfiles**  
see above.

Is it possible to fix this or is it related to xiaomi only?

**Versions:**

-   Adapter version: 3.3.3
-   JS-Controller version: 3.3.22
-   Node version: 14.18.2
-   vacuum cleaner: roborock.vacuum.a10 (S6 MaxV)

**Comment by dirkhe** [comment]
Wie startest du denn deinen Sauger? Manuell mit start?
So wie ich das akzuell sehe, wird per set_carpet_mode auf gerufen mit enable 0 oder enable 1. DIe Frage wäre zu kären, ob man die anderen Werte mit senden kann und was sie bedeuten. 
Da komme ich im  Moment nicht zu. Kann man dazu in der app auch was einstellen?
probiere doch mal, set_carpet_mode zu senden, indem du mit den Parametern spielst. Vlt. findest du dazu j auch was im Internet?

**Comment by sysadmin0815** [comment]
Servus,
ich teste das mal durch und geb dir feedback.

Mein aktuelles problem ist eher, den command zu bauen.
im log lese ich folgendes mit:
![image](https://user-images.githubusercontent.com/81157346/151794652-186c7e5d-4dd8-475c-81a0-74568329ba9c.png)

laut doku übergebe ich folgendes json:
```
{
  "method": "set_carpet_mode",
  "params": [
    {
      "enable": 0,
      "current_integral": 450
    }
  ]
}
```
ich hab ein paar varianten durchprobiert, aber das log schaut komisch aus mit den \ und 2 mal method im json.
sollt etwas anders aussehen.
weißt du wie die syntax im X_send_command sein sollte?

wenn ich `carpet_mode` von **true** auf **false** setzte, steht folgendes im log:
![image](https://user-images.githubusercontent.com/81157346/151795337-0219aac4-3a51-4f58-ac88-c7f8d0b3394e.png)
sieht besser aus als meine versuche...

**Comment by sysadmin0815** [comment]
ok, ich glaub ich habs.
Setzte Carpet_Mode:
`mihome-vacuum.0.control.X_send_command`
`set_carpet_mode;[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]`

Deaktiviere Carpet_Mode
`mihome-vacuum.0.control.X_send_command`
`set_carpet_mode;[{"enable":0}]`

Workaround wurde also gefunden :)

Meinen Tests nach dürften die Werte angeben, wann der Roborock erkennt, dass es sich um einen Teppich handelt. Dürfte irgendwie mit dem Drehmoment der Hauptbürste zu tun haben. Bin mir aber noch nicht ganz sicher...
Würde aber das Problem erklären, wenn alle Werte auf 0 gesetzt sind.
message when set in xiaomi app: `[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]`
message when set in iobroker: `[{"enable":1,"current_integral":0,"current_high":0,"current_low":0,"stall_time":0}]`
message when set in iobroker with cutom command: `[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]`

Nachdem ich nur einen Roborock (S6 maxV) habe, kann ich leider nicht sagen, ob auch andere Modelle betroffen sind oder ob dieser Command auch bei anderen Modellen funktioniert. 
Firmwareupdate von Xiaomi gabs in letzter zeit keines. 

Also man kann die Werte übergeben. Anscheinend macht die Xiaomi App das jedes mal, wenn die Teppichverstärkung aktiviert wird.

In der App habe ich folgende Einstellungen zur Auswahl:
**Robo-Einstellungen:**
![photo_2022-01-31_16-35-40 (2)_LI](https://user-images.githubusercontent.com/81157346/151824869-336ac641-8f02-4e66-8207-71c68fa6036b.jpg)


**Reaktive-AI-Einstellungen:**(Optional, unwichtig für dieses Issue)
![photo_2022-01-31_16-35-40](https://user-images.githubusercontent.com/81157346/151824692-e96bd97e-bb0d-4cea-a5bc-defb11ffa7b5.jpg)

Ich werde das jetzt mal mit dem custom command umsetzen.
Falls du noch Logs willst oder sonst irgendwelche Infos, einfach melden. Kann ich dir zukommen lassen.
Ansonten kann man das Issue schließen. Ist für mich erledigt.

Danke für die Unterstützung.

**Comment by dirkhe** [comment]
Ich habe das jetzt mal erweitert. Sobald der Robbi seine Parameter bei get_carpet_mode sendet und der enabled ist, merkt er sich die und sendet die beim nächsten mal genauso wieder mit. Es sieht aber so aus, dass die Werte aktuell fix sind, daher habe ich die auch als Defaultwerte hinterlegt
