### ISSUE TITLE
uncaught exception: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.mihome-vacuum#497]
v3.3.4 ist bei mir heute abgestürzt als ich über den mihome-vacuum.0.rooms.***.roomClean Button einen weiteren Raum zum Queue hinzufügen wollte während er bereits einen saugte.
Loglevel der Instanz ist warn, daher nur das aus dem Log:

> 2022-01-27 14:10:50.738 - error: mihome-vacuum.0 (1148) uncaught exception: Cannot read property 'body' of undefined
> 2022-01-27 14:10:50.748 - error: mihome-vacuum.0 (1148) TypeError: Cannot read property 'body' of undefined
> at Request._callback (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/maphelper.js:454:68)
> at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
> at Request.emit (events.js:400:28)
> at Request.emit (domain.js:475:12)
> at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
> at ClientRequest.emit (events.js:412:35)
> at ClientRequest.emit (domain.js:475:12)
> at TLSSocket.socketErrorListener (_http_client.js:475:9)
> at TLSSocket.emit (events.js:400:28)
> at TLSSocket.emit (domain.js:475:12)
> 2022-01-27 14:10:50.749 - error: mihome-vacuum.0 (1148) Cannot read property 'body' of undefined
> 2022-01-27 14:10:50.763 - error: mihome-vacuum.0 (1148) Socket Close
> 2022-01-27 14:10:50.765 - warn: mihome-vacuum.0 (1148) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 2022-01-27 14:10:51.364 - error: host.iobroker Caught by controller[0]: TypeError: Cannot read property 'body' of undefined
> 2022-01-27 14:10:51.371 - error: host.iobroker Caught by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/maphelper.js:454:68)
> 2022-01-27 14:10:51.371 - error: host.iobroker Caught by controller[0]: at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at Request.emit (events.js:400:28)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at Request.emit (domain.js:475:12)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at ClientRequest.emit (events.js:412:35)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at ClientRequest.emit (domain.js:475:12)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at TLSSocket.socketErrorListener (_http_client.js:475:9)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at TLSSocket.emit (events.js:400:28)
> 2022-01-27 14:10:51.372 - error: host.iobroker Caught by controller[0]: at TLSSocket.emit (domain.js:475:12)
> 2022-01-27 14:10:51.372 - error: host.iobroker instance system.adapter.mihome-vacuum.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

@dirkhe

**Comment by dirkhe** [comment]
I committed a fix, that the adapter no longer crashes here, but this solved not the root cause, the crashed connection. Will be part of next version

**Comment by Diginix** [comment]
Gestern hatte ich den selben Fehler beim ersten Start einer Raumreinigung und heute ist der Adapter einfach so mit diesem Fehler abgestürzt während der Sauger im Dock stand und das Netzwerk vollkommen unauffällig war.

**Comment by dirkhe** [comment]
Hast du denn die aktuelle Version vom master installiert? Hat noch keine neue Versionsnummer

**Comment by Diginix** [comment]
Die 3.3.4 von GIT wurde bei mir am 22.01.2022 installiert. Kann gern nochmal ein Update von GIT drüber installieren.

**Comment by dirkhe** [comment]
Ja, den fix hatte ich am 29. Committed

**Comment by Diginix** [comment]
Update soeben nochmal installiert.
Habe auch bissel was in der iobroker.mihome-vacuum\lib\vacuum.js geändert bei der history htmlTable damit die responsiv gut aussieht. Soll ich dafür ein Fork machen und dann ein Pullrequest?

**Comment by dirkhe** [comment]
Das mit der html table kann ich so nicht beurteilen, kommt drauf an, wer die wie, bzw. Wo benutzt. Am besten mach da mal ein PR. @MeisterTR hat den code etwas gesplittet, um mehr roboter zu unterstützen, kann sein, dass du den code noch an einer anderen Stelle ändern musst, suche bitte nochmal nach der Stelle
