### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.mihome-vacuum#516]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.mihome-vacuum

- [ ] [E506] Word "same star ttime of 2 timer not possible" is not translated to german in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [ ] [E506] Word "same star ttime of 2 timer not possible" is not translated to russian in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2022 bluefox <dogafox@gmail.com>" at the start of LICENSE

Thanks,
your automatic adapter checker.

**Comment by dirkhe** [comment]
is fixed in 3.3.4

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
