### ISSUE TITLE
Resetting values of command-states

### ISSUE THREAD

**Issue by stef-73** [iobroker-community-adapters/ioBroker.mihome-vacuum#52]
Actually, the states in the control-channel are not reset after using. So the state start remains on true, the zoneClean holds the last zone entered. This is quite annoying while using it in the vis. I've tried to use some bool-button with different texts for true and false, but as all the states remain on true, this doesn't work out.
As for now I use a trigger on the mihome-vacuum.0.info.state, but it would be very nice to have this done by the adapter itself.
So for the logic:
state 6 or 8 resets start, spotclean, pause, zoneclean.
state 8 resets "home" (going home)
state 11 (spot cleaning) resets start, pause
etcpp..

**Comment by BuZZy1337** [comment]
Wouldn't it be enough just to set all states to "false" if the Status is 2, 3, 6 or 8?
Because normally you never set "start" to true and then set for example "spot clean" to true without the cleaner reached state 2 3 6 or 8 after the normal "start"?

**Comment by stef-73** [comment]
Except Home, this should go to false after state 8, but not with 6.

**Comment by stef-73** [comment]
For the state pause, this is a little bit different. If triggered from outside, it should go to true by state 10 and go to false by any other state.

**Comment by BuZZy1337** [comment]
Do you just need it for displaying the states in VIS?
You can apply CSS to the widgets with an "if statement"..

For example "if mihome-vacuum.0.info.state == 8 then ......" so you can apply any styles with CSS to that Widget.

Maybe you should open a thread on forum.iobroker.de where we better can talk about that.

**Comment by stef-73** [comment]
This doesnt work with bool-switches. They are supposed to have a different look according to the value of the state. Of course its possible to overwrite this by a bit of js, but to have a reliable value in state would be much better. Will try to explain this in the forum..

**Comment by BuZZy1337** [comment]
Did you already post anything about that in the forum?

**Comment by stef-73** [comment]
Just a second ago: 
https://forum.iobroker.net/viewtopic.php?f=23&t=16952
Its in german..

**Comment by gaudes** [comment]
Hey,
I'd like to refresh this issue, same problem here. Bool objects in control or object "RoomClean" stay "true".
It would be perfect if states reset after changes (e.g. RoomClean=true until cleaning of room finished or canceled)

Thanks and regards,
Ralf

**Comment by dirkhe** [comment]
If a Button is triggered it id now Set to true, if action is triggered, gut this is Not the Cleaning Time.
As long as the robot is Cleaning the state control.clean_home is Set to true
