### ISSUE TITLE
Two Instances of Adapter, Second Robot "Helo Message Timeout"

### ISSUE THREAD

**Issue by thedd1337** [iobroker-community-adapters/ioBroker.mihome-vacuum#526]
I have two instances of mihome-vacuum running on my Pi4
First instance i used for my Roborock S5 and working fine
Now i have a new Roborock S7 which can be choosen by the new second instance without any Problems.
The S7 has ip address reservation so it will always receive the same ip.

![grafik](https://user-images.githubusercontent.com/47350081/154035810-73887f4f-4373-41c0-b819-cc6f661ebd2c.png)

![grafik](https://user-images.githubusercontent.com/47350081/154037107-bba1b8b4-fbe4-4ab3-a8f6-e755f7aad42d.png)

![grafik](https://user-images.githubusercontent.com/47350081/154036686-49a6a398-a90c-4f19-a319-11adc67f3408.png)
In the Mihome App the Netzwork informtion says 100% strength, no paket loss but in the Adapter i have always a timeout for the Hello Message

Just made another test:
If i choose the S7 in the first mihome adapter instance it is working and if i then choose the S5 in the second instance i am having the same issue.
So it seems the issue is related to having two instances running at the same time even if they use different ports.

**Versions:**

-   Adapter version: 3.3.1
-   JS-Controller version: 3.3.22
-   Node version: 12.22.10
-   vacuum cleaner: Roborock S7

**Comment by ThorstenBoettler** [comment]
Same problem here.
First instance with standard parameters is working fine. (roborock S50)
Second instance (roborock S7) does not connect. It's also not connecting with only one instance.
For the second instance I set the port to --> 53425

Logoutput:
mihome-vacuum.1 | 2022-04-27 20:03:09.004 | debug | Helo message Timeout
mihome-vacuum.1 | 2022-04-27 20:02:57.004 | debug | Helo message Timeout
mihome-vacuum.1 | 2022-04-27 20:02:45.003 | debug | Helo message Timeout
mihome-vacuum.1 | 2022-04-27 20:02:33.002 | debug | Helo message Timeout
mihome-vacuum.1 | 2022-04-27 20:02:31.001 | debug | server started on 0.0.0.0:53425
mihome-vacuum.1 | 2022-04-27 20:02:30.999 | info | IOT enabled, create state
mihome-vacuum.1 | 2022-04-27 20:02:30.997 | debug | MIIO: Config: ip:172.16.4.7 token: 5943xxxxxxxxxxxxxxxxxxxx4263746f
mihome-vacuum.1 | 2022-04-27 20:02:30.997 | debug | Create State for deviceInfowifi_signal
mihome-vacuum.1 | 2022-04-27 20:02:30.997 | debug | Create State for deviceInfofw_ver
mihome-vacuum.1 | 2022-04-27 20:02:30.997 | debug | Create State for deviceInfomodel
mihome-vacuum.1 | 2022-04-27 20:02:30.996 | debug | Create State for deviceInfomac
mihome-vacuum.1 | 2022-04-27 20:02:30.996 | debug | Create State for deviceInfo
mihome-vacuum.1 | 2022-04-27 20:02:30.945 | silly | States system redis pmessage system.adapter.mihome-vacuum.1.logLevel/system.adapter.mihome-vacuum.1.logLevel:{"val":"silly","ack":true,"ts":1651082550939,"q":0,"from":"system.adapter.mihome-vacuum.1","lc":1651082550939}
mihome-vacuum.1 | 2022-04-27 20:02:30.938 | debug | load Map creator... true
mihome-vacuum.1 | 2022-04-27 20:02:30.908 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.19.1, js-controller: 4.0.23
mihome-vacuum.1 | 2022-04-27 20:02:30.712 | debug | Plugin sentry Initialize Plugin (enabled=true)


Output of the ports on linux shows: 
sudo lsof -i -P -n | grep io.mihome
io.mihome  7834 iobroker   20u  IPv4 11201042      0t0  TCP 127.0.0.1:60250->127.0.0.1:9001 (ESTABLISHED)
io.mihome  7834 iobroker   21u  IPv4 11201043      0t0  TCP 127.0.0.1:60258->127.0.0.1:9001 (ESTABLISHED)
io.mihome  7834 iobroker   22u  IPv4 11201044      0t0  TCP 127.0.0.1:60260->127.0.0.1:9001 (ESTABLISHED)
io.mihome  7834 iobroker   23u  IPv4 11201045      0t0  TCP 127.0.0.1:35632->127.0.0.1:9000 (ESTABLISHED)
io.mihome  7834 iobroker   24u  IPv4 11201046      0t0  TCP 127.0.0.1:35634->127.0.0.1:9000 (ESTABLISHED)
io.mihome  7834 iobroker   25u  IPv4 11201047      0t0  TCP 127.0.0.1:35636->127.0.0.1:9000 (ESTABLISHED)
io.mihome  7834 iobroker   27u  IPv4 11203860      0t0  UDP *:53425 
io.mihome 26575 iobroker   20u  IPv4 10068740      0t0  TCP 127.0.0.1:50126->127.0.0.1:9001 (ESTABLISHED)
io.mihome 26575 iobroker   21u  IPv4 10068743      0t0  TCP 127.0.0.1:50134->127.0.0.1:9001 (ESTABLISHED)
io.mihome 26575 iobroker   22u  IPv4 10068744      0t0  TCP 127.0.0.1:50136->127.0.0.1:9001 (ESTABLISHED)
io.mihome 26575 iobroker   23u  IPv4 10068745      0t0  TCP 127.0.0.1:53736->127.0.0.1:9000 (ESTABLISHED)
io.mihome 26575 iobroker   24u  IPv4 10070856      0t0  TCP 127.0.0.1:53750->127.0.0.1:9000 (ESTABLISHED)
io.mihome 26575 iobroker   25u  IPv4 10070857      0t0  TCP 127.0.0.1:53752->127.0.0.1:9000 (ESTABLISHED)
io.mihome 26575 iobroker   27u  IPv4 10072464      0t0  UDP *:53421

**Comment by dirkhe** [comment]
is the problem still exist?
