### ISSUE TITLE
Use this adapter with roborock app/account simultaneously

### ISSUE THREAD

**Issue by stefanerdmann** [iobroker-community-adapters/ioBroker.mihome-vacuum#538]
Hi,

is it possible to use this adapter with the roborock app/account simultaneously? I did like to use the roborock app instead of the mihome app to control the robot with my phone and also want to use this adapter in order to do some automations in my smarthome. 

Did someone test if it is possible to send commands to the robot via the mi-cloud even if it is currently paired with the roborock app? I believe that there might be a chance that this could work.

**Comment by dirkhe** [comment]
You can use it whit miihome hub and iobroker. If you use the robirock app, you can't use it with mihome app and/or iobroker, because the firmware can only connect to one cloud account
