### ISSUE TITLE
Bekannte Geräte andere Bezeichnungen

### ISSUE THREAD

**Issue by jb-home** [iobroker-community-adapters/ioBroker.mihome-vacuum#550]
-   Marke: Roborock
-   Modell: S6 Pure
-   Bezeichnung: roborock.vacuum.a08

Hier scheinen sich nur die Modellbezeichnungen zu unterscheiden. Funktional sind die Geräte.

**Comment by dirkhe** [comment]
Geht es hier nur um die bezeichnung und der meldung im log?

**Comment by jb-home** [comment]
Geht nur um die Meldung im Log.
Soweit ist es funktional.
