### ISSUE TITLE
No Answer for DeviceModel use old one 

### ISSUE THREAD

**Issue by dadonali** [iobroker-community-adapters/ioBroker.mihome-vacuum#557]
Can not connect the adapter with my vacuum i get all time this error 

mihome-vacuum.0 | 2022-04-10 14:07:16.666 | warn | No Answer for DeviceModel use model from Config
-- | -- | -- | --
mihome-vacuum.0 | 2022-04-10 14:07:16.666 | warn | No Answer for DeviceModel use old one
mihome-vacuum.0 | 2022-04-10 14:07:16.665 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF

-   Adapter version: 3.3.5
-   JS-Controller version: 12.20.1 
-   Node version: 12.20.1
-   vacuum cleaner: roborock.vacuum.s5

**Comment by Diginix** [comment]
I had the same messages yesterday. When I'm opening the mihome App on my smartphone and open the vacuum device, the adapter connection goes green and all is working as expected.

**Comment by dadonali** [comment]
> I had the same messages yesterday. When I'm opening the mihome App on my smartphone and open the vacuum device, the adapter connection goes green and all is working as expected.

for me it doesnt work :(  i cant open the device in the app, only "loading infos" but nothing happen

**Comment by Diginix** [comment]
If the app also makes problems it seems to be a network issue of the device.

**Comment by dadonali** [comment]
now i had a connection to the app but the adapter is always yellow :(

**Comment by dadonali** [comment]
<img width="1214" alt="Bildschirmfoto 2022-04-10 um 14 31 20" src="https://user-images.githubusercontent.com/100767028/162618250-1af7d45b-1fb1-448e-891c-24e6b2d16273.png">
 But i see in the objects the adapter have no firmware vers. and wifi connection

**Comment by Diginix** [comment]
Ok, so your device was never working? It is the first try to connect the adapter with it?
Then it is a complete different case. I thought you got it only sometimes, but in general the adapter is working with your device.
Which cloud and server did you use in the app and which in the adapter? Did the adapter found your S5 automatically incl. token?

**Comment by dadonali** [comment]
The adapter ran without a problem until the beginning of the year and since then I have had this error.

Yes the vacuum cleaner is found in the adapter with IP and token

**Comment by dadonali** [comment]
everything worked now :) i had reset the whole vacuum and reinstall the app and the adapter with new token :)

**Comment by Diginix** [comment]
Then, you can close the issue.
