### ISSUE TITLE
Selecting device does not fill 'manual settings' automatically

### ISSUE THREAD

**Issue by Zinski** [iobroker-community-adapters/ioBroker.mihome-vacuum#564]
I only have one device in my new mi-account.
using the adapter with my cloud-login  I get my devices, but selecting this one device doesn't automatically set the corresponding entries in the fields under 'manual settings'. The adapter isn't establishing a connection once iI fill in the information manually so I assume that the default ports aren't working for my setup.

Can anyone help me here?

EDIT:
my robot is a Roborock S7 VMAX

**Comment by dirkhe** [comment]
Do you use the same subnet for ioBroker and your robot?

**Comment by dirkhe** [comment]
Is this issue still exist?
