### ISSUE TITLE
Multiroomclean S7 MaxV funktioniert zusammen mit der Ultra Station nicht!

### ISSUE THREAD

**Issue by saeft2003** [iobroker-community-adapters/ioBroker.mihome-vacuum#570]
Hallo,

Ich besitze den S7 MaxV (roborock.vacuum.a27) zusammen mit der Ultra Station. Wenn ich mehrere Räume anwähle ohne das die Wischplatte angebracht ist und nur gesaugt wird, funktioniert der Multiroomclean wie gewohnt.

Wenn allerdings die Wischplatte angebracht ist, funktioniert der Multiroomclean nicht mehr. Der Ablauf ist so:

1. state: 8 wird geladen
2. state: 23 mop wird nass gemacht
3. state: 18 Raumreinigung
4. state: 26 fahre zum mop waschen
5. state: 23 mop wird gereinigt
6. state: 22 Staub wird abgesaugt
7. state: 8 wird geladen

Da hier der state: 6 auf dem Heimweg nicht kommt, wird die nächste Raumreinigung aus der queue vom Adapter nicht angestoßen. 

Wäre hier eine Anpassung möglich?

**Comment by dirkhe** [comment]
Ich schaue mir das mal an

**Comment by saeft2003** [comment]
Das ist super! Nächste Woche könnte ich noch testen, danach bin ich leider 9-10 Wochen vereist.

**Comment by dirkhe** [comment]
Das mit dem zwischendurch hatte ich mir auch schon so gedacht. Was mich wundert, ist das es dennoch nicht funktioniert, denn eigentlich sucht er auch beim Status Charging in der queue, sprich startet die nächste Reinigung.
Kannst du das ganze mal mit debug log hier posten, bitte? 
Obwohl ich lese gerade, dass du von multiroomclean redest, also da werden ja alle räume gleichzeitig geschickt, da macht der robbi das selbstständig, da haben wir keinen Einfluß drauf. Ich dachte, das Problem wäre, wenn du die hintereinander anstösst. Am besten wäre wirklich das log.

**Comment by saeft2003** [comment]
Debug log kann ich heute Abend nachreichen. Multiroomclean macht nicht der Roboter selbstständig. Sobald er mit einem Raum fertig ist bekommt er vom Adapter den nächsten Befehl für den nächsten Raum in der queue. 

Über die App werden alle Räume gleichzeitig auf den Roboter geschickt.

**Comment by dirkhe** [comment]
Der Adapter kann auch beide Möflichkeiten, je nachdem wie du das antriggerst. Wenn du dir zb. einen virtuellen Raum machst, wo do 2 Räume (Index1,Index2) drin speicherst und den antriggerst, macht der robbi das alleine, weil er mit einem Befel beide Räume bekommt. Wenn du die aber hintereinander machst, habe ich die queue eingebaut, die den Reinigungsvorgang startet.
Du kannst da auch über Timer machen im Adapter machen, Der timer kann dann zb deaktiviert werden und bei Bedarf manuell angestartet werden.
Bei Befehlen hintereinander gibt es eine queue und wenn einer dieser Stati vom Robbi gemeldet wird, wird der nächste Befehl aus der queu genommen:
			if ([cleanStates.Sleeping, cleanStates.Waiting, cleanStates.Back_toHome, cleanStates.Charging, cleanStates.GoingToSpot].includes(this.cleandState)) {
So zumindest der aktuelle codestand. Und da ist halt charging (6) auch drin.

**Comment by saeft2003** [comment]
Ok das mit den virtuellen Raum wusste ich gar nicht.

**Comment by saeft2003** [comment]
[debug.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/8599177/debug.txt)

Hier das debug log von 3 Raumreinigungen von 16:30 - 17:00 Uhr. Bevor er angedockt hat habe ich Pause gedrückt und den nächsten Raum manuell ausgewählt über den Adapter.

**Comment by dirkhe** [comment]
Kannst du mal testen, bitte 
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tree/570-multiroomclean-s7-maxv

**Comment by saeft2003** [comment]
Ich hab die neue Version getestet. Funktioniert leider nicht, er fährt den neuen Raum nicht an. Hier das log.

[debug.txt](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/8599400/debug.txt)

**Comment by dirkhe** [comment]
Irgendwie passt das alles nicht zusammen:
Ich finde weder im 1. log noch im 2.log den Status charging. Ich finde pause, aber das würde ja eh nicht funktionieren. Weil pause ist pause, das heisst du pausierts nur den Vorgang. Im ersten log sehe ich dann auch, dass du die queue manuell löscht.

Also vom Ablauf ist das so, dass der Adapter den Befehl bekommt, zu reinigen. Den gibt er direkt weiter. Wenn dann während der Reinigung ein neuer Reinigungsbefehl kommt, wird der in die Queue eingereiht. Sobald dann einer der o.g. Stati (cleanStates.Sleeping, cleanStates.Waiting, cleanStates.Back_toHome, cleanStates.Charging, cleanStates.GoingToSpot] kommt, wird der nächste Befehl aus der Queue genommen.
Diese Abfolge konnte ich bei dir im log so nicht nachvollziehen,
Ich bräuchte mal das log, dass einer der stati nach dem raumreinigen kommt, ohne dass die Queue manuell gelöscht wurde.
Was man sinnvollerweise noch machen könnte, wäre 
DustExtracting: 22,
	CleaningMop: 23,
	GoingMopClean: 26
auch n och als aktiv anzusehen, dass würde ich jetzt nochmal machen, aber das würde nur helfen, wenn du während dieser Tätigkeit einen neuen Raum anwählst

**Comment by saeft2003** [comment]
Das ist korrekt. Bevor er den Mop gesäubert und danach geladen hätte, habe ich Pause gedrückt die Queue gelöscht und den nächsten Raum gewählt.

Weil wenn er laden würde, würde er sicherlich dann zur nächsten Raumreinigung aus der Queue starten. Ich will aber nicht nach jedem Raum eine Mopreinigung. 

Ich versuche gerade, dass für mich mit einem Blockly zu lösen. Wenn der state 26 kommt, wird geschaut welcher Raum als letztes in der Queue steht und ggf. ein roomclean gestartet. Das geht aber auch nur da ich nie mehr als 3 Räume am Stück reinige. Wenn man ein ganzes Geschoss am Stück reinigen möchte und eingestellt hat, dass nach 25min eine Mopreinigung gemacht wird, dann würde das ganze so nicht funktionieren...

![Unbenannt](https://user-images.githubusercontent.com/66335778/166161162-687c42d0-0a90-41bc-b393-9461b2a298a0.jpg)

**Comment by dirkhe** [comment]
Ok, dass ist jetzt etwas ganz anderes, wie in def fehlerbeschreibung.
Abef trotzdem habe ich ja jetzt fehler gefixt.
Zu drinem problem, was du willst, bekommen wir so nichg hin, weil eir ja nicht wissen, ob es eine zwischenreinigung oder das ende ist.
Das einfachste für dich wäre, wen  du in iobroker einen raum anlegst, wo du einfach 2 räume zuweist. Oder halt, wie geschrieben einen timer. Wie gesagt, den kannst du disablen und dann per vis oder ähnliches ejnmalig ausführen

**Comment by saeft2003** [comment]
Sorry, dann haben wir ein bisschen aneinander vorbei geredet. Kann ich in den DP addroom mehrere map index schreiben z.B. 18,19,20 (so richtig mit Komma?) und wenn ich dann den DP Multiroomclean auf true setzte, werden diese Räume gleichzeitig auf den Roboter geschickt?

**Comment by dirkhe** [comment]
Nein, addroom funktioniert nur mit einer id oder koordinaten.
Multiroom und tiner funktionieren mit den iobroker räumen. Du weist deinen adapter rümen datenpunkten per admin iobroker räume zu. Dem multioom datenpunkt weist du dsnn mehrere iobroker räume zu. Wenn du drn dsnn ttiggerst, hoot er sich die index nummer und triggert die an.
Oder du mavhst ex per custom command

**Comment by saeft2003** [comment]
Alles klar. Könntest du mir noch kurz sagen wie der custom command aussieht? 

cleanroom (und jetzt index1, index2 usw.)

**Comment by dirkhe** [comment]
Siege hier https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/blob/master/README_de.md
Cleanrooms bezieht dich auf räume,m was du willdt ist cleansegment

**Comment by saeft2003** [comment]
Ich hatte mir die readme schon in englisch durchgelesen, aber so wies aussieht nicht ganz kapiert. Danke für deine Hilfe, ich werde das nachher mit custom command testen…

**Comment by dirkhe** [comment]
@saeft2003  Ist das problem hier  jetzt gelöst?

**Comment by saeft2003** [comment]
Ja passt 👍
