### ISSUE TITLE
Ultra Station Meldung wenn Wasser leer

### ISSUE THREAD

**Issue by saeft2003** [iobroker-community-adapters/ioBroker.mihome-vacuum#584]
**Infos zum Gerät:**

-   Roborock
-   Ultra Station
-   roborock.vacuum.a27

Wäre es möglich das ein Datenpunkt angelegt wird der anzeigt ob das Wasser in der Ultra Station leer ist oder nicht? 

Mit get_status bekommt man die nötigen Infos. 

"dock_error_status":0 --> kein Fehler

"dock_error_status":38 --> Wasser von der Ultra Station leer

`[{"msg_ver":2,"msg_seq":6003,"state":8,"battery":91,"clean_time":957,"clean_area":17467500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":3,"water_box_status":1,"back_type":-1,"wash_phase":0,"wash_ready":0,"fan_power":102,"dnd_enabled":1,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":203,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":3457,"is_exploring":0,"home_sec_status":0,"home_sec_enable_password":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":3,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":5,"mop_mode":302,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":0,"charge_status":1}]`

**Comment by dirkhe** [comment]
Ich könnte da schon was einbauen, die Frage ist, welche Stati gibt es noch. Ich würde es dann eher so machen, dass es einen Datenpunkt dock_error mache, mit einer Liste 0, 38. Könntest du ggf. mal versuchen noch andere docking errors zu provozieren, wie zb behäter aus der station nehmen oder sowas?

**Comment by saeft2003** [comment]
Genau das hatte ich versucht um noch mehr Stati raus zu bekommen. Leider ohne Erfolg. 

Wenn der Schmutzwassertank voll ist gibt es keine Änderung. Wenn der Staubsaugerbeutel voll ist konnte ich noch nicht testen ob es hier eine Änderung gibt. Genauso wenn eine Wartung vom Sieb und der Bürste ansteht. 

Aber da Wassertank leer, weit am häufigsten vorkommt, wäre es nett wenn du es einbauen könntest. Man kann es dann ggf. noch erweitern.

**Comment by dirkhe** [comment]
Dann teste mal https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tree/584-ultra-station-meldung-wenn-wasser-leer, Mein System is momentan down, daher konntre ich keinen probelauf machen

**Comment by saeft2003** [comment]
Gibt es jetzt einen neuen DP? Falls ja wo ist der und wie heißt der?

**Comment by dirkhe** [comment]
hmmm, da müsste aber eigentlich mehr kommen, bei mir klappt das:
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tree/584-ultra-station-meldung-wenn-wasser-leer:
![grafik](https://user-images.githubusercontent.com/9537962/169386267-e41110a8-c2dd-4535-bc56-4bba4089c249.png)

**Comment by dirkhe** [comment]
Der Datenüunkt kommt erst, wenn er das erste mal connected hat, bei mir würde er gar nicht kommen

**Comment by saeft2003** [comment]
ich habe mit debug versucht zu installieren, aber es kommen keine Meldungen im log. Es passiert einfach rein gar nichts...

**Comment by dirkhe** [comment]
Irgendwo muss doch was stehen, hast du mal direkt im iobroker log geschaut oder auch im npm log. Irgenwie kann man das npm install log auch mit ausgeben. Ich habe da jetzt nicht so viel geändert

**Comment by saeft2003** [comment]
Wo finde ich das npm log? Unter home/iobroker/.npm/_log sind nur alte logs nicht von heute.

**Comment by dirkhe** [comment]
Sind die ggf in deinem home verzeichnis? Hast du mal in /opt/iobroker/log geschaut?
Ich würde mal vermuten, dass hat nichts mit dem adapter selber zu tun. Hast du mal probiert, den master branch zu installieren?

**Comment by saeft2003** [comment]
Ich hab bei anderen Adapter ein Update gemacht die laufen ganz normal durch. Unter opt/iobroker/log liegt das normale log und da ist gar nichts drin zu finden. Läuft das Update bei dir ganz normal durch? Kennst du vielleicht noch einen Dritten der das auf einem Testsystem mal probieren könnte?

**Comment by saeft2003** [comment]
Schau mal hier. Da wollte einer den mihome-vacuum über git installieren. Hat 50 min gedauert… evtl passt doch irgendwas nicht. 

https://www.facebook.com/groups/440499112958264/permalink/1757828007892028/

**Comment by dirkhe** [comment]
Du kanndt sucb folgendes machen, kopiere einfach fie beiden geänderten dateien lib/objects und lib/vacuum nsch /oot/iobroker/node_modules/iobroker.mihome–vacuum und stsrte den sdapter neu

**Comment by saeft2003** [comment]
Alles klar. Ich probiere das ganze heute Abend nochmal…

**Comment by saeft2003** [comment]
Keine Chance das update über die web oberfläche zu machen. Ich hab 2 Stunden gewartet. Ich habe jetzt wie von dir vorgeschlagen die zwei Dateien kopiert. Testen kann ich das allderings leider erst nächstes Wochenende da ich im Moment unterwegs bin.

**Comment by saeft2003** [comment]
Ich finde den neuen DP nicht. wie heißt der und wo müsste der sein? ich habe das adapter update gemacht und der roboter ist jetzt an. jetzt müsste doch der DP kommen oder?

**Comment by dirkhe** [comment]
Ich habe gerade nochmal was gefixt, wenn man copy and paste macht....

**Comment by saeft2003** [comment]
ich hab nochmal ein update von git gemacht. finde aber immer noch kein neuen DP. Könntest du mir bitte sagen wie der heißt und wo ich den finden müsste?

**Comment by saeft2003** [comment]
ich habe heute den ersten praxistest gemacht. funktioniert wie gewollt. vielen dank. wäre super wenn das in die stable version kommt...

**Comment by dirkhe** [comment]
ist in Version 3.4.0
