### ISSUE TITLE
Possibility to select between Roborock or Xiaomi App Cloud

### ISSUE THREAD

**Issue by Mathias2803** [iobroker-community-adapters/ioBroker.mihome-vacuum#595]
There are 2 kinds of apps you could install:
- The Roborock App including Camera support & other functionality
- The Xiaomi Home App

Currently your tool only supports to get the Token from the Xiaomi Home App.

Maybe it is possible to change this so you can select what App (Cloud) is used.

**Comment by Mathias2803** [comment]
Sorry, I just noticed this is already requested.

[https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/182}

I hope this could be fixed, or please add a note to the tool and tell the users to use this app or it won't work. It took me a lot of effort trying to get the token with the "wrong" app.

**Comment by dirkhe** [comment]
I already add a comment to the readme, but this is not published yet
