### ISSUE TITLE
Map doesn't load + CANVAS warning

### ISSUE THREAD

**Issue by jaschkopf** [iobroker-community-adapters/ioBroker.mihome-vacuum#599]
**Describe the bug**  
Map doesn't load, warning appears in log since updating to 3.4.1. Installing Canvas doesn't fix the Problem. After restarting iobroker, the problem appears again. I allready tried:

Please install canvas and the libs manually with: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
switch into : cd /opt/iobroker/node_modules/iobroker.mihome-vacuum then sudo npm install canvas --unsafe-perm=true

But it doesn't work. 

**To Reproduce**  
1. Restart iobroker

**Expected behavior**  
The map should update properly. No warning in log

**Screenshots & Logfiles**  
CANVAS package not installed....please install Canvas package manually or disable Map in config see also https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/blob/master/lib/canvaserror.md

**Versions:**
-   Adapter version: v3.4.1
-   JS-Controller version: v4.0.23
-   Node version: v14.19.3
-   vacuum cleaner: Roborock S5

**Comment by dirkhe** [comment]
if you have nodejs >= 14 and a 32 bit System it would not work, because it could not be compiled

**Comment by tobasium** [comment]
Hi,

I have the same Problem after Update NPM and node.js

Plattform: docker
Betriebssystem: linux
Architektur: x64
Node.js: v16.15.1
NPM: 8.11.0

**Comment by o0shojo0o** [comment]
reinstalling the adapter has solved the problem for me.

**Comment by Grothesk242** [comment]
> sudo npm install canvas --unsafe-perm=true

Wrong command. Never ever sudo npm in connection with sudo.
