### ISSUE TITLE
Mi vacuum error???

### ISSUE THREAD

**Issue by denjo82** [iobroker-community-adapters/ioBroker.mihome-vacuum#601]
**Describe the bug**  

**To Reproduce**  

2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**

-   Adapter version: <adapter-version>
-   JS-Controller version: <js-controller-version> 
-   Node version: <node-version> 
-   vacuum cleaner: <device-model>

Hallo, ich habe seit Tagen Probleme mit dem Adapter. Ich stürzt immer 
Node.js v16.15.1
Admin 5.3.8
mihome 3.3.3
js controller 4.0.23

host.raspberrypi

2022-06-12 09:37:11.744infoRestart adapter system.adapter.mihome-vacuum.0 because enabled

host.raspberrypi

2022-06-12 09:37:11.743infoinstance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)

mihome-vacuum.0

95132022-06-12 09:37:11.409infostarting. Version 3.4.1 (non-npm: iobroker-community-adapters/ioBroker.mihome-vacuum#e0a405414e2db379071da31b2b2ba29ce22c08aa) in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v16.15.1, js-controller: 4.0.23

host.raspberrypi

2022-06-12 09:37:06.545infoinstance system.adapter.mihome-vacuum.0 started with pid 9513

host.raspberrypi

2022-06-12 09:36:36.096infoRestart adapter system.adapter.mihome-vacuum.0 because enabled

host.raspberrypi

2022-06-12 09:36:36.095infoinstance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)

mihome-vacuum.0

7472022-06-12 09:36:35.483infoIOT enabled, create state

mihome-vacuum.0

7472022-06-12 09:36:35.299infostarting. Version 3.4.1 (non-npm: iobroker-community-adapters/ioBroker.mihome-vacuum#e0a405414e2db379071da31b2b2ba29ce22c08aa) in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v16.15.1, js-controller: 4.0.23

host.raspberrypi

2022-06-12 09:36:29.427infoinstance system.adapter.mihome-vacuum.0 started with pid 747

host.raspberrypi

2022-06-12 09:35:59.054infoRestart adapter system.adapter.mihome-vacuum.0 because enabled

host.raspberrypi

2022-06-12 09:35:59.053infoinstance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)

mihome-vacuum.0

241312022-06-12 09:35:58.810infoIOT enabled, create state

mihome-vacuum.0

241312022-06-12 09:35:58.631infostarting. Version 3.4.1 (non-npm: iobroker-community-adapters/ioBroker.mihome-vacuum#e0a405414e2db379071da31b2b2ba29ce22c08aa) in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v16.15.1, js-controller: 4.0.23

host.raspberrypi

2022-06-12 09:35:53.980infoinstance system.adapter.mihome-vacuum.0 started with pid 24131

host.raspberrypi

2022-06-12 09:35:23.733infoRestart adapter system.adapter.mihome-vacuum.0 because enabled

host.raspberrypi

2022-06-12 09:35:23.733infoinstance system.adapter.mihome-vacuum.0 terminated with code 0 (NO_ERROR)

**Comment by dirkhe** [comment]
Du hadt nodejs 16 und einen raspberry. Läuft der suf 64 bit?
Hadt du Die map eingeschaltet?
Die map braucht canvas und das funktioniert mit nidejs ≥14 nuf noch mit 64 bit

**Comment by denjo82** [comment]
Nein ich hab 32 bit weil 64 bit so viele Probleme macht

**Comment by dirkhe** [comment]
Entweder nodejs auf 12 downgraden oder die MAP abschalten. nodejs ab 14 unterstützt nur noch 64 bit und da kann canvas nicht compiliert werden.

**Comment by dirkhe** [comment]
Ist das Problem damit gelöst?

**Comment by Grothesk242** [comment]
Was mich verwundert: 
```
pi@mysterium:/opt/iobroker $ npm ls canvas
iobroker.inst@3.0.0 /opt/iobroker
├─┬ iobroker.echarts@1.0.12
│ ├── canvas@2.9.3
│ └─┬ jsdom@19.0.0
│   └── canvas@2.9.3 deduped
├─┬ iobroker.iot@1.11.8
│ └── canvas@2.9.3 deduped
└─┬ iobroker.mihome-vacuum@3.4.2
  └── canvas@2.9.3 deduped

pi@mysterium:/opt/iobroker $ uname -a
Linux mysterium 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
pi@mysterium:/opt/iobroker $ nodejs -v
v16.16.0
pi@mysterium:/opt/iobroker $
```
Sollte eigentlich ja nicht funktionieren. Tut's aber hier.

**Comment by dirkhe** [comment]
was hast du denn für eine distro drauf, bzw. woher bekommt er denn ggf die node versionen oder die canvas version? Prinzipiell sollte das auch laufen, aber es muß halt alles für 32bit gebuilded werden.

**Comment by Grothesk242** [comment]
Das ist ein 'Vanilla'-RaspberryOS 'Bullseye' auf 32bit mit node16. 
Für canvas dann die zum build erforderlichen Pakete installiert. Alles nix ungewöhnliches.
