### ISSUE TITLE
Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

### ISSUE THREAD

**Issue by aortmannm** [iobroker-community-adapters/ioBroker.mihome-vacuum#608]
I updated my system to node 16, everything else is newest version and was not changed since yesterday.

Error see screenshot. I have a raspbian with 64 bit Raspi 4.

![image](https://user-images.githubusercontent.com/3414298/174639875-0453c1ae-c34a-4729-9a71-ba2ddf82b7b6.png)

**Comment by dirkhe** [comment]
pleas provide debug log. 
Which version do you use?

**Comment by aortmannm** [comment]
Ok, I activated debug right now and will wait until it happens again, I think tomorrow when the vacuum will clean again.

I have installed the v3.4.1 I think it's the latest from github.

**Comment by aortmannm** [comment]
Ok, seems like I can't reproduce this issue since I changed the log level to debug. I close this Issue and will reopen it if it happens again.
