### ISSUE TITLE
Möglichkeit Etagen zu wechseln

### ISSUE THREAD

**Issue by Frank1604** [iobroker-community-adapters/ioBroker.mihome-vacuum#611]
Im iobroker werden mir zwar Räume als Objekte angelegt, jedoch sind diese nur von der aktuellen Etage (Karte) benutzbar. Möchte ich eine Reinigung ausführen so muss ich erst in der Xiaomi App die Etage wechseln und kann dann über die Objekte des iobrokers die Reinigung anstoßen.

Es wäre schön eine Möglichkeit zu haben über einen Datenpunkt die korrekte Etage auswählen zu können oder noch besser die Zugehörigkeit eines Raumes zur Etage im entsprechenden Datenpunkt zu haben.

**Versions:**

-   Adapter version: 3.4.2
-   JS-Controller version: 4.0.23
-   Node version: 16.15.1
-   vacuum cleaner: Roborock S7

**Comment by dirkhe** [comment]
Da ich das leider nicht nachstellen kann, brauche ich zumindest Informationen. Dazu Stelle den Adapter Mal auf debug und wechsle Mal die Etage in der App und schicke ihn dann Mal los. Dann das ganze Mal am besten als zip hier hochladen, ggf key und so weiter vorher rauslöschen

**Comment by dirkhe** [comment]
Ich habe mir das mal im code angeschaut. Normalerweise müstest du unter dem Punkt cleanmap die aktuelle map angezeigt bekommen und mit load map die auch wechseln können

**Comment by Frank1604** [comment]
Naja, aber load Map ist ein Button, wie gebe ich dem den Parameter an, welche Map ich laden will? Ich will ja die Map wecheln können auf eine andere Etage.

**Comment by dirkhe** [comment]
probiere mal in actualMap einen anderen Wert einzutragen

**Comment by Frank1604** [comment]
Ok, ich habe den Fehler gefunden. Dem Datenpunkt actualMap fehlt ein "type": "state". Dadurch zeigt er weder Werte noch lässt sich schalten. Nachdem ich das eingefügt habe, erscheinen meine Etagen im Dropdown und der Wechsel der Etagen funktioniert einwandfrei.

![grafik](https://user-images.githubusercontent.com/10420590/176360339-2b0d9dbc-4b50-4482-b248-bec9dbca568e.png)

**Comment by dirkhe** [comment]
Die erstellt er aber normalerweise hier getMultiMapsList(), welche einmal am Start des Adapters aufgerufen werden sollte.Das sehe ich in deinem Log nicht. Im debug Modus sollte sowas kommen wie Statup getMultiMapsList und dann get_multi_maps_list.
Kannst du deinen adapter nochmal auf debug stellen und wirklich von anfang an das log schicken?
Vlt läuft da ja nochwas schief, was wir gerade rücken müssen.

**Comment by Frank1604** [comment]
Kein Problem, hier ein kompletter Start im debug-Mode.
[robolog.zip](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/9007658/robolog.zip)

**Comment by Frank1604** [comment]
Um Missverständnisse zu vermeiden: Der Datenpunkt war angelegt und auch meine Etagen standen als Werte im Datenpunkt. Er hat aber nichts angezeigt und ließ sich auch nicht schalten weil dem Datenpunkt die Typendefinition "state" gefehlt hat. Ich habe nur die rot markierte Zeile in meinem Screenshot eingefügt, der Rest stand schon drin.

**Comment by dirkhe** [comment]
Ja, dann haben wir da een fehler, denke ich. Vom code her ist das aber schon richtig, bei mir steht das auch richtig drin, dann schliesse ich mal

**Comment by Frank1604** [comment]
Nur, wie ist es denn dazu gekommen? Der Datenpunkt wurde ja nicht von mir angelegt.

**Comment by dirkhe** [comment]
Hast du versucht, manuell da was einzutragen? Ich hatte das letztens auch Mal, da hat der Admin daraus type text gemacht

**Comment by Frank1604** [comment]
Ich habe den Datenpunkt gelöscht, den Adapter neu gestartet und der Datenpunkt wurde wieder ohne den type angelegt. Ich glaube da stimmt was nicht,

<html><body>


mihome-vacuum.0 | 2022-06-29 13:10:22.566 | info | create state for carpet_mode
-- | -- | -- | --
mihome-vacuum.0 | 2022-06-29 13:10:21.765 | warn | This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2022-06-29 13:10:21.764 | warn | Object mihome-vacuum.0.cleanmap.actualMap is invalid: obj.type has to exist
mihome-vacuum.0 | 2022-06-29 13:10:20.696 | info | settest next timer: not available
mihome-vacuum.0 | 2022-06-29 13:10:20.537 | warn | State "mihome-vacuum.0.cleanmap.actualMap" has no existing object, this might lead to an error in future versions


</body>
</html>

**Comment by dirkhe** [comment]
Obwohl, wenn ich es Recht überdenke, ist type state auch falsch, dass muss number sein. Ich schaue mir das heute Abend Mal an

**Comment by Apollon77** [comment]
der "obere type" ist richtig mit state ... common.type muss number sein ... also das eine Objekt oben ist korrekt so, also ja das obere type muss rein mit "state"

**Comment by Frank1604** [comment]
Ja, so hatte ich das auch verstanden. Nur wenn es übergeordnet ein state ist, funktioniert der Datenpunkt. Weitere Einschränkungen und Definitionen können dann im "common" Teil gemacht werden. Read und Write z.B. und die Einschränkung auf einen Typ wie hier eben number.

**Comment by dirkhe** [comment]
hab den Fehler gefunden. Wenn man die Karte nicht aktiviert hatte, wurden die DP nicht initial angelegt. Dann wurde nur der Inalt, bzw. die verschiednen states geschrieben,, da fehlen dann natürlich die anderen Angaben. Ich habe das mal gefixt, dass die immer geschrieben werden

**Comment by Frank1604** [comment]
Die Karte kann ich nicht aktivieren, dann stürzt der Adapter ständig ab. Das 32/64 bit Problem.

Danke fürs fixen und natürlich danke fürs Entwickeln! 👍

**Comment by dirkhe** [comment]
ich habe das gefixt, in der 3.5.0 werden dp immer erstellt, unabhängig, ob aktiviert oder nicht

**Comment by Frank1604** [comment]
Vielen Dank fürs fixen. Ich habe es in der aktuellen Version getestet und es funktioniert einwandfrei. 👍
