### ISSUE TITLE
Custom room cleaning command not working with latest valetudo version

### ISSUE THREAD

**Issue by mar565** [iobroker-community-adapters/ioBroker.mihome-vacuum#612]
**Describe the bug**  
Custom room cleaning command not working anymore with newest Valetudo firmware.

**To Reproduce**  
`sendTo("mihome-vacuum.0", 
        "cleanRooms", 
        "enum.rooms.Toilette, enum.rooms.Kitchen, enum.rooms.esszimmer, enum.rooms.Wohnzimmer", 
        function (response) { /* do something with the result */}
    );`

**Expected behavior**  
start room cleaning

**Screenshots & Logfiles**  
no error in log.

**Versions:**

-   Adapter version: 3.5.0
-   JS-Controller version: 4.0.19
-   Node version: v14.19.0
-   vacuum cleaner: S5 - Valetudo 2022.06.0

**Comment by dirkhe** [comment]
Please provide debug log

**Comment by mar565** [comment]
nvm, a reboot of the robot fixed the issue. Sorry for the trouble.
