### ISSUE TITLE
Absaugung der Station ansteuern

### ISSUE THREAD

**Issue by Stormbringer11** [iobroker-community-adapters/ioBroker.mihome-vacuum#617]
Hallo,

wäre es vielleicht möglich in den Adapter den Absaugbefehl für die neuen Dockingstationen zu integrieren?

Hätte den 
**Roborock S7 MaxV Ultra*

API Hinweis kenne ich mich leider nicht aus, könnte nur auf das Homebridge Modul verweisen bei dem es  schon implementiert ist unter dem Befehl dustCollection:

https://www.npmjs.com/package/homebridge-xiaomi-roborock-vacuum

Danke :o)

**Comment by dirkhe** [comment]
Wenn ich das richtig sehe, wird dir ja zumindest schon angezeigt, wenn er am absaugen ist, das hatten wir schon mal integriert. Was du jetzt nocn brauchst, ist das als Button an, bzw. abzuschalten, korrekt?
Dan code von homebridge könnte man adaptiern

**Comment by Stormbringer11** [comment]
Ja genau zum manuellen auslösen des Absaugens (so wie es in der App geht) damit die Steuerung der Broker übernehmen kann. Wäre super 😉

**Comment by dirkhe** [comment]
stelle den Adapter dabei mal auf debug, da wird zb. regelmäßig der status abgefragt, darin kommt ein dust_collection_status vor, wäre mal interressant, welche Werte er wann annimmt. Vlt. kann man da auch den Füllstand oder so abelsen, oder in den consumable Meldung. Vlt einfach zwischendurch mal schauen?

**Comment by Stormbringer11** [comment]
Danke, wow das ging ja schnell *g* Habe die Version von Github geladen und einen Upload gemacht aber irgendwie finde ich keinen neuen Datenpunkt zum Ansteuern.

**Comment by dirkhe** [comment]
Steht denn was im Log? Wenn der Status abgefragt wird, müsste da dust_collection_status gemeldet werden, zb:
`[{'msg_ver': 2, 'msg_seq': 1839, 'state': 8, 'battery': 100,
        # 'clean_time': 2311, 'clean_area': 35545000, 'error_code': 0,
        # 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0,
        # 'in_fresh_state': 1, 'lab_status': 3, 'water_box_status': 1,
        # 'fan_power': 102, 'dnd_enabled': 0, 'map_status': 3, 'is_locating': 0,
        # 'lock_status': 0, 'water_box_mode': 202, 'water_box_carriage_status': 0,
        # 'mop_forbidden_enable': 0, 'adbumper_status': [0, 0, 0],
        # 'water_shortage_status': 0, 'dock_type': 0, 'dust_collection_status': 0,
        # 'auto_dust_collection': 1,  'mop_mode': 300, 'debug_mode': 0}]`

dann sollte unter control ein neuer DP angelegt werden

**Comment by Stormbringer11** [comment]
Mit Debug LOG kommt bei mir so etwas auch:



mihome-vacuum.0 | 2022-07-07 17:41:31.607 | debug | setGetStatus {"msg_ver":2,"msg_seq":2364,"state":8,"battery":100,"clean_time":3449,"clean_area":43465000,"error_code":0,"map_present":true,"in_cleaning":false,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"back_type":-1,"wash_phase":0,"wash_ready":0,"fan_power":102,"dnd_enabled":false,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":201,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":3459,"is_exploring":0,"home_sec_status":0,"home_sec_enable_password":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":3,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":155,"mop_mode":300,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":38,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0,"error_text":"No error"}


Fehler bringt er keine aber der DP ist nicht da. Die Objekte habe ich testweise auch schon gelöscht und neu anlegen lassen vom Adapter. 

<img width="1464" alt="Bildschirmfoto 2022-07-07 um 17 45 17" src="https://user-images.githubusercontent.com/43651672/177815970-529bbbb4-8bde-4174-9ced-acb70cb86b91.png">

**Comment by dirkhe** [comment]
sorry, da war noch ein Fehler drin, bitte nochmal testen

**Comment by Stormbringer11** [comment]
kein Problem ;-) Aber ist leider nach wie vor das Selbe...

**Comment by dirkhe** [comment]
Bitte nochmal, jetzt sollter auf jeden Fall eine Info ausgeben, entweder 
	adapter.log.info('create states for dust collecting');
oder
	adapter.log.info('dust collecting not found ' + JSON.stringify(dust_collection_status));

**Comment by Stormbringer11** [comment]
Sehe da leider noch immer nichts 



mihome-vacuum.0 | 2022-07-07 20:47:24.714 | info | create state for carpet_mode
-- | -- | -- | --
mihome-vacuum.0 | 2022-07-07 20:47:23.147 | info | create new room: 995001044896
mihome-vacuum.0 | 2022-07-07 20:47:23.147 | info | create new room: 995001007178
mihome-vacuum.0 | 2022-07-07 20:47:23.146 | info | create new room: 995001044874
mihome-vacuum.0 | 2022-07-07 20:47:23.145 | info | create new room: 995001044879
mihome-vacuum.0 | 2022-07-07 20:47:23.145 | info | create new room: 995001044875
mihome-vacuum.0 | 2022-07-07 20:47:23.144 | info | create new room: 995001007176
mihome-vacuum.0 | 2022-07-07 20:47:22.120 | info | create states for mop
mihome-vacuum.0 | 2022-07-07 20:47:22.116 | info | create states for dock status
mihome-vacuum.0 | 2022-07-07 20:47:22.112 | info | create states for water box mode
mihome-vacuum.0 | 2022-07-07 20:47:22.104 | info | create states for water box
mihome-vacuum.0 | 2022-07-07 20:47:22.100 | info | change states from State control.fan_power
mihome-vacuum.0 | 2022-07-07 20:47:21.841 | info | Map selected create states...
mihome-vacuum.0 | 2022-07-07 20:47:21.506 | info | settest next timer: not available
mihome-vacuum.0 | 2022-07-07 20:47:20.905 | info | select standard vacuum protocol....
mihome-vacuum.0 | 2022-07-07 20:47:20.703 | info | IOT enabled, create state
mihome-vacuum.0 | 2022-07-07 20:47:20.610 | info | starting. Version 3.5.0 (non-npm: iobroker-community-adapters/ioBroker.mihome-vacuum#76233f39a0d5af56ae6db485a6ad11fa8eee27c8) in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.19.3, js-controller: 4.0.23
mihome-vacuum.0 | 2022-07-07 20:47:20.610 | info | starting. Version 3.5.0 (non-npm: iobroker-community-adapters/ioBroker.mihome-vacuum#76233f39a0d5af56ae6db485a6ad11fa8eee27c8) in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.19.3, js-controller: 4.0.23
mihome-vacuum.0 | 2022-07-07 20:47:05.248 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 | 2022-07-07 20:47:05.247 | debug | Plugin sentry destroyed
mihome-vacuum.0 | 2022-07-07 20:47:05.247 | info | terminating
mihome-vacuum.0 | 2022-07-07 20:47:05.247 | error | Socket Close

**Comment by dirkhe** [comment]
Bist du sicher, dass du den code geupdated hast? Die Meldung muss nach dem create states for dock status kommen

**Comment by dirkhe** [comment]
Alles gut, kein Thema. Wäre halt noch interessant, wenn man mit dem Status noch mehr anfangen könnte, gibt ja auch noch auto_dust_collection, wäre die Frage, was das ist?

**Comment by dirkhe** [comment]
Ja, da arbeitet ja schon jemand dran, ob man den Adapter auch mit der roborock App verknüpfen kann. Das mit der Kamera wäre mir jetzt eine Nummer zu viel. Das braucht bestimmt länger. Ich würde dann jetzt hier zumachen, ggf. müsstest du dann ein neues Issue aufmachen, vlt findet sich ja jemand der die Zeit hat
