### ISSUE TITLE
Vacuum Adapter stürzt immer ab und veersucht zu starten

### ISSUE THREAD

**Issue by Henny4184** [iobroker-community-adapters/ioBroker.mihome-vacuum#618]
Adapter Vers. 3.4.2
JS 4.0.23
Node 16.15.1
Model Xiaomi 1S
![image](https://user-images.githubusercontent.com/66122139/177756814-c4dc42cb-2da8-4c7f-b7a9-5c81c900357b.png)

Woran kann es liegen mache ich selber den Fehler? Letzt stand da meine ich auch was ich nun noch nicht wieder gesehen habe JS sei zu neu für den Adapter kam aber noch nicht wieder die Meldung. 

Vielleicht kann ja einer hier weiter helfen., 

	🚨🚨🚨 ATTENTION! ATTENTION! ATTENTION! 🚨🚨🚨

	Bugreports without DEBUG log will be closed without comment
-->

**Describe the bug**  

**To Reproduce**  

2. Click on '...'

**Comment by Apollon77** [comment]
Please show more log, not only adapter, also whyat the js.contreoller logs.

Please also check that you have not set a "restart cron" on that instance!

**Comment by Henny4184** [comment]
![image](https://user-images.githubusercontent.com/66122139/177816549-e51fb44f-d181-435b-ad55-b1e27c9c8345.png)
So sieht es nach dem derzeitigen neustart aus.

**Comment by dirkhe** [comment]
Bitte stelle den Adapter auf debug und gebe nur die relavanten Zeilen aus. Aktuell verbinder er sich erstmal nicht, das kann schon mal vorkommen, dann muss man mal abwarten. Wenn er wiklich abstürzt, wäre interressant, wann. BItte dann auch mal die Karte auschalten, denn oft liegt es an der canvas. Gebe auch  mal mehr Informationen ünber dein System. Linux, windows, Raspi, 32bit/64bit

**Comment by Apollon77** [comment]
Was hast Du denn 17:47:47 gemacht=? Da wurde der adapter deaktiviert und daher neu gestartet ... war das Absicht? SOnst wäre natürlich das Log con so einem spontanen "nicht user verurachten Restart" relevant

**Comment by Henny4184** [comment]
Ich habe jetzt die Karte deaktiviert und schaue dann mal.

**Comment by Henny4184** [comment]
Hallo, habe die Karte mal deaktiviert wie oben empfohlen wurde und hat bisher keinen Neustart des Adapters. Für mich wäre es somit erst einmal erledigt und behoben.  Vielen Dank für die schnelle Problemlösung.
