### ISSUE TITLE
Can't run more then 1 instance at the same time

### ISSUE THREAD

**Issue by Flux3PO** [iobroker-community-adapters/ioBroker.mihome-vacuum#627]
**Describe the bug**  
Only one active Instance is working. Might be related to bug #626 ?
I got 2 cleaners and I want to use them both but only one instance can be run at the same time.

**To Reproduce**  

Setup 2 Instances and start them.

**Expected behavior**  
Each Instance should start and run as expected.

**Screenshots & Logfiles**  

host.ioBroker | 2022-07-26 17:23:35.090 | info | Restart adapter system.adapter.mihome-vacuum.1 because enabled
-- | -- | -- | --
host.ioBroker | 2022-07-26 17:23:35.090 | info | instance system.adapter.mihome-vacuum.1 terminated with code 0 (NO_ERROR)
mihome-vacuum.1 | 2022-07-26 17:23:34.945 | info | starting. Version 3.4.2 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v16.16.0, js-controller: 4.0.23
host.ioBroker | 2022-07-26 17:23:32.672 | info | instance system.adapter.mihome-vacuum.1 started with pid 508978
host.ioBroker | 2022-07-26 17:23:02.594 | info | Restart adapter system.adapter.mihome-vacuum.1 because enabled
host.ioBroker | 2022-07-26 17:23:02.593 | info | instance system.adapter.mihome-vacuum.1 terminated with code 0 (NO_ERROR)
mihome-vacuum.1 | 2022-07-26 17:23:02.446 | info | starting. Version 3.4.2 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v16.16.0, js-controller: 4.0.23
host.ioBroker | 2022-07-26 17:23:00.129 | info | instance system.adapter.mihome-vacuum.1 started with pid 508939
host.ioBroker | 2022-07-26 17:23:00.027 | info | "system.adapter.mihome-vacuum.1" enabled

![grafik](https://user-images.githubusercontent.com/11157007/181046083-85921054-5b00-4ab8-8393-4b7ac9555cbd.png)

**Versions:**

-   Adapter version: 3.4.2
-   JS-Controller version: 4.0.23
-   Node version: v16.16.0
-   vacuum cleaner: S5/S4

**Comment by MeisterTR** [comment]
Die you read  the Readme, what you need to do with a second instance? Did
you change the port?!

Flux3PO ***@***.***> schrieb am Di., 26. Juli 2022, 17:24:

**Comment by Flux3PO** [comment]
Outch, yes I've read the readme but overlooked this, already running fine. Thanks
