### ISSUE TITLE
How to add rooms to multiRoomClean

### ISSUE THREAD

**Issue by L-C-P** [iobroker-community-adapters/ioBroker.mihome-vacuum#628]
Hi,

not a bug!

Can you please provide a ts example, how to connect rooms to the "clean all rooms" datapoint?

Thank you!

**Comment by dirkhe** [comment]
the clean all rooms cleaned all rooms, which are assigned to the dp. This is working with ioBroker rooms. So assign your roomss to a iobroker room. Than assign one ore more rooms to the dp Multiroom clean and trigger them:
![grafik](https://user-images.githubusercontent.com/9537962/187507269-4a43fa84-c948-45c3-b2f1-70e346f58490.png)

**Comment by dirkhe** [comment]
This is for the case, if you want to do this via admin ui. If you want to this via script, you shoul do this via send command, see docu.

**Comment by dirkhe** [comment]
Because no further response, I close ticket
