### ISSUE TITLE
Model roborock.vacuum.a62 not supported! /Roborock S7 Pro Ultra

### ISSUE THREAD

**Issue by martin86x** [iobroker-community-adapters/ioBroker.mihome-vacuum#630]
**Infos zum Gerät:**

-   Marke: Roborock 
-   Modell S7 Pro Ultra
-   Bezeichnung laut IoBrocker roborock.vacuum.a62

Folgende meldung erscheint im Io Broker :

Model roborock.vacuum.a62 not supported! Please open issue on git: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues

Danke

**Comment by dirkhe** [comment]
Ist in der nächsten Version mit drin

**Comment by dirkhe** [comment]
Implemented in 3.7.0
