### ISSUE TITLE
Two Devices on different ports?

### ISSUE THREAD

**Issue by Alwiz79** [iobroker-community-adapters/ioBroker.mihome-vacuum#64]
Somehow I can't get two devices connected to the iobroker. One of them always keeps yellow state.
In the readme it says, that for two devices one of them needs to change the ports from default 54321 to something else. I changed to 54322 but it doesn't work.

Are there special ports that neeed to be used?
I have a Mi Robo (Gen 1) and a Roborock (Gen 2) does that make any difference concerning the ports?

**Comment by BuZZy1337** [comment]
Nope, that does not make any difference - Port 54322 should be okay.. You could try to set the instance which is staying yellow to debug loglevel and check if you get any messages in the Log.

**Comment by Paalap** [comment]
@Alwiz79 the _own_ port should be different for both devices (but the same default robot's port)
