### ISSUE TITLE
Unhandled prefetch abort: breakpoint debug exception (0x222) at 0x00000000

### ISSUE THREAD

**Issue by ch90045** [iobroker-community-adapters/ioBroker.mihome-vacuum#647]
Morning,

running Debian on 

Linux pibroker 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux

with all updates installed enabling the adapter leads to:

Unhandled prefetch abort: breakpoint debug exception (0x222) at 0x00000000

filling up the logs very fast:

-rw-r-----   1 root     adm             1.7G Aug 30 20:26 kern.log
-rw-r-----   1 root     adm             1.7G Aug 31 07:29 syslog

Size has been reached within one hour.

In addition the adapter is eating 100% of one CPU

**Comment by ch90045** [comment]
Disabling the map seems to be a Workaround

**Comment by Apollon77** [comment]
32 or 64bis OS? maybe same as #487 ?

**Comment by ch90045** [comment]
32 Bit, standard Debian for Raspberry 4B

**Comment by dirkhe** [comment]
for 32 bit there is the needed canvas lib not compiled. Do change to 64 bit or use the adapter without map.

**Comment by ch90045** [comment]
Changing to 64 bit is not that easy - especially for ONE  library not being ported (yet). I would recommend to adjust the readme to reflect that 32 bit apparently is not supported.

**Comment by dirkhe** [comment]
I can add some hints i  the readme

**Comment by patrickbs96** [comment]
@ch90045 I had the same problem but I could solve it by switching the kernel to 64-bit.
With these [instructions](https://www.sindastra.de/p/1345/switch-your-raspberry-pi-to-64-bit-kernel-raspbian), it only took me two minutes and since then I haven't had any more problems with this error.

**Comment by dirkhe** [comment]
Thank you, mI will take this link in the readme

**Comment by ch90045** [comment]
Thanks, nice to know. I took the long route of reinstall but this may be something to consider for my other Pi's
