### ISSUE TITLE
Multiple Zones are crashing the adapter (3.6.0)

### ISSUE THREAD

**Issue by JoJ123** [iobroker-community-adapters/ioBroker.mihome-vacuum#652]
**Describe the bug**  
- Adding Rooms by Zones
- MutliRoom with minimum two rooms
- Adapter will stop

**Expected behavior**  
Both zones will be cleaned

**Screenshots & Logfiles**
From the screenshot, it could be the issue that in the JSON message there are " " where no should be.
  
![image](https://user-images.githubusercontent.com/38938791/189532502-7caf53d5-68d0-47ca-91a5-3feb3a92a5eb.png)

**Versions:**
-   Adapter version: 3.6.0
-   JS-Controller version: 4.0.23
-   vacuum cleaner: S50

**Comment by JoJ123** [comment]
If I send the same command without the two mentioned " "
Like that: `app_zoned_clean;[[15735,27629,21285,31729,1],[27580,25100,30980,31700,1]]`

it's working fine.

**Comment by JoJ123** [comment]
@Apollon77  The error in the original post was created from within the adapter.
I've created multiple rooms with the "addRoom" and coordinated for the zones.

Then I've assigned the room to the multiRoom state and click on start. --> Error

**Comment by dirkhe** [comment]
I will check that

**Comment by dirkhe** [comment]
Please test this Version: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tree/620-feature-request-queue-shall-contain-fan_power-and-water_box_mode-for-each-command-given There the error is fixed

**Comment by dirkhe** [comment]
Implemented in 3.7.0
