### ISSUE TITLE
READING TOKEN DOES NOT REALLY WORK

### ISSUE THREAD

**Issue by typxxi** [iobroker-community-adapters/ioBroker.mihome-vacuum#66]
everything went fine and the windows dialogbox appeared with a lot of xiaomi devices from my phone (redmi note 5 with double Mi Home App using the Xiaomi on board tool to create a "second" app that I need for my second home / installation).

I did not get any thing that looked like a 32 character long token but I got a list with all xiaomi mi home devices from both places starting with the "shadow or second installation"

Here is an excerpt 
isa.camera.df3 - VÖGEL 1 -  - 192.168.178.32
cleargrass.sensor_ht.dk1 - Temperatur Luftfeuchte Monitor -  - 
lumi.sensor_86sw2.v1 - KAMIN Schalter -  - 
chuangmi.plug.m1 - My Plug 1 -  - 192.168.0.48
lumi.gateway.v3 - ZIGbee GATEway -  - 192.168.0.27
lumi.sensor_magnet.v2 - TÜR -  - 
lumi.sensor_switch.aq2 - Aqara Wireless Mini Switch -  - 
philips.light.bulb - E27 weiß -  - 192.168.0.38
yeelink.light.virtual - BULB+STR_1 -  - 
mijia.camera.v1 - WAB FLUR -  - 192.168.0.221
mijia.camera.v1 - WAB TV -  - 192.168.0.22
isa.camera.df3 - BAD 360 -  - 192.168.0.20
lumi.sensor_cube.aqgl01 - ACTION WÜRFEL -  - 

It feels like the tokens are missing between the 2 "-" before the ip adress like seen here 
"philips.light.bulb - E27 weiß -  - 192.168.0.38"

How can I get these tokens and do I need them to use that particular Xiaomie Philips E27 white bulb with the mi home desk lamp?

The Mi Home App for example doesn't have that LAN Support option the Yeelights offer.

**Comment by Wox1** [comment]
Hello,
I have the same problem.
The App start. Then the Mi App make a Backup. The Mitoolkit can expand the Backup and then i only see:
roborock.vacuum.s6 - Roborock S6 -  - 10.0.0.253

**Comment by MeisterTR** [comment]
You only can get the token with the Russian version of mihome app

**Comment by Wox1** [comment]
Thank you for the fast answer :)
I have found this link:
http://za.kapiba.ru/files/MiHome_5.5.51_vevs.apk
Is this version the right?
