### ISSUE TITLE
Datenpunkt für Wischroute (mop_mode) hinzufügen

### ISSUE THREAD

**Issue by MPTrixi** [iobroker-community-adapters/ioBroker.mihome-vacuum#670]
Beim Roborock S7 Ultra Pro kann man via App die Wischroute einstellen. Dies wird im get status als "mop_mode" zurückgegeben. Einstellungen sind:
300=Standard
301=Gründlich
303=Gründlich+

**Comment by dirkhe** [comment]
Bitte mal testen mit folgendem release https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tree/620-feature-request-queue-shall-contain-fan_power-and-water_box_mode-for-each-command-given

**Comment by dirkhe** [comment]
Implemented in 3.7.0
