### ISSUE TITLE
Model roborock.vacuum.a38 not supported! Roborock Q7 Max

### ISSUE THREAD

**Issue by Vumer4** [iobroker-community-adapters/ioBroker.mihome-vacuum#671]
Info zum Gerät:

-   Marke: Roborock
-   Modell: Q7 Max
-   Bezeichnung : roborock.vacuum.a38 

Folgende meldung erscheint im Io Broker :
Model roborock.vacuum.a38 not supported! Please open issue on git: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues

Danke

**Comment by dirkhe** [comment]
Implemented in 3.7.0
