### ISSUE TITLE
State value to set for "mihome-vacuum.0.control.fan_power" has value "108" greater than max "106"

### ISSUE THREAD

**Issue by Wildbill-Z** [iobroker-community-adapters/ioBroker.mihome-vacuum#677]
Ich habe heute meinen Roborock S7 MAXV Ultra mal im Nur-Saugen-Modus mit Stufe MAX+ laufen lassen. Dabei kamen folgende Fehler im Log im 20-Sekunden-Takt:
`
State value to set for "mihome-vacuum.0.control.fan_power" has value "108" greater than max "106"
 `
Ich habe den Datenpunkt manuell geändert und den Max-Wert auf 108 gesetzt und die Meldungen waren weg.
Installierte Adapter-Version ist 3.6.0.

Gruss, Jürgen

**Comment by Wildbill-Z** [comment]
Ich habe mal alle Modi in der App nacheinander durchprobiert. Es scheint beim Mode "Nur wischen" unter fan_power für 105 die Zuweisung zu fehlen. Da steht dann nur 105 drin, wird wohl 'OFF' bedeuten. Und beim Mode "Nur saugen" gibt es noch eine Stufe "MAX+", bei der kommt dann unter fan_power die 108. Und eben im Log die Warnung, da der Datenpunkt für einen maximalen Wert von 106 vorgesehen ist.
Modell laut Log: roborock.vacuum.a27
Ist ein S7 MaxV Ultra, also der mit Kameras und kombinierter Absaug- und  Wischerstation.

`

APP Mode | Saugleistung | Wischintensität | iob fan_power | iob water_box_mode
-- | -- | -- | -- | --
Vac & Mop | Leise | unabhängig | QUIET(101) |  
Vac & Mop | Normal | unabhängig | BALANCED(102) |  
Vac & Mop | Turbo | unabhängig | TURBO(103) |  
Vac & Mop | unabhängig | Sanft |   | LOW(201)
Vac & Mop | unabhängig | Mittel |   | MEDIUM(202)
Vac & Mop | unabhängig | Intensiv |   | HIGH(203)
Nur wischen |   | Sanft | 105 | LOW(201)
Nur wischen |   | Mittel | 105 | MEDIUM(202)
Nur wischen |   | Intensiv | 105 | HIGH(203)
Nur saugen | Leise |   | QUIET(101) | OFF(200)
Nur saugen | Normal |   | BALANCED(102) | OFF(200)
Nur saugen | Turbo |   | TURBO(103) | OFF(200)
Nur saugen | Max. |   | MAXIMUM(104) | OFF(200)
Nur saugen | MAX+ |   | 108 | OFF(200)

`

Wenn Du noch was brauchst, dann meld Dich.

Gruss, Jürgen

**Comment by dirkhe** [comment]
Bitte mal https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tree/620-feature-request-queue-shall-contain-fan_power-and-water_box_mode-for-each-command-given testen, ich habe da die fan_power bei dem a27 angepasst. Kann aber einen Moment dauern.

**Comment by Wildbill-Z** [comment]
Sieht gut aus. Beim umstellen der Stufen taucht jetzt MAXIMUM+(108) auf und es wird nix mehr ins Log geschrieben. Ich schliesse dann das Issue.
Danke
