### ISSUE TITLE
v3.8.3 rooms.state wird zu früh auf null gesetzt / queue funktioniert nicht sauber

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.mihome-vacuum#684]
![image](https://user-images.githubusercontent.com/39678667/199306844-37f6f9f2-667b-45e1-bf42-9fa4de8b4f05.png)

Beim ersten Raum bleibt der state auf "clean Room" bis der Raum fertig ist. Aber bei denen aus der queue, die vorher ein "waiting position x" haben, wird nur wenige Sekunden "clean Room" gesetzt und noch während der Sauger den Raum weiter saugt wird bereit auf null gesetzt.

Hier der Sauger state für den Zeitraum:
![image](https://user-images.githubusercontent.com/39678667/199307349-2a93f95d-0371-48e9-86ba-f449ea7645a7.png)

Bis 18:11 Uhr hätte also "clean Room" im rooms.state stehen müssen.

**Comment by Diginix** [comment]
@dirkhe Gibt es da kurzfristig eine Lösung?
Kann ich das selbst patchen?

**Comment by dirkhe** [comment]
Ich habe versucht, das nachzustellen, bekomme es aber nicht hin, habe auch die dp Mal gespeichert. Was mich wundert ist null, es wird eigentlich immer nur ein leerer String gespeichert, oder halt reinigen oder warte position

**Comment by Diginix** [comment]
Admin History zeigt glaub bei leeren String null an. Aber wenn du es nicht nachstellen kannst, muss ich erstmal wieder auf 3.6.0 zurück. Leider dann auch alles wieder rückgängig machen was ich wegen den map Änderungen anpassen musste. Aber 3.8.x hat für meinen roborock.vacuum.m1s Sauger keinerlei Mehrwerte und bisher leider nur Nachteile.
Vorhin ist die Instanz auch wieder auf 100% CPU Last gelaufen und ich musste sie abschießen damit es sich beruhigt.
Habe aber leider auch nicht die Zeit groß Debug Logs o.ä. zu liefern. Glaube auch fast nicht dass da sachdienliche Hinweise drin wären. Der Adaptercode hat ja schonmal komplett gepasst. Und die Xiaomi Firmware und Cloud hat sich nicht geändert.
In den Commit Diffs müsste man also finden können was möglicherweise für die Probleme sorgt.

**Comment by Diginix** [comment]
Mit 3.8.4 und 2 Räumen, also einer mit "clean Room" und einer mit "waiting position 0" hat es heute funktioniert.
Übermorgen sind wieder 7 Räume dran, dann sind mehr in der queue.

**Comment by dirkhe** [comment]
Teste bitte mal die 3.8.5, habe hier was dazu geschrieben https://forum.iobroker.net/topic/59480/test-f%C3%BCr-mihome-vacuum?page=1

**Comment by Diginix** [comment]
Ist da auch das [CPU Last Problem von hier](https://forum.iobroker.net/post/889624) ggf. mit gefixt?

**Comment by Diginix** [comment]
Bug scheint gefixt mit 3.8.5. Danke!
