### ISSUE TITLE
error not connected

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.mihome-vacuum#685]
started with 3.8.3

<html><body>

mihome-vacuum.0 | 2022-11-04 09:52:29.226 | error | sendMessage throws error ==>not connected
-- | -- | -- | --
mihome-vacuum.0 | 2022-11-04 09:52:29.214 | error | sendMessage throws error ==>not connected
mihome-vacuum.0 | 2022-11-04 09:52:29.099 | error | sendMessage throws error ==>not connected
mihome-vacuum.0 | 2022-11-04 09:52:28.925 | error | sendMessage throws error ==>not connected
mihome-vacuum.0 | 2022-11-04 09:52:28.914 | error | sendMessage throws error ==>not connected

</body>
</html>

**Comment by Diginix** [comment]
duplicate #681
