### ISSUE TITLE
Helo message Timeout

### ISSUE THREAD

**Issue by MischaI** [iobroker-community-adapters/ioBroker.mihome-vacuum#688]
Roborock S7 MaxV Ultra
Daten über Adapter aus Xiaomi Cloud geholt. 
Server China.

Alle Daten sind richtig.

<details>
  <summary>Log</summary>

```
mihome-vacuum.0 2022-11-08 16:09:33.709	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:09:21.707	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:09:09.705	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:08:57.699	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:08:45.697	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:08:33.694	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:08:21.690	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:08:09.688	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:07:57.686	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:07:45.683	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:07:33.681	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:07:21.677	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:07:09.675	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:06:57.671	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:06:45.667	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:06:33.664	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:06:21.660	debug	Helo message Timeout
mihome-vacuum.0 2022-11-08 16:06:19.652	debug	server started on 0.0.0.0:53421
mihome-vacuum.0 2022-11-08 16:06:19.646	info	IOT enabled, create state
mihome-vacuum.0 2022-11-08 16:06:19.634	debug	MIIO: Config: ip:xxx.xxx.xxx.xx token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mihome-vacuum.0 2022-11-08 16:06:19.632	debug	Create State for deviceInfowifi_signal
mihome-vacuum.0 2022-11-08 16:06:19.631	debug	Create State for deviceInfofw_ver
mihome-vacuum.0 2022-11-08 16:06:19.629	debug	Create State for deviceInfomodel
mihome-vacuum.0 2022-11-08 16:06:19.628	debug	Create State for deviceInfomac
mihome-vacuum.0 2022-11-08 16:06:19.620	debug	Create State for deviceInfo
mihome-vacuum.0 2022-11-08 16:06:19.554	debug	load Map creator... true
mihome-vacuum.0 2022-11-08 16:06:19.196	info	starting. Version 3.4.2 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v16.18.1, js-controller: 4.0.23
mihome-vacuum.0 2022-11-08 16:06:18.103	debug	Plugin sentry Initialize Plugin (enabled=true)
mihome-vacuum.0 2022-11-08 16:06:10.215	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome-vacuum.0 2022-11-08 16:06:10.210	debug	Plugin sentry destroyed
mihome-vacuum.0 2022-11-08 16:06:10.203	info	terminating
mihome-vacuum.0 2022-11-08 16:06:10.202	error	Socket Close
mihome-vacuum.0 2022-11-08 16:06:10.188	info	Got terminate signal TERMINATE_YOURSELF
mihome-vacuum.0 2022-11-08 16:06:10.180	silly	States system redis pmessage system.adapter.mihome-vacuum.0.sigKill/system.adapter.mihome-vacuum.0.sigKill:{"val":-1,"ack":false,"ts":1667919970170,"q":0,"from":"system.host.raspberrypi","lc":1667919970170}
```

</details>
Kann sein, dass es noch bisschen alte Daten reinkammen, die wegen dem Adapterneustart entstanden sind
Token und IP sind richtig, und wurden auf xxx geändert

Roborock an sich angemeldet in der Roborock App.

**Versions:**

-   Adapter version: <3.4.2>
-   JS-Controller version: <4.0.23> 
-   Node version: <16.18.1> 
-   vacuum cleaner: <roborock.vacuum.a27>

**Comment by dirkhe** [comment]
Bei soviel timeout sieht das nach netzwerkprobleme aus, schau mal hier
server started on 0.0.0.0:53421
Schau mal in deine einstellungen

**Comment by MischaI** [comment]
![image](https://user-images.githubusercontent.com/34452995/200771835-971a4df3-490e-4e23-8b5a-fdbcb509eb8c.png)
scheint alles io zu sein?

**Comment by dirkhe** [comment]
Ok, ich habe gerade nochmal geschaut, bei mir steht auch 0.0.0.0 scheint also localhost zu sein.
Sind iobroker und der Robbi im selben netzt ich glaube bein s7 gab es da eine einschränkung, gab hier auch xchon mal ein issue

**Comment by MischaI** [comment]
Ja, gleicher Netz.
Liegt es vllt an dem china Server und eventuell eu roborock?
Wurde im Saturn gekauft, deswegen gehe ich davon aus dass es eu ist.
Oder liegt es an der roborock app?
Weil dort Staubsauger angebunden ist. Aber xiaomi cloud im adapter sieht den

**Comment by dirkhe** [comment]
Wenn du den Adapter nutzen willst, musst du aus der roborock App raus, der Robbi kann sich immer nur mit einem env connecten, entweder mihome oder roborock. Finden kann er ihn, weil der mihome Server dein Gerät ja kennt. Aber er kann nicht kommunizieren

**Comment by MischaI** [comment]
Habe schon irgendwo mal sowas gelesen

Aber aus dem Debug sieht man das nicht wirklich, dass Roborock App Probleme macht.

Kann man dann irgendwie ne Fehlermeldung anpassen(wenn es ne Möglichkeit gibt, das irgendwie zu erkennen, dass Roborock in der Roborock und nicht in Mi Home App angebunden ist)?

**Comment by dirkhe** [comment]
Also der adapter kann sich nicht mit dem robbi verbinden, das kann viele ursachen haben. Zum anderen dauert es manchmal, bis er sich connected. Wenn er sich nicht verbindet, lohnt sich vlt ein blivk in die readme unter known errors.
Obwohl ich sagen würde, da lohnt sich vlt. Eine zwischenüberschrift, aber stehenn tut es da zumindest, habe ich gerade nachgeschaut.

**Comment by dirkhe** [comment]
Ich habe in der readme dafür jetzt nochmal eine extra überschrift eingefügt
