### ISSUE TITLE
Bitte ROIDMI EVE Plus hinzufügen

### ISSUE THREAD

**Issue by Apropo1710** [iobroker-community-adapters/ioBroker.mihome-vacuum#689]
**Infos zum Gerät:**

-   Roidmi
-   Eve Plus
-   roidmi.vacuum.v60

Ich hoffe es hilft weiter. Ich habe unter https://github.com/al-one/hass-xiaomi-miot was für Home Assistant gefunden wo der roidmi.vacuum.v66 gelistet ist. Woanders habe ich gelesen, dass damit ebenso der roidmi.vacuum.v60 funktionieren soll. Vielleicht lässt sich davon was für den ioBroker Adapter verwenden?

**Comment by dirkhe** [comment]
Für ein neues gerät ist es echt schwer. Wenn es ein neuere roborock ist, sind ss kleinigkeiten, die kann man durch andere resten lassen, sber kein ganz neues gerät

**Comment by Apropo1710** [comment]
Testen wäre ja kein Problem, könnte ich ja machen.
Ich gebe die Hoffnung nicht auf 😁

Falls ich sonst irgendwie helfen kann oder andere Infos liefern soll einfach bescheid sagen.
