### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.mihome-vacuum#69]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.mihome-vacuum

- [ ] [E145] No news found for actual version 3.1.6
- [ ] [E812] file test/ found in repository, but not found in .npmignore

Thanks,
your automatic adapter checker.

**Comment by GermanBluefox** [comment]
Fixed

**Comment by MeisterTR** [comment]
fixed
