### ISSUE TITLE
Reinigungszyklen (1 bis 3) einstellen

### ISSUE THREAD

**Issue by kosmix1980** [iobroker-community-adapters/ioBroker.mihome-vacuum#690]
Hallo,

erstmal großes Lob für diesen tollen Adapter dank Eure Arbeit. 

Ich habe einen A15 (S7) und bin auf der Suche nach der Option die Reinigungszyklen einstellen zu können. In der Xiaomi-App kann man den Wert zwischen 1 und 3 variieren (siehe Screenshot). Den entsprechenden DP habe ich leider bisher nicht gefunden (oder übersehen).

Gibt es diese Option aktuell? 

- Wenn ja, dann würde ich mich freuen, wenn ihr mir den DP nennen könnt oder wie ich es hinbekomme den Saugroboter entsprechend zu steuern.
- wenn nein, dann würde ich mich über eine Aufnahme dieser Funktion für ein nächstes Release freuen

Vielen Lieben Dank

Kosmix
![20221109_154709](https://user-images.githubusercontent.com/117357803/200861439-4bcd5160-03c1-46be-9382-7f742151a82f.jpg)

**Comment by dirkhe** [comment]
Aktuell geht das nur bei zonen, nicht bei segmenten(räume). Ivh mpsdte wissen, was die app an den robbi schickt. Müsste man entweder mal mitsniffen oder mal hier auf github suchen

**Comment by kosmix1980** [comment]
Hmm... vielleicht hab ich etwas gefunden was weiterhilft:

[Hier](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#supported-repeats-types) auf Github, zwar für HomeAssistant, aber vielleicht trotzdem hilfreich?!

**Comment by kosmix1980** [comment]
Klasse

**Comment by Jather90** [comment]
Eine kleine Anmerkung zu der Thematik (weil ich mich gerade auf die Suche nach genau dieser Funktion ("einen/mehrere Räume 2x/3x saugen lassen") gemacht habe und hier drüber gestolpert bin(y) )
Über die App werden die Räume im zweiten Zyklus um 90° gedreht abgefahren (statt z.B. Ost-West im Nord-Süd Zickzack) . Das finde ich ziemlich praktisch (oder besser gesagt, es gibt mir das Gefühl noch gründlicher gesaugt zu haben ;-)). Ich vermute ein simples Wiederholen der Segmente würde das nicht schaffen, weil hierbei die Anweisungen getrennt gesendet werden oder? Für den Saugroboter wären es vermutlich unabhängige 1-zyklische Anweisungen für den gleichen Raum. Das fände ich sehr schade, zumal man dieses Verhalten ja theoretisch auch über (zugegeben kompliziertere...) Skripte erreichen könnte... Falls mir jemand etwas unter die Arme greift und mir erklärt was ich wie mitloggen kann/soll, um dem Geheimnis auf die Schliche zu kommen: Ich bin gerne bereit ein paar Pakete zwischen App und Roboter zu loggen. Verwende die Xiami Home App (Android) mit einem Roborock S5 Max (Firmware 4.1.2_1646)

**Comment by dirkhe** [comment]
Das ist hier beschrieben
https://python-miio.readthedocs.io/en/latest/contributing.html#traffic-capturing

**Comment by Jather90** [comment]
Hallo zusammen, bin leider erst jetzt wieder dazu gekommen. Ich scheitere gerade daran das capture zu erzeugen... Folgende Situation: Ich habe in meinem Netzwerk einen LXC Container ausgesetzt, um über miiocli das capture mit dem token zu entschlüsseln (oder so ähnlich.. sorry, falls die begriffe total falsch sind).. über meine pfSense hab ich dann ein capture gestartet und sehe dort auch, dass diverse pakete zum und vom roboter geloggt werden. Das kuriose ist allerdings: ich kann nur die Pakete vom iobroker entschlüsseln. Die restlichen Pakete (also die, die ich ja über die App lostrete..) gehen nicht an eine lokale IP und werden nicht über miiocli devtools parse-pcap aufgedröselt... Smartphone und Roboter sind im gleichen Subnetz. Mein iobroker ist sogar in einem anderen Netz und trotzdem funktioniert es... irgendeine Idee?

**Comment by dirkhe** [comment]
Da habe leider auch keine Idee, gibt es da noch ein Problem zwischen docker und Host?
Aber wenn ich das richtig weiß, kommuniziert deine App auch nicht lokal mit deinem robbi. Ich vermute mal, das geht immer über die cloud.
Du musst die app im emulator installieren und da den traffic mitschneiden, vermute ich mal

**Comment by dirkhe** [comment]
ist enthalten in 3.9.0

**Comment by Kusi-Schweiz** [comment]
Wo finde ich diese Einstellung/Datenpunkt?

**Comment by kosmix1980** [comment]
> Wo finde ich diese Einstellung/Datenpunkt?

Hi Kusi-Schweiz,

du findest den Datenpunkt (repeat) unter dem jeweiligen Raum:
![Screenshot_20230731-094259_Firefox](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/117357803/8cd76555-0627-4e48-89df-212866ed35d0)

**Comment by Kusi-Schweiz** [comment]
> Datenpunkt (repeat)

Danke, habe ich gefunden.
Reinigt er damit den Raum nur mehrmals (identisch) oder in einem unterschiedlichem Muster?

**Comment by kosmix1980** [comment]
Also bei mir wiederholt er (leider) nur die Raumreinigung. Der Roboter macht sich nach der ersten Reinigung auf den Weg zur Ladestation und kriegt dann die scheinbar die Info, dass er den Raum nochmal reinigen soll. Mich störts nicht aber die Frage bleibt...
@dirkhe wird die Reinigung mit der 90°-Drehung noch implementiert?

LG

**Comment by kosmix1980** [comment]
> Also bei mir wiederholt er (leider) nur die Raumreinigung. Der Roboter macht sich nach der ersten Reinigung auf den Weg zur Ladestation und kriegt dann die scheinbar die Info, dass er den Raum nochmal reinigen soll. Mich störts nicht aber die Frage bleibt... @dirkhe wird die Reinigung mit der 90°-Drehung noch implementiert?
> 
> LG

Ich muss korrigieren... mit der Version von GitHub funktioniert alles wie gewünscht... also der Roboter dreht bei der zweiten Reinigung sein Muster um 90°.

LG

**Comment by Kusi-Schweiz** [comment]
Ich habe es soeben bei mir ausgiebig getestet.

Was funktioniert:
Wenn ich einen einzelnen Raum reinige, dann funktioniert die Funktion "Repeat" einwandfrei und der Raum wird in unterschiedliches Muster gereinigt.

Was nicht funktioniert:
Wenn ich mehrere Räume reinige, dann funktioniert die Funktion "Repeat" nicht.
Es ist egal, ob ich bei allen Räume denselben Repeat-Wert einfüge, oder ob diese unterschiedlich sind.

@kosmix1980 kannst du dies bei mir nochmals prüfen?
