### ISSUE TITLE
Roborock S 7 Ultra Pro

### ISSUE THREAD

**Issue by Trunks1982** [iobroker-community-adapters/ioBroker.mihome-vacuum#691]
**Infos zum Gerät:**

-   Roborock
-   S7 Ultra Pro
-   roborock.vacuum.s7ultrapro

**Wichtig**  
Das Einbinden neuer Geräte ist aufwending und erfordert viel Recherche,
hierfür fehlt mir die Zeit. Also bitte sucht selbst auf git ob und wie der Sauger eingebunden werden kann,
und verlinkt die stellen

**Comment by dirkhe** [comment]
Seit wann haben die denn sprechende namen, kannst du das log mal mit anhängen, bitte?

**Comment by Trunks1982** [comment]
[iobroker.2022-11-11.log](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/files/9989243/iobroker.2022-11-11.log)
Reicht das?

**Comment by dirkhe** [comment]
Ist der a62, ist ab der3.8,X bereits drin

**Comment by Trunks1982** [comment]
![Bildschirm­foto 2022-11-12 um 10 21 26](https://user-images.githubusercontent.com/62701386/201467686-134d0a8b-67e1-4bf8-9817-a3ab86d81931.png)
naja hier fehlen einige Sachen bzw funktionieren nicht.

**Comment by dirkhe** [comment]
Was erwartest du, schreibdt kommentarlos dein gerät da hin, dazu noch falsch (also nicht das geforderte aus dem log) und den rest sollen andere machen?
Wenn irgendwas nicht funktioniert, mach ein issue auf und liefere vor allen debug logs mit. Da es such hier um opensource handelt, wäre ein bisschen mithilfe auch nicht schlecht, zb. Ist es ein bekanntes problem..

Nimm dir ein beispiel hier dran https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/690

**Comment by Trunks1982** [comment]
Erstmal ist die Geräte Bezeichnung nicht falsch, und ich habe das eingegeben was mir oben vorgeben worden ist.Sonst hätte ich es auch anders eingegeben.
Und ich bin immer bereit zu helfen was benötigt wird.
