### ISSUE TITLE
Roidmi Eve Plus

### ISSUE THREAD

**Issue by zoulhh** [iobroker-community-adapters/ioBroker.mihome-vacuum#694]
**Infos zum Gerät:**

-   Roidmi
-   Eve Plus
- roidmi.vacuum.v60

Wird zwar erkannt, kann aber nicht gesteuert werden. Kannst Du da was machen? Ich gehe über den Xiaomi Login, Roboter wird auch angezeigt samt Token und IP. Aber keine Verbindung zum Gerät.

**Comment by dirkhe** [comment]
Wenn due roidmi genauso ticken, wie die roborock, dann ja, sonst nicht. Du kannst ja mal bei dir hart in die main.js deinen robbi unter fie roborock schreiben und adapter neu starten
	'roidmi.vacuum.v60': VacuumManager,

**Comment by zoulhh** [comment]
Macht er nicht. Keine Verbindung zum Gerät. Schade. Du meinst "Instanz" neu starten, richtig? Hat er aber trotzdem nicht gemacht. Habs so eingefügt, das meintest Du oder?

	'roborock.vacuum.a27': VacuumManager, // Roborock S7 MaxV 
	'roborock.vacuum.a38': VacuumManager, // Roborock Q7 Max
	'roborock.vacuum.a62': VacuumManager, // Roborock S7 Pro Ultra
        'roidmi.vacuum.v60': VacuumManager,

**Comment by dirkhe** [comment]
Genau, dann hat er den codr für roborock geladen. Aber wenn er nicht reagiert, scheint er andere befehle zu brauchen

**Comment by zoulhh** [comment]
Verbindet auch gar nicht. Schade. Aber danke für Deine Tipps.
