### ISSUE TITLE
Datapoint for garbage bin

### ISSUE THREAD

**Issue by Kuddel071089** [iobroker-community-adapters/ioBroker.mihome-vacuum#70]
When i open the top of my Vacuum V1, there is noice, that says me, that the top is opened.

It would be nice to have a datapoint for that status.

Then i would use it, to reset the level of my bin

**Comment by PhilippLeitner** [comment]
+1

**Comment by BuZZy1337** [comment]
You mean when you remove the dust-container from the vacuum?
When i just open the top nothing happens.. The Vacuum first reacts with "Staubbehälter entnommen" when i take the container out..?

**Comment by Kuddel071089** [comment]
Ja genau, es wäre gut, wenn der Adapter es mitbekommt, wenn man den Staubbehälter entfernt. Aktuell muss ich den Werte meines Staubbehälters immer manuell auf 0 setzen (über VIS oder Alexa).

**Comment by Knallochse** [comment]
Ich hänge mich mal mit ran. Ich würde mich auch über eine Statusmeldung „Staubbehälter entfernt“
freuen

**Comment by BuZZy1337** [comment]
Sorry, hatte in letzter Zeit seeeehr viel um die Ohren deswegen leider die sehr späte Antwort:

Diese Funktion unterstützt der Staubsauger nicht. Wenn der Hersteller da nichts ändert können wir nichts machen.
