### ISSUE TITLE
Roborock Q7 Max /A38 (Rooms are not created)

### ISSUE THREAD

**Issue by New-three** [iobroker-community-adapters/ioBroker.mihome-vacuum#707]
My Q7 Max works fine with the adapter. 
Only no rooms are created. Is there anything else to consider here? 
I've tried loading the rooms manually. 
The aim is to clean rooms using the tablet.

![roborock](https://user-images.githubusercontent.com/99345562/205491888-7071f77f-a5e9-4962-906f-9c7886597f60.jpg)

**Comment by M0dj0** [comment]
Same here. I have a S5 and a S7. For both the rooms are not created.
Version is 3.88.

**Comment by dirkhe** [comment]
Yes, this is correct, we only get the rooms from the cloud and the assigned segment Nr.
We had the same issue some days before, but than he changed name from küche to kitchen an than it works, but it could also be, that he loads the map and that this helped.
Can you check, where the NaN room was created with 3.8.8 or before?

**Comment by dirkhe** [comment]
I did not recreate the issue with NaN, i would need debug log for this, therefore I close it
