### ISSUE TITLE
Fehler beim Start des Saugvorgangs

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.mihome-vacuum#719]
**Describe the bug**  
Beim Start des Saugvorgangs wird folgender Log geschrieben, auf den Saugvorgang und den Ablauf selbst hat es keinen Einfluss. Läuft alles wie erwartet. 
**To Reproduce**  

1. Starten des Saugvorgangs

**Expected behavior**  
Früher wurden keine Fehler erzeugt wenn der Saugvorgang gestartet wurde

**Screenshots & Logfiles**  
Hier der Auszug aus dem Logfile:
`
- 2022-12-19 07:12:57.271 - error: host.IoBroker Caught by controller[0]: FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
- 2022-12-19 07:12:57.271 - error: host.IoBroker Caught by controller[1]: 1: 0xb06730 node::Abort() [io.mihome-vacuum.0]
- 2022-12-19 07:12:57.271 - error: host.IoBroker Caught by controller[2]: 2: 0xa1b5d0 node::FatalError(char const*, char const*) [io.mihome-vacuum.0]
- 2022-12-19 07:12:57.271 - error: host.IoBroker Caught by controller[3]: 3: 0xce1bca v8::Utils::ReportApiFailure(char const*, char const*) [io.mihome-vacuum.0]
- 2022-12-19 07:12:57.272 - error: host.IoBroker Caught by controller[3]: 4: 0x7f0b8c469fee - Context2d::GetImageData(Nan::FunctionCallbackInfo const&) [/opt/iobroker/node_modules/canvas/build/Release/canvas.node]
- 2022-12-19 07:12:57.272 - error: host.IoBroker Caught by controller[4]: 5: 0x7f0b8c45ae58 [/opt/iobroker/node_modules/canvas/build/Release/canvas.node]
- 2022-12-19 07:12:57.272 - error: host.IoBroker Caught by controller[5]: 6: 0xd3e3ce [io.mihome-vacuum.0]
- 2022-12-19 07:12:57.272 - error: host.IoBroker Caught by controller[6]: 7: 0xd3f7ef v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [io.mihome-vacuum.0]
- 2022-12-19 07:12:57.272 - error: host.IoBroker Caught by controller[7]: 8: 0x15da239 [io.mihome-vacuum.0]
- 2022-12-19 07:12:57.272 - warn: host.IoBroker instance system.adapter.mihome-vacuum.0 terminated due to SIGABRT
`

**Versions:**

-   Adapter version: 3.8.6
-   JS-Controller version: 4.0.23
-   Node version: 16.18.1
-   vacuum cleaner: rockrobo vacuum v1

**Comment by dirkhe** [comment]
Das sieht so aus, als wenn die canvas version nicht passt. also entweder die karte ausschalten oder passende canvas installieren, such mal im forum nach canvas.
der adapter crasht und restartet, darum merkst du nichts.

**Comment by peoples0815** [comment]
Welches wäre die richtige?

`iobroker.inst@3.0.0 /opt/iobroker
├─┬ iobroker.echarts@1.0.12
│ ├── canvas@2.10.2
│ └─┬ jsdom@19.0.0
│   └── canvas@2.10.2 deduped
├─┬ iobroker.iot@1.11.9
│ └── canvas@2.10.2 deduped
└─┬ iobroker.mihome-vacuum@3.8.6
  └── canvas@2.10.2 deduped
`

**Comment by dirkhe** [comment]
Hmm, sieht prinzipiell richtig aus. Dein System ist aber 64bit? Mit 32bit gibt es probleme.
ich kenne mich mit der canvas geschichte auch nicht so gut aus, ggf mal debuglog mitschicken

**Comment by peoples0815** [comment]
Ja ist 64bit, ich habe nun den ganzen Canvas Mist mal neu installiert, dann war der Fehler weg, genau 2 Fahrten.
Nun ist er wieder da.
Da der Debuglog sehr umfangreich ist, was brauchst du denn genau?

**Comment by dirkhe** [comment]
Das reconnect kann schon mal dauern. Wss idt das denn gensu fürvein sauger, ein roborock? 
Das debug lor dem crash, also da einige zeilen davor, damit man sieht, was das auslöst. Da das alles async ist, kann das auch ein paar sekunden vorher ausgelöst worden sein

**Comment by peoples0815** [comment]
Ich habe den Xiaomi Mi Robot Vacuum V1

Bin aber gerade verwundert, weil der Fehler nur sporadisch Auftritt. Wenn ich rausgefunden habe was genau der Auslöser ist berichte ich.

**Comment by Standarduser** [comment]
Bei mir tritt ein sehr Ähnliches Problem auf.

```
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | warn | instance system.adapter.mihome-vacuum.0 terminated due to SIGABRT
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[7]: 8: 0x15da239 [io.mihome-vacuum.0]
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[6]: 7: 0xd3f7ef v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [io.mihome-vacuum.0]
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[5]: 6: 0xd3e3ce [io.mihome-vacuum.0]
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[4]: 5: 0x7f086c22ae58 [/opt/iobroker/node_modules/canvas/build/Release/canvas.node]
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[3]: 4: 0x7f086c239fee Context2d::GetImageData(Nan::FunctionCallbackInfo<v8::Value> const&) [/opt/iobroker/node_modules/canvas/build/Release/canvas.node]
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[3]: 3: 0xce1bca v8::Utils::ReportApiFailure(char const*, char const*) [io.mihome-vacuum.0]
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[2]: 2: 0xa1b5d0 node::FatalError(char const*, char const*) [io.mihome-vacuum.0]
host.srv-iobroker1 | 2023-01-08 14:04:37.840 | error | Caught by controller[1]: 1: 0xb06730 node::Abort() [io.mihome-vacuum.0]
host.srv-iobroker1 | 2023-01-08 14:04:37.837 | error | Caught by controller[0]: FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
```

Canvas ist auch bei mir scheinbar in der richtigen Version installiert:
```
/opt/iobroker$ npm list canvas

iobroker.inst@3.0.0 /opt/iobroker
├─┬ iobroker.mihome-vacuum@3.8.6
│ └── canvas@2.10.2
└─┬ iobroker.parcel@0.0.23
  └─┬ jsdom@20.0.3
    └── canvas@2.10.2 deduped
```

Specs meines Systems:
```
Plattform: linux
Betriebssystem: linux (Ubuntu 22 LTS)
Architektur: x64
Modell: Common KVM processor
Node.js: v16.18.1
NPM: 8.19.2
```

Der Roboter ist ein Roborock S5 Max
