### ISSUE TITLE
Feature Request: Zone Support (one state for each room)

### ISSUE THREAD

**Issue by t6a** [iobroker-community-adapters/ioBroker.mihome-vacuum#72]
With the models S6 and S4 one can create zones / mark rooms in the Mi Home App.
It would be great if the adapter creates states (with a button) for each zone (/room) automatically, so that I (or a script) can just press the button and the robot cleans the respective zone.

There is a workaround here [#79](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/79) but it's not even in the readme of the adapter and a bit too complicated for a lot users

**Comment by Fiiti** [comment]
+1

**Comment by Apollon77** [comment]
@Fiiti For "+1" there is the thumbs up button ... please use this because more visible

**Comment by backfisch88** [comment]
The s6 seems to work
The fan speeds are 101 - 104

**Comment by MeisterTR** [comment]
#79

**Comment by dirkhe** [comment]
@t6a  I Think your request should be fixed with 1.10, please confirm, than we can close the ticket

**Comment by dirkhe** [comment]
Closed, because no response from t6a
