### ISSUE TITLE
Räume Name

### ISSUE THREAD

**Issue by tommyMX** [iobroker-community-adapters/ioBroker.mihome-vacuum#734]
Hi,

ist es möglich dass man die Raum Namen in den datenpunkten stehen ?

oder wie finde ich raus welche Nummer zu welchem Raum gehört ?

hab grad den s6 roborock I’m test

**Comment by dirkhe** [comment]
Geht leider nicht, die Namen stehen nur in der App. Also losschicken und sehen, wo er hinfährt.
