### ISSUE TITLE
Zone Cleaning by Zone Name (Valetudo 0.4.0 Feature)

### ISSUE THREAD

**Issue by Floo0S** [iobroker-community-adapters/ioBroker.mihome-vacuum#76]
Hello,

it would be nice to have a function for Zone cleaning by name.
In Valetudo 0.4.0 it is now possible to save several Zones with names. 
A Function like zoneClean with names instead coordinates will be perfect.

**Comment by MeisterTR** [comment]
you can use mqtt adapter to control valetudo
