### ISSUE TITLE
Modus nicht mehr für jeden Raum separat einstellbar

### ISSUE THREAD

**Issue by kosmix1980** [iobroker-community-adapters/ioBroker.mihome-vacuum#762]
Hallo zusammen,

ich habe den Adapter schon eine ganze Weile in Betrieb und kann mich nur immer wieder für die tolle Leistung bedanken.

Nun aber zum Thema:
Seit einiger Zeit reagiert mein RoboS7 nicht mehr auf die Einstellungen, die ich unter dem Raum vornehme (wenn ich einen Raum einzeln reinige oder sie hintereinander in die Queue packe):

- roomFanPower
- roomMopMode
- roomWaterBoxMode

Sondern er nimmt immer die Einstellungen aus **control**:

- fan_power
- mop_mode
- water_box_mode

Ich würde euch natürlich gerne Logs ranpacken, weiß aber nicht welche hilfreich wären.

Auch wenn ich den Robo über die XiaomiApp steuer (und einen Raum auswähle und dann die o.g. Einstellungen änder), dann werden nur die Werte unter ++control++ geändert, nicht die unter dem entsprechenden Raum!

Ich hoffe ihr habt eine Idee... hatte schon überlegt, ob ich mir ein Script baue, welches das quasi semi-automatisch löst. 
(Liest aus, welcher Raum gerade gereinigt wird, holt sich die Einstellungen und schreibt sie in control.)

**Versions:**

-   Adapter version: 3.9.5
-   JS-Controller version: 4.0.24
-   Node version: v16.19.0
-   vacuum cleaner: Roborock S7 (mit Absaugstation)

**Comment by dirkhe** [comment]
control sind die Werte, die der robbi aktuell hat und die werden auch aktualisiert. Wenn du über einen Raum gehst, schickt er normalerweise dessen Werte an den robbi.  Als notwendig wäre ein debug log, von dem Zeitpunkt an, wo du den robbi über den Raum losschickst (bzw kurz davor) und dann ein bisschen, bis er wirklich am saugen ist

**Comment by kosmix1980** [comment]
Hmm... was auch immer da los war ... alles funktioniert so, wie es soll.
