### ISSUE TITLE
Repeat dosn't work

### ISSUE THREAD

**Issue by andreas-dd** [iobroker-community-adapters/ioBroker.mihome-vacuum#781]
I have a problem with the "Repeat". No matter if I specify the "repeat" in the Room or in a zone cleaning, the robot drives only once. 

- Adapter version: 3.9.5. 
- JS-Controller version: 4.0.24
- Node version: 12.22.5
- vacuum cleaner: Roborock S7 (roborock.vacuum.a15)

**Comment by dirkhe** [comment]
Please add debug log. And what is the content of dp unsuportet?

**Comment by andreas-dd** [comment]
Mea culpa! I should have looked in there myself. I passed a string instead of a number via NodeRed. Now everything works. Thanks for the effort.
