### ISSUE TITLE
Unable to bypass currently active cleaning process (Missing stopVacuuming)

### ISSUE THREAD

**Issue by sd-nxp** [iobroker-community-adapters/ioBroker.mihome-vacuum#784]
**Describe the bug**  
Szenario: 
- I would like to send the robot to a room for cleaning.
- After a short time I change my mind or even see that the robot has just finished. 
- In order to send the robot to the next room, i have to wait for the robot to go back to the docking station.

=> Unable to bypass currently active cleaning process without sending the robot to the docking station.

**To Reproduce**  
- start cleaning segment
- pause
- start cleaning the same segment / different segment

**Expected behavior**  
Provide stopVacuuming() method in control.

**Screenshots & Logfiles**  
![grafik](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/3188139/a7d469e3-1956-4723-8a98-4d68ed114642)

**Versions:**

-   Adapter version: 3.9.5
-   JS-Controller version: 4.0.23
-   Node version: v14.21.1
-   vacuum cleaner: roborock.vacuum.s5e

mihome-vacuum.0 | 2023-05-12 15:13:10.495 | info | should trigger cleaning segment 17, but is currently active(18). Add to queue
-- | -- | -- | --
mihome-vacuum.0 | 2023-05-12 15:12:59.445 | warn | State value to set for "mihome-vacuum.0.control.water_box_mode" has value "207" greater than max "204"
mihome-vacuum.0 | 2023-05-12 15:12:55.977 | info | should trigger cleaning segment 19, but is currently active(18). Add to queue
mihome-vacuum.0 | 2023-05-12 15:12:39.291 | warn | State value to set for "mihome-vacuum.0.control.water_box_mode" has value "207" greater than max "204"
mihome-vacuum.0 | 2023-05-12 15:12:38.743 | warn | State value to set for "mihome-vacuum.0.control.water_box_mode" has value "207" greater than max "204"
mihome-vacuum.0 | 2023-05-12 15:12:38.659 | warn | State value to set for "mihome-vacuum.0.control.water_box_mode" has value "207" greater than max "204"
mihome-vacuum.0 | 2023-05-12 15:12:38.652 | info | trigger cleaning segment 22

**Comment by dirkhe** [comment]
the robot does not know stop, only home or pause.
Try this
while cleaning room1, send cleanjng room2 (will be add to aueue), send home.
The queue function is implemented by me, so if the robot send status change, the next room ftom queue will start. So it could be, that it takes some sec until it dtart the next room. 
But ee can not change the firmware

**Comment by IchBauPV** [comment]
gelöst/solved: Zonenreinigung unterbrechen, und andere Zonenreinigung starten ohne Rückkehr an dockingstation / Stop command senden

Getestet für Mi-Roboter 1, node.JS 18.18.2, mihome vacuum Adapter 3.9.5

Man muss in beim mihome vacuum Adapter (Instanz, Settings) den Haken bei "Sende eigene Befehle" setzen. Dadurch erscheint in der Objektliste unter control zusätzlich der Eintrag "x_send_command". Wenn man hier den Wert
stop_zoned_clean
einträgt, wird die Zonenreinigung gestoppt. Im Anschluss kann unmittelbar eine neue Zonenreinigung gestartet werden. 
Man kann dann die beiden Befehle auch in einer Szene zusammenfassen, um eine laufende Zonenreinigung direkt durch eine neue zu ersetzen. Nach meinen Tests muss der Abstand von Stop command und neuem Aufruf mindestens eine Sekunde besser 1,5 Sekunden betragen.
Das funktioniert übrigens auch, wenn der Sauger sich auf dem Weg zur Dockingstation befindet. Hier muss vorher einmal der Pause Befehl gesendet werden. Danach kann wie oben beschrieben eine neue Zone gewählt werden. Wichtig ist, dass der Roboter sich schon auf dem Rückweg befindet, und nicht in der Dreh/Suchphase, die muss man erst abwarten.
