### ISSUE TITLE
Support for „real“ room cleaning

### ISSUE THREAD

**Issue by amathebest123** [iobroker-community-adapters/ioBroker.mihome-vacuum#79]
First of all: great work, my appreciation! 

I tried this adapter with the new model Roborock s4 and it works! 

However with the latest version of the mihome app it’s possible to create rooms and even give them names. 

Would it be possible to integrate this interface so that rooms can be targeted directly?

Unfortunately I’m not an experienced code and can do it hey my own...

Thanks in advance for a reply.

**Comment by MeisterTR** [comment]
please try these commands with the selfcomand object in the adapter:
get_room_mapping
get_segment_status

**Comment by amathebest123** [comment]
Thanks for the reply. 

I tried get_room_mapping, here the result:

[[16,"895001005948"],[17,"895001005870"],[18,"895001005941"],[19,"895001005943"],[20,"895001005942"],[21,"895001005944"],[22,"895001005945"],[23,"895001005946"],[24,"895001005947"]]

A very nice result, I think these are my rooms, as the number matches exactly. 

But how can I tell him to use these „coordinates“ to start cleaning? I tried it with zone clean, but it didn’t work. Do you have an idea?

I also tried the command get_segment_status, it returned only „[1]“, no matter if I use some of the rooms as parameters or not (e.g. get_segment_status;[17,"895001005870"]).

**Comment by amathebest123** [comment]
Hey there,
Sorry for the delay in answer, lot of stuff to do.

In the meantime everything runs perfectly for me, here is what I figured out:

App_segment_clean;[parameter] works, even with more than one room. However, the order of the segments will be ignored, means you can‘t choose which room to clean first. Solved this issue in iobroker with an array from which the commands are sent one after another.

App_zoned_clean also works as command, only btw

Pause command works, resuming with either resume_segment_clean or resume_zoned_clean works perfectly.

So, what do the number you get from the command get_room_mapping mean? Well, the first number is the number of the segment/room. But the number between the „“ - I really don’t know. I assume it’s some kind of description of the room in the mihome app. It seems that there‘s a system behind, but i can’t  figure out which.

Result of get_segment_status: I tried nearly every combination. I send the command as the robo was charging, as he was cleaning, with argument, without argument - however the response was always „[1]“. Don’t know what I should do with this.

**Comment by ozboss** [comment]
This is amazing. Where can I find a documentation for these commands? Or how did you find out about these commands?

**Comment by amathebest123** [comment]
Go to the page https://python-miio.readthedocs.io/en/latest/miio.html

And search for the chapter named “miio.vacuum module„.

**Comment by tschaefer-cema** [comment]
Hi, I´ve got an Mijia 1s, got the token and the adapter works great! 
But what doesn´t work is the room cleanup by the IDs from "get_room_mapping". 
As a response I get the IDs which seems to look good (17, 21, and so on). But when I try to send the command App_segment_clean;[17] as a response I get "unknown method".

Other commands like set_dnd_timer are working.

Any ideas?

**Comment by amathebest123** [comment]
Please use „app_segment_clean“ instead of „App_segment_clean“ -> no capital „A“. It was a mistake from my auto correction as I wrote this post by mobile phone.

**Comment by t6a** [comment]
This workaround here is not even in the readme of the adapter...
It would be great if the adapter does the work and creates states (with a button) for each zone (room) automatically, so that I (or a script) can just press the button and the robot cleans the respective zone.

**Comment by dirkhe** [comment]
Hi @amathebest123 ,

please have a look here 
https://forum.iobroker.net/topic/28615/adapter-mihome-vacuum-anpassungen/12

**Comment by dirkhe** [comment]
Is Implemented in v 1.10
