### ISSUE TITLE
Map does not load in Xiaomi App when adapter is connected to the robot

### ISSUE THREAD

**Issue by BigMastA88** [iobroker-community-adapters/ioBroker.mihome-vacuum#790]
I don't know when it started, but my Xiaomi Home App can not load the map anymore.

In this thread I read about the same problem and the guys seem to know the reason. 

https://www.roboter-forum.com/threads/serverproblem-roborock-geraete-sind-ueber-die-xiaomi-home-app-nicht-erreichbar.55061/page-2

And I can confirm. When I stop the adapter and wait til the next day, everything works fine. Is there any setting I can try to solve the problem. I need both, the app and the adapter.

**Versions:**

-   Adapter version: <3.9.5>
-   JS-Controller version: <4.0.24>
-   Node version: <node-version> <20.0.0>
-   vacuum cleaner: <roborock.vacuum.s5, FW: 3.5.8_002034>

**Comment by Ilovegym66** [comment]
Hi, Test the latest Version from Git, please.

**Comment by BigMastA88** [comment]
Ok, I installed 3.11.0 from Git. Will report the result asap

**Comment by BigMastA88** [comment]
Hi, everything looks fine so far. Thx
