### ISSUE TITLE
Please add NPM package to iobroker-community-adapters:developers team

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.mihome-vacuum#80]
verifying all repos and NPM ownership we noticed the NPM package of this repo is not part of our team.

please execute : 

`npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>`

or add the package by web : 

https://www.npmjs.com/settings/iobroker-community-adapters/teams/team/developers/access

**Comment by Apollon77** [comment]
Done. Please verify

**Comment by MeisterTR** [comment]
looks god !

**Comment by DutchmanNL** [comment]
Thanks ;)
