### ISSUE TITLE
Mop Cleaning for new Generation

### ISSUE THREAD

**Issue by JoJ123** [iobroker-community-adapters/ioBroker.mihome-vacuum#81]
I've integrated these changes one year ago:
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/pull/61/files

Today I've detected, that the special value _"105"_ for the S5 roborock is not there anymore.
I will try to have a look what is going wrong.

**Comment by dirkhe** [comment]
Is fixed in v 1.10
