### ISSUE TITLE
roborock.vacuum.a70 not supported (but works)

### ISSUE THREAD

**Issue by tipp88** [iobroker-community-adapters/ioBroker.mihome-vacuum#816]
-   roborock
-   modell S8 Ultra Pro
-   Bezeichnung roborock.vacuum.a70

Adapter sagt "Model roborock.vacuum.a70 not supported! Please open issue on git: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues"
Ich habe den Roborock S8 Ultra Pro mittels des Adapters eingebunden (Xiaomi Cloud nicht roborock App) und kann keine Probleme feststellen. Alle Datenpunkte funktionieren und machen was sie sollen. Meines Erachtens kann der Roboter in die supported devices aufgenommen werden.
![image](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/68737433/97a03722-8326-4c6b-bf04-50c9c4f625b1)

**Comment by dirkhe** [comment]
added in 4.0
