### ISSUE TITLE
Object "Vacuum state" missing state (cleaning rooms)

### ISSUE THREAD

**Issue by ltsalvatore** [iobroker-community-adapters/ioBroker.mihome-vacuum#82]
Hi there.. 
i have a new roborock s5 max.. 
my vis shows me the status of the vacuum, which worked fine with the old model. 

unfortunately the vacuum state is not being shown if i use **room** cleaning. 
i noticed that the value of the object displayed is different than the others... 

normally you have something like "status(number)"
if i select room cleaning the value is just a number... in that specific case it is the number **18**.

with the widget "basic - view in widget" it shows every status i set, except for the 18...

is it yet not well implemented?

**Comment by Diginix** [comment]
I have model 1S and did some enhancements for this model, but not yet commited to git.
The state for room cleaning is number 18.
Due to not knowing which other vacuum model supports this, my enhancement checks the model type and at the moment only whether it is a "roborock.vacuum.m1s". Also the "fan_power" has 4 new different values for my model.
Maybe I have to ask @MeisterTR or some other involved dev. how to merge the new model specific stuff correct for keeping the adapter generic. Then I can make a pull request in near future.

**Comment by ltsalvatore** [comment]
Hi diginix, 

thanks for your feedback. 
i finally got it working
i edited the object raw data and added a new line with "18": "Room Cleaning"

i dont know why it did not work instantly... but now it works.

**Comment by honk95** [comment]
> I have model 1S and did some enhancements for this model, but not yet commited to git.
> The state for room cleaning is number 18.
> Due to not knowing which other vacuum model supports this, my enhancement checks the model type and at the moment only whether it is a "roborock.vacuum.m1s". Also the "fan_power" has 4 new different values for my model.
> Maybe I have to ask @MeisterTR or some other involved dev. how to merge the new model specific stuff correct for keeping the adapter generic. Then I can make a pull request in near future.

Can you commit your changes? I cannot get my mi robot 1S to run and your other changes also sound really useful

**Comment by Diginix** [comment]
It's already committed to my fork. But it will not help if the old adapter won't run with your 1S. I was able to use my 1S fully with adapter version 1.1.6 without my changes.

**Comment by dirkhe** [comment]
@ltsalvatore, @honk95 can you check, if this with current Version 1.10.1 solved?

**Comment by ltsalvatore** [comment]
> @ltsalvatore, @honk95 can you check, if this with current Version 1.10.1 solved?

i do have the version 1.1.5 installed currently... 
how do i get the latest version installed. i was expecting the versions above 1.1.5 to be shown under adapter updates

**Comment by dirkhe** [comment]
Sou have to install the adapter via git over own URL and than Search for mihome-vakuum

**Comment by ltsalvatore** [comment]
ok.. i have installed the adapter and everything looks fine so far.. 
though i cant tell if it is because i did the changes manually or if the come from the update now.. 
guess someone else who hasnt done any manual changes would be the apropriate candidate to test. 

to me the issues is solved 
so feel free to close this issues.
