### ISSUE TITLE
Model roborock.vacuum.a70 not supported! Please open issue on git

### ISSUE THREAD

**Issue by BrightM91** [iobroker-community-adapters/ioBroker.mihome-vacuum#824]
**Infos zum Gerät:**
Achtung! Aktuell nur Roborock Geräte anfragen
-   roborock
-   modell Roborock S8 Ultra Pro
-   Bezeichnung roborock.vacuum.a70

aktuellstes Modell von Roborock

Steuerung mit dem Adapter ist möglich, soweit beurteilbar. Das Übertragen von Map und Räumen jedoch nicht. Ich habe schon viel Manuell probiert die hinzuzufügen, leider ohne Erfolg

**Comment by dirkhe** [comment]
Wurde in der 4.0 hinzugefügt, hier funktioniert anscheinend such die karte
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/816

**Comment by dirkhe** [comment]
Was die karte angeht, stelle auf jeden fall sicher, das canvas korrekt installiert ist. Das Forum ist voll mit Hinweisen
