### ISSUE TITLE
Reinigungszyklen einstellen

### ISSUE THREAD

**Issue by Kusi-Schweiz** [iobroker-community-adapters/ioBroker.mihome-vacuum#825]
Was funktioniert:
Wenn ich einen einzelnen Raum reinige, dann funktioniert die Funktion "Repeat" einwandfrei und der Raum wird in unterschiedliches Muster gereinigt.

Was nicht funktioniert:
Wenn ich mehrere Räume reinige, dann funktioniert die Funktion "Repeat" nicht.
Es ist egal, ob ich bei allen Räume denselben Repeat-Wert einfüge, oder ob diese unterschiedlich sind.
Ändere ich die "Zyklen" in der App, dann sehe ich keinen Wert, welcher sich in ioBroker ändert (dies zur Info).

Getestet mit Roborock S7 MaxV Ultra.
Installiert ist der Adapter in der Version 3.11.0

Siehe auch #690

**Comment by Kusi-Schweiz** [comment]
Welchen Bereich genau brauchst du??

Ich habe ein Skript geschrieben, mit welchem bei allen Räumen der "Repeat"-Wert auf einmal ändert.
Wenn ich die Reinigungszyklen verstelle, dann wird mir im Debug folgendes angezeigt:
`<html>
<body>


mihome-vacuum.0 | 2023-08-19 07:49:37.813 | debug | command: repeat parent: 181001061006
-- | -- | -- | --
mihome-vacuum.0 | 2023-08-19 07:49:37.813 | debug | command: repeat parent: 181001061005
mihome-vacuum.0 | 2023-08-19 07:49:37.812 | debug | command: repeat parent: 181001061004
mihome-vacuum.0 | 2023-08-19 07:49:37.811 | debug | command: repeat parent: 181001061003
mihome-vacuum.0 | 2023-08-19 07:49:37.810 | debug | command: repeat parent: 181001061002
mihome-vacuum.0 | 2023-08-19 07:49:37.810 | debug | command: repeat parent: 181001061001
mihome-vacuum.0 | 2023-08-19 07:49:37.808 | debug | command: repeat parent: 181001061000
mihome-vacuum.0 | 2023-08-19 07:49:37.807 | debug | command: repeat parent: 181001060999
mihome-vacuum.0 | 2023-08-19 07:49:37.765 | debug | command: repeat parent: 181001060996
mihome-vacuum.0 | 2023-08-19 07:49:37.764 | debug | command: repeat parent: 181001060981


</body>
</html>`

Wenn ich einen einzelnen Raum mit 2 Reinigungszyklen starte, dann erhalte ich folgendes Log:
`<html>
<body>


mihome-vacuum.0 | 2023-08-19 07:58:03.268 | debug | start Cleaning: 18 MObj: {"command":"cleanSegments","message":"21","from":"system.adapter.mihome-vacuum.0","_id":23953814,"segments":[21],"channels":["mihome-vacuum.0.rooms.181001061000"]}
-- | -- | -- | --
mihome-vacuum.0 | 2023-08-19 07:58:03.268 | debug | We are in onMessage:{"command":"cleanSegments","message":{"segments":[21],"channels":["mihome-vacuum.0.rooms.181001061000"]},"from":"system.adapter.mihome-vacuum.0","_id":23953814}
mihome-vacuum.0 | 2023-08-19 07:58:03.257 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
mihome-vacuum.0 | 2023-08-19 07:58:03.246 | debug | command: multiRoomClean parent: rooms


</body>
</html>`

Wenn ich 2 Räume mit 2 Reinigungszyklen starte, dann erscheint folgendes:
`<html>
<body>


mihome-vacuum.0 | 2023-08-19 08:07:33.962 | debug | get params for stock Vacuum
-- | -- | -- | --
mihome-vacuum.0 | 2023-08-19 08:07:31.463 | debug | Time difference between Mihome Vacuum and ioBroker: -1692406875 sec
mihome-vacuum.0 | 2023-08-19 08:07:31.463 | debug | Receive <<< Helo <<< 21310020000000002620d78f000047c8ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2023-08-19 08:07:21.451 | debug | Time difference between Mihome Vacuum and ioBroker: -1692406875 sec
mihome-vacuum.0 | 2023-08-19 08:07:21.451 | debug | Receive <<< Helo <<< 21310020000000002620d78f000047beffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2023-08-19 08:07:14.895 | debug | command: multiRoomClean parent: rooms
mihome-vacuum.0 | 2023-08-19 08:07:13.943 | debug | MIIO RECIVE: {"id":124,"result":["ok"],"exe_time":11}
mihome-vacuum.0 | 2023-08-19 08:07:13.942 | debug | MIIO MESSAGE TESTING: {"id":124,"result":["ok"],"exe_time":11}
mihome-vacuum.0 | 2023-08-19 08:07:13.919 | debug | Message= {"id":124,"method":"app_segment_clean","params":[21,25]}
mihome-vacuum.0 | 2023-08-19 08:07:13.918 | info | trigger cleaning segment 21,25
mihome-vacuum.0 | 2023-08-19 08:07:13.918 | debug | start Cleaning: 18 MObj: {"command":"cleanSegments","message":"21,25","from":"system.adapter.mihome-vacuum.0","_id":23953815,"segments":[21,25],"channels":["mihome-vacuum.0.rooms.181001061000","mihome-vacuum.0.rooms.181001061005"]}
mihome-vacuum.0 | 2023-08-19 08:07:13.918 | debug | We are in onMessage:{"command":"cleanSegments","message":{"segments":[21,25],"channels":["mihome-vacuum.0.rooms.181001061000","mihome-vacuum.0.rooms.181001061005"]},"from":"system.adapter.mihome-vacuum.0","_id":23953815}
mihome-vacuum.0 | 2023-08-19 08:07:13.904 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
mihome-vacuum.0 | 2023-08-19 08:07:13.892 | debug | command: multiRoomClean parent: rooms


</body>
</html>`

**Comment by dirkhe** [comment]
Was genau triggerst du denn? Wenn du 2 räume gleichzeitig direkt an den staubi triggerst, must du das repeat mitgeben, siehe doku.
Wenn du repeat in den raum dp verstellst, wird das nur gezogen, wenn der raum über den adapter direkt getriggert wird und es auch nur den raum betrifft.

**Comment by Kusi-Schweiz** [comment]
Mein Vorgehen für die Reinigung, identisch ob ein oder mehrere Räume:

Ich befülle beim Datenpunkt "mihome-vacuum.0.rooms.multiRoomClean" den Raum mit den Räumen, welche ich gereinigt haben möchte. Dann starte ich die Reinigung mit "mihome-vacuum.0.rooms.multiRoomClean".
Sämtliche Einstellungen wie "Saugstärke", mit/ohne Aufwischen usw. verstelle ich vor dem Start direkt in ioBroker, mit Änderung der Datenpunkte "mihome-vacuum.0.control.fan_power", "mihome-vacuum.0.control.water_box_mode" und "mihome-vacuum.0.control.mop_mode".

Ist dieses Vorgehen somit falsch?

**Comment by dirkhe** [comment]
Genau, denn wenn mehrere räume auf einmal gereinugt werden soll, von welchem raum soll er denn dann die einstellungen übernehmen. Wenn du beide räume nacheinander triggerst, reinigt er erst raum1, mit seinen einstellungen, den 2. Raum packt er dann erst in eine queue, wenn dann raum1 fertig ist, startet er raum2, mit seinen einstellungen.
Wenn du aber eh blocky nutzt, mache es doch über sendto via clean segments

**Comment by Kusi-Schweiz** [comment]
> sendto via clean segments

Dies ist Neuland für mich... Kannst du mir sagen, wie man dies macht?

**Comment by dirkhe** [comment]
mit blocky selber kenne ich mich leider nicht aus, ist mir zu kompliziert und unübersichtlich.
`sendTo("mihome-vacuum.0", 
    "cleanSegments", 
 {rooms:[23,24],fanSpeed:100,repeat:3}, 
    function (response) { /* do something with the result */}
);`
Probiere mal so, du kannst suvh sofort mehrere sachen mitübergeben, siehe readme

**Comment by Kusi-Schweiz** [comment]
Problem gelöst, indem ich mit Blockly und Javascript-Funktion die Reinigung starte.
Siehe in meinem [Forumbeitrag](https://forum.iobroker.net/topic/28615/adapter-mihome-vacuum-anpassungen/456?_=1693193355445)
