### ISSUE TITLE
Meldung "Wasserfilter reinigen" fehlt "Roborock S7 MaxV Ultra

### ISSUE THREAD

**Issue by Kusi-Schweiz** [iobroker-community-adapters/ioBroker.mihome-vacuum#829]
Ich bekomme seit einem Tag in meiner "Xiaomi Home"-App untenstehende Meldung.

![Screenshot_20230828-044335](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/71840093/c66702fa-bc16-43f2-a330-b386e9e2e4d2)

![Screenshot_20230828-044345](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/71840093/bc0f455d-79df-4176-9457-11bdd81352f5)

Lässt sich dies auch in den miHome-Adapter integrieren?

**Comment by dirkhe** [comment]
Wie sieht denn die kommunikation mit dem adapter aus?
Im prinzip gibt es ja die consumables datenpunkte, wo das dtin stehen sollte. Eine warnung gibt der adapter aber nicht aus

**Comment by Kusi-Schweiz** [comment]
> Wie sieht denn die kommunikation mit dem adapter aus?

Was meinst du damit?

Den Wasserfilter habe ich nicht in "consumables".

![Screenshot_20230828-222349](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/71840093/c04036a0-f389-4202-8033-5cc0ea86939d)

**Comment by Kusi-Schweiz** [comment]
![Uploading Screenshot_20230828-222614.png…]()

**Comment by dirkhe** [comment]
Dann zeige bitte mal das log, da sollte dann bei den consumables ein wert übermittelt werden

**Comment by Kusi-Schweiz** [comment]
`2023-08-28 05:17:07.199  - [34mdebug[39m: mihome-vacuum.0 (157469) Message= {"id":314,"method":"get_consumable"}
2023-08-28 05:17:07.199  - [34mdebug[39m: mihome-vacuum.0 (157469) Message= {"id":315,"method":"get_network_info"}
2023-08-28 05:17:07.220  - [34mdebug[39m: mihome-vacuum.0 (157469) MIIO MESSAGE TESTING: {"id":314,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":151,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":10}
2023-08-28 05:17:07.220  - [34mdebug[39m: mihome-vacuum.0 (157469) MIIO RECIVE: {"id":314,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":151,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":10}
2023-08-28 05:17:07.220  - [34mdebug[39m: mihome-vacuum.0 (157469) MIIO MESSAGE TESTING: {"id":314,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":151,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":10}`

**Comment by Kusi-Schweiz** [comment]
`<html>
<body>


mihome-vacuum.0 | 2023-08-29 01:10:52.043 | debug | MIIO MESSAGE TESTING: {"id":4,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":151,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":10}
-- | -- | -- | --
mihome-vacuum.0 | 2023-08-29 01:10:52.043 | debug | MIIO RECIVE: {"id":4,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":151,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":10}
mihome-vacuum.0 | 2023-08-29 01:10:52.043 | debug | MIIO MESSAGE TESTING: {"id":4,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":151,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":10}
mihome-vacuum.0 | 2023-08-29 01:10:52.013 | debug | Message= {"id":5,"method":"get_network_info"}
mihome-vacuum.0 | 2023-08-29 01:10:52.013 | debug | Message= {"id":4,"method":"get_consumable"}


</body>
</html>`

**Comment by Kusi-Schweiz** [comment]
`<html>
<body>


mihome-vacuum.0 | 2023-08-29 01:22:21.741 | debug | MIIO MESSAGE TESTING: {"id":17,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":0,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":11}
-- | -- | -- | --
mihome-vacuum.0 | 2023-08-29 01:22:21.740 | debug | MIIO RECIVE: {"id":17,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":0,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":11}
mihome-vacuum.0 | 2023-08-29 01:22:21.740 | debug | MIIO MESSAGE TESTING: {"id":17,"result":[{"main_brush_work_time":313778,"side_brush_work_time":313778,"filter_work_time":313778,"filter_element_work_time":0,"sensor_dirty_time":195498,"strainer_work_times":0,"dust_collection_work_times":150,"cleaning_brush_work_times":151}],"exe_time":11}


</body>
</html>`

Hier das Log, nachdem ich den **Wasserfilter zurückgesetzt** habe.

**Comment by dirkhe** [comment]
V 4.1.0 Bitte mal testen, ob die jetzt angezeigt werden, du solltest 3 weitere states + reset button bekommen, alle 3 sind reine Zähler, also nicht als %

**Comment by Kusi-Schweiz** [comment]
Mir werden (nur) 2 weitere States angezeigt, und zwar "dust_collection" und "strainer".

Fragen zur Bezeichnung:
Bedeutet "dust_collection" Staubbeutel? Dieser wird in der App als "nach Bedarf ersetzen" angezeigt.
Bedeutet "strainer" vielleicht Wasserfilter? Übersetzt würde dies Sieb bedeuten.
Dann würde allerdings die Reinigungsbürste fehlen...

![image](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/71840093/165f6146-9d69-4aa2-a97a-3997b9b54d96)

**Comment by dirkhe** [comment]
Ja leider ist das so, wie das aufgebaut ist, nicht so einfach. Ist auf jeden Fall eine Menge Arbeit, weil dann ziemlich viel umprogrammiert werden muss. Wenn ich mal ganz viel Zeit habe, müsste ich das alles nochmal komplett überarbeiten, daher mache ich das erstmal wierder zu hier
