### ISSUE TITLE
Erweiterung des Adapters um eine Berechnung des Füllstand des Behälters sowie das Anfahren zum Mülleimer (GoTo-Punktes)

### ISSUE THREAD

**Issue by mumu-rik** [iobroker-community-adapters/ioBroker.mihome-vacuum#85]
Wünschenswert wäre eine Erweiterung des Adapters um eine Berechnung des Füllstand des Behälters sowie das automatische Anfahren zum Mülleimer (GoTo-Punktes) sobald ein gesetzter Schwellwert erreicht worden ist.

Aktuell habe ich dies mit einem Skript gelöst, eventuell könnte man dies als Denkanstoß zu Implementierung nehmen.

Das Skript ist nicht super elegant gelöst, funktioniert aber soweit für mich...

`// Behälterstand in % für VIS 
on({id: 'javascript.0.Staubsauger.Behaelterstand', change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
 
 // 200=200qm=100% Behälterstand
  setState("javascript.0.Staubsauger.Behaelterstand_prozent"/*Behaelterstand_prozent*/, ((getState("javascript.0.Staubsauger.Behaelterstand").val * 100) / 200), true);
});

on({id: 'mihome-vacuum.0.info.state', change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
 
 // Behälterstand wird aus gefahrenen qm + dem aktuelle Behälterstand zusammen gerechnet
  if (getState("mihome-vacuum.0.info.state").val == 6) {
    setState("javascript.0.Staubsauger.Behaelterstand"/*Behaelterstand*/, (getState("javascript.0.Staubsauger.Behaelterstand").val + getState("mihome-vacuum.0.info.cleanedarea").val), true);
  }
  // bei 80% Behälterstand wird zu einem goTo-Punkt (Mülleimer) gefahren und die Hilfsvariable wieder auf 0 (geleert) gesetzt
  if (getState("javascript.0.Staubsauger.Behaelterstand_prozent").val == 80 && getState("mihome-vacuum.0.info.state").val == 8) {
    setState("mihome-vacuum.0.control.goTo"/*Go to point*/, 'xyz,xyz');
    sendTo("telegram", "send", {
        text: 'Staubsauger leeren ! 🚮'
    });
    setState("javascript.0.Staubsauger.Behaelterstand"/*Behaelterstand*/, 0, true);
  }
});`

**Comment by Diginix** [comment]
Der Flächenwert ist aber bei jedem ein anderer und noch nicht mal pro Haushalt wird einer dauerhaft passen. Nur wer den Sauger täglich per Timer arbeiten lässt, kann evtl. einen Flächenwert ermitteln nachdem der Behälter in den meisten Fällen entleert werden sollte.
Es muss also die Gesamtfläche inkl. Saugvorgängen und über welchen Zeitraum betrachtet werden.
Bei 10 Saugvorgänge in einem 20 qm Raum in 10 Tagen kommt weniger zusammen als 200 qm am Stück wenn dies nur 1 mal im Monat gesaugt worden.

Die Idee ist gut aber wahrscheinlich nur wie bei dir mit einem persönlichen Skript brauchbar realisierbar.

**Comment by dirkhe** [comment]
Ich denke, ich werde zumindest mal einen Button einbauen, der den Staubi zum Mülleimer schickt, nachdem man seine Koordinaten hinterlegt hat.
Den könnte man dann auch Alexa zugänglich machen.
Vlt. könnte man eine Mischung aus maxZeit und maxFläche nehmen?

**Comment by Diginix** [comment]
Der Button ist eine gute Idee. Den habe ich bei mir auch weil die Ladestation unter der Couch steht.
Ich sage "Alexa, Staubsauger ausparken" und er fährt unter der Couch vor.
Für den Füllstand braucht es mMn 3 Parameter: Fläche pro Zeit und Saugvorgänge

Ich lasse ca. 1-2mal die Woche die Wohnung saugen. Würde er täglich fahren, wäre der Behälter erst nach deutlich mehr Fläche voll weil sich in der kürzeren Zeit zwischen den Saugvorgängen weniger Staub am Boden sammelt.

**Comment by dirkhe** [comment]
Obwohl Fläche  pro zeit ist bei mir ca 1, da er für 1m2 ca 1 min. Braucht. Das hängt natürlich auch von der saugstärke ab. Müsste man einfach mal testen und die Parameter einstellbar machen

**Comment by Diginix** [comment]
Ich meine nicht die Zeit die er pro qm braucht.
Ich habe doch oben schon ein Beispiel geschrieben:
"Bei 10 Saugvorgänge in einem 20 qm Raum in 10 Tagen kommt weniger zusammen als 200 qm am Stück wenn dies nur 1 mal im Monat gesaugt worden."
Hier wäre also die Zeit nicht die 200 Minuten sondern 10 Saugvorgänge geteilt durch 10 Tage im Gegensatz zu 1 Saugvorgang an einem Tag.
Wenn du jeden Tag 200 Minuten saugst, ist der Behälter sicher nicht jedesmal voll. Aber ganz sicher wenn du 200 qm über ein Jahr verteilt saugst.

**Comment by dirkhe** [comment]
Sorry, hab ich nicht genau genug gelesen, ja haste recht. Ich mach mir mal Gedanken

**Comment by MeisterTR** [comment]
ein button für einen Festgelegten punkt ist eine Möglichkeit, aber  die Adapter sollten sich auf die Grundfunktionen die das jeweilige Gerät zur Verfügung stellt, beschränken. Gerade die Behälterleerung die von vielen Sachen abhängt und vom Sauger nicht bereit stellt. Für solche Sachen gibt es ja den Javascript Adapter...

**Comment by Coffee-lover** [comment]
Ich bin der gleichen Meinung wie @MeisterTR . Eine einfache Lösung ohne aufwändige Berechnung: Mein Robbi fährt jeden Samstag um 09:00 zum Abfalleimer. Um 11:00 fährt er zurück. Da ist die Wahrscheinlichkeit sehr groß, dass er in der Sitation auch geleert wird. Im Adapter brauche ich sowas nicht.

**Comment by Diginix** [comment]
Ich habe das jetzt bei mir seit Monaten im Test und bei meinem Rhythmus alle 6 Tage ca. 80 qm ist der Behälter nach 250 qm voll. Somit habe ich einen eigenen Datenpunkt und wenn der >= 250 ist dann fährt der Sauger unter dem Sofa vor oder bleibt nach der Reinigung direkt davor stehen wenn der Akku >10% hat.
Komme ich heim, sagt mir Alexa dass der Staubbehälter geleert werden sollte und parkt aus falls er nicht schon vor dem Sofa steht.
Im Adapter bräuchte es also max. einen solchen State für die gereinigte Fläche seit letzter Leerung und ein Button der ihn nullt. Aber das lässt sich eben auch bequem mit eigenen Objekte lösen. Das persönliche Skript für Aktionen bzw. Benachrichtigung braucht man sowieso.

**Comment by linchen4000** [comment]
> Um 11:00 fährt er zurück. Da ist die Wahrscheinlichkeit sehr groß, dass er in der Sitation auch geleert wird. 

Es wäre natürlich cool, einen Status im Adapter über den Staubbehälter zu bekommen. (Behälter entfernt & Behälter wieder eingesetzt). Dadurch könnte der Roboter 5 Sekunden nachdem der Behälter geleert worden ist, wieder automatisch zurück zur Dockingstation fahren.

**Comment by MeisterTR** [comment]
Der Füllstand wird vom Roboter nicht unterstützt. Scripte und Workaround können im Forum Besprochen werden
