### ISSUE TITLE
Multiroom Cleaning

### ISSUE THREAD

**Issue by schneidy76** [iobroker-community-adapters/ioBroker.mihome-vacuum#850]
Hi,
wie kann ich dies umsetzen?
`Wenn man spontan mal mehrere Räume reinigen will, kann man das über multiRoomClean tun, indem man diesem Datenpunkt die ioBroker-Räume zuweist und dann den Button drückt.`
Ich habe noch keine Möglichkeit gefunden, wie man dies in ioBroker, oder Node-Red umsetzen könnte. Im Forum konnte mir auch bisher Keiner helfen.
Über Hilfe wäre ich echt dankbar.
LG Torsten

**Comment by dirkhe** [comment]
Im Admin weißt du jedem Raum einen iobroker Raum zu. Wenn du dann den multiroom Button dann auch mehrere Räume zumeist und dann drückst, saugt er los. Ist aber nur für Mal eben manuell. Du kannst auch direkt die Einzelräume nacheinander drücken, werden mittlerweile gequeued

**Comment by mcm1957** [comment]
Solche FRAGEN sollten besser im Forum diskutiert werden - was du aber offensichtlich schon versucht hast.

Trotzdem schließe ich hier mal, da es nicht um einen Featurerequest oder einen Fehler geht. Eine Antwort hast du ja schon erhalten.
