### ISSUE TITLE
Model roborock.vacuum.a51 not supported!

### ISSUE THREAD

**Issue by eric4980** [iobroker-community-adapters/ioBroker.mihome-vacuum#859]
**Infos zum Gerät:**
Achtung! Aktuell nur Roborock Geräte anfragen
-   roborock
-   S8
-   Bezeichnung roborock.vacuum.a51

**Wichtig**  
Das Einbinden neuer Geräte ist aufwending und erfordert viel Recherche,
hierfür fehlt mir die Zeit. Also bitte sucht selbst auf git ob und wie der Sauger eingebunden werden kann,
und verlinkt die stellen

**Comment by dirkhe** [comment]
Im standard wird die roborock lib gezogen, also sollte soweit alles funktionieren. Bitte bestätige das oder beschreibe, was nicht funktioniert.
Da ich keinen S8 habe, bin ich auf deine rückmeldung angewiesen.
Im einfachsten fall braucht nur das modell hinzugefügt werden, damit die warnung verschwindet

**Comment by eric4980** [comment]
Es funktioniert alles wie es soll. Es geht wie von dir geschrieben nur um die Einbindung des Modells :-)

**Comment by dirkhe** [comment]
4.1
