### ISSUE TITLE
add Roborock S50 version 3.5.7_002008

### ISSUE THREAD

**Issue by Ceel84** [iobroker-community-adapters/ioBroker.mihome-vacuum#87]
the new version 3.5.7_002008 from Roborock S50 doesn´t work

**Comment by MeisterTR** [comment]
Log?

**Comment by MeisterTR** [comment]
Any informations?

**Comment by Ceel84** [comment]
Yes sorry
I have updated the roborock s50 and the Adapter are yellow
![Screenshot_20200123-181905](https://user-images.githubusercontent.com/60227609/73007722-503ea080-3e0d-11ea-9535-df495186523d.jpg)

**Comment by MeisterTR** [comment]
I need a Debug log. If the adapter is yellow the robot is not answering. maybe wrong ip or something else, the adapter work normally with 2008 version.

**Comment by Ceel84** [comment]
The Adapter works fine before i updated to 3.5.7_002008

**Comment by Ceel84** [comment]
Sorry my failure
Nice Idea with the ip
