### ISSUE TITLE
Keine Verbindung mit Gerät oder Dienst

### ISSUE THREAD

**Issue by Tim0thY11** [iobroker-community-adapters/ioBroker.mihome-vacuum#877]
**Describe the bug**  
Der Adapter startet nicht richtig, sodass das gelbe Dreieck erscheint. Verbunden mit Dienst oder Gerät schlägt fehl.

**To Reproduce**  
1. Starten des Adapters
2. Der Startvorgang kann nicht korrekt durchgeführt werden

**Expected behavior**  
Der Adapter müsste sauber starten und eine Verbindung zum Roboter aufbauen.

**Screenshots & Logfiles**  
<img width="834" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/46317239/d71454df-2d47-4f1c-8e5b-70ef55b02089">
<img width="836" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/46317239/8d0a3330-c934-451c-a325-b9381af9bf60">

Unter "Get Devices" findet er meinen S7 sofort. 

<img width="837" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/46317239/d378355a-ac77-4109-ae58-42c65749f675">

Protokoll:
mihome-vacuum.0 | 2023-10-24 10:10:54.130 | info | IOT enabled, create state
-- | -- | -- | --
mihome-vacuum.0 | 2023-10-24 10:10:53.966 | info | starting. Version 4.0.0 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v18.18.2, js-controller: 5.0.12

Weiter geht es im Protokoll leider nicht.

**Versions:**

Adapter version: v0.4.4
JS-Controller version: js-controller: 5.0.12
Node version: node: v18.18.2
Operating system: iobroker v6.10.1
robot: Roborock S7

Ich habe vor kurzem das ganze System (iobroker, node, js-controller, adapter) geupdatet.

**Comment by mcm1957** [comment]
Ich würde empfehlen das Problem (acuh) im Forum anzusprechen forum.iobroker.net. Ev. kriegst du dort schneller eine Rückmeldung.

**Comment by Tim0thY11** [comment]
Der Roborock-Adapter funktioniert besser. Ich nutze diesen nun zur Steueerung.
