### ISSUE TITLE
Adapter lässt sich nicht über git installieren

### ISSUE THREAD

**Issue by Andi19851985** [iobroker-community-adapters/ioBroker.mihome-vacuum#88]
Hallo,
ich versuche momentan die aktuelle Version  mihome-vacuum Adapter zu installieren.
Leider bekomme ich ständig folgende Fehlermeldung:
Fertig mit Fehler: host.rock64 Cannot install https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tarball/585bb16f8436d595b4b8ce94b9fecd87155ecebe: 1

Log:
$ ./iobroker url "https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum" --debug
install https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tarball/585bb16f8436d595b4b8ce94b9fecd87155ecebe
NPM version: 6.9.0
npm install https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tarball/585bb16f8436d595b4b8ce94b9fecd87155ecebe --loglevel error --prefix "/opt/iobroker" (System call)
> canvas@2.6.1 install /opt/iobroker/node_modules/canvas> node-pre-gyp install --fallback-to-build
Package pixman-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `pixman-1.pc'to the PKG_CONFIG_PATH environment variableNo package 'pixman-1' foundgyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp
 ERR!
 configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)gyp ERR! stack     at ChildProcess.emit (events.js:198:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2egyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v10.16.2gyp ERR! node-gyp -v v3.8.0gyp
 ERR! not ok 
node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2enode-pre-gyp ERR! command "/usr/local/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v10.16.2node-pre-gyp ERR! node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the canvas@2.6.1 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-01-27T20_08_01_833Z-debug.log
ERROR: host.rock64 Cannot install https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/tarball/585bb16f8436d595b4b8ce94b9fecd87155ecebe: 1
ERROR: process exited with code 25

**Comment by dirkhe** [comment]
Das scheint ein Problem mit 32 Bit Systemen zu sein, siehe mal hier 
https://forum.iobroker.net/topic/26900/hinzufuegen-von-roomba-adapter-wirft-fehler

**Comment by Andi19851985** [comment]
Vielen Dank für die schnelle Antwort.
Das wars.
Da hätte ich mir die 2 letzten Stunden sparen können.
