### ISSUE TITLE
Bitte "stopZoneClean" Befehl/control hinzufügen - gelöst #784

### ISSUE THREAD

**Issue by IchBauPV** [iobroker-community-adapters/ioBroker.mihome-vacuum#880]
Sorry, wenn das formal nicht ganz korrekt ist - ich versuche hier eine Lösung für das **Stoppen und Neustarten einer  anderen Zonenreinigung OHNE Rückkehr an die Dockingstation)** zu geben und eine Implementierung als command stopZoneClean anzuregen.
DANKE

**Lösung:** "x_send_command"  Wert: stop_zoned_clean

**Version:**Mi-Roboter 1, node.JS 18.18.2, mihome vacuum Adapter 3.9.5

**Lösung mit bestehendem Adapter**
Man muss in beim mihome vacuum Adapter (Instanz, Settings) den Haken bei "Sende eigene Befehle" setzen. Dadurch erscheint in der Objektliste unter control zusätzlich der Eintrag "x_send_command". Wenn man hier den Wert
stop_zoned_clean
einträgt, wird die Zonenreinigung gestoppt. Im Anschluss kann unmittelbar eine neue Zonenreinigung gestartet werden.
Man kann dann die beiden Befehle auch in einer Szene zusammenfassen, um eine laufende Zonenreinigung direkt durch eine neue zu ersetzen. Nach meinen Tests muss der Abstand von Stop command und neuem Aufruf mindestens eine Sekunde besser 1,5 Sekunden betragen.
Das funktioniert übrigens auch, wenn der Sauger sich auf dem Weg zur Dockingstation befindet. Hier muss vorher einmal der Pause Befehl gesendet werden. Danach kann wie oben beschrieben eine neue Zone gewählt werden. Wichtig ist, dass der Roboter sich schon auf dem Rückweg befindet, und nicht in der Dreh/Suchphase, die muss man erst abwarten.

**Comment by dirkhe** [comment]
Wenn du in der config den sendePause Button gesetzt hast, macht er genau das, dass er erst Pause sendet, wenn du stop sendest. Dann würde er schauen, ob noch was in der queue ist und würde dann den Sauger dahin schicken, andernfalls nauch Hause
