### ISSUE TITLE
dreame.vacuum.p2028. "restart loop detected"

### ISSUE THREAD

**Issue by PeKa-123** [iobroker-community-adapters/ioBroker.mihome-vacuum#884]
<html>
<body>

mihome-vacuum.0 | 2023-11-06 12:14:44.235 | info | IOT enabled, create state
-- | -- | -- | --
mihome-vacuum.0 | 2023-11-06 12:14:44.172 | info | starting. Version 4.0.0 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v18.18.2, js-controller: 5.0.16
mihome-vacuum.0 | 2023-11-06 12:14:31.193 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
mihome-vacuum.0 | 2023-11-06 12:14:31.146 | error | adapter disabled
mihome-vacuum.0 | 2023-11-06 12:13:59.491 | info | terminating
mihome-vacuum.0 | 2023-11-06 12:13:58.992 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
mihome-vacuum.0 | 2023-11-06 12:13:58.991 | info | terminating
mihome-vacuum.0 | 2023-11-06 12:13:58.991 | error | Socket Close
mihome-vacuum.0 | 2023-11-06 12:13:58.977 | error | objects.stockConsumable.map is not a function
mihome-vacuum.0 | 2023-11-06 12:13:58.977 | error | TypeError: objects.stockConsumable.map is not a function at DreameManager.init (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/dreame.js:372:45) at DreameManager.main (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/dreame.js:406:3)
mihome-vacuum.0 | 2023-11-06 12:13:58.969 | error | unhandled promise rejection: objects.stockConsumable.map is not a function
mihome-vacuum.0 | 2023-11-06 12:13:58.966 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mihome-vacuum.0 | 2023-11-06 12:13:57.297 | info | IOT enabled, create state
mihome-vacuum.0 | 2023-11-06 12:13:57.246 | info | starting. Version 4.1.0 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v18.18.2, js-controller: 5.0.16

</body>
</html>

</body>
</html>
-->

**Describe the bug**  
Seit mihome-vacuum 4.1.0 bekomme ich fehler mit einem dreame.vacuum.p2028. "restart loop detected" und die Fehler die im Log in der Zeit 12:13Uhr  passieren. Sobald ich wieder auf 4.0.0 gehe ist alles in ordnung. Siehe die Logs um 12:14Uhr. Bei meinem Roborock passiert das nicht. den kann ich in jeder Verssion normal einbinden. Neuinstallationen haben auch nicht geholfen. 

**Versions:**

-   Adapter version: <6.12.2>
-   JS-Controller version: <5.0.16> 
-   Node version: <18.18.2> 
-   vacuum cleaner: <dreame.vacuum.p2028>

**Comment by Airwave1981** [comment]
Auch hier besteht das Problem. Jemand einen Workaround parat?

**Comment by PeKa-123** [comment]
Naja, ein Workaround wäre einfach auf die Version 4.0.0 zurück zu gehen. So habe ich es auch erstmal gemacht. Trotzdem sollte der Fehler ausgebaut werden, wird ja nicht im Sinne des Erfinders sein ...

**Comment by hai5ive** [comment]
Hatte den gleichen Fehler bei meinem neuen Roboter. 
Der alte läuft mit Valetudo ohne Probleme unter 4.1.0 mit 4.0.0 funktionieren beide.

Dadurch, dass der erste Roboter ohne Probleme funktionierte, hat es ewig gedauert, bis ich den Beitrag gefunden habe -.-

**Comment by DemigodCode** [comment]
Ich gucke gleich mal rein. Habe auch 4.1 installiert und scheinbar wurde dreame nicht angepasst. @dirkhe 

mihome-vacuum.0 | 2024-01-03 14:26:20.368 | error | Socket Close
-- | -- | -- | --
mihome-vacuum.0 | 2024-01-03 14:26:20.345 | error | objects.stockConsumable.map is not a function
mihome-vacuum.0 | 2024-01-03 14:26:20.345 | error | TypeError: objects.stockConsumable.map is not a function at DreameManager.init (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/dreame.js:372:45) at DreameManager.main (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/dreame.js:406:3)
mihome-vacuum.0 | 2024-01-03 14:26:20.339 | error | unhandled promise rejection: objects.stockConsumable.map is not a function
mihome-vacuum.0 | 2024-01-03 14:26:20.339 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by DemigodCode** [comment]
Okay, ist mir zu aufwendig. Da wurde die Struktur der Consumables komplett verändert und ist nicht mehr ähnlich zu den anderen. Da müsste ich länger drüber nachdenken. Ich gehe auch zurück auf 4.0

**Comment by dirkhe** [comment]
@DemigodCode  stimmt, dad muss ich noch nachziehen, ich dachte, ich hätte gesucht, aber nichts gefunden. Ich habe das geändert, damit man da mehr generisch drüber iterieren kann . Ich pass das nachher an.
Sorry dafür, aber irgendwie dachte ich wohl,  dass du kpl. Eigene Strukturen nutzt.

**Comment by DemigodCode** [comment]
Genau das wollte ich damals verhindern, damit es nicht ein eigener Adapter innerhalb eines Adapters wird.

Hatte auch mal versucht damals einfach einen eigenen Adapter nur für die Dreame zu schreiben, weil die ganzen Datenpunkte nicht zwingend passten. Hatte mich dann aber dagegen entschieden, da es noch ein Repo mit den Grundfunktionen für alle Sauger hätte geben müssen und ich den Aufwand nicht betreiben wollte.

**Comment by dirkhe** [comment]
Also normalerweise hätte ich das mit angepasst, aber ich arbeite mit visual code und suche dort nach Verwendung im Ornder. Neuerdings haben die dort aber etwas eingebasut, dass er nur noch in offenen Dateinbe sucht, das muss man erst disablem. Das hatte ich übersehen und daher hatte er mir die Verwendung in dreame.js nicht angezeigt.

Ich habe das jetzt nachgezogen, muss aber sagen, dass es vlt nicht so clever ist, eine Negative Liste aufzubauen. Ich hatte nämlich in dem Zuge die Stockcommands auch erweitert. Aktuelle habe ich die "neuen" und die von extendCommand mal in deine Negativliste eingetragen, siehe DreameBlockedObjects, ob ich da aber nächstes mal dran denke, neue Objekte dorrt einzutragen????

Ich lege die Objekte an, wenn ich das 1. mal die Statis der consumables vom robby bekomme. Alle, die es dort gibt, lege ich dann in iobroker an. Bei den consumables gibt es ja immer in pärchen, nämlich den Status und den Button, dementsprechend  habe ich die struktur jetzt aufgebaut.
Wenn ich das auf die Schnelle richtig gesehen habe, solltest du vlt. fragen, ob du ein entsprechendes DreameActions["RESET_" + id.toUppercase()] hast, dann anlegen

**Comment by dirkhe** [comment]
@PeKa-123 du könntest mal die aktuelle Version von github installieren und schauen, ob dein Fehler weg ist

**Comment by chrkan** [comment]
sieht gut aus dreame und robrok s5 werden angesprochen

**Comment by dirkhe** [comment]
Möchtest du dir das noch anschauen und vlt. Bei den consumables  das schon mal umbauen, oder soll ich eine hotfix version raushauen?

**Comment by PeKa-123** [comment]
> @PeKa-123 du könntest mal die aktuelle Version von github installieren und schauen, ob dein Fehler weg ist

Vielen Dank! Der Fehler ist weg!

**Comment by dirkhe** [comment]
hotfix ist raus. Ich schlisse das ticket mal.
