### ISSUE TITLE
Adapter startet nicht durch 

### ISSUE THREAD

**Issue by SidvsKaliman** [iobroker-community-adapters/ioBroker.mihome-vacuum#885]
Guten Tag,
der Adapter startet einfach nicht richtig seit dem update.
Habe bereits mehrmals versucht diesen neu zu installieren aber jedes mal startet er nur bis 

mihome-vacuum.0 | 2023-11-07 18:33:37.476 | info | IOT enabled, create state
-- | -- | -- | --
mihome-vacuum.0 | 2023-11-07 18:33:37.378 | info | State value to set for "mihome-vacuum.0.deviceInfo.wifi_signal" has to be type "number" but received type "string"
mihome-vacuum.0 | 2023-11-07 18:33:37.274 | warn | This object will not be created in future versions. Please report this to the developer.
mihome-vacuum.0 | 2023-11-07 18:33:37.271 | warn | Object mihome-vacuum.0.deviceInfo.wifi_signal is invalid: Default value has to be type "number" but received type "string"
mihome-vacuum.0 | 2023-11-07 18:33:37.162 | info | starting. Version 4.0.0 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v18.17.1, js-controller: 5.0.12

bin ehr Laie und kann den Fehler nicht finden.
Bin für jede Hilfe echt dankbar .

**Comment by dirkhe** [comment]
Bitte debug log hier posten, so kann man nichts erkennen

**Comment by SidvsKaliman** [comment]
<html><body>


mihome-vacuum.0 | 2023-11-07 20:15:04.009 | debug | Helo message Timeout
-- | -- | -- | --
mihome-vacuum.0 | 2023-11-07 20:14:52.007 | debug | Helo message Timeout
mihome-vacuum.0 | 2023-11-07 20:14:40.003 | debug | Helo message Timeout
mihome-vacuum.0 | 2023-11-07 20:14:28.002 | debug | Helo message Timeout
mihome-vacuum.0 | 2023-11-07 20:14:15.999 | debug | Helo message Timeout
mihome-vacuum.0 | 2023-11-07 20:14:03.995 | debug | Helo message Timeout
mihome-vacuum.0 | 2023-11-07 20:13:51.993 | debug | Helo message Timeout
mihome-vacuum.0 | 2023-11-07 20:13:51.993 | debug | Helo message Timeout
mihome-vacuum.0 | 2023-11-07 20:13:49.989 | debug | server started on 0.0.0.0:53421
mihome-vacuum.0 | 2023-11-07 20:13:49.982 | info | IOT enabled, create state
mihome-vacuum.0 | 2023-11-07 20:13:49.977 | debug | MIIO: Config: ip:192.168.178.45 token: 4a70436c75XXXXXXXXX
mihome-vacuum.0 | 2023-11-07 20:13:49.976 | debug | Create State for deviceInfounsupported
mihome-vacuum.0 | 2023-11-07 20:13:49.975 | debug | Create State for deviceInfowifi_signal
mihome-vacuum.0 | 2023-11-07 20:13:49.975 | debug | Create State for deviceInfofw_ver
mihome-vacuum.0 | 2023-11-07 20:13:49.974 | debug | Create State for deviceInfomodel
mihome-vacuum.0 | 2023-11-07 20:13:49.973 | debug | Create State for deviceInfomac
mihome-vacuum.0 | 2023-11-07 20:13:49.972 | debug | Create State for deviceInfo
mihome-vacuum.0 | 2023-11-07 20:13:49.934 | debug | load Map creator... true
mihome-vacuum.0 | 2023-11-07 20:13:49.831 | info | starting. Version 4.0.0 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v18.17.1, js-controller: 5.0.12
mihome-vacuum.0 | 2023-11-07 20:13:49.283 | debug | Plugin sentry Initialize Plugin (enabled=true)
mihome-vacuum.0 | 2023-11-07 20:13:49.170 | debug | States connected to redis: 127.0.0.1:9000
mihome-vacuum.0 | 2023-11-07 20:13:49.097 | debug | States create User PubSub Client
mihome-vacuum.0 | 2023-11-07 20:13:49.096 | debug | States create System PubSub Client
mihome-vacuum.0 | 2023-11-07 20:13:49.076 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
mihome-vacuum.0 | 2023-11-07 20:13:49.031 | debug | Objects connected to redis: 127.0.0.1:9001
mihome-vacuum.0 | 2023-11-07 20:13:49.019 | debug | Objects client initialize lua scripts
mihome-vacuum.0 | 2023-11-07 20:13:48.962 | debug | Objects create User PubSub Client
mihome-vacuum.0 | 2023-11-07 20:13:48.960 | debug | Objects create System PubSub Client
mihome-vacuum.0 | 2023-11-07 20:13:48.957 | debug | Objects client ready ... initialize now
mihome-vacuum.0 | 2023-11-07 20:13:48.906 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001


</body>
</html>

**Comment by dirkhe** [comment]
Was ist das denn für ein mdell?

**Comment by SidvsKaliman** [comment]
s5 max

**Comment by SidvsKaliman** [comment]
![Screenshot 2023-11-07 213906](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/assets/150178769/556e9e19-c266-446b-80a8-3fe3723f43d3)

**Comment by dirkhe** [comment]
Dein robbi scheint nicht erreichbar. Firewall? Gerät ausgeschaltet, oder nicht im netzwerk/wlan?

**Comment by SidvsKaliman** [comment]
über handy app gehts ohne probleme auch meine fritzbox meckert nicht

**Comment by SidvsKaliman** [comment]
halt stop mit CMD kann ich ihn nicht anpingen

**Comment by dirkhe** [comment]
Kannst du mal schauen, ob es noch einen zombie prozess auf dem iobroker server läuft? Aber eigentlich kann es nicht sein, weil er sonst wegem dem port meckern würde.

**Comment by SidvsKaliman** [comment]
wie finde ich diesen zombie prozess

**Comment by SidvsKaliman** [comment]
oha hab den Fehler gefunden .
Mein Mädel ....     hat in der app rumgespielt und den robotor geupdated iwie muss er sich dort verhaspelt haben... auf jeden fall hat er sich zwar angemeldet an der Fritzbox aber anscheind auch nicht richtig . habe den roboter und die fritzbox neu gestartet jetzt komuniziert er wieder mit mir. 
manchmal sollte man nicht so kompliziert denken . 
Sry
Trotzdem danke für deine schnelle reaktion und zeit.

**Comment by dirkhe** [comment]
Gerne, kein problem. Schön, das er wieder mit dir spielt...
