### ISSUE TITLE
Warnmeldung verweist auf fehlendes Objekt

### ISSUE THREAD

**Issue by DcFamas** [iobroker-community-adapters/ioBroker.mihome-vacuum#886]
Hallo zusammen,

ich habe heute die folgende Fehlermeldung im log gesehen:

`2023-11-10 09:10:48.363 - warn: mihome-vacuum.0 (753) CANVAS package not installed....please install Canvas package manually or disable Map in config see also https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/blob/master/lib/canvaserror.md`

Leider scheint die canvaserror.md nicht mehr zu existieren. Dies sollte ggf. angepasst werden.

Vielen Dank und Grüße :)

**Comment by DcFamas** [comment]
Ist ggf. nur ein Verweis hierrauf:
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum#error-at-installation

Ich persönlich hatte die richtigen Module schon installiert, hier fehlte nur 

`npm install canvas`

im angegebenen Ordner

`cd /opt/iobroker/node_modules/iobroker.mihome-vacuum`

**Comment by dirkhe** [comment]
Danke für den Hinweis. habe ich mal kmorrigiert
