### ISSUE TITLE
Question about Vacuum state

### ISSUE THREAD

**Issue by gaudes** [iobroker-community-adapters/ioBroker.mihome-vacuum#90]
Hey,
question about the state 8 (Charging) of the vacuum:

The state seems to stay 8 when the battery is full loaded. Is is possible to change the state from 8 to 2 (Sleeping) when battery is 100% ?

Thanks and regards, 

Ralf

**Comment by MeisterTR** [comment]
No it's not possible, because state 2 is not for the dock. When the battery is 100 percent the robot is still loading.
