### ISSUE TITLE
Map - HTML Widget

### ISSUE THREAD

**Issue by hail0** [iobroker-community-adapters/ioBroker.mihome-vacuum#935]
Hello all 

I currently have an issue with displaying the MAP in VIS. The map is regularly updated in the data point map64 (regular change of the timestamp), but when I try to integrate the map into VIS, no map is displayed. Currently, I am using a simple HTML widget (see exported widget). Am I doing something wrong with the settings or am I using the wrong widget? Thank you for your help.

BR hail0

`[{"tpl":"tplHtml","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","refreshInterval":"1000","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"html":"<img src=\"mihome-vacuum.0.cleanmap.map64\">"},"style":{"left":"1026px","top":"219px","z-index":"100"},"widgetSet":"basic"}]`

**Versions:**

-   Adapter version: 4.1.1
-   JS-Controller version: <8.19.3
-   Node version: v16.19.1
-   vacuum cleaner: roborock.vacuum.s5e

**Comment by dirkhe** [comment]
Please search the forum, there are a lot of examples descrived. You can use the imafe url ir the base64 dats, but then you have to use it dara, i guess sonething like `<img style='display:block; width:100px;height:100px;' id='base64image'
       src='data:image/jpeg;base64, LzlqLzRBQ... ' />`

**Comment by dirkhe** [comment]
Closed, because no response
