### ISSUE TITLE
mihome-vacuum adapter version 2.0.1 does not start

### ISSUE THREAD

**Issue by jayfizzle** [iobroker-community-adapters/ioBroker.mihome-vacuum#94]
hi,
yesterday i installed the new version (2.0.1).
After starting the instance i get the following error log:

mihome-vacuum.0 | 2020-02-14 06:38:46.781 | info | (1181) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
mihome-vacuum.0 | 2020-02-14 06:38:46.779 | info | (1181) terminating
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at client.keys (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:684:17)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at states.getKeys (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6814:25)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at initLogging (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7117:22)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at Adapter.emit (events.js:208:7)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at emitNone (events.js:106:13)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at Adapter.main (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:1173:15)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at new Maphelper (/opt/iobroker/node_modules/iobroker.mihome-vacuum/lib/maphelper.js:35:24)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | at JSON.parse (<anonymous>)
mihome-vacuum.0 | 2020-02-14 06:38:46.718 | error | (1181) SyntaxError: Unexpected end of JSON input
mihome-vacuum.0 | 2020-02-14 06:38:46.717 | error | (1181) uncaught exception: Unexpected end of JSON input
mihome-vacuum.0 | 2020-02-14 06:38:46.696 | info | (1181) Create state clean_home for controlling by cloud adapter
mihome-vacuum.0 | 2020-02-14 06:38:46.694 | info | (1181) Expert mode enabled, states created
mihome-vacuum.0 | 2020-02-14 06:38:46.641 | info | (1181) starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v8.16.0
mihome-vacuum.0 | 2020-02-14 06:38:43.305 | debug | (1181) statesDB connected
mihome-vacuum.0 | 2020-02-14 06:38:43.304 | debug | (1181) States connected to redis: 127.0.0.1:9000
mihome-vacuum.0 | 2020-02-14 06:38:43.283 | debug | (1181) States create System PubSub Client
mihome-vacuum.0 | 2020-02-14 06:38:43.278 | debug | (1181) States create User PubSub Client
mihome-vacuum.0 | 2020-02-14 06:38:43.264 | debug | (1181) Redis States: Use Redis connection: 127.0.0.1:9000
mihome-vacuum.0 | 2020-02-14 06:38:43.258 | debug | (1181) objectDB connected
mihome-vacuum.0 | 2020-02-14 06:38:43.244 | debug | (1181) Objects connected to redis: 127.0.0.1:9001
mihome-vacuum.0 | 2020-02-14 06:38:43.214 | debug | (1181) Objects client initialize lua scripts
mihome-vacuum.0 | 2020-02-14 06:38:43.212 | debug | (1181) Objects create User PubSub Client
mihome-vacuum.0 | 2020-02-14 06:38:43.210 | debug | (1181) Objects create System PubSub Client
mihome-vacuum.0 | 2020-02-14 06:38:43.201 | debug | (1181) Objects client ready ... initialize now
mihome-vacuum.0 | 2020-02-14 06:38:42.313 | debug | (1181) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.raspberrypi | 2020-02-14 06:38:40.648 | info | instance system.adapter.mihome-vacuum.0 started with pid 1181
host.raspberrypi | 2020-02-14 06:38:40.468 | info | "system.adapter.mihome-vacuum.0" enabled

system information:
Node.js v8.16.0
NPM 6.13.6

**Comment by MeisterTR** [comment]
Already fixed
