### ISSUE TITLE
dependency of zlib get error with node-js 18.20

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.mihome-vacuum#940]
Hallo,

ich habe heute auf node-js 18.20 aktualisiert.

Seitdem bekomme ich bezüglich dem zlib einen Fehler.
Könnte bitte zlib entfernt werden oder die dependecy auf node-gyp oder den node-js core zlib gelegt werden?

Fehler:
```
mario@iobroker:/opt/iobroker$ iob upgrade hm-rpc@1.16.0
Would you like to reinstall version 1.16.0 of hm-rpc now? [(y)es, (n)o]: y
Update hm-rpc from @1.16.0 to @1.16.0
NPM version: 10.5.0
Installing iobroker.hm-rpc@1.16.0... (System call)
npm ERR! code 127
npm ERR! path /opt/iobroker/node_modules/zlib
npm ERR! command failed
npm ERR! command sh -c node-waf clean || true; node-waf configure build
npm ERR! sh: 1: node-waf: not found
npm ERR! sh: 1: node-waf: not found

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-03-29T20_31_44_159Z-debug-0.log
host.iobroker Cannot install iobroker.hm-rpc@1.16.0: 127
mario@iobroker:/opt/iobroker$
```

**Comment by dirkhe** [comment]
Hast du dich im projekt vertan? Du willst hm-rpc installieren, hier ist mihome-vacuum

**Comment by mcm1957** [comment]
Das Ganze dürfte in Zusammenhang mit https://forum.iobroker.net/topic/73800/iobroker-exit-25-bei-adapter-update/28 stehen. Hab das aber noch nicht durchgesehen und verstanden um wasces wirklichvgeht . Den Zusammenhang verschweigt der TE leider ...

**Comment by mcm1957** [comment]
@Siggi0904 

Bitte bei ALLEN issues um vollständige Versiobaangaben

Adapter
Js-controller
Admin
Node  18.20.??
Npm
O/S

Danke

**Comment by dirkhe** [comment]
Du könntest mal probieren, die zlib version im adapter auf 3.0.0 zu heben und zu updaten

**Comment by Siggi0904** [comment]
Hallo euch beide,

ich verheimliche hier nichts, auch wenn der Zusammenhang auch mir verwirrend ist.
Aber hoffentlich erklärt der Link zum Forum und die Analyse von Thomas Braun ein wenig das Thema.
Ja, es geht um das Forenthema: https://forum.iobroker.net/topic/73800/iobroker-exit-25-bei-adapter-update

Soweit wir ermitteln konnten, kann ich aufgrund falscher Abhängigkeiten keine Addons mehr aktualisieren.
Es führte vom Fehler im npm ERR! invalid: xmlbuilder@0.4.2 siehe https://forum.iobroker.net/post/1145360
zur Erkenntnis, dass zlib zu alt ist und die Abhängigkeiten dabei nicht aufgelöst werden können.
Siehe https://forum.iobroker.net/post/1145372

Somit hänge ich nun in einem Deadlock. Ich kann keine Apps mehr updaten oder (de)installieren.
Es kommt immer der gleiche Fehler 127.
Im log steht dabei:
`npm ERR! code 127
npm ERR! path /opt/iobroker/node_modules/zlib
npm ERR! command failed
npm ERR! command sh -c node-waf clean || true; node-waf configure build
npm ERR! sh: 1: node-waf: not found
npm ERR! sh: 1: node-waf: not found`

Daher kam die Frage, wie ich das auflösen kann und ob ggf. zlib überhaupt benötigt wird.
Gern auch per Teamviewer oder im Forum weiter.

**Comment by dirkhe** [comment]
Ich hatte doch geschrieben, versuche mal die zlib 3.0.0 zu installieren. Gehe dazu in iobroker/node_modules/iobroker-mihome–vacuum/package.json und ändere dort die versionsnummer. Anschliessend updatest du den mihome-vacuum adapter.
Dann sollte er die neueste zlib version installieren.

Wozu die zlib benötigt wird, kann ich gerade njcht sagen, aber die kann nan nicht einfach weglassen

**Comment by Siggi0904** [comment]
da brauche ich Hilfe.

Bedeutet folgendes ändern?
`"dependencies": {
    "@iobroker/adapter-core": "^3.0.4",
    "zlib": "^1.0.5",`

ändern in

`"dependencies": {
    "@iobroker/adapter-core": "^3.0.4",
    "zlib": "^3.0.0",`

**Comment by Siggi0904** [comment]
Irgendwie zerlege ich mir gerade mein IOBroker.
Fehler:
`login as: mario
mario@192.168.178.64's password:
Linux iobroker 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Mar 29 20:47:18 2024 from 192.168.178.41
mario@iobroker:~$ nano /opt/iobroker/node_modules/io
iobroker/                 iobroker.flot/            iobroker.simple-api/
iobroker.admin/           iobroker.heatingcontrol/  iobroker.socketio/
iobroker.alarm/           iobroker.hm-rega/         iobroker.sonoff/
iobroker.alexa2/          iobroker.hm-rpc/          iobroker.sql/
iobroker.alexa-timer-vis/ iobroker.ical/            iobroker.tankerkoenig/
iobroker.awtrix-light/    iobroker.icons-mfd-svg/   iobroker.tr-064/
iobroker.backitup/        iobroker.iot/             iobroker.trashschedule/
iobroker.cloud/           iobroker.javascript/      iobroker.type-detector/
iobroker.daswetter/       iobroker.js-controller/   iobroker.vis/
iobroker.deconz/          iobroker.mihome-vacuum/   iobroker.web/
iobroker.discovery/       iobroker.openweathermap/  iobroker.ws/
iobroker.dwd/             iobroker.ping/            ioredis/
iobroker.email/           iobroker.scenes/
iobroker.feiertage/       iobroker.shelly/
mario@iobroker:~$ ls /opt/iobroker/node_modules/iobroker.mihome-vacuum/
admin  io-package.json  lib  LICENSE  main.js  package.json  README.md
mario@iobroker:~$ nano /opt/iobroker/node_modules/iobroker.mihome-vacuum/package.json
mario@iobroker:~$ nano /opt/iobroker/node_modules/iobroker.mihome-vacuum/package.json
mario@iobroker:~$ iob upgrade mihome-vacuum@4.1.1
Would you like to reinstall version 4.1.1 of mihome-vacuum now? [(y)es, (n)o]: y
Update mihome-vacuum from @4.1.1 to @4.1.1
NPM version: 10.5.0
Installing iobroker.mihome-vacuum@4.1.1... (System call)
npm ERR! code 127
npm ERR! path /opt/iobroker/node_modules/zlib
npm ERR! command failed
npm ERR! command sh -c node-waf clean || true; node-waf configure build
npm ERR! sh: 1: node-waf: not found
npm ERR! sh: 1: node-waf: not found

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-03-31T12_32_38_352Z-debug-0.log
host.iobroker Cannot install iobroker.mihome-vacuum@4.1.1: 127
mario@iobroker:~$ npm ls zlib
/home/mario
└── (empty)

mario@iobroker:~$ iob upgrade mihome-vacuum@4.1.1
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.20.0
mario@iobroker:~$
`

**Comment by mcm1957** [comment]
@dirkhe
Bist du sicher?
Bei einer Instsllation verwendet npm doch hoffentlich sas im Paket (!) enthaltene oacksge.json
Und nur package.json und nicht packsge-lock.json zu ändernnust auch keine gut Idee.

Persönlich bezweifle ichcsehr dass due zlib Verdion hier ursächlich das Problemnist. Es gibt ha genug adapterinstallationen und da mit dicherheit auchbjede Menge nidec18.

Und die GH Test gaben ha auch kein Probkem mut node 18. Oder?

Hst du den Adapter bei dir installiert? Mit welcher Nide versuon?

Ich würde nal den Adapter deinstallieten (adapter nucht nur instanz)  wenn dann das Problem wegbist den Adapter neu in0stallieren. Dann weiss man mehr.

Hast fu azsserdem geprüftbob zlib 3 das zwei neue major versionen höher ist noch lompatibel ist oder ob Codeanpassungen notwendig sind ?

**Comment by softwarecrash** [comment]
ich häng mich mal mit hier drann,
aktuell auch keine installation möglich, ist heute aufgefallen als ich den iob umziehen wollte. backup hat gemeckert beim wiederstellen, testweise iob frisch auf einer vm aufgesetzt, mit dem fehler

```
$ iobroker add mihome-vacuum --host iobroker
NPM version: 10.5.0
Installing iobroker.mihome-vacuum@4.1.1... (System call)
npm ERR! code 127npm ERR! path /opt/iobroker/node_modules/zlibnpm ERR! command failednpm ERR! command sh -c node-waf clean || true; node-waf configure buildnpm ERR! sh: 1: node-waf: not foundnpm ERR! sh: 1: node-waf: not foundnpm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-03-31T14_30_30_973Z-debug-0.loghost.iobroker Cannot install iobroker.mihome-vacuum@4.1.1: 127
ERROR: Process exited with code 25
```


js-controller: 5.0.19
Node.js: v18.20.0
NPM: 10.5.0

**Comment by mcm1957** [comment]
@softwarecrash 
Danke f d Zusatzinfo.
Da scheintcwirklichvwas an dem Adapter zu sein ...

**Comment by Siggi0904** [comment]
Ich hab nun meine proxmox-vm zurückgerollt.
Nutze nun wieder node-js 18.19.1, alle Adapter uptodate mit dem aktuellen stable mihome-vacuum Adapter.

Ich müsste nun node-js updaten.

Wir sollten nur schauen, wo wir weiter diskutieren.
Hier oder im Forum https://forum.iobroker.net/topic/73800/iobroker-exit-25-bei-adapter-update

**Comment by mcm1957** [comment]
Wenn ich es richtig sehe ist zlib nun direct in node verfügbar. Das wütde bedeuten dass die Abhängigkeit aus packsge raus muss und beim require node:zlib rein sollte.

Hab aber keine Ahnung ob das klmpatibel ustbjnd hab schonnim Forum geschrieben dass ich wahrscheinlich etst di einen blick drauf werfen könnte.

Abercevvgst dirkhe ja vorher Zeit

Hab zZ nur handy zuhang

**Comment by Siggi0904** [comment]
Aber das ist es doch schon lange, oder?
Es ist parallel in node-gyp und im Core verfügbar.

Generell sollte sehr dringend eine Info an alle User raus, dass man nicht auf node-js 18.20 updaten darf.

**Comment by Diginix** [comment]
Bin auf nodejs 18.20.0 und habe keine Probleme mit dem Adapter und zlib 1.0.5. Neuinst. mag ggf Probleme machen, aber node Update auf Bestandssystem funktionierte bei mir.

**Comment by dirkhe** [comment]
Ich versuche morgen mal die native version zu testen

**Comment by dirkhe** [comment]
So, mit der native zlib funktioniert es. Ich habe daher mal die zlib rausgeworfen. Ich denke aber auch, dass das nicht die Ursache war. Daher schließe ich den Issue hier mal

**Comment by Grothesk242** [comment]
Zumindest für die Fehlermeldungen 
```
109 error sh: 1: node-waf: not found
109 error sh: 1: node-waf: not found
```
dürfte die seit Jahren obsolete Version schon der Grund sein. Der Aufruf steht nämlich in dessen Code drin. Und node-waf gibt es nicht mehr.
