### ISSUE TITLE
(1890) SyntaxError: Unexpected token G in JSON at position 0

### ISSUE THREAD

**Issue by losnoxos** [iobroker-community-adapters/ioBroker.mihome-vacuum#95]
Vielleicht bereits bekannt.

Adapter Version: 2.0.3
IoB usw alles aktuell.

Wenn ich beim Roborock S6 das reinigen eines Raumes starte, wird der Log mit dieser Meldung massiv gefüllt.
Weiß grade nicht welche hilfreichen Infos ich hinterlassen könnte.

**Comment by dirkhe** [comment]
Kannst du mal debug einschalten und dieses dann hier posten? Vorher besser nochmal ein update machen

**Comment by losnoxos** [comment]
Werde ich später machen und Feedback geben.

Danke!

**Comment by losnoxos** [comment]
Keine Fehler mehr im Log nach dem Update

Klasse !!
Du machst viele Roborock S6 Besitzer glücklich :)

Gestern hatte ich beim Login immer ein "auth error" im Log. Diese Meldung ist jetzt auch weg.

Was eben noch komisch war:
Habe die Räume in Alexa eingerichtet und mir einen Trigger jeweils für die Räume gemacht.
Der Adapter hat erst nicht reagiert. Mehrfach neu gestartet. Dann habe ich mich mit der mihome App verbunden und nur "goto Point" benutzt, damit der Robo sich bewegt. Anschließend konnte ich dann das Saugen über den Adapter starten. 

Im Log steh nix drin. Nur das die Cloud deaktiviert wird. 

Vielen Dank für deine tolle Arbeit!

**Comment by losnoxos** [comment]
Wenn ich auf die farbige Karte umstelle, kommt eine Fehlermeldung:


mihome-vacuum.0 | 2020-02-18 08:03:22.971 | error | (8033) Error when receiving mapurl
-- | -- | -- | --
mihome-vacuum.0 | 2020-02-18 08:03:22.910 | debug | (8033) Xiaomi Cloud: Login successful

**Comment by losnoxos** [comment]
![image](https://user-images.githubusercontent.com/34764696/74728447-106bad00-5243-11ea-8139-a010d3c7ae20.png)


Jetzt ist der Fehler wieder da. 
Wenn ich den Adapter auf "debug" stelle, kommen keine Fehlermeldungen.

Mal sehen ob man da eine Linie erkennen kann.

**Comment by losnoxos** [comment]
mihome-vacuum.0 | 2020-02-18 14:05:15.669 | debug | (9151) lastid{"get_status":2300,"get_consumable":2292,"get_clean_summary":2293,"get_clean_record":1000,"X_send_command":0,"miIO.info":2291,"get_sound_volume":2294,"get_carpet_mode":2295,"get_room_mapp
-- | -- | -- | --
mihome-vacuum.0 | 2020-02-18 14:05:14.974 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:05:12.920 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:05:10.853 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:05:08.797 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:05:06.729 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:05:04.673 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:05:02.588 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:05:00.532 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:04:58.457 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:04:56.682 | debug | (9151) Mappointer_updated
mihome-vacuum.0 | 2020-02-18 14:04:56.681 | debug | (9151) Receive <<< {"result":["tanos%2F260221108%2F18"],"id":2299}<<< 21310060010461451ba904d
mihome-vacuum.0 | 2020-02-18 14:04:56.676 | debug | (9151) Mappointer_nomap___retry
mihome-vacuum.0 | 2020-02-18 14:04:56.676 | debug | (9151) sendMsgRaw >>> 2131003c2521
mihome-vacuum.0 | 2020-02-18 14:04:56.676 | debug | (9151) sendMsg >>> {"id":2299,"method":"get_fresh_map_v1"}
mihome-vacuum.0 | 2020-02-18 14:04:56.676 | debug | (9151) Timestamp: 5e4be0f8
mihome-vacuum.0 | 2020-02-18 14:04:56.676 | debug | (9151) lastid{"get_status":2297,"get_consumable":2292,"get_clean_summary":2293,"get_clean_record":1000,"X_send_command":0,"miIO.info":2291,"get_sound_volume":2294,"get_carpet_mode":2295,"get_room_mapp
mihome-vacuum.0 | 2020-02-18 14:04:56.401 | error | (9151) SyntaxError: Unexpected token G in JSON at position 0
mihome-vacuum.0 | 2020-02-18 14:04:56.175 | debug | (9151) Receive <<< {"result":["retry"],"id":2298}<<< 213100757a28
mihome-vacuum.0 | 2020-02-18 14:04:56.169 | debug | (9151) Mappointer_nomap___retry
mihome-vacuum.0 | 2020-02-18 14:04:56.169 | debug | (9151) sendMsgRaw >>> 21310066b2d4088d8e35
mihome-vacuum.0 | 2020-02-18 14:04:56.169 | debug | (9151) sendMsg >>> {"id":2298,"method":"get_fresh_map_v1"}

Ich habe die ID´s gekürzt. Da ich nicht weiß was sie besagen :)
Das scheint immer zu sein, wenn der Adapter lange verbunden war. Wenn man ihn neu startet passiert das nicht.

**Comment by dirkhe** [comment]
Das tritt alle 2 sec auf. @MeisterTR  Ich glaube,  das ist in der Funktion _MapPoll

**Comment by MeisterTR** [comment]
versuch nochmal mit der Verion von git

**Comment by losnoxos** [comment]
mihome-vacuum.0 | 2020-02-19 09:05:08.549 | debug | (16687) Timestamp: 5e4cec34
-- | -- | -- | --
mihome-vacuum.0 | 2020-02-19 09:05:08.549 | debug | (16687) lastid{"get_status":8,"get_consumable":3,"get_clean_summary":4,"get_clean_record":0,"X_send_command":0,"miIO.info":2,"get_sound_volume":5,"get_carpet_mode":6,"get_room_mapping":7}
mihome-vacuum.0 | 2020-02-19 09:04:51.565 | warn | (16687) ReferenceError: that is not defined
mihome-vacuum.0 | 2020-02-19 09:04:51.564 | debug | (16687) Xiaomi Cloud: Login successful
mihome-vacuum.0 | 2020-02-19 09:04:51.550 | debug | (16687) sendMsgRaw >>> 2130add168773c9
mihome-vacuum.0 | 2020-02-19 09:04:51.550 | debug | (16687) sendMsg >>> {"id":7,"method":"get_room_mapping"}
mihome-vacuum.0 | 2020-02-19 09:04:51.550 | debug | (16687) Timestamp: 5e4cec23


Beim starten des Adapter kommt eine Warnmeldung. Rest teste ich später.

**Comment by MeisterTR** [comment]
bitte nochmal von git probieren, hatte  noch einen fehler drin

**Comment by losnoxos** [comment]
Sieht jetzt wirklich gut aus!
Aktuell bekomme ich weder Warnung noch Fehlermeldungen.

**Comment by MeisterTR** [comment]
jep kannst mich gerne über telegram gleicher Username
