### ISSUE TITLE
change settings from ms to s

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.mihome-vacuum#98]
having setting in ms is very dangerous, most people only recognize seconds or minutes.
and using 30 seconds is really something different than using 30 ms, so suggest to calculate value * 1000 in the adapter itself.

![Schermafbeelding 2020-02-19 om 12 09 30](https://user-images.githubusercontent.com/7318445/74829373-32336580-5311-11ea-96c7-483280280eff.png)

**Comment by dirkhe** [comment]
Will be fixed in Next version

**Comment by dirkhe** [comment]
Is now in current Version
