### ISSUE TITLE
LoadRooms funktioniert seit Version 4.x nicht mehr --> Roborock S5

### ISSUE THREAD

**Issue by blackeagle998** [iobroker-community-adapters/ioBroker.mihome-vacuum#993]
Debug LOG
`
mihome-vacuum.0 | 2024-10-27 20:29:43.368 | debug | MIIO RECIVE: {"result":[],"id":33}
mihome-vacuum.0 | 2024-10-27 20:29:43.368 | debug | MIIO MESSAGE TESTING: {"result":[],"id":33}
mihome-vacuum.0 | 2024-10-27 20:29:43.330 | debug | Message= {"id":33,"method":"get_room_mapping"}
mihome-vacuum.0 | 2024-10-27 20:29:43.330 | debug | command: loadRooms parent: rooms
`

**Describe the bug**  
Roborock S5, Button LoadRooms liefert seit Version 4.x nur ein leeres Array.
Getestet mit Adapter Version 3.11.0, da funktionierte das Laden der Räume noch, ab Version 4.0.0 und Folgende nicht mehr.

**Versions:**

-   Adapter version: 4.2.0
-   JS-Controller version: 6.0.11
-   Node version: 20.17.0
-   vacuum cleaner: Roborock S5

**Comment by dirkhe** [comment]
Das kann mit dem adapter nichts zu tun haben. Du siehst ja im log, dass der befehl zum roboter gesendet wird und auch, welche antwort kommt.
Wenn du sagst, dass es mit der alten funktioniert, schau da doch ml ins log, aber eigentlich hat sich da auch nichts geändert...

**Comment by blackeagle998** [comment]
Danke für die schnelle Rückmeldung, ich habe heute ausgiebig auf meinem ioBroker Testsystem die Varianten durchgespielt.

Fazit Testsystem:
Die Räume werden geladen, allerdings nur, wenn ich einmal die Option "enable Map from xiaomi cloud" aktiviert habe.
Dies ist unabhängig ob Node 18 oder 20 und auch egal welche Adapterversion.

Leider bekomme ich es auf meinem Produktivsystem einfach nicht hin. Habe auch schon den Adapter deinstalliert, neugestartet und dann den Adapter neu installiert, geht trotzdem nicht. Die Softwarestände beider Systemumgebungen sind gleich, keine Ahnung woran es hängt. Auch ein Neustart des Saugers brachte leider keinen Erfolg.

Am Ende ist es wie du sagst, es liegt wohl nicht am Adapter.
Dank des Testsystems kenne ich ja zumindest die Index Nummern und lege die Räume jetzt manuell an.

**Comment by dirkhe** [comment]
Das ist schon komisch, hast du das Testsystem vorher runtergefahren, bzw, den Adapter gestoppt? Nicht dass er ein Problem hat, wenn 2 Adapter sich mit der cloed verbunden haben? Ist nur eine Überlegung. Wenn du die Map anabled hast, bekom,mst du die in der prod auch aungezeigt im Datenpunkt? Der robbi kann ja auch mehrere Karften verwalten, nicht dass er auf der faldchen Karte hängt?

**Comment by dirkhe** [comment]
Was auch helfen könnte, wenn er im prod komplett grün ist, den Sauger einmal zu starten und dann nochmal zu probieren

**Comment by blackeagle998** [comment]
Die Idee mit den zwei Instanzen hatte ich auch, aber das Testsystem ist inaktiv und die Instanz habe ich wieder gelöscht, müsste also jetzt wieder funktionieren. Zumal die Produktivinstanz die ganze Zeit aktiv war, auch als das Testsystem die Räume geladen hat.
Ich lasse ihn morgen mal saugen und probiere es dann nochmal und melde mich.

**Comment by blackeagle998** [comment]
Einen Tag warten war offensichtlich die Lösung.
Habe gerade die Cloud Karte aktiviert und die Instanz neu gestartet und nun sind die Räume da.
Danke für den emotionalen Beistand :-)
